{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadio\/init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)","interfaceLanguage":"swift"},"metadata":{"title":"init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"anchorAllowWhiteSpaceInCharacters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"anchorAllowWhiteSpaceInCharactersMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorCaseSensitive"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"anchorCaseSensitiveMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"anchorHorizontalAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"anchorHorizontalAlignmentMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorIgnoreIfNotPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"anchorIgnoreIfNotPresentMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorMatchWholeWord"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"anchorMatchWholeWordMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorString"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"anchorStringMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorTabProcessorVersion"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorTabProcessorVersionMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorUnits"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorUnitsMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"anchorXOffset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"anchorXOffsetMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorYOffset"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"anchorYOffsetMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bold"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"boldMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"errorDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"fontColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"fontColorMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fontMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fontSize"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fontSizeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"italic"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"italicMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"locked","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"lockedMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pageNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pageNumberMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"required","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requiredMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selected"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"selectedMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"statusMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"tabId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tabIdMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tabOrder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"tabOrderMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"underline"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"underlineMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"valueMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"xPosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"xPositionMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"yPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"yPositionMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?)","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRadio(im)initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:","symbolKind":"init","navigatorTitle":[{"text":"initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadio"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"anchorAllowWhiteSpaceInCharacters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"anchorAllowWhiteSpaceInCharactersMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"anchorCaseSensitive"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"anchorCaseSensitiveMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"anchorHorizontalAlignment"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"anchorHorizontalAlignmentMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"anchorIgnoreIfNotPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"anchorIgnoreIfNotPresentMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"anchorMatchWholeWord"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"anchorMatchWholeWordMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"anchorString"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"anchorStringMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"anchorTabProcessorVersion"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"anchorTabProcessorVersionMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"anchorUnits","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"anchorUnitsMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"anchorXOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"anchorXOffsetMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"anchorYOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"anchorYOffsetMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"bold"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"boldMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"errorDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"? = nil, ","kind":"text"},{"text":"font","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"fontColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fontColorMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fontMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"fontSize"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fontSizeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"italic"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"italicMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"locked"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"lockedMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"pageNumber"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"pageNumberMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"required","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"requiredMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"selected"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"selectedMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"statusMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"tabId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"tabIdMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"tabOrder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"tabOrderMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"underline"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"underlineMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"valueMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"xPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"xPositionMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"yPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"yPositionMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiradio\/init(anchorallowwhitespaceincharacters:anchorallowwhitespaceincharactersmetadata:anchorcasesensitive:anchorcasesensitivemetadata:anchorhorizontalalignment:anchorhorizontalalignmentmetadata:anchorignoreifnotpresent:anchorignoreifnotpresentme-1q9ya"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiradio\/init(anchorallowwhitespaceincharacters:anchorallowwhitespaceincharactersmetadata:anchorcasesensitive:anchorcasesensitivemetadata:anchorhorizontalalignment:anchorhorizontalalignmentmetadata:anchorignoreifnotpresent:anchorignoreifnotpresentme-1q9ya"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadio":{"role":"symbol","abstract":[{"type":"text","text":"One of the selectable radio buttons in the `radios` property of a "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","type":"reference","isActive":true},{"type":"text","text":" tab."}],"kind":"symbol","title":"DSAPIRadio","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadio","url":"\/documentation\/docusignapi\/dsapiradio","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRadio","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DSAPIRadio","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadio/init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)":{"navigatorTitle":[{"text":"initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadio\/init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"anchorAllowWhiteSpaceInCharacters"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorCaseSensitive"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"anchorCaseSensitiveMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorHorizontalAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorHorizontalAlignmentMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"anchorIgnoreIfNotPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"anchorIgnoreIfNotPresentMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"anchorMatchWholeWord","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"anchorMatchWholeWordMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"anchorString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"anchorStringMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"anchorTabProcessorVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"anchorTabProcessorVersionMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"anchorUnits","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorUnitsMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"anchorXOffset"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"anchorXOffsetMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"anchorYOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"anchorYOffsetMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"bold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"boldMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fontColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"fontColorMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"fontMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"fontSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fontSizeMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"italic","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"italicMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"locked"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"lockedMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pageNumber"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pageNumberMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"required","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"requiredMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"selected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"selectedMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"statusMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tabId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"tabIdMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"tabOrder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"tabOrderMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"underline","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"underlineMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"valueMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"xPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"xPositionMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"yPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"yPositionMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"title":"init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)","url":"\/documentation\/docusignapi\/dsapiradio\/init(anchorallowwhitespaceincharacters:anchorallowwhitespaceincharactersmetadata:anchorcasesensitive:anchorcasesensitivemetadata:anchorhorizontalalignment:anchorhorizontalalignmentmetadata:anchorignoreifnotpresent:anchorignoreifnotpresentme-1q9ya"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/":{"type":"link","title":"`radioGroup`","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","titleInlineContent":[{"type":"text","text":"`radioGroup`"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAnchorAllowWhiteSpaceInCharacters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"anchorAllowWhiteSpaceInCharacters","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorAllowWhiteSpaceInCharactersMetadata:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"anchorAllowWhiteSpaceInCharactersMetadata"},{"text":" ","kind":"text"},{"text":"anchorCaseSensitive:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"anchorCaseSensitive"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorCaseSensitiveMetadata:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"anchorCaseSensitiveMetadata"},{"kind":"text","text":" "},{"text":"anchorHorizontalAlignment:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"anchorHorizontalAlignment"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorHorizontalAlignmentMetadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"text":"anchorHorizontalAlignmentMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"anchorIgnoreIfNotPresent:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"anchorIgnoreIfNotPresent"},{"kind":"text","text":" "},{"text":"anchorIgnoreIfNotPresentMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"anchorIgnoreIfNotPresentMetadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorMatchWholeWord:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"anchorMatchWholeWord","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorMatchWholeWordMetadata:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"anchorMatchWholeWordMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorString:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"anchorString"},{"text":" ","kind":"text"},{"text":"anchorStringMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"anchorStringMetadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorTabProcessorVersion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"anchorTabProcessorVersion","kind":"internalParam"},{"kind":"text","text":" "},{"text":"anchorTabProcessorVersionMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"text":"anchorTabProcessorVersionMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"anchorUnits:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"anchorUnits","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorUnitsMetadata:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"anchorUnitsMetadata"},{"text":" ","kind":"text"},{"text":"anchorXOffset:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"anchorXOffset","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorXOffsetMetadata:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"anchorXOffsetMetadata"},{"text":" ","kind":"text"},{"text":"anchorYOffset:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"anchorYOffset","kind":"internalParam"},{"kind":"text","text":" "},{"text":"anchorYOffsetMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"anchorYOffsetMetadata"},{"text":" ","kind":"text"},{"text":"bold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"bold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"boldMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"boldMetadata"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDetails:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","kind":"typeIdentifier","text":"DSAPIErrorDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"errorDetails"},{"text":" ","kind":"text"},{"text":"font:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"font","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fontColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"fontColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontColorMetadata:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"fontColorMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"fontMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fontMetadata"},{"text":" ","kind":"text"},{"text":"fontSize:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fontSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontSizeMetadata:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fontSizeMetadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"italic:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"italic","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"italicMetadata:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"italicMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locked:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"locked","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockedMetadata:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"lockedMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pageNumber:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pageNumber","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNumberMetadata:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageNumberMetadata"},{"text":" ","kind":"text"},{"kind":"identifier","text":"required:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"required","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"requiredMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requiredMetadata"},{"text":" ","kind":"text"},{"text":"selected:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"selected","kind":"internalParam"},{"kind":"text","text":" "},{"text":"selectedMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"selectedMetadata"},{"kind":"text","text":" "},{"text":"status:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusMetadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"statusMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tabId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"tabId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tabIdMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"text":"tabIdMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tabOrder:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tabOrder"},{"text":" ","kind":"text"},{"text":"tabOrderMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tabOrderMetadata"},{"text":" ","kind":"text"},{"text":"underline:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"underline","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"underlineMetadata:"},{"text":"(","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"underlineMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":" "},{"text":"valueMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"valueMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"xPosition:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"xPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xPositionMetadata:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"xPositionMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"yPosition:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"yPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"yPositionMetadata:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":" *) ","kind":"text"},{"text":"yPositionMetadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadio\/title","value":"DSAPIRadio","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadio\/fragments","value":[{"text":"DSAPIRadio","kind":"identifier"}],"op":"replace"},{"value":"initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadio~1init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithAnchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadio~1init(anchorAllowWhiteSpaceInCharacters:anchorAllowWhiteSpaceInCharactersMetadata:anchorCaseSensitive:anchorCaseSensitiveMetadata:anchorHorizontalAlignment:anchorHorizontalAlignmentMetadata:anchorIgnoreIfNotPresent:anchorIgnoreIfNotPresentMetadata:anchorMatchWholeWord:anchorMatchWholeWordMetadata:anchorString:anchorStringMetadata:anchorTabProcessorVersion:anchorTabProcessorVersionMetadata:anchorUnits:anchorUnitsMetadata:anchorXOffset:anchorXOffsetMetadata:anchorYOffset:anchorYOffsetMetadata:bold:boldMetadata:errorDetails:font:fontColor:fontColorMetadata:fontMetadata:fontSize:fontSizeMetadata:italic:italicMetadata:locked:lockedMetadata:pageNumber:pageNumberMetadata:required:requiredMetadata:selected:selectedMetadata:status:statusMetadata:tabId:tabIdMetadata:tabOrder:tabOrderMetadata:underline:underlineMetadata:value:valueMetadata:xPosition:xPositionMetadata:yPosition:yPositionMetadata:)\/fragments"},{"value":"DSAPIErrorDetails","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]},{"value":"DSAPIPropertyMetadata","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}