{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"certifiedDeliveries"},{"text":": [","kind":"text"},{"text":"DSAPICertifiedDelivery","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certifiedDeliveries"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery","text":"DSAPICertifiedDelivery","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"certifiedDeliveries","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"certifiedDeliveries"}],"roleHeading":"Instance Property","modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients(py)certifiedDeliveries"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/certifiedDeliveries","interfaceLanguage":"swift"},"abstract":[{"text":"A complex type containing information on a recipient the must receive the completed documents for the envelope to be completed, but the recipient does not need to sign, initial, date, or add information to any of the documents.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapirecipients\/certifieddeliveries"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapirecipients\/certifieddeliveries"]}],"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/certifiedDeliveries":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"certifiedDeliveries","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery","text":"DSAPICertifiedDelivery","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"abstract":[{"text":"A complex type containing information on a recipient the must receive the completed documents for the envelope to be completed, but the recipient does not need to sign, initial, date, or add information to any of the documents.","type":"text"}],"title":"certifiedDeliveries","url":"\/documentation\/docusignapi\/dsapirecipients\/certifieddeliveries","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"certifiedDeliveries","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/certifiedDeliveries"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipients","kind":"identifier"}],"abstract":[{"text":"Specifies the envelope recipients.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapirecipients","title":"DSAPIRecipients","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPIRecipients","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"abstract":[{"text":"Contains information about a certified delivery recipient. Certified delivery recipients must receive the completed documents for the envelope to be completed. However, they don't need to sign, initial, date or add information to any of the documents.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapicertifieddelivery","kind":"symbol","title":"DSAPICertifiedDelivery","role":"symbol","navigatorTitle":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"certifiedDeliveries","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"certifiedDeliveries","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DSAPICertifiedDelivery *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"certifiedDeliveries","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1certifiedDeliveries\/title","value":"certifiedDeliveries","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1certifiedDeliveries\/fragments","value":[{"kind":"identifier","text":"certifiedDeliveries"}]},{"value":"DSAPIRecipients","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipients"}]},{"value":"DSAPICertifiedDelivery","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/title"},{"value":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}