{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAgent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAgent","text":"DSAPIAgent"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"carbonCopies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICarbonCopy","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICarbonCopy","text":"DSAPICarbonCopy"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"certifiedDeliveries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery","text":"DSAPICertifiedDelivery"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"currentRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"editors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEditor","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEditor","text":"DSAPIEditor"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"inPersonSigners"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner","text":"DSAPIInPersonSigner"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"intermediaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary","text":"DSAPIIntermediary"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"notaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient","text":"DSAPINotaryRecipient"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recipientCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"seals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISealSign","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISealSign","text":"DSAPISealSign"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"signers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISigner","text":"DSAPISigner"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"witnesses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIWitness","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIWitness","text":"DSAPIWitness"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipients\/init(agents:carboncopies:certifieddeliveries:currentroutingorder:editors:errordetails:inpersonsigners:intermediaries:notaries:recipientcount:seals:signers:witnesses:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipients\/init(agents:carboncopies:certifieddeliveries:currentroutingorder:editors:errordetails:inpersonsigners:intermediaries:notaries:recipientcount:seals:signers:witnesses:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIAgent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAgent"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"carbonCopies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICarbonCopy","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICarbonCopy"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"certifiedDeliveries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICertifiedDelivery","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"currentRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"editors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEditor","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEditor"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inPersonSigners"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInPersonSigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"intermediaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIIntermediary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotaryRecipient","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISealSign","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISealSign"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISigner"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"witnesses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIWitness","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIWitness"},{"kind":"text","text":"]?)"}],"title":"init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients(im)initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"role":"symbol","title":"DSAPIRecipients","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipients"}],"abstract":[{"type":"text","text":"Specifies the envelope recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipients"}],"url":"\/documentation\/docusignapi\/dsapirecipients"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInPersonSigner":{"role":"symbol","title":"DSAPIInPersonSigner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIInPersonSigner"}],"abstract":[{"type":"text","text":"Contains information about an in-person recipient. This is a DocuSign user, acting as a Signing Host, who is in the same physical location as the signer. To learn about the fields used for the eNotary feature, see the [recipients resource][resource].  [resource]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipients\/#in-person-signer-recipient"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIInPersonSigner"}],"url":"\/documentation\/docusignapi\/dsapiinpersonsigner"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIWitness":{"role":"symbol","title":"DSAPIWitness","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIWitness"}],"abstract":[{"type":"text","text":"A complex type containing information about a witness recipient. Witnesses are recipients whose signatures affirm that the identified signers have signed the documents in the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIWitness","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIWitness"}],"url":"\/documentation\/docusignapi\/dsapiwitness"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISigner":{"role":"symbol","title":"DSAPISigner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISigner"}],"abstract":[{"type":"text","text":"A complex type containing information about a signer recipient. A signer is a recipient who must take action on a document, such as sign, initial, date, or add data to form fields on a document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISigner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISigner"}],"url":"\/documentation\/docusignapi\/dsapisigner"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAgent":{"role":"symbol","title":"DSAPIAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAgent"}],"abstract":[{"type":"text","text":"Contains information about an agent recipient. An agent is a recipient who can add name and email information for recipients that appear after the agent in routing order."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIAgent"}],"url":"\/documentation\/docusignapi\/dsapiagent"},"https://support.docusign.com/en/guides/ndse-user-guide-apply-electronic-seals":{"title":"Apply Electronic Seals to Your Documents","titleInlineContent":[{"type":"text","text":"Apply Electronic Seals to Your Documents"}],"type":"link","identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-apply-electronic-seals","url":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-apply-electronic-seals"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary":{"role":"symbol","title":"DSAPIIntermediary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIIntermediary"}],"abstract":[{"type":"text","text":"Contains information about an intermediary recipient. An intermediary is a recipient who can, but is not required to, add name and email information for recipients at the same or subsequent level in the routing order, unless subsequent agents, editors or intermediaries are added."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIIntermediary"}],"url":"\/documentation\/docusignapi\/dsapiintermediary"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEditor":{"role":"symbol","title":"DSAPIEditor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEditor"}],"abstract":[{"type":"text","text":"A complex type defining the management and access rights of a recipient assigned as an editor on the envelope. Editors have the same management and access rights for the envelope as the sender. They can make changes to the envelope as if they were using the Correct feature. This recipient can add name and email information, add or change the routing order and set authentication options for the remaining recipients. Additionally, this recipient can edit signature\/initial tabs and text tabs for the remaining recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEditor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEditor"}],"url":"\/documentation\/docusignapi\/dsapieditor"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISealSign":{"role":"symbol","title":"DSAPISealSign","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISealSign"}],"abstract":[{"type":"text","text":"Specifies one or more electronic seals to apply on documents. An electronic seal recipient is a legal entity rather than an actual person. Electronic Seals can be used by organizations and governments to show evidence of origin and integrity of documents. Even though electronic seals can be represented by a tab in a document, they do not require user interaction and apply automatically in the order specified by the sender. The sender is therefore the person authorizing usage of the electronic seal in the flow.  Example:   ```json &quot;recipients&quot;: {       &quot;seals&quot;: [         {           &quot;recipientId&quot;: &quot;1&quot;,           &quot;routingOrder&quot; : 1,           &quot;recipientSignatureProviders&quot;: [             {               &quot;sealName&quot;: &quot;52e9d968-xxxx-xxxx-xxxx-4682bc45c106&quot;             }        ]      }    ]  },     .     .     . ``` For more information about Electronic Seals, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-apply-electronic-seals"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISealSign","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISealSign"}],"url":"\/documentation\/docusignapi\/dsapisealsign"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICarbonCopy":{"role":"symbol","title":"DSAPICarbonCopy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICarbonCopy"}],"abstract":[{"type":"text","text":"Contains information about a carbon copy recipient. Carbon copy recipients get a copy of the envelope but don't need to sign, initial, date or add information to any of the documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICarbonCopy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICarbonCopy"}],"url":"\/documentation\/docusignapi\/dsapicarboncopy"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"role":"symbol","title":"DSAPIErrorDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIErrorDetails"}],"abstract":[{"type":"text","text":"This object describes errors that occur. It is only valid for responses and ignored in requests."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"url":"\/documentation\/docusignapi\/dsapierrordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery":{"role":"symbol","title":"DSAPICertifiedDelivery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICertifiedDelivery"}],"abstract":[{"type":"text","text":"Contains information about a certified delivery recipient. Certified delivery recipients must receive the completed documents for the envelope to be completed. However, they don't need to sign, initial, date or add information to any of the documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICertifiedDelivery"}],"url":"\/documentation\/docusignapi\/dsapicertifieddelivery"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient":{"role":"symbol","title":"DSAPINotaryRecipient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotaryRecipient"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINotaryRecipient"}],"url":"\/documentation\/docusignapi\/dsapinotaryrecipient"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)":{"role":"symbol","title":"init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIAgent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAgent"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"carbonCopies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICarbonCopy","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICarbonCopy"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"certifiedDeliveries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICertifiedDelivery","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"currentRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"editors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEditor","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEditor"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inPersonSigners"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInPersonSigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"intermediaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIIntermediary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotaryRecipient","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISealSign","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISealSign"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISigner"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"witnesses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIWitness","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIWitness"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/init(agents:carboncopies:certifieddeliveries:currentroutingorder:editors:errordetails:inpersonsigners:intermediaries:notaries:recipientcount:seals:signers:witnesses:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAgents:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIAgent *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"agents"},{"kind":"text","text":" "},{"kind":"identifier","text":"carbonCopies:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPICarbonCopy *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"carbonCopies"},{"kind":"text","text":" "},{"kind":"identifier","text":"certifiedDeliveries:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPICertifiedDelivery *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"certifiedDeliveries"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentRoutingOrder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"currentRoutingOrder"},{"kind":"text","text":" "},{"kind":"identifier","text":"editors:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIEditor *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"editors"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"errorDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"inPersonSigners:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIInPersonSigner *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"inPersonSigners"},{"kind":"text","text":" "},{"kind":"identifier","text":"intermediaries:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIIntermediary *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"intermediaries"},{"kind":"text","text":" "},{"kind":"identifier","text":"notaries:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPINotaryRecipient *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"notaries"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"recipientCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"seals:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPISealSign *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"seals"},{"kind":"text","text":" "},{"kind":"identifier","text":"signers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPISigner *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signers"},{"kind":"text","text":" "},{"kind":"identifier","text":"witnesses:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIWitness *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"witnesses"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title","value":"DSAPIRecipients"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipients"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner\/title","value":"DSAPIInPersonSigner"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner\/fragments","value":[{"kind":"identifier","text":"DSAPIInPersonSigner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIWitness\/title","value":"DSAPIWitness"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIWitness\/fragments","value":[{"kind":"identifier","text":"DSAPIWitness"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISigner\/title","value":"DSAPISigner"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISigner\/fragments","value":[{"kind":"identifier","text":"DSAPISigner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAgent\/title","value":"DSAPIAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAgent\/fragments","value":[{"kind":"identifier","text":"DSAPIAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/title","value":"DSAPIIntermediary"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/fragments","value":[{"kind":"identifier","text":"DSAPIIntermediary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEditor\/title","value":"DSAPIEditor"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEditor\/fragments","value":[{"kind":"identifier","text":"DSAPIEditor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISealSign\/title","value":"DSAPISealSign"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISealSign\/fragments","value":[{"kind":"identifier","text":"DSAPISealSign"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICarbonCopy\/title","value":"DSAPICarbonCopy"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICarbonCopy\/fragments","value":[{"kind":"identifier","text":"DSAPICarbonCopy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/title","value":"DSAPICertifiedDelivery"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/fragments","value":[{"kind":"identifier","text":"DSAPICertifiedDelivery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/title","value":"DSAPINotaryRecipient"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/fragments","value":[{"kind":"identifier","text":"DSAPINotaryRecipient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)\/title","value":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}