{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Updates a template document.","type":"text"}],"metadata":{"roleHeading":"Type Method","externalID":"s:11DocuSignAPI09TemplatesC0C46documentsPutTemplateDocumentWithRequestBuilder9accountId08documentM008templateM04body20isEnvelopeDefinitionAA0jK0CyAA013DSAPIEnvelopeH0CGSS_S2SAA0tS0CSgSSSgtFZ","role":"symbol","modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentsPutTemplateDocumentWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","text":"DSAPIEnvelopeDefinition","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"isEnvelopeDefinition","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPIEnvelopeDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument","kind":"typeIdentifier"},{"text":">","kind":"text"}],"symbolKind":"method","title":"documentsPutTemplateDocumentWithRequestBuilder(accountId:documentId:templateId:body:isEnvelopeDefinition:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/documentsPutTemplateDocumentWithRequestBuilder(accountId:documentId:templateId:body:isEnvelopeDefinition:)"},"variants":[{"paths":["\/documentation\/docusignapi\/templatesapi\/documentsputtemplatedocumentwithrequestbuilder(accountid:documentid:templateid:body:isenvelopedefinition:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentsPutTemplateDocumentWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","text":"DSAPIEnvelopeDefinition"},{"text":"? = nil, ","kind":"text"},{"text":"isEnvelopeDefinition","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument","text":"DSAPIEnvelopeDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument","kind":"typeIdentifier"},{"kind":"text","text":">"}]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}],"type":"paragraph"}]},{"name":"documentId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The ID of the document being accessed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(path) The ID of the template being accessed.","type":"text"}]}],"name":"templateId"},{"name":"body","content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}],"name":"isEnvelopeDefinition"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"RequestBuilder","type":"text"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PUT \/v2.1\/accounts\/{accountId}\/templates\/{templateId}\/documents\/{documentId}"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OAuth:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"inlineContent":[{"text":"name: docusignAccessCode","type":"text"}],"type":"paragraph"}]}]}]}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/documentsPutTemplateDocumentWithRequestBuilder(accountId:documentId:templateId:body:isEnvelopeDefinition:)":{"type":"topic","abstract":[{"text":"Updates a template document.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/documentsPutTemplateDocumentWithRequestBuilder(accountId:documentId:templateId:body:isEnvelopeDefinition:)","title":"documentsPutTemplateDocumentWithRequestBuilder(accountId:documentId:templateId:body:isEnvelopeDefinition:)","url":"\/documentation\/docusignapi\/templatesapi\/documentsputtemplatedocumentwithrequestbuilder(accountid:documentid:templateid:body:isenvelopedefinition:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentsPutTemplateDocumentWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"isEnvelopeDefinition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument","kind":"typeIdentifier","text":"DSAPIEnvelopeDocument"},{"kind":"text","text":">"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"title":"DSAPIEnvelopeDefinition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"text":"Envelope object definition.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopedefinition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocument":{"navigatorTitle":[{"text":"DSAPIEnvelopeDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopedocument","role":"symbol","abstract":[{"type":"text","text":"This object contains details about the envelope document."}],"title":"DSAPIEnvelopeDocument","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIEnvelopeDocument"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"url":"\/documentation\/docusignapi\/templatesapi","navigatorTitle":[{"text":"TemplatesAPI","kind":"identifier"}],"kind":"symbol","title":"TemplatesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TemplatesAPI","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument\/title","value":"DSAPIEnvelopeDocument"},{"value":[{"kind":"identifier","text":"DSAPIEnvelopeDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument\/fragments"},{"value":"TemplatesAPI","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","op":"replace","value":[{"text":"TemplatesAPI","kind":"identifier"}]}]}]}