{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lockPostTemplateLockWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockRequest","text":"DSAPILockRequest","preciseIdentifier":"s:11DocuSignAPI16DSAPILockRequestV"},{"text":"? = nil) -> ","kind":"text"},{"text":"RequestBuilder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"text":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}]},{"name":"templateId","content":[{"inlineContent":[{"type":"text","text":"(path) The ID of the template being accessed."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}],"name":"body"}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}],"kind":"content"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"POST \/v2.1\/accounts\/{accountId}\/templates\/{templateId}\/lock"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OAuth:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}]}]}],"type":"unorderedList"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/lockPostTemplateLockWithRequestBuilder(accountId:templateId:body:)"},"variants":[{"paths":["\/documentation\/docusignapi\/templatesapi\/lockposttemplatelockwithrequestbuilder(accountid:templateid:body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockPostTemplateLockWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPILockRequest","preciseIdentifier":"s:11DocuSignAPI16DSAPILockRequestV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","text":"DSAPILockInformation"},{"kind":"text","text":">"}],"title":"lockPostTemplateLockWithRequestBuilder(accountId:templateId:body:)","externalID":"s:11DocuSignAPI09TemplatesC0C38lockPostTemplateLockWithRequestBuilder9accountId08templateM04bodyAA0jK0CyAA20DSAPILockInformationCGSS_SSAA0pJ0VSgtFZ","role":"symbol","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","symbolKind":"method"},"abstract":[{"type":"text","text":"Locks a template."}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation":{"url":"\/documentation\/docusignapi\/dsapilockinformation","title":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILockInformation"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPILockInformation"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"url":"\/documentation\/docusignapi\/templatesapi","navigatorTitle":[{"text":"TemplatesAPI","kind":"identifier"}],"kind":"symbol","title":"TemplatesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TemplatesAPI","kind":"identifier"}],"type":"topic","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/lockPostTemplateLockWithRequestBuilder(accountId:templateId:body:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/lockPostTemplateLockWithRequestBuilder(accountId:templateId:body:)","title":"lockPostTemplateLockWithRequestBuilder(accountId:templateId:body:)","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lockPostTemplateLockWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"DSAPILockRequest","preciseIdentifier":"s:11DocuSignAPI16DSAPILockRequestV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","text":"DSAPILockInformation","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"text":"Locks a template.","type":"text"}],"kind":"symbol","url":"\/documentation\/docusignapi\/templatesapi\/lockposttemplatelockwithrequestbuilder(accountid:templateid:body:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockRequest":{"url":"\/documentation\/docusignapi\/dsapilockrequest","title":"DSAPILockRequest","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPILockRequest","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPILockRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"This request object contains information about the lock that you want to create or update."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"}},"variantOverrides":[{"patch":[{"value":"DSAPILockInformation","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/fragments","value":[{"text":"DSAPILockInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title","value":"TemplatesAPI","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","value":[{"text":"TemplatesAPI","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}