{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/templatesapi\/notificationputtemplatestemplateidnotificationwithrequestbuilder(accountid:templateid:body:)"]}],"metadata":{"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"DocuSignAPI"}],"title":"notificationPutTemplatesTemplateIdNotificationWithRequestBuilder(accountId:templateId:body:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationPutTemplatesTemplateIdNotificationWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPITemplateNotificationRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI32DSAPITemplateNotificationRequestV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotification","kind":"typeIdentifier","text":"DSAPINotification"},{"text":">","kind":"text"}],"externalID":"s:11DocuSignAPI09TemplatesC0C015notificationPutD40TemplateIdNotificationWithRequestBuilder07accountH008templateH04bodyAA0kL0CyAA17DSAPINotificationCGSS_SSAA013DSAPITemplateiK0VSgtFZ","role":"symbol"},"abstract":[{"text":"Updates the notification  structure for an existing template.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationPutTemplatesTemplateIdNotificationWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"templateId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateNotificationRequest","text":"DSAPITemplateNotificationRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI32DSAPITemplateNotificationRequestV"},{"kind":"text","text":"? = nil) -> "},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotification","text":"DSAPINotification","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}]},{"name":"templateId","content":[{"inlineContent":[{"type":"text","text":"(path) The ID of the template being accessed."}],"type":"paragraph"}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"PUT \/v2.1\/accounts\/{accountId}\/templates\/{templateId}\/notification","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"OAuth:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/notificationPutTemplatesTemplateIdNotificationWithRequestBuilder(accountId:templateId:body:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotification":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotification"}],"url":"\/documentation\/docusignapi\/dsapinotification","title":"DSAPINotification","kind":"symbol","abstract":[{"text":"A complex element that specifies the notification settings for the envelope.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPINotification"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/notificationPutTemplatesTemplateIdNotificationWithRequestBuilder(accountId:templateId:body:)":{"type":"topic","abstract":[{"type":"text","text":"Updates the notification  structure for an existing template."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/notificationPutTemplatesTemplateIdNotificationWithRequestBuilder(accountId:templateId:body:)","title":"notificationPutTemplatesTemplateIdNotificationWithRequestBuilder(accountId:templateId:body:)","url":"\/documentation\/docusignapi\/templatesapi\/notificationputtemplatestemplateidnotificationwithrequestbuilder(accountid:templateid:body:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationPutTemplatesTemplateIdNotificationWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"DSAPITemplateNotificationRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI32DSAPITemplateNotificationRequestV"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotification","text":"DSAPINotification","kind":"typeIdentifier"},{"kind":"text","text":">"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateNotificationRequest":{"kind":"symbol","title":"DSAPITemplateNotificationRequest","url":"\/documentation\/docusignapi\/dsapitemplatenotificationrequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateNotificationRequest"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPITemplateNotificationRequest","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateNotificationRequest","type":"topic","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"url":"\/documentation\/docusignapi\/templatesapi","navigatorTitle":[{"text":"TemplatesAPI","kind":"identifier"}],"kind":"symbol","title":"TemplatesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TemplatesAPI","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification\/title","value":"DSAPINotification","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification\/fragments","value":[{"text":"DSAPINotification","kind":"identifier"}]},{"value":"TemplatesAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","value":[{"text":"TemplatesAPI","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}