{"sections":[],"metadata":{"roleHeading":"Type Method","role":"symbol","title":"recipientsDeleteTemplateRecipientsWithRequestBuilder(accountId:templateId:body:)","modules":[{"name":"DocuSignAPI"}],"externalID":"s:11DocuSignAPI09TemplatesC0C52recipientsDeleteTemplateRecipientsWithRequestBuilder9accountId08templateM04bodyAA0jK0CyAA15DSAPIRecipientsCGSS_SSAA013DSAPITemplateH0VSgtFZ","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsDeleteTemplateRecipientsWithRequestBuilder"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateRecipientsV","text":"DSAPITemplateRecipients","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","kind":"typeIdentifier","text":"DSAPIRecipients"},{"text":">","kind":"text"}]},"abstract":[{"type":"text","text":"Deletes recipients from a template."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/recipientsDeleteTemplateRecipientsWithRequestBuilder(accountId:templateId:body:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recipientsDeleteTemplateRecipientsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRecipients","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateRecipientsV","text":"DSAPITemplateRecipients"},{"text":"? = nil) -> ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","text":"RequestBuilder"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"typeIdentifier","text":"DSAPIRecipients","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients"},{"kind":"text","text":">"}]}]},{"parameters":[{"name":"accountId","content":[{"inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}],"type":"paragraph"}]},{"name":"templateId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The ID of the template being accessed.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}],"name":"body"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"DELETE \/v2.1\/accounts\/{accountId}\/templates\/{templateId}\/recipients","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"OAuth:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"type: oauth2"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"name: docusignAccessCode","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/docusignapi\/templatesapi\/recipientsdeletetemplaterecipientswithrequestbuilder(accountid:templateid:body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateRecipients":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRecipients","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITemplateRecipients"}],"url":"\/documentation\/docusignapi\/dsapitemplaterecipients","title":"DSAPITemplateRecipients","navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateRecipients"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/recipientsDeleteTemplateRecipientsWithRequestBuilder(accountId:templateId:body:)":{"url":"\/documentation\/docusignapi\/templatesapi\/recipientsdeletetemplaterecipientswithrequestbuilder(accountid:templateid:body:)","title":"recipientsDeleteTemplateRecipientsWithRequestBuilder(accountId:templateId:body:)","type":"topic","abstract":[{"text":"Deletes recipients from a template.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recipientsDeleteTemplateRecipientsWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateRecipientsV","text":"DSAPITemplateRecipients"},{"kind":"text","text":"?) -> "},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","kind":"typeIdentifier","text":"DSAPIRecipients"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/recipientsDeleteTemplateRecipientsWithRequestBuilder(accountId:templateId:body:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"url":"\/documentation\/docusignapi\/templatesapi","navigatorTitle":[{"text":"TemplatesAPI","kind":"identifier"}],"kind":"symbol","title":"TemplatesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TemplatesAPI","kind":"identifier"}],"type":"topic","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipients","kind":"identifier"}],"abstract":[{"text":"Specifies the envelope recipients.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapirecipients","title":"DSAPIRecipients","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPIRecipients","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TemplatesAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","op":"replace","value":[{"kind":"identifier","text":"TemplatesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title","value":"DSAPIRecipients"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIRecipients"}]}]}]}