{"kind":"symbol","metadata":{"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","symbolKind":"method","title":"recipientsPutTemplateRecipientTabsWithRequestBuilder(accountId:recipientId:templateId:body:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recipientsPutTemplateRecipientTabsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipientId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI17DSAPITemplateTabsV","text":"DSAPITemplateTabs","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":">"}],"externalID":"s:11DocuSignAPI09TemplatesC0C52recipientsPutTemplateRecipientTabsWithRequestBuilder9accountId09recipientN008templateN04bodyAA0kL0CyAA9DSAPITabsCGSS_S2SAA013DSAPITemplateI0VSgtFZ","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsPutTemplateRecipientTabsWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"templateId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateTabs","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI17DSAPITemplateTabsV","text":"DSAPITemplateTabs"},{"text":"? = nil) -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}]},{"name":"recipientId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The ID of the recipient being accessed.","type":"text"}]}]},{"name":"templateId","content":[{"inlineContent":[{"type":"text","text":"(path) The ID of the template being accessed."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}],"name":"body"}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"RequestBuilder","type":"text"}]}],"kind":"content"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"text":"PUT \/v2.1\/accounts\/{accountId}\/templates\/{templateId}\/recipients\/{recipientId}\/tabs","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"OAuth:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"type: oauth2"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/recipientsPutTemplateRecipientTabsWithRequestBuilder(accountId:recipientId:templateId:body:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"abstract":[{"text":"Updates the tabs for a recipient.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/templatesapi\/recipientsputtemplaterecipienttabswithrequestbuilder(accountid:recipientid:templateid:body:)"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"url":"\/documentation\/docusignapi\/templatesapi","navigatorTitle":[{"text":"TemplatesAPI","kind":"identifier"}],"kind":"symbol","title":"TemplatesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TemplatesAPI","kind":"identifier"}],"type":"topic","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateTabs":{"kind":"symbol","title":"DSAPITemplateTabs","abstract":[],"url":"\/documentation\/docusignapi\/dsapitemplatetabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateTabs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITemplateTabs"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateTabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/recipientsPutTemplateRecipientTabsWithRequestBuilder(accountId:recipientId:templateId:body:)":{"role":"symbol","url":"\/documentation\/docusignapi\/templatesapi\/recipientsputtemplaterecipienttabswithrequestbuilder(accountid:recipientid:templateid:body:)","title":"recipientsPutTemplateRecipientTabsWithRequestBuilder(accountId:recipientId:templateId:body:)","type":"topic","abstract":[{"type":"text","text":"Updates the tabs for a recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/recipientsPutTemplateRecipientTabsWithRequestBuilder(accountId:recipientId:templateId:body:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsPutTemplateRecipientTabsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"DSAPITemplateTabs","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI17DSAPITemplateTabsV"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"text":">","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title","value":"TemplatesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","value":[{"text":"TemplatesAPI","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs","op":"replace"},{"op":"replace","value":[{"text":"DSAPITabs","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments"}]}]}