{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsPostTemplateRecipientsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRecipients","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateRecipientsV","text":"DSAPITemplateRecipients"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"resendEnvelope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","text":"DSAPIRecipients"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"templateId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The ID of the template being accessed."}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]},{"name":"resendEnvelope","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"POST \/v2.1\/accounts\/{accountId}\/templates\/{templateId}\/recipients"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/templatesapi\/recipientsposttemplaterecipientswithrequestbuilder(accountid:templateid:body:resendenvelope:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/recipientsPostTemplateRecipientsWithRequestBuilder(accountId:templateId:body:resendEnvelope:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds tabs for a recipient."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsPostTemplateRecipientsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITemplateRecipients","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateRecipientsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"resendEnvelope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIRecipients","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients"},{"kind":"text","text":">"}],"title":"recipientsPostTemplateRecipientsWithRequestBuilder(accountId:templateId:body:resendEnvelope:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:11DocuSignAPI09TemplatesC0C50recipientsPostTemplateRecipientsWithRequestBuilder9accountId08templateM04body14resendEnvelopeAA0jK0CyAA15DSAPIRecipientsCGSS_SSAA013DSAPITemplateH0VSgSSSgtFZ","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"role":"symbol","title":"RequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestBuilder"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"url":"\/documentation\/docusignapi\/requestbuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/recipientsPostTemplateRecipientsWithRequestBuilder(accountId:templateId:body:resendEnvelope:)":{"role":"symbol","title":"recipientsPostTemplateRecipientsWithRequestBuilder(accountId:templateId:body:resendEnvelope:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsPostTemplateRecipientsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITemplateRecipients","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateRecipientsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"resendEnvelope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIRecipients","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Adds tabs for a recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/recipientsPostTemplateRecipientsWithRequestBuilder(accountId:templateId:body:resendEnvelope:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/templatesapi\/recipientsposttemplaterecipientswithrequestbuilder(accountid:templateid:body:resendenvelope:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"role":"symbol","title":"TemplatesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplatesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TemplatesAPI"}],"url":"\/documentation\/docusignapi\/templatesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"role":"symbol","title":"DSAPIRecipients","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipients"}],"abstract":[{"type":"text","text":"Specifies the envelope recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipients"}],"url":"\/documentation\/docusignapi\/dsapirecipients"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateRecipients":{"role":"symbol","title":"DSAPITemplateRecipients","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITemplateRecipients"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRecipients","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateRecipients"}],"url":"\/documentation\/docusignapi\/dsapitemplaterecipients"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title","value":"TemplatesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","value":[{"kind":"identifier","text":"TemplatesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title","value":"DSAPIRecipients"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipients"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}