{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"templatesGetTemplates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"createdFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"createdToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"folderIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"folderTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"fromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"include"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isDeletedTemplateOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"modifiedFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"modifiedToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"orderBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"searchFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"searchText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"sharedByMe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"startPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"templateIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"toDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"usedFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"usedToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplateResults","text":"DSAPIEnvelopeTemplateResults"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"count","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) Number of records to return in the cache. (optional)"}]}]},{"name":"createdFromDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"createdToDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"folderIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) A comma separated list of folder ID GUIDs. (optional)"}]}]},{"name":"folderTypes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"fromDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) Start of the search date range. Only returns templates created on or after this date\/time. If no value is specified, there is no limit on the earliest date created. (optional)"}]}]},{"name":"include","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) A comma separated list of additional template attributes to include in the response. Valid values are: recipients, folders, documents, custom_fields, and notifications. (optional)"}]}]},{"name":"isDeletedTemplateOnly","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"isDownload","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"modifiedFromDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"modifiedToDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"order","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) Sets the direction order used to sort the list. Valid values are: -asc = ascending sort order (a to z)  -desc = descending sort order (z to a) (optional)"}]}]},{"name":"orderBy","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) Sets the file attribute used to sort the list. Valid values are:  -name: template name  -modified: date\/time template was last modified.  -used: date\/time the template was last used. (optional)"}]}]},{"name":"searchFields","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"searchText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) The search text used to search the names of templates. (optional)"}]}]},{"name":"sharedByMe","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) If true, the response only includes templates shared by the user. If false, the response only returns template not shared by the user. If not specified, the response is not affected. (optional)"}]}]},{"name":"startPosition","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) The starting index for the first template shown in the response. This must be greater than or equal to 0 (zero). (optional)"}]}]},{"name":"templateIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"toDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) End of the search date range. Only returns templates created up to this date\/time. If no value is provided, this defaults to the current date. (optional)"}]}]},{"name":"usedFromDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) Start of the search date range. Only returns templates used or edited on or after this date\/time. If no value is specified, there is no limit on the earliest date used. (optional)"}]}]},{"name":"usedToDate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) End of the search date range. Only returns templates used or edited up to this date\/time. If no value is provided, this defaults to the current date. (optional)"}]}]},{"name":"userFilter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) Sets if the templates shown in the response Valid values are:  -owned_by_me: only shows templates the user owns.  -shared_with_me: only shows templates that are shared with the user.  -all: shows all templates owned or shared with the user. (optional)"}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/templatesapi\/templatesgettemplates(accountid:count:createdfromdate:createdtodate:folderids:foldertypes:fromdate:include:isdeletedtemplateonly:isdownload:modifiedfromdate:modifiedtodate:order:orderby:searchfields:searchtext:sharedbyme:startposition:templ-87otr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/templatesapi\/templatesgettemplates(accountid:count:createdfromdate:createdtodate:folderids:foldertypes:fromdate:include:isdeletedtemplateonly:isdownload:modifiedfromdate:modifiedtodate:order:orderby:searchfields:searchtext:sharedbyme:startposition:templ-87otr"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the list of templates."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"templatesGetTemplates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"include"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDeletedTemplateOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"modifiedFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"modifiedToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"orderBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sharedByMe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"startPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"templateIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"usedFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"usedToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeTemplateResults","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplateResults"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)TemplatesAPI(cm)templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults":{"role":"symbol","title":"DSAPIEnvelopeTemplateResults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeTemplateResults"}],"abstract":[{"type":"text","text":"Information about templates."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeTemplateResults"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI":{"role":"symbol","title":"TemplatesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplatesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TemplatesAPI"}],"url":"\/documentation\/docusignapi\/templatesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TemplatesAPI/templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)":{"role":"symbol","title":"templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"templatesGetTemplates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"include"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDeletedTemplateOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"modifiedFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"modifiedToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"orderBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sharedByMe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"startPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"templateIds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"usedFromDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"usedToDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeTemplateResults","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplateResults"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Gets the list of templates."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TemplatesAPI\/templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:"}],"url":"\/documentation\/docusignapi\/templatesapi\/templatesgettemplates(accountid:count:createdfromdate:createdtodate:folderids:foldertypes:fromdate:include:isdeletedtemplateonly:isdownload:modifiedfromdate:modifiedtodate:order:orderby:searchfields:searchtext:sharedbyme:startposition:templ-87otr"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"templatesGetTemplatesWithAccountId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"count:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"count"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdFromDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"createdFromDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdToDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"createdToDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"folderIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"folderIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"folderTypes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"folderTypes"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"fromDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"include:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"include"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeletedTemplateOnly:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"isDeletedTemplateOnly"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDownload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"isDownload"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifiedFromDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"modifiedFromDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifiedToDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"modifiedToDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"order:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"order"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderBy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"orderBy"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchFields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"searchFields"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"searchText"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedByMe:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sharedByMe"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"startPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"templateIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"toDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"toDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedFromDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"usedFromDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedToDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"usedToDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"userFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DSAPIEnvelopeTemplateResults *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplateResults#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults\/title","value":"DSAPIEnvelopeTemplateResults"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeTemplateResults"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/title","value":"TemplatesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI\/fragments","value":[{"kind":"identifier","text":"TemplatesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI~1templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)\/title","value":"templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TemplatesAPI~1templatesGetTemplates(accountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"templatesGetTemplatesWithAccountId:count:createdFromDate:createdToDate:folderIds:folderTypes:fromDate:include:isDeletedTemplateOnly:isDownload:modifiedFromDate:modifiedToDate:order:orderBy:searchFields:searchText:sharedByMe:startPosition:templateIds:toDate:usedFromDate:usedToDate:userFilter:userId:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}