{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirations"},{"kind":"text","text":": "},{"text":"DSAPIExpirations","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"text":"? = nil, ","kind":"text"},{"text":"reminders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIReminders","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders"},{"text":"? = nil, ","kind":"text"},{"text":"useAccountDefaults","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification\/init(expirations:reminders:useAccountDefaults:)"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapinotification\/init(expirations:reminders:useaccountdefaults:)"]},{"paths":["\/documentation\/docusignapi\/dsapinotification\/init(expirations:reminders:useaccountdefaults:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"initWithExpirations:reminders:useAccountDefaults:","kind":"identifier"}],"title":"init(expirations:reminders:useAccountDefaults:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirations"},{"text":": ","kind":"text"},{"text":"DSAPIExpirations","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"reminders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","text":"DSAPIReminders"},{"kind":"text","text":"?, "},{"text":"useAccountDefaults","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPINotification(im)initWithExpirations:reminders:useAccountDefaults:","roleHeading":"Initializer"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations":{"type":"topic","role":"symbol","abstract":[{"text":"A complex element that specifies the expiration settings for the envelope. When an envelope expires, it is voided and no longer available for signing. ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" there is a short delay between when the envelope expires and when it is voided."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIExpirations"}],"title":"DSAPIExpirations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIExpirations","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiexpirations","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotification":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotification"}],"url":"\/documentation\/docusignapi\/dsapinotification","title":"DSAPINotification","kind":"symbol","abstract":[{"text":"A complex element that specifies the notification settings for the envelope.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPINotification"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIReminders":{"kind":"symbol","title":"DSAPIReminders","url":"\/documentation\/docusignapi\/dsapireminders","role":"symbol","navigatorTitle":[{"text":"DSAPIReminders","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIReminders"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","type":"topic","abstract":[{"type":"text","text":"A complex element that specifies reminder settings for the envelope."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotification/init(expirations:reminders:useAccountDefaults:)":{"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification\/init(expirations:reminders:useAccountDefaults:)","url":"\/documentation\/docusignapi\/dsapinotification\/init(expirations:reminders:useaccountdefaults:)","title":"init(expirations:reminders:useAccountDefaults:)","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithExpirations:reminders:useAccountDefaults:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirations"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","kind":"typeIdentifier","text":"DSAPIExpirations"},{"text":"?, ","kind":"text"},{"text":"reminders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIReminders","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders"},{"text":"?, ","kind":"text"},{"text":"useAccountDefaults","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithExpirations:reminders:useAccountDefaults:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithExpirations:reminders:useAccountDefaults:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithExpirations:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSAPIExpirations","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations"},{"kind":"text","text":" *) "},{"text":"expirations","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reminders:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSAPIReminders","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders"},{"text":" *) ","kind":"text"},{"text":"reminders","kind":"internalParam"},{"kind":"text","text":" "},{"text":"useAccountDefaults:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"useAccountDefaults","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DSAPIExpirations","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/fragments","op":"replace","value":[{"text":"DSAPIExpirations","kind":"identifier"}]},{"value":"DSAPINotification","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification\/fragments","value":[{"text":"DSAPINotification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/title","value":"DSAPIReminders"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/fragments","value":[{"text":"DSAPIReminders","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification~1init(expirations:reminders:useAccountDefaults:)\/title","value":"initWithExpirations:reminders:useAccountDefaults:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification~1init(expirations:reminders:useAccountDefaults:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithExpirations:reminders:useAccountDefaults:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}