{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"agentCanEditName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/agentCanEditName"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/agentcaneditname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/agentcaneditname"]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentCanEditName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"agentCanEditName","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery(py)agentCanEditName","roleHeading":"Instance Property","navigatorTitle":[{"text":"agentCanEditName","kind":"identifier"}]},"abstract":[{"text":"Optional element. When ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"text":" the agents recipient associated with this recipient can change the recipient's pre-populated name. This element is only active if enabled for the account.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery/agentCanEditName":{"type":"topic","url":"\/documentation\/docusignapi\/dsapicertifieddelivery\/agentcaneditname","abstract":[{"text":"Optional element. When ","type":"text"},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"text":" the agents recipient associated with this recipient can change the recipient's pre-populated name. This element is only active if enabled for the account.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"agentCanEditName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/agentCanEditName","navigatorTitle":[{"kind":"identifier","text":"agentCanEditName"}],"role":"symbol","title":"agentCanEditName"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"abstract":[{"text":"Contains information about a certified delivery recipient. Certified delivery recipients must receive the completed documents for the envelope to be completed. However, they don't need to sign, initial, date or add information to any of the documents.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapicertifieddelivery","kind":"symbol","title":"DSAPICertifiedDelivery","role":"symbol","navigatorTitle":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"agentCanEditName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"agentCanEditName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"agentCanEditName","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"agentCanEditName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1agentCanEditName\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1agentCanEditName\/fragments","value":[{"text":"agentCanEditName","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/title","value":"DSAPICertifiedDelivery","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/fragments","value":[{"kind":"identifier","text":"DSAPICertifiedDelivery"}],"op":"replace"}]}]}