{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedCount"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/completedCount","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"]]},"abstract":[{"type":"text","text":"Indicates the number of times that the recipient has been through a signing completion for the envelope. If this number is greater than 0 for a signing group, only the user who previously completed may sign again. This property is read-only."}],"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery(py)completedCount","roleHeading":"Instance Property","title":"completedCount","navigatorTitle":[{"text":"completedCount","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"completedCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"DocuSignAPI"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/completedcount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/completedcount"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"abstract":[{"text":"Contains information about a certified delivery recipient. Certified delivery recipients must receive the completed documents for the envelope to be completed. However, they don't need to sign, initial, date or add information to any of the documents.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapicertifieddelivery","kind":"symbol","title":"DSAPICertifiedDelivery","role":"symbol","navigatorTitle":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery/completedCount":{"type":"topic","url":"\/documentation\/docusignapi\/dsapicertifieddelivery\/completedcount","abstract":[{"text":"Indicates the number of times that the recipient has been through a signing completion for the envelope. If this number is greater than 0 for a signing group, only the user who previously completed may sign again. This property is read-only.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/completedCount","navigatorTitle":[{"kind":"identifier","text":"completedCount"}],"role":"symbol","title":"completedCount"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"completedCount"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"completedCount"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"completedCount"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/title","value":"DSAPICertifiedDelivery"},{"op":"replace","value":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1completedCount\/title","value":"completedCount"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1completedCount\/fragments","value":[{"text":"completedCount","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}