{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/signedDateTime"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Reserved for DocuSign."}],"variants":[{"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/signeddatetime"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/signeddatetime"]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signedDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery(py)signedDateTime","navigatorTitle":[{"text":"signedDateTime","kind":"identifier"}],"title":"signedDateTime","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"signedDateTime","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"]]},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery/signedDateTime":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapicertifieddelivery\/signeddatetime","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/signedDateTime","navigatorTitle":[{"kind":"identifier","text":"signedDateTime"}],"abstract":[{"type":"text","text":"Reserved for DocuSign."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signedDateTime"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"signedDateTime","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"abstract":[{"text":"Contains information about a certified delivery recipient. Certified delivery recipients must receive the completed documents for the envelope to be completed. However, they don't need to sign, initial, date or add information to any of the documents.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapicertifieddelivery","kind":"symbol","title":"DSAPICertifiedDelivery","role":"symbol","navigatorTitle":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"signedDateTime","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"signedDateTime","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"signedDateTime"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"signedDateTime","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1signedDateTime\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1signedDateTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"signedDateTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/title","value":"DSAPICertifiedDelivery"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/fragments","value":[{"kind":"identifier","text":"DSAPICertifiedDelivery"}]}]}]}