{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialAuthentications"},{"kind":"text","text":": ["},{"text":"DSAPISocialAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication"},{"text":"]?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/socialauthentications"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapicertifieddelivery\/socialauthentications"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"]]},"abstract":[{"type":"text","text":"Deprecated."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/socialAuthentications","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery(py)socialAuthentications","modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"socialAuthentications","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialAuthentications"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"socialAuthentications"}],"symbolKind":"property"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"abstract":[{"text":"Contains information about a certified delivery recipient. Certified delivery recipients must receive the completed documents for the envelope to be completed. However, they don't need to sign, initial, date or add information to any of the documents.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapicertifieddelivery","kind":"symbol","title":"DSAPICertifiedDelivery","role":"symbol","navigatorTitle":[{"text":"DSAPICertifiedDelivery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICertifiedDelivery/socialAuthentications":{"type":"topic","url":"\/documentation\/docusignapi\/dsapicertifieddelivery\/socialauthentications","abstract":[{"text":"Deprecated.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"socialAuthentications","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICertifiedDelivery\/socialAuthentications","navigatorTitle":[{"text":"socialAuthentications","kind":"identifier"}],"role":"symbol","title":"socialAuthentications"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication","type":"topic","navigatorTitle":[{"text":"DSAPISocialAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","role":"symbol","title":"DSAPISocialAuthentication","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"socialAuthentications","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"socialAuthentications"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DSAPISocialAuthentication *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"socialAuthentications"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DSAPICertifiedDelivery","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/title"},{"value":[{"kind":"identifier","text":"DSAPICertifiedDelivery"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1socialAuthentications\/title","value":"socialAuthentications"},{"value":[{"kind":"identifier","text":"socialAuthentications"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICertifiedDelivery~1socialAuthentications\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title","op":"replace","value":"DSAPISocialAuthentication"},{"value":[{"text":"DSAPISocialAuthentication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}