{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/init(basePath:customHeaders:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"basePath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customHeaders"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/HeadersDict","preciseIdentifier":"s:11DocuSignAPI11HeadersDicta","kind":"typeIdentifier","text":"HeadersDict"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/docusignapi\/dsclientapi\/init(basepath:customheaders:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsclientapi\/init(basepath:customheaders:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DocuSignAPI@objc(cs)DSClientAPI(im)initWithBasePath:customHeaders:","modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"init(basePath:customHeaders:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"basePath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"customHeaders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeadersDict","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI11HeadersDicta"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBasePath:customHeaders:"}],"symbolKind":"init"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI/init(basePath:customHeaders:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/init(basePath:customHeaders:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"basePath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"customHeaders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeadersDict","preciseIdentifier":"s:11DocuSignAPI11HeadersDicta","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"init(basePath:customHeaders:)","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBasePath:customHeaders:"}],"url":"\/documentation\/docusignapi\/dsclientapi\/init(basepath:customheaders:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI":{"navigatorTitle":[{"text":"DSClientAPI","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsclientapi","role":"symbol","title":"DSClientAPI","abstract":[],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSClientAPI"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/HeadersDict":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/HeadersDict","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"HeadersDict","kind":"identifier"}],"type":"topic","abstract":[],"title":"HeadersDict","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HeadersDict","kind":"identifier"}],"url":"\/documentation\/docusignapi\/headersdict"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithBasePath:customHeaders:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBasePath:customHeaders:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBasePath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"basePath"},{"kind":"text","text":" "},{"text":"customHeaders:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"customHeaders"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"initWithBasePath:customHeaders:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1init(basePath:customHeaders:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBasePath:customHeaders:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1init(basePath:customHeaders:)\/fragments"},{"value":"DSClientAPI","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI\/title"},{"value":[{"text":"DSClientAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI\/fragments"}]}]}