{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bccEmailAddresses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBccEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIBccEmailAddress","text":"DSAPIBccEmailAddress"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiemailsettings\/bccemailaddresses"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiemailsettings\/bccemailaddresses"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailSettings\/bccEmailAddresses","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An array containing the email address that should receive a copy of all email communications related to an envelope for archiving purposes. Maximum Length: 100 characters.  While this property is an array, note that it takes only a single email address.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Only users with the `canManageAccount` setting set to "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":" can use this option.   DocuSign verifies that the email format is correct, but does not verify that the email address is active. You can use this for archiving purposes. However, using this property overrides the BCC for Email Archive information setting for this envelope.   "},{"type":"strong","inlineContent":[{"type":"text","text":"Example:"}]},{"type":"text","text":" if your account has BCC for Email Archive set up for the email address archive@mycompany.com and you send an envelope using the BCC Email Override to send a BCC email to salesarchive@mycompany.com, then a copy of the envelope is only sent to the salesarchive@mycompany.com email address."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bccEmailAddresses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBccEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIBccEmailAddress"},{"kind":"text","text":"]?"}],"title":"bccEmailAddresses","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailSettings(py)bccEmailAddresses","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"bccEmailAddresses"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailSettings"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmailSettings":{"role":"symbol","title":"DSAPIEmailSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEmailSettings"}],"abstract":[{"type":"text","text":"A complex element that allows  the sender to override some envelope email setting information. This can be used to override the Reply To email address and name associated with the envelope and to override the BCC email addresses to which an envelope is sent.   When the emailSettings information is used for an envelope, it only applies to that envelope.   "},{"type":"strong","inlineContent":[{"type":"text","text":"IMPORTANT:"}]},{"type":"text","text":" The emailSettings information is not returned in the GET for envelope status. Use GET \/email_settings to return information about the emailSettings.   EmailSettings consists of:   * replyEmailAddressOverride - The Reply To email used for the envelope. DocuSign will verify that a correct email format is used, but does not verify that the email is active. Maximum Length: 100 characters. * replyEmailNameOverride - The name associated with the Reply To email address. Maximum Length: 100 characters. * bccEmailAddresses - An array of up to five email addresses to which the envelope is sent to as a BCC email. Only users with canManageAccount setting set to true can use this option.  DocuSign verifies that the email format is correct, but does not verify that the email is active. Using this overrides the BCC for Email Archive information setting for this envelope. Maximum Length: 100 characters. "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Example"}]},{"type":"text","text":": if your account has BCC for Email Archive set up for the email address 'archive@mycompany.com' and you send an envelope using the BCC Email Override to send a BCC email to 'salesarchive@mycompany.com', then a copy of the envelope is only sent to the 'salesarchive@mycompany.com' email address."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEmailSettings"}],"url":"\/documentation\/docusignapi\/dsapiemailsettings"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmailSettings/bccEmailAddresses":{"role":"symbol","title":"bccEmailAddresses","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bccEmailAddresses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBccEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIBccEmailAddress"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array containing the email address that should receive a copy of all email communications related to an envelope for archiving purposes. Maximum Length: 100 characters.  While this property is an array, note that it takes only a single email address.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Only users with the `canManageAccount` setting set to "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":" can use this option.   DocuSign verifies that the email format is correct, but does not verify that the email address is active. You can use this for archiving purposes. However, using this property overrides the BCC for Email Archive information setting for this envelope.   "},{"type":"strong","inlineContent":[{"type":"text","text":"Example:"}]},{"type":"text","text":" if your account has BCC for Email Archive set up for the email address archive@mycompany.com and you send an envelope using the BCC Email Override to send a BCC email to salesarchive@mycompany.com, then a copy of the envelope is only sent to the salesarchive@mycompany.com email address."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailSettings\/bccEmailAddresses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bccEmailAddresses"}],"url":"\/documentation\/docusignapi\/dsapiemailsettings\/bccemailaddresses"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBccEmailAddress":{"role":"symbol","title":"DSAPIBccEmailAddress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBccEmailAddress"}],"abstract":[{"type":"text","text":"Contains information about the BCC email address."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBccEmailAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBccEmailAddress"}],"url":"\/documentation\/docusignapi\/dsapibccemailaddress"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bccEmailAddresses"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bccEmailAddresses"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DSAPIBccEmailAddress *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bccEmailAddresses"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailSettings\/title","value":"DSAPIEmailSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailSettings\/fragments","value":[{"kind":"identifier","text":"DSAPIEmailSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailSettings~1bccEmailAddresses\/title","value":"bccEmailAddresses"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailSettings~1bccEmailAddresses\/fragments","value":[{"kind":"identifier","text":"bccEmailAddresses"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIBccEmailAddress\/title","value":"DSAPIBccEmailAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIBccEmailAddress\/fragments","value":[{"kind":"identifier","text":"DSAPIBccEmailAddress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}