{"variants":[{"paths":["\/documentation\/docusignapi\/dsapifoldersresponse\/init(endposition:envelopes:folders:nexturi:previousuri:resultsetsize:startposition:totalsetsize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapifoldersresponse\/init(endposition:envelopes:folders:nexturi:previousuri:resultsetsize:startposition:totalsetsize:)"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersResponse"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"endPosition"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"envelopes"},{"text":": [","kind":"text"},{"text":"DSAPIEnvelopeSummary","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"folders","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIFolder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"nextUri"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"previousUri","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"resultSetSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"startPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"totalSetSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersResponse\/init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)"},"sections":[],"metadata":{"title":"init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:","kind":"identifier"}],"modules":[{"name":"DocuSignAPI"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIFoldersResponse(im)initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"endPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"envelopes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIEnvelopeSummary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary"},{"text":"]?, ","kind":"text"},{"text":"folders","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"nextUri"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"previousUri","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"resultSetSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"startPosition"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"totalSetSize"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"symbolKind":"init","role":"symbol"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolder":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFolder"}],"url":"\/documentation\/docusignapi\/dsapifolder","title":"DSAPIFolder","kind":"symbol","abstract":[{"type":"text","text":"This object contains details about a folder."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFolder"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFoldersResponse":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFoldersResponse","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapifoldersresponse","title":"DSAPIFoldersResponse","navigatorTitle":[{"text":"DSAPIFoldersResponse","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFoldersResponse/init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)":{"kind":"symbol","abstract":[],"title":"init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"endPosition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"envelopes"},{"kind":"text","text":": ["},{"text":"DSAPIEnvelopeSummary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"folders"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder","text":"DSAPIFolder","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"nextUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"text":"previousUri","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"resultSetSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"startPosition"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"totalSetSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersResponse\/init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","url":"\/documentation\/docusignapi\/dsapifoldersresponse\/init(endposition:envelopes:folders:nexturi:previousuri:resultsetsize:startposition:totalsetsize:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeSummary":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeSummary"}],"title":"DSAPIEnvelopeSummary","url":"\/documentation\/docusignapi\/dsapienvelopesummary","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeSummary","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIEnvelopeSummary"}],"kind":"symbol","abstract":[{"text":"This object describes an envelope.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithEndPosition:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"endPosition"},{"text":" ","kind":"text"},{"kind":"identifier","text":"envelopes:"},{"kind":"text","text":"("},{"text":"NSArray<DSAPIEnvelopeSummary *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"envelopes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"folders:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DSAPIFolder *>"},{"kind":"text","text":" *) "},{"text":"folders","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextUri:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nextUri"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousUri:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previousUri"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultSetSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"resultSetSize"},{"kind":"text","text":" "},{"text":"startPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"startPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalSetSize:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"totalSetSize"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/title","value":"DSAPIFolder"},{"value":[{"text":"DSAPIFolder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/fragments","op":"replace"},{"value":"DSAPIFoldersResponse","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFoldersResponse\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFoldersResponse\/fragments","value":[{"text":"DSAPIFoldersResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFoldersResponse~1init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)\/title","op":"replace","value":"initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEndPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFoldersResponse~1init(endPosition:envelopes:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeSummary\/title","value":"DSAPIEnvelopeSummary","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeSummary\/fragments","op":"replace","value":[{"text":"DSAPIEnvelopeSummary","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}