{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPISsn(py)anchorAllowWhiteSpaceInCharactersMetadata","title":"anchorAllowWhiteSpaceInCharactersMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn"]]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapissn\/anchorallowwhitespaceincharactersmetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapissn\/anchorallowwhitespaceincharactersmetadata"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn\/anchorAllowWhiteSpaceInCharactersMetadata","interfaceLanguage":"swift"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISsn/anchorAllowWhiteSpaceInCharactersMetadata":{"type":"topic","role":"symbol","title":"anchorAllowWhiteSpaceInCharactersMetadata","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapissn\/anchorallowwhitespaceincharactersmetadata","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn\/anchorAllowWhiteSpaceInCharactersMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISsn":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISsn"}],"abstract":[{"type":"text","text":"A one-line field that allows the recipient to enter a Social Security Number. The SSN can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for SSN information."}],"url":"\/documentation\/docusignapi\/dsapissn","navigatorTitle":[{"kind":"identifier","text":"DSAPISsn"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn","kind":"symbol","role":"symbol","type":"topic","title":"DSAPISsn"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"anchorAllowWhiteSpaceInCharactersMetadata"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":" * ","kind":"text"},{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"anchorAllowWhiteSpaceInCharactersMetadata","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn~1anchorAllowWhiteSpaceInCharactersMetadata\/title"},{"op":"replace","value":[{"text":"anchorAllowWhiteSpaceInCharactersMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn~1anchorAllowWhiteSpaceInCharactersMetadata\/fragments"},{"op":"replace","value":"DSAPISsn","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn\/title"},{"value":[{"text":"DSAPISsn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","op":"replace","value":"DSAPIPropertyMetadata"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"op":"replace"}]}]}