{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"checkboxTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox","text":"DSAPICheckbox","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","text":"DSAPIRadioGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"senderCompanyTabs"},{"text":": [","kind":"text"},{"text":"DSAPISenderCompany","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISenderCompany","preciseIdentifier":"s:11DocuSignAPI18DSAPISenderCompanyV"},{"text":"]? = nil, ","kind":"text"},{"text":"senderNameTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISenderName","preciseIdentifier":"s:11DocuSignAPI15DSAPISenderNameV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISenderName"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"tabGroups"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","text":"DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup"},{"kind":"text","text":"]? = nil, "},{"text":"textTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText","text":"DSAPIText"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiprefilltabs\/init(checkboxtabs:radiogrouptabs:sendercompanytabs:sendernametabs:tabgroups:texttabs:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs\/init(checkboxTabs:radioGroupTabs:senderCompanyTabs:senderNameTabs:tabGroups:textTabs:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11DocuSignAPI16DSAPIPrefillTabsV08checkboxE0010radioGroupE0013senderCompanyE00i4NameE09tabGroups04textE0ACSayAA13DSAPICheckboxCGSg_SayAA010DSAPIRadioH0CGSgSayAA011DSAPISenderJ0VGSgSayAA0qK0VGSgSayAA08DSAPITabH0CGSgSayAA9DSAPITextCGSgtcfc","roleHeading":"Initializer","title":"init(checkboxTabs:radioGroupTabs:senderCompanyTabs:senderNameTabs:tabGroups:textTabs:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"checkboxTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox","text":"DSAPICheckbox","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"radioGroupTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup","text":"DSAPIRadioGroup","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"senderCompanyTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISenderCompany","preciseIdentifier":"s:11DocuSignAPI18DSAPISenderCompanyV"},{"text":"]?, ","kind":"text"},{"text":"senderNameTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI15DSAPISenderNameV","text":"DSAPISenderName","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"tabGroups","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup","text":"DSAPITabGroup"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"textTabs"},{"kind":"text","text":": ["},{"text":"DSAPIText","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"text":"]?)","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"symbolKind":"init"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadioGroup":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIRadioGroup"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiradiogroup","role":"symbol","abstract":[{"text":"This group tab is used to place radio buttons on a document. The `radios` property contains a list of ","type":"text"},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","isActive":true},{"text":" objects  associated with the group. Only one radio button can be selected in a group.","type":"text"}],"title":"DSAPIRadioGroup","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIRadioGroup","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIText":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIText"}],"url":"\/documentation\/docusignapi\/dsapitext","title":"DSAPIText","abstract":[{"text":"A tab that allows the recipient to enter any type of text.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIText"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPrefillTabs/init(checkboxTabs:radioGroupTabs:senderCompanyTabs:senderNameTabs:tabGroups:textTabs:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"checkboxTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPICheckbox","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup","kind":"typeIdentifier","text":"DSAPIRadioGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"senderCompanyTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI18DSAPISenderCompanyV","kind":"typeIdentifier","text":"DSAPISenderCompany"},{"text":"]?, ","kind":"text"},{"text":"senderNameTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPISenderName","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI15DSAPISenderNameV"},{"kind":"text","text":"]?, "},{"text":"tabGroups","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup","kind":"typeIdentifier","text":"DSAPITabGroup"},{"kind":"text","text":"]?, "},{"text":"textTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIText","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"text":"]?)","kind":"text"}],"title":"init(checkboxTabs:radioGroupTabs:senderCompanyTabs:senderNameTabs:tabGroups:textTabs:)","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs\/init(checkboxTabs:radioGroupTabs:senderCompanyTabs:senderNameTabs:tabGroups:textTabs:)","url":"\/documentation\/docusignapi\/dsapiprefilltabs\/init(checkboxtabs:radiogrouptabs:sendercompanytabs:sendernametabs:tabgroups:texttabs:)"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/":{"titleInlineContent":[{"text":"`radio`","type":"text"}],"title":"`radio`","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","type":"link","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPrefillTabs":{"kind":"symbol","title":"DSAPIPrefillTabs","abstract":[{"text":"Prefill tabs are tabs that the sender can fill in before the envelope is sent. They are sometimes called sender tags or pre-fill fields.  Only the following tab types can be prefill tabs:  - text - check boxes - radio buttons    [Pre-Fill Your Own Document Fields][app] describes how prefill tabs work in the web application.   [Customize your envelopes with pre-fill fields][catblog] shows how to use prefill tabs in your application using the eSignature SDKs.  [app]:      https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-prefill-fields [catblog]:  https:\/\/www.docusign.com\/blog\/developers\/common-api-tasks-customize-your-envelopes-pre-fill-fields","type":"text"}],"url":"\/documentation\/docusignapi\/dsapiprefilltabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIPrefillTabs"}],"navigatorTitle":[{"text":"DSAPIPrefillTabs","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISenderCompany":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISenderCompany","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPISenderCompany","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapisendercompany","title":"DSAPISenderCompany","navigatorTitle":[{"text":"DSAPISenderCompany","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicheckbox","abstract":[{"type":"text","text":"A tab that allows the recipient to select a yes\/no (on\/off) option."}],"title":"DSAPICheckbox","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPICheckbox","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICheckbox"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISenderName":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPISenderName"}],"type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapisendername","abstract":[],"title":"DSAPISenderName","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISenderName","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPISenderName","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabGroup":{"navigatorTitle":[{"kind":"identifier","text":"DSAPITabGroup"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","type":"topic","title":"DSAPITabGroup","url":"\/documentation\/docusignapi\/dsapitabgroup","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabGroup"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/title","value":"DSAPIRadioGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/fragments","value":[{"kind":"identifier","text":"DSAPIRadioGroup"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/title","value":"DSAPIText","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/fragments","value":[{"kind":"identifier","text":"DSAPIText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/title","value":"DSAPICheckbox"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/fragments","op":"replace","value":[{"text":"DSAPICheckbox","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/title","value":"DSAPITabGroup"},{"value":[{"text":"DSAPITabGroup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}