# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIApp
  pod 'DocuSign', :git => 'https://github.com/docusign/native-ios-sdk.git', :branch => "release/2.5.3-legacy"

  target 'SwiftUIAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIAppUITests' do
    # Pods for testing
  end

end
