{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A string specifying the group in which to place the guided form HTML. Each group displays as a separate guided forms page in the signing experience.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapisignerattachment\/formpagelabel"]},{"paths":["\/documentation\/docusignapi\/dsapisignerattachment\/formpagelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment"]]},"metadata":{"title":"formPageLabel","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formPageLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment(py)formPageLabel","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"formPageLabel","kind":"identifier"}],"modules":[{"name":"DocuSignAPI"}]},"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment\/formPageLabel","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"formPageLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignerAttachment/formPageLabel":{"title":"formPageLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"formPageLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A string specifying the group in which to place the guided form HTML. Each group displays as a separate guided forms page in the signing experience."}],"url":"\/documentation\/docusignapi\/dsapisignerattachment\/formpagelabel","role":"symbol","navigatorTitle":[{"text":"formPageLabel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment\/formPageLabel","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignerAttachment":{"title":"DSAPISignerAttachment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignerAttachment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPISignerAttachment"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to attach supporting documents to an envelope."}],"url":"\/documentation\/docusignapi\/dsapisignerattachment"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"formPageLabel","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"formPageLabel","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"formPageLabel"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment~1formPageLabel\/title","op":"replace","value":"formPageLabel"},{"op":"replace","value":[{"kind":"identifier","text":"formPageLabel"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment~1formPageLabel\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment\/title","op":"replace","value":"DSAPISignerAttachment"},{"op":"replace","value":[{"text":"DSAPISignerAttachment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment\/fragments"}]}]}