#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESRecipientViewRequest
@end

@interface DSESRecipientViewRequest : DSESObject

/* A sender created value that shows the recipient is embedded (captive). \n\nMaximum length: 100 characters. [optional]
 */
@property(nonatomic) NSString* clientUserId;
/* Specifies the user ID of the recipient. You can use with user ID or email and user name to identify the recipient. If user ID is used and a client user ID is provided, the value in the `userId` property must match a recipient ID (which can be retrieved with a GET recipients call) for the envelope. If a user ID is used and a clientUser ID is not provided, the user ID match the user ID of the authenticating user. [optional]
 */
@property(nonatomic) NSString* userId;
/* Specifies the username of the recipient. You can use either email and userName or userId to identify the recipient. [optional]
 */
@property(nonatomic) NSString* userName;
/* Specifies the email of the recipient. You can use either email and userName or userId to identify the recipient. [optional]
 */
@property(nonatomic) NSString* email;
/* Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document. [optional]
 */
@property(nonatomic) NSString* recipientId;
/* The URL the recipient is directed to on certain events. DocuSign sends returns to the URL and includes an event parameter that can be used to redirect the recipient to another location. The possible event parameters returned are: \n\n* cancel (recipient cancels signing)\n* decline (recipient declines signing)\n* exception (exception occurs)\n* fax_pending (recipient has fax pending)\n* check); session_timeout (session times out)\n* completes signing)\n* expires)\n* viewing_complete (recipient completes viewing the envelope)\n\n## Important: You must include HTTPS:// in the URL or the redirect might be blocked by some browsers. [optional]
 */
@property(nonatomic) NSString* returnUrl;
/* A client Url to be pinged by the DocuSign Signing experience to indicate to the client that Signing is active. An HTTP Get is executed against the client. The response from the client is ignored. The intent is for the client to reset it's session timer when the request is received. [optional]
 */
@property(nonatomic) NSString* pingUrl;
/* Only used if pingUrl is specified. This is the interval, in seconds, between pings on the pingUrl.  The default is 300 seconds. Valid values are 60-1200 seconds. [optional]
 */
@property(nonatomic) NSString* pingFrequency;
/* A sender created value that indicates the convention used to authenticate the signer. This information is included in the Certificate of Completion. [optional]
 */
@property(nonatomic) NSString* authenticationMethod;
/* A unique identifier of the authentication event executed by the client application. [optional]
 */
@property(nonatomic) NSString* assertionId;
/* A sender generated value that indicates the date/time that the signer was authenticated. [optional]
 */
@property(nonatomic) NSString* authenticationInstant;
/* The domain in which the user authenticated. [optional]
 */
@property(nonatomic) NSString* securityDomain;

@end
