#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESSsn9InformationInput
@end

@interface DSESSsn9InformationInput : DSESObject

/* The recipient's Social Security Number(SSN). [optional]
 */
@property(nonatomic) NSString* ssn9;
/* Specifies the display level for the recipient. \nValid values are: \n\n* ReadOnly\n* Editable\n* DoNotDisplay [optional]
 */
@property(nonatomic) NSString* displayLevelCode;

@end
