#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESLoginAccount.h>


@protocol DSESLoginInformation
@end

@interface DSESLoginInformation : DSESObject

/* The list of accounts that authenticating user is a member of. [optional]
 */
@property(nonatomic) NSArray<DSESLoginAccount>* loginAccounts;
/* Contains a token that can be used for authentication in API calls instead of using the user name and password. Only returned if the `api_password=true` query string is added to the URL. [optional]
 */
@property(nonatomic) NSString* apiPassword;

@end
