#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESEnvelopeIdsRequest
@end

@interface DSESEnvelopeIdsRequest : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray* /* NSString */ envelopeIds;
/*  [optional]
 */
@property(nonatomic) NSArray* /* NSString */ transactionIds;

@end
