#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESUserInfo.h>


@protocol DSESEnvelopeTemplateDefinition
@end

@interface DSESEnvelopeTemplateDefinition : DSESObject

/* The unique identifier of the template. If this is not provided, DocuSign will generate a value. [optional]
 */
@property(nonatomic) NSString* templateId;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/* When set to **true**, this custom tab is shared. [optional]
 */
@property(nonatomic) NSString* shared;
/*  [optional]
 */
@property(nonatomic) NSString* password;
/*  [optional]
 */
@property(nonatomic) NSString* varNewPassword;
/*  [optional]
 */
@property(nonatomic) NSString* _description;
/*  [optional]
 */
@property(nonatomic) NSString* lastModified;

@property(nonatomic) DSESUserInfo* lastModifiedBy;
/* An integer value specifying the number of document pages in the template. Omit this property if not submitting a page count. [optional]
 */
@property(nonatomic) NSNumber* pageCount;
/*  [optional]
 */
@property(nonatomic) NSString* uri;
/* The name of the folder in which the template is located. [optional]
 */
@property(nonatomic) NSString* folderName;
/* The ID for the folder. [optional]
 */
@property(nonatomic) NSString* folderId;
/* The URI of the folder. [optional]
 */
@property(nonatomic) NSString* folderUri;
/*  [optional]
 */
@property(nonatomic) NSString* parentFolderUri;

@property(nonatomic) DSESUserInfo* owner;

@end
