#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESSenderEmailNotifications
@end

@interface DSESSenderEmailNotifications : DSESObject

/* When set to **true**, the user receives notification that the envelope has been completed. [optional]
 */
@property(nonatomic) NSString* envelopeComplete;
/* When set to **true**, the sender receives notification if the signer changes. [optional]
 */
@property(nonatomic) NSString* changedSigner;
/*  [optional]
 */
@property(nonatomic) NSString* senderEnvelopeDeclined;
/* When set to **true**, the user receives notification if consent is withdrawn. [optional]
 */
@property(nonatomic) NSString* withdrawnConsent;
/* When set to **true**, the sender receives notification that the recipient viewed the enveloper. [optional]
 */
@property(nonatomic) NSString* recipientViewed;
/* When set to **true**, the sender receives notification if the delivery of the envelope fails. [optional]
 */
@property(nonatomic) NSString* deliveryFailed;
/* When set to **true**, the user receives notification if the offline signing failed. [optional]
 */
@property(nonatomic) NSString* offlineSigningFailed;

@end
