#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESDocumentTemplate.h>


@protocol DSESDocumentTemplateList
@end

@interface DSESDocumentTemplateList : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray<DSESDocumentTemplate>* documentTemplates;

@end
