#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESFileType
@end

@interface DSESFileType : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* fileExtension;
/* The mime-type of a file type listed in a fileTypes collection. [optional]
 */
@property(nonatomic) NSString* mimeType;

@end
