#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESFileType.h>


@protocol DSESFileTypeList
@end

@interface DSESFileTypeList : DSESObject

/* A collection of file types. [optional]
 */
@property(nonatomic) NSArray<DSESFileType>* fileTypes;

@end
