#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESBccEmailAddress.h>


@protocol DSESEmailSettings
@end

@interface DSESEmailSettings : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* replyEmailAddressOverride;
/*  [optional]
 */
@property(nonatomic) NSString* replyEmailNameOverride;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESBccEmailAddress>* bccEmailAddresses;

@end
