#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESTabMetadataList.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESTabMetadata.h>
#import <DocuSignSDK/DSESObject.h>
#import <DocuSignSDK/DSESApiClient.h>


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */
 


/**
 * 
 */
 

@interface DSESCustomTabsApi_ListOptions : DSESObject
/*
 * customTabOnly When set to **true**, only custom tabs are returned in the response.
 */
@property NSString* customTabOnly;

@end






 
@interface DSESCustomTabsApi: NSObject

@property(nonatomic, assign)DSESApiClient *apiClient;

-(instancetype) initWithApiClient:(DSESApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DSESCustomTabsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DSESCustomTabsApi*) sharedAPI;

///
///
/// Gets a list of all account tabs.
/// Retrieves a list of all tabs associated with the account.
///
///  @param accountId The external account number (int) or account ID Guid.
///
///
/// @param DSESCustomTabsApi_ListOptions  Options for modifying the request.
/// @return DSESTabMetadataList*

-(NSNumber*) listWithCompletionBlock :(NSString*) accountId  
     
    
    completionHandler: (void (^)(DSESTabMetadataList* output, NSError* error))completionBlock;
    




///
///
/// Gets a list of all account tabs.
/// Retrieves a list of all tabs associated with the account.
///
///  @param accountId The external account number (int) or account ID Guid.
///
///
/// @param DSESCustomTabsApi_ListOptions  Options for modifying the request.
/// @return DSESTabMetadataList*

-(NSNumber*) listWithCompletionBlock :(NSString*) accountId  
     
     options:(DSESCustomTabsApi_ListOptions*) options
    
    completionHandler: (void (^)(DSESTabMetadataList* output, NSError* error))completionBlock;
    


	
	



///
///
/// Creates a custom tab.
/// Creates a tab with pre-defined properties, such as a text tab with a certain font type and validation pattern. Users can access the custom tabs when sending documents through the DocuSign web application.\n\nCustom tabs can be created for approve, checkbox, company, date, date signed, decline, email, email address, envelope ID, first name, formula, full name, initial here, last name, list, note, number, radio, sign here, signer attachment, SSN, text, title, and zip tabs.
///
///  @param accountId The external account number (int) or account ID Guid.
///
/// @param tabMetadata TBD Description 
///
/// @return DSESTabMetadata*

-(NSNumber*) createWithCompletionBlock :(NSString*) accountId  
    tabMetadata:(DSESTabMetadata*) tabMetadata 
    
    
    completionHandler: (void (^)(DSESTabMetadata* output, NSError* error))completionBlock;
    


	
	



///
///
/// Gets custom tab information.
/// Retrieves information about the requested custom tab on the specified account.
///
///  @param accountId The external account number (int) or account ID Guid.
///  @param customTabId 
///
///
///
/// @return DSESTabMetadata*

-(NSNumber*) getWithCompletionBlock :(NSString*) accountId 
     customTabId:(NSString*) customTabId  
     
    
    
    completionHandler: (void (^)(DSESTabMetadata* output, NSError* error))completionBlock;
    


	
	



///
///
/// Updates custom tab information.
/// Updates the information in a custom tab for the specified account.
///
///  @param accountId The external account number (int) or account ID Guid.
///  @param customTabId 
///
/// @param tabMetadata TBD Description 
///
/// @return DSESTabMetadata*

-(NSNumber*) updateWithCompletionBlock :(NSString*) accountId 
     customTabId:(NSString*) customTabId  
    tabMetadata:(DSESTabMetadata*) tabMetadata 
    
    
    completionHandler: (void (^)(DSESTabMetadata* output, NSError* error))completionBlock;
    


	
	



///
///
/// Deletes custom tab information.
/// Deletes the custom from the specified account.
///
///  @param accountId The external account number (int) or account ID Guid.
///  @param customTabId 
///
///
///
/// @return 

-(NSNumber*) deleteWithCompletionBlock :(NSString*) accountId 
     customTabId:(NSString*) customTabId  
     
    
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


	
	

@end
