#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESServiceInformation.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESResourceInformation.h>
#import <DocuSignSDK/DSESApiRequestLogsResult.h>
#import <DocuSignSDK/DSESDiagnosticsSettingsInformation.h>
#import <DocuSignSDK/DSESObject.h>
#import <DocuSignSDK/DSESApiClient.h>


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */
 


/**
 * 
 */
 



@interface DSESDiagnosticsApi_ListRequestLogsOptions : DSESObject
/*
 * encoding 
 */
@property NSString* encoding;

@end






 
@interface DSESDiagnosticsApi: NSObject

@property(nonatomic, assign)DSESApiClient *apiClient;

-(instancetype) initWithApiClient:(DSESApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DSESDiagnosticsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DSESDiagnosticsApi*) sharedAPI;



///
///
/// Retrieves the available REST API versions.
/// Retrieves the available REST API versions.\n\nDocuSign Production system: https://www.docusign.net/restapi/service_information\nDocuSign Demo system: https://demo.docusign.net/restapi/service_information\n\nYou do not need an integrator key to view the REST API versions and resources.
///
///
///
///
/// @return DSESServiceInformation*

-(NSNumber*) getServiceWithCompletionBlock : 
     
    
    (void (^)(DSESServiceInformation* output, NSError* error))completionBlock;
    


	
	



///
///
/// Lists resources for REST version specified
/// Retrieves the base resources available for the DocuSign REST APIs.\n\nYou do not need an integrator key to view the REST API versions and resources.\n\nExample: https://demo.docusign.net/restapi/v2 lists all of the base resources available in version 2 of the REST API on the DocuSign Demo system.\n\nTo view descriptions and samples of the service operations for all versions, remove the version number and add /help to the URL.\n\nExample: https://demo.docusign.net/restapi/help lists the REST API operations on the DocuSign Demo system with XML and json request and response samples.
///
///
///
///
/// @return DSESResourceInformation*

-(NSNumber*) getResourcesWithCompletionBlock : 
     
    
    (void (^)(DSESResourceInformation* output, NSError* error))completionBlock;
    


	
	

///
///
/// Gets the API request logging log files.
/// Retrieves a list of log entries as a JSON or xml object or as a zip file containing the entries.\n\nIf the Accept header is set to application/zip, the response is a zip file containing individual text files, each representing an API request.\n\nIf the Accept header is set to `application/json` or `application/xml`, the response returns list of log entries in either JSON or XML. An example JSON response body is shown below.
///
///
///
/// @param DSESDiagnosticsApi_ListRequestLogsOptions  Options for modifying the request.
/// @return DSESApiRequestLogsResult*

-(NSNumber*) listRequestLogsWithCompletionBlock : 
     
    (void (^)(DSESApiRequestLogsResult* output, NSError* error))completionBlock;
    




///
///
/// Gets the API request logging log files.
/// Retrieves a list of log entries as a JSON or xml object or as a zip file containing the entries.\n\nIf the Accept header is set to application/zip, the response is a zip file containing individual text files, each representing an API request.\n\nIf the Accept header is set to `application/json` or `application/xml`, the response returns list of log entries in either JSON or XML. An example JSON response body is shown below.
///
///
///
/// @param DSESDiagnosticsApi_ListRequestLogsOptions  Options for modifying the request.
/// @return DSESApiRequestLogsResult*

-(NSNumber*) listRequestLogsWithCompletionBlock : 
     
    (DSESDiagnosticsApi_ListRequestLogsOptions*) options
    
    completionHandler: (void (^)(DSESApiRequestLogsResult* output, NSError* error))completionBlock;
    


	
	



///
///
/// Deletes the request log files.
/// Deletes the request log files.
///
///
///
///
/// @return 

-(NSNumber*) deleteRequestLogsWithCompletionBlock : 
     
    
    
    (void (^)(NSError* error))completionBlock;


	
	



///
///
/// Gets a request logging log file.
/// Retrieves information for a single log entry.\n\n**Request**\nThe `requestLogfId` property can be retrieved by getting the list of log entries. The Content-Transfer-Encoding header can be set to base64 to retrieve the API request/response as base 64 string. Otherwise the bytes of the request/response are returned.\n\n**Response**\nIf the Content-Transfer-Encoding header was set to base64, the log is returned as a base64 string.
///
///  @param requestLogId 
///
///
///
/// @return NSURL*

-(NSNumber*) getRequestLogWithCompletionBlock :(NSString*) requestLogId  
     
    
    
    completionHandler: (void (^)(NSURL* output, NSError* error))completionBlock;
    


	
	



///
///
/// Gets the API request logging settings.
/// Retrieves the current API request logging setting for the user and remaining log entries.\n\n**Response**\nThe response includes the current API request logging setting for the user, along with the maximum log entries and remaining log entries.
///
///
///
///
/// @return DSESDiagnosticsSettingsInformation*

-(NSNumber*) getRequestLogSettingsWithCompletionBlock : 
     
    
    (void (^)(DSESDiagnosticsSettingsInformation* output, NSError* error))completionBlock;
    


	
	



///
///
/// Enables or disables API request logging for troubleshooting.
/// Enables or disables API request logging for troubleshooting.\n\nWhen enabled (apiRequestLogging is set to true), REST API requests and responses for the user are added to a log. A log can have up to 50 requests/responses and the current number of log entries can be determined by getting the settings. Logging is automatically disabled when the log limit of 50 is reached.\n\nYou can call [ML:GetRequestLog] or [ML:GetRequestLogs] to download the log files (individually or as a zip file). Call [ML:DeleteRequestLogs] to clear the log by deleting current entries.\n\nPrivate information, such as passwords and integrator key information, which is normally located in the call header is omitted from the request/response log.\n\n### Note: API request logging only captures requests from the authenticated user. Any call that does not authenticate the user and resolve a userId isn't logged. Meaning that login_information, NewAccounts, or other distributor-credential calls are not logged.
///
///
/// @param diagnosticsSettingsInformation TBD Description 
///
/// @return DSESDiagnosticsSettingsInformation*

-(NSNumber*) updateRequestLogSettingsWithCompletionBlock : 
    (DSESDiagnosticsSettingsInformation*) diagnosticsSettingsInformation 
    
    
    completionHandler: (void (^)(DSESDiagnosticsSettingsInformation* output, NSError* error))completionBlock;
    


	
	

@end
