#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESUserSettingsInformation.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESObject.h>
#import <DocuSignSDK/DSESApiClient.h>


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */
 


/**
 * 
 */
 

 
@interface DSESUsersApi: NSObject

@property(nonatomic, assign)DSESApiClient *apiClient;

-(instancetype) initWithApiClient:(DSESApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DSESUsersApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DSESUsersApi*) sharedAPI;



///
///
/// Gets the user account settings for a specified user.
/// Retrieves a list of the account settings and email notification information for the specified user.\n\nThe response returns the account setting name/value information and the email notification settings for the specified user. For more information about the different user settings, see the [ML:userSettings list].
///
///  @param accountId The external account number (int) or account ID Guid.
///  @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
///
///
///
/// @return DSESUserSettingsInformation*

-(NSNumber*) getSettingsWithCompletionBlock :(NSString*) accountId 
     userId:(NSString*) userId  
     
    
    
    completionHandler: (void (^)(DSESUserSettingsInformation* output, NSError* error))completionBlock;
    


	
	

@end
