#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESErrorDetails.h>


@protocol DSESBulkEnvelope
@end

@interface DSESBulkEnvelope : DSESObject

/* Used to identify an envelope. The id is a sender-generated value and is valid in the DocuSign system for 7 days. It is recommended that a transaction ID is used for offline signing to ensure that an envelope is not sent multiple times. The `transactionId` property can be used determine if an envelope status (i.e. was created or not) for cases where an internet connection was lost before the envelope status could be returned. [optional]
 */
@property(nonatomic) NSString* transactionId;
/*  [optional]
 */
@property(nonatomic) NSString* submittedDateTime;
/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;
/* Contains a URI for an endpoint that you can use to retrieve the envelope or envelopes. [optional]
 */
@property(nonatomic) NSString* envelopeUri;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* bulkRecipientRow;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/*  [optional]
 */
@property(nonatomic) NSString* email;
/*  [optional]
 */
@property(nonatomic) NSString* bulkStatus;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
