#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESApiRequestLog.h>


@protocol DSESApiRequestLogsResult
@end

@interface DSESApiRequestLogsResult : DSESObject

/* Reserved: TBD [optional]
 */
@property(nonatomic) NSArray<DSESApiRequestLog>* apiRequestLogs;

@end
