#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESLockRequest
@end

@interface DSESLockRequest : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* lockedByApp;
/*  [optional]
 */
@property(nonatomic) NSString* lockDurationInSeconds;
/*  [optional]
 */
@property(nonatomic) NSString* lockType;
/* Reserved for future use.\n\nIndicates whether a scratchpad is used for editing information. [optional]
 */
@property(nonatomic) NSString* useScratchPad;
/*  [optional]
 */
@property(nonatomic) NSString* templatePassword;

@end
