#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESReminders
@end

@interface DSESReminders : DSESObject

/* When set to **true**, the envelope expires (is no longer available for signing) in the set number of days. If false, the account default setting is used. If the account does not have an expiration setting, the DocuSign default value of 120 days is used. [optional]
 */
@property(nonatomic) NSString* reminderEnabled;
/* An interger that sets the number of days after the recipient receives the envelope that reminder emails are sent to the recipient. [optional]
 */
@property(nonatomic) NSString* reminderDelay;
/* An interger that sets the interval, in days, between reminder emails. [optional]
 */
@property(nonatomic) NSString* reminderFrequency;

@end
