#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESUserInfo.h>
#import <DocuSignSDK/DSESSharedItem.h>


@protocol DSESMemberSharedItems
@end

@interface DSESMemberSharedItems : DSESObject


@property(nonatomic) DSESUserInfo* user;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESSharedItem>* envelopes;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
