#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESTabMetadata.h>


@protocol DSESTabMetadataList
@end

@interface DSESTabMetadataList : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray<DSESTabMetadata>* tabs;

@end
