#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESErrorDetails.h>


@protocol DSESNameValue
@end

@interface DSESNameValue : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* name;
/* Specifies the value of the tab. [optional]
 */
@property(nonatomic) NSString* value;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
