#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESEnvelopeEvent
@end

@interface DSESEnvelopeEvent : DSESObject

/* he envelope status, this can be Sent, Delivered, Completed, Declined, or Voided. [optional]
 */
@property(nonatomic) NSString* envelopeEventStatusCode;
/* When set to **true**, the envelope time zone information is included in the message. [optional]
 */
@property(nonatomic) NSString* includeDocuments;

@end
