#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESErrorDetails.h>


@protocol DSESCustomFieldV2
@end

@interface DSESCustomFieldV2 : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* fieldId;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/*  [optional]
 */
@property(nonatomic) NSString* show;
/* When set to **true**, the signer is required to fill out this tab [optional]
 */
@property(nonatomic) NSString* required;
/* The value of the custom field. [optional]
 */
@property(nonatomic) NSString* value;
/*  [optional]
 */
@property(nonatomic) NSString* configurationType;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
