#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESAddressInformation
@end

@interface DSESAddressInformation : DSESObject

/* The first line of the address. [optional]
 */
@property(nonatomic) NSString* street1;
/* The second line of the address (optional). [optional]
 */
@property(nonatomic) NSString* street2;
/* The city associated with the address. [optional]
 */
@property(nonatomic) NSString* city;
/* The state or province associated with the address. [optional]
 */
@property(nonatomic) NSString* state;
/* The zip or postal code associated with the address. [optional]
 */
@property(nonatomic) NSString* zip;
/* A phone number associated with the address. [optional]
 */
@property(nonatomic) NSString* phone;
/* A Fax number associated with the address if one is available. [optional]
 */
@property(nonatomic) NSString* fax;
/* Specifies the country associated with the address. [optional]
 */
@property(nonatomic) NSString* country;

@end
