#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESRecipientEvent
@end

@interface DSESRecipientEvent : DSESObject

/* The recipient status, this can be Sent, Delivered, Completed, Declined, AuthenticationFailed, and AutoResponded. [optional]
 */
@property(nonatomic) NSString* recipientEventStatusCode;
/* When set to **true**, the envelope time zone information is included in the message. [optional]
 */
@property(nonatomic) NSString* includeDocuments;

@end
