#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESViewUrl
@end

@interface DSESViewUrl : DSESObject

/* The view URL to be navigated to. [optional]
 */
@property(nonatomic) NSString* url;

@end
