#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESMatchBox
@end

@interface DSESMatchBox : DSESObject

/* Specifies the page number on which the tab is located. [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* This indicates the horizontal offset of the object on the page. DocuSign uses 72 DPI when determining position. [optional]
 */
@property(nonatomic) NSNumber* xPosition;
/* This indicates the vertical offset of the object on the page. DocuSign uses 72 DPI when determining position. [optional]
 */
@property(nonatomic) NSNumber* yPosition;
/* Width of the tab in pixels. [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height of the tab in pixels. [optional]
 */
@property(nonatomic) NSNumber* height;

@end
