#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESFoldersRequest
@end

@interface DSESFoldersRequest : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray* /* NSString */ envelopeIds;
/* The folder ID the envelope is being moved from. [optional]
 */
@property(nonatomic) NSString* fromFolderId;

@end
