#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESDiagnosticsSettingsInformation
@end

@interface DSESDiagnosticsSettingsInformation : DSESObject

/* When set to **true**, enables API request logging for the user. [optional]
 */
@property(nonatomic) NSString* apiRequestLogging;
/* Specifies the maximum number of API requests to log. [optional]
 */
@property(nonatomic) NSString* apiRequestLogMaxEntries;
/* Indicates the remaining number of API requests that can be logged. [optional]
 */
@property(nonatomic) NSString* apiRequestLogRemainingEntries;

@end
