#import <Foundation/Foundation.h>

#pragma mark - DSM language codes for branding

extern NSString * const DSM_LANGUAGE_CODE_FOR_ARABIC;
extern NSString * const DSM_LANGUAGE_CODE_FOR_ARMENIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_BAHASA_INDONESIA;
extern NSString * const DSM_LANGUAGE_CODE_FOR_BAHASA_MALAY;
extern NSString * const DSM_LANGUAGE_CODE_FOR_BULGARIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_CHINESE_SIMPLIFIED;
extern NSString * const DSM_LANGUAGE_CODE_FOR_CHINESE_TRADITIONAL;
extern NSString * const DSM_LANGUAGE_CODE_FOR_CROATIAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_CZECH;

extern NSString * const DSM_LANGUAGE_CODE_FOR_DANISH;
extern NSString * const DSM_LANGUAGE_CODE_FOR_DUTCH;

extern NSString * const DSM_LANGUAGE_CODE_FOR_ENGLISH_UK;
extern NSString * const DSM_LANGUAGE_CODE_FOR_ENGLISH_US;
extern NSString * const DSM_LANGUAGE_CODE_FOR_ESTONIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_FARSI;
extern NSString * const DSM_LANGUAGE_CODE_FOR_FINNISH;
extern NSString * const DSM_LANGUAGE_CODE_FOR_FRENCH;
extern NSString * const DSM_LANGUAGE_CODE_FOR_FRENCH_CANADA;

extern NSString * const DSM_LANGUAGE_CODE_FOR_GERMAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_FRENCH_GREEK;

extern NSString * const DSM_LANGUAGE_CODE_FOR_HEBREW;
extern NSString * const DSM_LANGUAGE_CODE_FOR_HINDI;
extern NSString * const DSM_LANGUAGE_CODE_FOR_HUNGARIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_ITALIAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_JAPANESE;

extern NSString * const DSM_LANGUAGE_CODE_FOR_KOREAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_LATVIAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_LITHUANIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_NORWEGIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_POLISH;
extern NSString * const DSM_LANGUAGE_CODE_FOR_PORTUGUESE;
extern NSString * const DSM_LANGUAGE_CODE_FOR_PORTUGUESE_BRAZIL;

extern NSString * const DSM_LANGUAGE_CODE_FOR_ROMANIAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_RUSSIAN;
  
extern NSString * const DSM_LANGUAGE_CODE_FOR_SERBIAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_SLOVAK;
extern NSString * const DSM_LANGUAGE_CODE_FOR_SLOVENIAN;
extern NSString * const DSM_LANGUAGE_CODE_FOR_SPANISH;
extern NSString * const DSM_LANGUAGE_CODE_FOR_SPANISH_LATIN_AMERICA;
extern NSString * const DSM_LANGUAGE_CODE_FOR_SWEDISH;

extern NSString * const DSM_LANGUAGE_CODE_FOR_THAI;
extern NSString * const DSM_LANGUAGE_CODE_FOR_TURKISH;

extern NSString * const DSM_LANGUAGE_CODE_FOR_UKRAINIAN;

extern NSString * const DSM_LANGUAGE_CODE_FOR_VIETNAMESE;

