{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brandCompany"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"brandId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"brandLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"brandName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"colors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue","text":"DSAPINameValue"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"defaultBrandLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailContent"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandEmailContent","preciseIdentifier":"s:11DocuSignAPI22DSAPIBrandEmailContentV","text":"DSAPIBrandEmailContent"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isOverridingCompanyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"isSendingDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"isSigningDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"landingPages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue","text":"DSAPINameValue"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"links"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandLink","preciseIdentifier":"s:11DocuSignAPI14DSAPIBrandLinkV","text":"DSAPIBrandLink"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"logos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandLogos","preciseIdentifier":"s:11DocuSignAPI15DSAPIBrandLogosV","text":"DSAPIBrandLogos"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"resources"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandResourceUrls","preciseIdentifier":"s:11DocuSignAPI22DSAPIBrandResourceUrlsV","text":"DSAPIBrandResourceUrls"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapibrand\/init(brandcompany:brandid:brandlanguages:brandname:colors:defaultbrandlanguage:emailcontent:errordetails:isoverridingcompanyname:issendingdefault:issigningdefault:landingpages:links:logos:resources:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrand\/init(brandCompany:brandId:brandLanguages:brandName:colors:defaultBrandLanguage:emailContent:errorDetails:isOverridingCompanyName:isSendingDefault:isSigningDefault:landingPages:links:logos:resources:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brandCompany"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brandId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brandLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"brandName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"colors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"defaultBrandLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailContent"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBrandEmailContent","preciseIdentifier":"s:11DocuSignAPI22DSAPIBrandEmailContentV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isOverridingCompanyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isSendingDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isSigningDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"landingPages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"links"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBrandLink","preciseIdentifier":"s:11DocuSignAPI14DSAPIBrandLinkV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"logos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIBrandLogos","preciseIdentifier":"s:11DocuSignAPI15DSAPIBrandLogosV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"resources"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIBrandResourceUrls","preciseIdentifier":"s:11DocuSignAPI22DSAPIBrandResourceUrlsV"},{"kind":"text","text":"?)"}],"title":"init(brandCompany:brandId:brandLanguages:brandName:colors:defaultBrandLanguage:emailContent:errorDetails:isOverridingCompanyName:isSendingDefault:isSigningDefault:landingPages:links:logos:resources:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI10DSAPIBrandV12brandCompany0E2Id0E9Languages0E4Name6colors20defaultBrandLanguage12emailContent12errorDetails012isOverridingfI00R14SendingDefault0r7SigningU012landingPages5links5logos9resourcesACSSSg_ASSaySSGSgASSayAA14DSAPINameValueCGSgASSayAA0d5EmailO0VGSgAA010DSAPIErrorQ0CSgS3bAYSayAA0D4LinkVGSgAA0D5LogosVSgAA0D12ResourceUrlsVSgtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrand"]]},"references":{"/docs/esign-rest-api/reference/accounts/accountbrands/updatelogo/":{"title":"AccountBrands: updateLogo","titleInlineContent":[{"type":"text","text":"AccountBrands: updateLogo"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountbrands\/updatelogo\/","url":"\/docs\/esign-rest-api\/reference\/accounts\/accountbrands\/updatelogo\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBrand":{"role":"symbol","title":"DSAPIBrand","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBrand"}],"abstract":[{"type":"text","text":"Information about a brand that is associated with an account. A brand applies custom styles and text to an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBrand"}],"url":"\/documentation\/docusignapi\/dsapibrand"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBrand/init(brandCompany:brandId:brandLanguages:brandName:colors:defaultBrandLanguage:emailContent:errorDetails:isOverridingCompanyName:isSendingDefault:isSigningDefault:landingPages:links:logos:resources:)":{"role":"symbol","title":"init(brandCompany:brandId:brandLanguages:brandName:colors:defaultBrandLanguage:emailContent:errorDetails:isOverridingCompanyName:isSendingDefault:isSigningDefault:landingPages:links:logos:resources:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brandCompany"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brandId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brandLanguages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"brandName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"colors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"defaultBrandLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailContent"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBrandEmailContent","preciseIdentifier":"s:11DocuSignAPI22DSAPIBrandEmailContentV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isOverridingCompanyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isSendingDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isSigningDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"landingPages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"links"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBrandLink","preciseIdentifier":"s:11DocuSignAPI14DSAPIBrandLinkV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"logos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIBrandLogos","preciseIdentifier":"s:11DocuSignAPI15DSAPIBrandLogosV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"resources"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIBrandResourceUrls","preciseIdentifier":"s:11DocuSignAPI22DSAPIBrandResourceUrlsV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrand\/init(brandCompany:brandId:brandLanguages:brandName:colors:defaultBrandLanguage:emailContent:errorDetails:isOverridingCompanyName:isSendingDefault:isSigningDefault:landingPages:links:logos:resources:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapibrand\/init(brandcompany:brandid:brandlanguages:brandname:colors:defaultbrandlanguage:emailcontent:errordetails:isoverridingcompanyname:issendingdefault:issigningdefault:landingpages:links:logos:resources:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"role":"symbol","title":"DSAPIErrorDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIErrorDetails"}],"abstract":[{"type":"text","text":"This object describes errors that occur. It is only valid for responses and ignored in requests."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"url":"\/documentation\/docusignapi\/dsapierrordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBrandLink":{"role":"symbol","title":"DSAPIBrandLink","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBrandLink"}],"abstract":[{"type":"text","text":"Information about a link that a brand uses."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandLink","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBrandLink"}],"url":"\/documentation\/docusignapi\/dsapibrandlink"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue":{"role":"symbol","title":"DSAPINameValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINameValue"}],"abstract":[{"type":"text","text":"A name-value pair that describes an item and provides a value for the item."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINameValue"}],"url":"\/documentation\/docusignapi\/dsapinamevalue"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBrandLogos":{"role":"symbol","title":"DSAPIBrandLogos","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBrandLogos"}],"abstract":[{"type":"text","text":"The URIs for retrieving the logos that are associated with the brand.  These are read-only properties that provide a URI to logos in use. To update a logo use "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountbrands\/updatelogo\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandLogos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBrandLogos"}],"url":"\/documentation\/docusignapi\/dsapibrandlogos"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBrandEmailContent":{"role":"symbol","title":"DSAPIBrandEmailContent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBrandEmailContent"}],"abstract":[{"type":"text","text":"Deprecated."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandEmailContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBrandEmailContent"}],"url":"\/documentation\/docusignapi\/dsapibrandemailcontent"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBrandResourceUrls":{"role":"symbol","title":"DSAPIBrandResourceUrls","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBrandResourceUrls"}],"abstract":[{"type":"text","text":"Brands use resource files to style the following experiences:   - Email - Sending - Signing - Captive (embedded) signing   You can modify these resource files to customize these experiences."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBrandResourceUrls","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBrandResourceUrls"}],"url":"\/documentation\/docusignapi\/dsapibrandresourceurls"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue\/title","value":"DSAPINameValue"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue\/fragments","value":[{"kind":"identifier","text":"DSAPINameValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}