{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsusersessionmanager\/deleteuserinfo()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsusersessionmanager\/deleteuserinfo()"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager\/deleteUserInfo()"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"deleteUserInfoAndReturnError:"}],"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","externalID":"c:@M@DocuSignAPI@objc(cs)DSUserSessionManager(cm)deleteUserInfoAndReturnError:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteUserInfo"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"deleteUserInfo()","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteUserInfo"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSUserSessionManager":{"title":"DSUserSessionManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSUserSessionManager","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsusersessionmanager","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"DSUserSessionManager","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSUserSessionManager/deleteUserInfo()":{"navigatorTitle":[{"text":"deleteUserInfoAndReturnError:","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsusersessionmanager\/deleteuserinfo()","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager\/deleteUserInfo()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteUserInfo","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"deleteUserInfo()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"deleteUserInfoAndReturnError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteUserInfoAndReturnError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"deleteUserInfoAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager\/title","op":"replace","value":"DSUserSessionManager"},{"value":[{"kind":"identifier","text":"DSUserSessionManager"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager\/fragments"},{"value":"deleteUserInfoAndReturnError:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager~1deleteUserInfo()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager~1deleteUserInfo()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"deleteUserInfoAndReturnError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}