{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPrimaryUserInfo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIAccountServerUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Type Method","modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"getPrimaryUserInfo()","externalID":"c:@M@DocuSignAPI@objc(cs)DSUserSessionManager(cm)getPrimaryUserInfo","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getPrimaryUserInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIAccountServerUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"getPrimaryUserInfo","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsusersessionmanager\/getprimaryuserinfo()"]},{"paths":["\/documentation\/docusignapi\/dsusersessionmanager\/getprimaryuserinfo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager\/getPrimaryUserInfo()","interfaceLanguage":"swift"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"title":"DSAPIAccountServerUserInfo","role":"symbol","navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSUserSessionManager/getPrimaryUserInfo()":{"navigatorTitle":[{"kind":"identifier","text":"getPrimaryUserInfo"}],"url":"\/documentation\/docusignapi\/dsusersessionmanager\/getprimaryuserinfo()","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager\/getPrimaryUserInfo()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getPrimaryUserInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"DSAPIAccountServerUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"getPrimaryUserInfo()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSUserSessionManager":{"title":"DSUserSessionManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSUserSessionManager","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsusersessionmanager","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"DSUserSessionManager","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"getPrimaryUserInfo","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"getPrimaryUserInfo","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIAccountServerUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo"},{"kind":"text","text":" *) "},{"text":"getPrimaryUserInfo","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DSAPIAccountServerUserInfo","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments","value":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"op":"replace"},{"value":"getPrimaryUserInfo","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager~1getPrimaryUserInfo()\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager~1getPrimaryUserInfo()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getPrimaryUserInfo"}]},{"value":"DSUserSessionManager","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager\/title","op":"replace"},{"value":[{"text":"DSUserSessionManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager\/fragments"}]}]}