{"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"text":"persistAuthWithObjcEnv:error:","kind":"identifier"}],"title":"persistAuth(objcEnv:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistAuth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"objcEnv","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ObjcEnviromment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSUserSessionManager(cm)persistAuthWithObjcEnv:error:","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsusersessionmanager\/persistauth(objcenv:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsusersessionmanager\/persistauth(objcenv:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"persistAuth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"objcEnv","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ObjcEnviromment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager\/persistAuth(objcEnv:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSUserSessionManager":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager","url":"\/documentation\/docusignapi\/dsusersessionmanager","abstract":[],"navigatorTitle":[{"text":"DSUserSessionManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSUserSessionManager","kind":"identifier"}],"role":"symbol","title":"DSUserSessionManager","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObjcEnviromment"}],"abstract":[],"type":"topic","title":"ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","kind":"symbol","url":"\/documentation\/docusignapi\/objcenviromment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcEnviromment"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSUserSessionManager/persistAuth(objcEnv:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSUserSessionManager\/persistAuth(objcEnv:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistAuth","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"objcEnv"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment","text":"ObjcEnviromment","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","title":"persistAuth(objcEnv:)","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"persistAuthWithObjcEnv:error:","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsusersessionmanager\/persistauth(objcenv:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"persistAuthWithObjcEnv:error:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"persistAuthWithObjcEnv:error:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"persistAuthWithObjcEnv:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ObjcEnviromment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"objcEnv"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DSUserSessionManager","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager\/fragments","value":[{"text":"DSUserSessionManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/title","op":"replace","value":"ObjcEnviromment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/fragments","value":[{"kind":"identifier","text":"ObjcEnviromment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager~1persistAuth(objcEnv:)\/title","value":"persistAuthWithObjcEnv:error:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSUserSessionManager~1persistAuth(objcEnv:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"persistAuthWithObjcEnv:error:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}