{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInlineTemplate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInlineTemplate\/init(customFields:documents:envelope:recipients:sequence:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiinlinetemplate\/init(customfields:documents:envelope:recipients:sequence:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:11DocuSignAPI19DSAPIInlineTemplateV12customFields9documents8envelope10recipients8sequenceAcA011DSAPICustomG0CSg_SayAA13DSAPIDocumentCGSgAA13DSAPIEnvelopeCSgAA15DSAPIRecipientsCSgSSSgtcfc","symbolKind":"init","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"customFields","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"documents","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocument"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"envelope"},{"kind":"text","text":": "},{"text":"DSAPIEnvelope","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipients"},{"kind":"text","text":": "},{"text":"DSAPIRecipients","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"sequence"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","role":"symbol","title":"init(customFields:documents:envelope:recipients:sequence:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"customFields","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","kind":"typeIdentifier","text":"DSAPICustomFields"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"documents"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocument","text":"DSAPIDocument","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"envelope"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIEnvelope","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope"},{"kind":"text","text":"? = nil, "},{"text":"recipients","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","text":"DSAPIRecipients"},{"text":"? = nil, ","kind":"text"},{"text":"sequence","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument":{"abstract":[{"type":"text","text":"A document object."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument","type":"topic","url":"\/documentation\/docusignapi\/dsapidocument","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocument"}],"title":"DSAPIDocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIDocument"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInlineTemplate/init(customFields:documents:envelope:recipients:sequence:)":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiinlinetemplate\/init(customfields:documents:envelope:recipients:sequence:)","title":"init(customFields:documents:envelope:recipients:sequence:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInlineTemplate\/init(customFields:documents:envelope:recipients:sequence:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customFields"},{"text":": ","kind":"text"},{"text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"documents"},{"kind":"text","text":": ["},{"text":"DSAPIDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocument","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"envelope","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIEnvelope","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipients"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","text":"DSAPIRecipients"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"sequence"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInlineTemplate":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIInlineTemplate","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIInlineTemplate","kind":"identifier"}],"title":"DSAPIInlineTemplate","url":"\/documentation\/docusignapi\/dsapiinlinetemplate","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInlineTemplate","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicustomfields","abstract":[{"type":"text","text":"Contains information about custom fields."}],"title":"DSAPICustomFields","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope":{"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelope","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIEnvelope","kind":"identifier"}],"abstract":[],"title":"DSAPIEnvelope","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelope"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipients","kind":"identifier"}],"abstract":[{"text":"Specifies the envelope recipients.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapirecipients","title":"DSAPIRecipients","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPIRecipients","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument\/title","value":"DSAPIDocument"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument\/fragments","value":[{"text":"DSAPIDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title","op":"replace","value":"DSAPICustomFields"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments","value":[{"text":"DSAPICustomFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/title","value":"DSAPIEnvelope"},{"value":[{"kind":"identifier","text":"DSAPIEnvelope"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/fragments","op":"replace"},{"op":"replace","value":"DSAPIRecipients","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title"},{"op":"replace","value":[{"text":"DSAPIRecipients","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments"}]}]}