{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapifailedtelemetryevent\/init(event:failurereason:)"]},{"paths":["\/documentation\/docusignapi\/dsapifailedtelemetryevent\/init(event:failurereason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"text":"initWithEvent:failureReason:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"text":"DSAPITelemetryEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvent"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(event:failureReason:)","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent(im)initWithEvent:failureReason:"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPITelemetryEvent","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvent","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"failureReason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent\/init(event:failureReason:)"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEvent":{"navigatorTitle":[{"text":"DSAPITelemetryEvent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapitelemetryevent","role":"symbol","title":"DSAPITelemetryEvent","abstract":[{"text":"The telemetry event model.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPITelemetryEvent","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFailedTelemetryEvent/init(event:failureReason:)":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapifailedtelemetryevent\/init(event:failurereason:)","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent\/init(event:failureReason:)","navigatorTitle":[{"text":"initWithEvent:failureReason:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvent","text":"DSAPITelemetryEvent"},{"kind":"text","text":"?, "},{"text":"failureReason","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(event:failureReason:)","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFailedTelemetryEvent":{"title":"DSAPIFailedTelemetryEvent","navigatorTitle":[{"text":"DSAPIFailedTelemetryEvent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFailedTelemetryEvent","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapifailedtelemetryevent","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent","abstract":[{"type":"text","text":"This response object is returned after you post a telemetry event."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithEvent:failureReason:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEvent:failureReason:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithEvent:"},{"kind":"text","text":"("},{"text":"DSAPITelemetryEvent","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"failureReason"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"DSAPITelemetryEvent","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvent\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPITelemetryEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent~1init(event:failureReason:)\/title","value":"initWithEvent:failureReason:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent~1init(event:failureReason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvent:failureReason:"}],"op":"replace"},{"value":"DSAPIFailedTelemetryEvent","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent\/fragments","value":[{"text":"DSAPIFailedTelemetryEvent","kind":"identifier"}],"op":"replace"}]}]}