{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharing"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canManageSharing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesharing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesharing"]}],"sections":[],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"text":" if the user can manage sharing.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canManageSharing","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserAccountManagementGranularInformation(py)canManageSharing","role":"symbol","title":"canManageSharing","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"canManageSharing"}]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageSharing":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesharing","title":"canManageSharing","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharing","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageSharing"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"inlineContent":[{"type":"text","text":"True"}],"type":"strong"},{"type":"text","text":" if the user can manage sharing."}],"navigatorTitle":[{"text":"canManageSharing","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation":{"kind":"symbol","title":"DSAPIUserAccountManagementGranularInformation","type":"topic","abstract":[{"text":"Describes which account management capabilities a user has.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"canManageSharing"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"canManageSharing"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"canManageSharing","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"canManageSharing","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSharing\/title"},{"value":[{"text":"canManageSharing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSharing\/fragments","op":"replace"},{"value":"DSAPIUserAccountManagementGranularInformation","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}