{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsers"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canManageGroupsButNotUsers","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagegroupsbutnotusers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagegroupsbutnotusers"]}],"metadata":{"roleHeading":"Instance Property","title":"canManageGroupsButNotUsers","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserAccountManagementGranularInformation(py)canManageGroupsButNotUsers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canManageGroupsButNotUsers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"canManageGroupsButNotUsers"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation":{"kind":"symbol","title":"DSAPIUserAccountManagementGranularInformation","type":"topic","abstract":[{"text":"Describes which account management capabilities a user has.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageGroupsButNotUsers":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagegroupsbutnotusers","title":"canManageGroupsButNotUsers","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"canManageGroupsButNotUsers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"canManageGroupsButNotUsers","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"canManageGroupsButNotUsers"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"canManageGroupsButNotUsers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"canManageGroupsButNotUsers"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/title","op":"replace","value":"DSAPIUserAccountManagementGranularInformation"},{"op":"replace","value":[{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageGroupsButNotUsers\/title","value":"canManageGroupsButNotUsers"},{"op":"replace","value":[{"kind":"identifier","text":"canManageGroupsButNotUsers"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageGroupsButNotUsers\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}