{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation"]]},"metadata":{"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"}],"title":"init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"canManageAccountSecuritySettings"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"canManageAccountSecuritySettingsMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageAccountSettings"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"canManageAccountSettingsMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageAdmins","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"canManageAdminsMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageConnect","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageConnectMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageDocumentRetention","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"canManageDocumentRetentionMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"canManageEnvelopeTransfer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"canManageEnvelopeTransferMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"canManageGroupsButNotUsers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"canManageGroupsButNotUsersMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageReporting"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageReportingMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSharing"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageSharingMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageSigningGroups"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"canManageSigningGroupsMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageUsers","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"canManageUsersMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canViewUsers"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserAccountManagementGranularInformation(im)initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/init(canmanageaccountsecuritysettings:canmanageaccountsecuritysettingsmetadata:canmanageaccountsettings:canmanageaccountsettingsmetadata:canmanageadmins:canmanageadminsmetadata:canmanageconnect:canmanageconnectmetadata:canmanagedocumentrete-56knj"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/init(canmanageaccountsecuritysettings:canmanageaccountsecuritysettingsmetadata:canmanageaccountsettings:canmanageaccountsettingsmetadata:canmanageadmins:canmanageadminsmetadata:canmanageconnect:canmanageconnectmetadata:canmanagedocumentrete-56knj"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"canManageAccountSecuritySettings","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"canManageAccountSecuritySettingsMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canManageAccountSettings"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"canManageAccountSettingsMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","kind":"typeIdentifier","text":"DSAPISettingsMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"canManageAdmins","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"canManageAdminsMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},{"kind":"text","text":"? = nil, "},{"text":"canManageConnect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"canManageConnectMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"canManageDocumentRetention"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"canManageDocumentRetentionMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"canManageEnvelopeTransfer"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"canManageEnvelopeTransferMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canManageGroupsButNotUsers"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"canManageGroupsButNotUsersMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"canManageReporting","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"canManageReportingMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canManageSharing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"canManageSharingMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"? = nil, "},{"text":"canManageSigningGroups","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canManageSigningGroupsMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canManageUsers"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"canManageUsersMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canViewUsers"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/init(canmanageaccountsecuritysettings:canmanageaccountsecuritysettingsmetadata:canmanageaccountsettings:canmanageaccountsettingsmetadata:canmanageadmins:canmanageadminsmetadata:canmanageconnect:canmanageconnectmetadata:canmanagedocumentrete-56knj","title":"init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"canManageAccountSecuritySettings","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageAccountSecuritySettingsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageAccountSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageAccountSettingsMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageAdmins"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageAdminsMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageConnect","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"canManageConnectMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageDocumentRetention","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageDocumentRetentionMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageEnvelopeTransfer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"canManageEnvelopeTransferMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageGroupsButNotUsers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"canManageGroupsButNotUsersMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"text":"canManageReporting","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"canManageReportingMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSharing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSharingMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSigningGroups"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canManageSigningGroupsMetadata"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"text":"canManageUsers","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"canManageUsersMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"canViewUsers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation":{"kind":"symbol","title":"DSAPIUserAccountManagementGranularInformation","type":"topic","abstract":[{"text":"Describes which account management capabilities a user has.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCanManageAccountSecuritySettings:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"canManageAccountSecuritySettings","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAccountSecuritySettingsMetadata:"},{"text":"(","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"text":"canManageAccountSecuritySettingsMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canManageAccountSettings:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"canManageAccountSettings","kind":"internalParam"},{"kind":"text","text":" "},{"text":"canManageAccountSettingsMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":" *) "},{"text":"canManageAccountSettingsMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canManageAdmins:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"canManageAdmins","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canManageAdminsMetadata:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"text":"canManageAdminsMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageConnect:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"canManageConnect","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canManageConnectMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageConnectMetadata"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canManageDocumentRetention:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageDocumentRetention"},{"text":" ","kind":"text"},{"text":"canManageDocumentRetentionMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","kind":"typeIdentifier","text":"DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageDocumentRetentionMetadata"},{"text":" ","kind":"text"},{"text":"canManageEnvelopeTransfer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageEnvelopeTransfer"},{"text":" ","kind":"text"},{"text":"canManageEnvelopeTransferMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"canManageEnvelopeTransferMetadata"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canManageGroupsButNotUsers:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"canManageGroupsButNotUsers"},{"kind":"text","text":" "},{"text":"canManageGroupsButNotUsersMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageGroupsButNotUsersMetadata"},{"kind":"text","text":" "},{"text":"canManageReporting:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"canManageReporting","kind":"internalParam"},{"kind":"text","text":" "},{"text":"canManageReportingMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"canManageReportingMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canManageSharing:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageSharing"},{"kind":"text","text":" "},{"text":"canManageSharingMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"text":"canManageSharingMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canManageSigningGroups:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"canManageSigningGroups"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageSigningGroupsMetadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":" *) "},{"text":"canManageSigningGroupsMetadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canManageUsers:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"canManageUsers"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canManageUsersMetadata:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"canManageUsersMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"canViewUsers:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"canViewUsers","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)\/title","value":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:","kind":"identifier"}]},{"value":"DSAPIUserAccountManagementGranularInformation","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/fragments","op":"replace","value":[{"text":"DSAPIUserAccountManagementGranularInformation","kind":"identifier"}]},{"value":"DSAPISettingsMetadata","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title"},{"op":"replace","value":[{"text":"DSAPISettingsMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}