{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/NetworkManager\/syncAdditionalData(userInfo:completion:)"},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)NetworkManager(cm)syncAdditionalDataWithUserInfo:completion:","modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncAdditionalData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","text":"DSAPIAccountServerUserInfo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"title":"syncAdditionalData(userInfo:completion:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"syncAdditionalDataWithUserInfo:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/NetworkManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncAdditionalData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"text":"DSAPIAccountServerUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}]}]}],"variants":[{"paths":["\/documentation\/docusignapi\/networkmanager\/syncadditionaldata(userinfo:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/networkmanager\/syncadditionaldata(userinfo:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"title":"DSAPIAccountServerUserInfo","role":"symbol","navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/NetworkManager":{"title":"NetworkManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NetworkManager","kind":"identifier"}],"url":"\/documentation\/docusignapi\/networkmanager","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NetworkManager"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/NetworkManager","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/NetworkManager/syncAdditionalData(userInfo:completion:)":{"title":"syncAdditionalData(userInfo:completion:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"syncAdditionalData","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIAccountServerUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"url":"\/documentation\/docusignapi\/networkmanager\/syncadditionaldata(userinfo:completion:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"syncAdditionalDataWithUserInfo:completion:"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/NetworkManager\/syncAdditionalData(userInfo:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"syncAdditionalDataWithUserInfo:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"syncAdditionalDataWithUserInfo:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"syncAdditionalDataWithUserInfo:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DSAPIAccountServerUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title","op":"replace","value":"DSAPIAccountServerUserInfo"},{"value":[{"kind":"identifier","text":"DSAPIAccountServerUserInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1NetworkManager\/title","value":"NetworkManager","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1NetworkManager\/fragments","value":[{"text":"NetworkManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1NetworkManager~1syncAdditionalData(userInfo:completion:)\/title","value":"syncAdditionalDataWithUserInfo:completion:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"syncAdditionalDataWithUserInfo:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1NetworkManager~1syncAdditionalData(userInfo:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}