{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorHorizontalAlignment","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"anchorHorizontalAlignment","roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove(py)anchorHorizontalAlignment","modules":[{"name":"DocuSignAPI"}],"role":"symbol","navigatorTitle":[{"text":"anchorHorizontalAlignment","kind":"identifier"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove\/anchorHorizontalAlignment"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove"]]},"abstract":[{"type":"text","text":"This property controls how [anchor tabs][AnchorTabs] are aligned in relation to the anchor text. Possible values are :  - `left`: Aligns the left side of the tab with the beginning of the first character of the matching anchor word. This is the default value. - `right`: Aligns the tab’s left side with the last character of the matching anchor word.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" You can only specify the value of this property in POST requests.  [AnchorTabs]: \/docs\/esign-rest-api\/esign101\/concepts\/tabs\/auto-place\/"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiapprove\/anchorhorizontalalignment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiapprove\/anchorhorizontalalignment"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorHorizontalAlignment","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIApprove":{"type":"topic","title":"DSAPIApprove","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIApprove","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIApprove"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to approve documents without placing a signature or initials on the document."}],"role":"symbol","kind":"symbol","url":"\/documentation\/docusignapi\/dsapiapprove"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIApprove/anchorHorizontalAlignment":{"navigatorTitle":[{"kind":"identifier","text":"anchorHorizontalAlignment"}],"url":"\/documentation\/docusignapi\/dsapiapprove\/anchorhorizontalalignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorHorizontalAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"This property controls how [anchor tabs][AnchorTabs] are aligned in relation to the anchor text. Possible values are :  - `left`: Aligns the left side of the tab with the beginning of the first character of the matching anchor word. This is the default value. - `right`: Aligns the tab’s left side with the last character of the matching anchor word.  ","type":"text"},{"inlineContent":[{"type":"text","text":"Note:"}],"type":"strong"},{"type":"text","text":" You can only specify the value of this property in POST requests.  [AnchorTabs]: \/docs\/esign-rest-api\/esign101\/concepts\/tabs\/auto-place\/"}],"title":"anchorHorizontalAlignment","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove\/anchorHorizontalAlignment","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"anchorHorizontalAlignment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"anchorHorizontalAlignment","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"anchorHorizontalAlignment","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove\/title","value":"DSAPIApprove","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove\/fragments","value":[{"text":"DSAPIApprove","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove~1anchorHorizontalAlignment\/title","value":"anchorHorizontalAlignment"},{"value":[{"kind":"identifier","text":"anchorHorizontalAlignment"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove~1anchorHorizontalAlignment\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}