# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'docusign-sdk-sample-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for docusign-sdk-sample-swift
  pod 'SVProgressHUD'

  # Specific branch with published SDK
  pod 'DocuSign', :git => 'https://github.com/docusign/native-ios-sdk.git', :branch => 'release/2.5.3-legacy'

end
