# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'docusign-sdk-sample-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for docusign-sdk-sample-swift
  pod 'SVProgressHUD'

end
