{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/declineTabs"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapitabs\/declinetabs"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapitabs\/declinetabs"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"declineTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDecline","text":"DSAPIDecline","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"]]},"abstract":[{"type":"text","text":"A list of [Decline tabs][decline].  A Decline tab enables the recipient to decline the envelope. If the recipient clicks the tab during the signing process, the envelope is voided. The value of this tab can't be set.   [decline]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"declineTabs","kind":"identifier"},{"kind":"text","text":": ["},{"text":"DSAPIDecline","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"text":"]?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITabs(py)declineTabs","symbolKind":"property","title":"declineTabs","navigatorTitle":[{"kind":"identifier","text":"declineTabs"}]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/declineTabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs\/declinetabs","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"declineTabs","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDecline","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"text":"]?","kind":"text"}],"abstract":[{"type":"text","text":"A list of [Decline tabs][decline].  A Decline tab enables the recipient to decline the envelope. If the recipient clicks the tab during the signing process, the envelope is voided. The value of this tab can't be set.   [decline]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/declineTabs","kind":"symbol","title":"declineTabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"declineTabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDecline":{"navigatorTitle":[{"text":"DSAPIDecline","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A tab that allows the recipient the option of declining an envelope. If the recipient clicks the tab during the signing process, the envelope is voided."}],"title":"DSAPIDecline","kind":"symbol","url":"\/documentation\/docusignapi\/dsapidecline","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIDecline","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDecline"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"declineTabs","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"declineTabs","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DSAPIDecline *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"declineTabs","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1declineTabs\/title","value":"declineTabs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1declineTabs\/fragments","value":[{"text":"declineTabs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs","op":"replace"},{"value":[{"text":"DSAPITabs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments"},{"value":"DSAPIDecline","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDecline\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDecline\/fragments","value":[{"text":"DSAPIDecline","kind":"identifier"}]}]}]}