{"abstract":[{"text":"A list of [Email tabs][email].  An Email tab enables the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information. This value can be set.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response.  [email]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitabs\/emailtabs"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapitabs\/emailtabs"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailTabs"},"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITabs(py)emailTabs","symbolKind":"property","title":"emailTabs","modules":[{"name":"DocuSignAPI"}],"role":"symbol","navigatorTitle":[{"text":"emailTabs","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emailTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail","text":"DSAPIEmail"},{"kind":"text","text":"]?"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emailTabs"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail","text":"DSAPIEmail"},{"text":"]?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmail":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEmail"}],"type":"topic","title":"DSAPIEmail","url":"\/documentation\/docusignapi\/dsapiemail","abstract":[{"type":"text","text":"A tab that allows the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIEmail"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/emailTabs":{"type":"topic","abstract":[{"text":"A list of [Email tabs][email].  An Email tab enables the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information. This value can be set.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response.  [email]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"emailTabs","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailTabs","title":"emailTabs","url":"\/documentation\/docusignapi\/dsapitabs\/emailtabs","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emailTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"kind":"text","text":"]?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"emailTabs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"emailTabs"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DSAPIEmail *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"emailTabs","kind":"identifier"}]}]}},{"op":"replace","value":"DSAPIEmail","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/fragments","value":[{"kind":"identifier","text":"DSAPIEmail"}],"op":"replace"},{"op":"replace","value":"DSAPITabs","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1emailTabs\/title","value":"emailTabs"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1emailTabs\/fragments","op":"replace","value":[{"kind":"identifier","text":"emailTabs"}]}]}]}