{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName","text":"DSAPIFirstName"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitabs\/firstnametabs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapitabs\/firstnametabs"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/firstNameTabs","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A list of [First Name tabs][firstName].  A First Name tab displays the recipient's first name. The system automatically populates this field by splitting the name in the recipient information on spaces. This value can't be set.   [firstName]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#parameters_firstname"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"kind":"text","text":"]?"}],"title":"firstNameTabs","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITabs(py)firstNameTabs","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"firstNameTabs"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/firstNameTabs":{"role":"symbol","title":"firstNameTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [First Name tabs][firstName].  A First Name tab displays the recipient's first name. The system automatically populates this field by splitting the name in the recipient information on spaces. This value can't be set.   [firstName]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#parameters_firstname"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/firstNameTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstNameTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/firstnametabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","title":"DSAPITabs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}],"url":"\/documentation\/docusignapi\/dsapitabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFirstName":{"role":"symbol","title":"DSAPIFirstName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFirstName"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's first name. This tab takes the recipient's name as entered in the recipient information, splits it into sections based on spaces and uses the first section as the first name."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFirstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFirstName"}],"url":"\/documentation\/docusignapi\/dsapifirstname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"firstNameTabs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"firstNameTabs"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DSAPIFirstName *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"firstNameTabs"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1firstNameTabs\/title","value":"firstNameTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1firstNameTabs\/fragments","value":[{"kind":"identifier","text":"firstNameTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFirstName\/title","value":"DSAPIFirstName"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFirstName\/fragments","value":[{"kind":"identifier","text":"DSAPIFirstName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}