{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"approveTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove","text":"DSAPIApprove"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"checkboxTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox","text":"DSAPICheckbox"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commentThreadTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommentThread","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV","text":"DSAPICommentThread"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionCountyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV","text":"DSAPICommissionCounty"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionExpiration","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV","text":"DSAPICommissionExpiration"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV","text":"DSAPICommissionNumber"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionStateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionState","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV","text":"DSAPICommissionState"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"companyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany","text":"DSAPICompany"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV","text":"DSAPICurrency"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"dateSignedTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateSigned","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned","text":"DSAPIDateSigned"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"dateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDate","text":"DSAPIDate"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"declineTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDecline","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline","text":"DSAPIDecline"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"drawTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDraw","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV","text":"DSAPIDraw"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress","text":"DSAPIEmailAddress"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"emailTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail","text":"DSAPIEmail"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"envelopeIdTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeId","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId","text":"DSAPIEnvelopeId"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName","text":"DSAPIFirstName"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"formulaTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab","text":"DSAPIFormulaTab"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"fullNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName","text":"DSAPIFullName"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"initialHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere","text":"DSAPIInitialHere"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"lastNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName","text":"DSAPILastName"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"listTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList","text":"DSAPIList"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"notarizeTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV","text":"DSAPINotarize"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"notarySealTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV","text":"DSAPINotarySeal"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"noteTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINote","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote","text":"DSAPINote"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"numberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINumber","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINumber","text":"DSAPINumber"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"phoneNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPhoneNumber","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV","text":"DSAPIPhoneNumber"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"polyLineOverlayTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV","text":"DSAPIPolyLineOverlay"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"prefillTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs","preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV","text":"DSAPIPrefillTabs"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup","text":"DSAPIRadioGroup"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"signerAttachmentTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment","text":"DSAPISignerAttachment"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"signHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere","text":"DSAPISignHere"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"smartSectionTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV","text":"DSAPISmartSection"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"ssnTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn","text":"DSAPISsn"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"tabGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup","text":"DSAPITabGroup"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"textTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText","text":"DSAPIText"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"titleTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle","text":"DSAPITitle"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"viewTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV","text":"DSAPIView"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"zipTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip","text":"DSAPIZip"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitabs\/init(approvetabs:checkboxtabs:commentthreadtabs:commissioncountytabs:commissionexpirationtabs:commissionnumbertabs:commissionstatetabs:companytabs:currencytabs:datesignedtabs:datetabs:declinetabs:drawtabs:emailaddresstabs:emailtabs:envelope-go8c"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"approveTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIApprove","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"checkboxTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commentThreadTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommentThread","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionCountyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionExpiration","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionStateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionState","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"companyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICompany","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateSignedTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDateSigned","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declineTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDecline","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"drawTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDraw","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeIdTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeId","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"formulaTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"fullNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFullName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"initialHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInitialHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lastNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"listTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIList","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarizeTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarySealTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"noteTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINote","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"numberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINumber","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINumber"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"phoneNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPhoneNumber","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"polyLineOverlayTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"prefillTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPrefillTabs","preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRadioGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signerAttachmentTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignerAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"smartSectionTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"ssnTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIText","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"titleTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITitle","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"viewTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"zipTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip"},{"kind":"text","text":"]?)"}],"title":"init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI9DSAPITabsC11approveTabs08checkboxF0013commentThreadF0016commissionCountyF00j10ExpirationF00j6NumberF00j5StateF007companyF008currencyF0010dateSignedF00qF007declineF004drawF0012emailAddressF00uF0010envelopeIdF009firstNameF007formulaF004fullzF0011initialHereF004lastzF004listF008notarizeF0010notarySealF004noteF006numberF005phonemF0015polyLineOverlayF007prefillF0010radioGroupF0016signerAttachmentF008signHereF0012smartSectionF003ssnF09tabGroups04textF005titleF004viewF003zipF0ACSayAA12DSAPIApproveCGSg_SayAA13DSAPICheckboxCGSgSayAA012DSAPICommentI0VGSgSayAA015DSAPICommissionK0VGSgSayAA015DSAPICommissionL0VGSgSayAA015DSAPICommissionM0VGSgSayAA015DSAPICommissionN0VGSgSayAA12DSAPICompanyCGSgSayAA13DSAPICurrencyVGSgSayAA09DSAPIDateR0CGSgSayAA9DSAPIDateCGSgSayAA12DSAPIDeclineCGSgSayAA9DSAPIDrawVGSgSayAA010DSAPIEmailV0CGSgSayAA10DSAPIEmailCGSgSayAA013DSAPIEnvelopeX0CGSgSayAA010DSAPIFirstZ0CGSgSayAA15DSAPIFormulaTabCGSgSayAA09DSAPIFullZ0CGSgSayAA16DSAPIInitialHereCGSgSayAA09DSAPILastZ0CGSgSayAA9DSAPIListCGSgSayAA13DSAPINotarizeVGSgSayAA15DSAPINotarySealVGSgSayAA9DSAPINoteCGSgSayAA11DSAPINumberCGSgSayAA010DSAPIPhoneM0VGSgSayAA20DSAPIPolyLineOverlayVGSgAA012DSAPIPrefillF0VSgSayAA15DSAPIRadioGroupCGSgSayAA21DSAPISignerAttachmentCGSgSayAA13DSAPISignHereCGSgSayAA17DSAPISmartSectionVGSgSayAA8DSAPISsnCGSgSayAA13DSAPITabGroupCGSgSayAA9DSAPITextCGSgSayAA10DSAPITitleCGSgSayAA9DSAPIViewVGSgSayAA8DSAPIZipCGSgtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionNumber":{"role":"symbol","title":"DSAPICommissionNumber","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommissionNumber"}],"abstract":[{"type":"text","text":"A Commission Number tab displays a notary's commission number. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICommissionNumber"}],"url":"\/documentation\/docusignapi\/dsapicommissionnumber"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateSigned":{"role":"symbol","title":"DSAPIDateSigned","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateSigned"}],"abstract":[{"type":"text","text":"A tab that displays the date that the recipient signed the document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateSigned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDateSigned"}],"url":"\/documentation\/docusignapi\/dsapidatesigned"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDate":{"role":"symbol","title":"DSAPIDate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDate"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to enter a date. Date tabs are one-line fields that allow date information to be entered in any format. The tooltip for this tab recommends entering the date as MM\/DD\/YYYY, but this is not enforced. The format entered by the signer is retained. If you need a particular date format enforced, DocuSign recommends using a Text tab with a validation pattern and a validation message to enforce the format."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDate"}],"url":"\/documentation\/docusignapi\/dsapidate"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITitle":{"role":"symbol","title":"DSAPITitle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITitle"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's title."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITitle"}],"url":"\/documentation\/docusignapi\/dsapititle"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICurrency":{"role":"symbol","title":"DSAPICurrency","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICurrency"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICurrency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICurrency"}],"url":"\/documentation\/docusignapi\/dsapicurrency"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabGroup":{"role":"symbol","title":"DSAPITabGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabGroup"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabGroup"}],"url":"\/documentation\/docusignapi\/dsapitabgroup"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIView":{"role":"symbol","title":"DSAPIView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIView"}],"abstract":[{"type":"text","text":"This tab is used with the Approve tab to handle supplemental documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIView"}],"url":"\/documentation\/docusignapi\/dsapiview"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISmartSection":{"role":"symbol","title":"DSAPISmartSection","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISmartSection"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISmartSection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISmartSection"}],"url":"\/documentation\/docusignapi\/dsapismartsection"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINote":{"role":"symbol","title":"DSAPINote","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINote"}],"abstract":[{"type":"text","text":"A tab that displays additional information, in the form of a note, for the recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINote"}],"url":"\/documentation\/docusignapi\/dsapinote"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","title":"DSAPITabs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}],"url":"\/documentation\/docusignapi\/dsapitabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignHere":{"role":"symbol","title":"DSAPISignHere","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISignHere"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to sign a document. May be optional."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISignHere"}],"url":"\/documentation\/docusignapi\/dsapisignhere"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISsn":{"role":"symbol","title":"DSAPISsn","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISsn"}],"abstract":[{"type":"text","text":"A one-line field that allows the recipient to enter a Social Security Number. The SSN can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for SSN information."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISsn"}],"url":"\/documentation\/docusignapi\/dsapissn"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIZip":{"role":"symbol","title":"DSAPIZip","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIZip"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to enter a ZIP code. The ZIP code can be five digits or nine digits in the ZIP+4 format. The zip code can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for ZIP code information."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIZip","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIZip"}],"url":"\/documentation\/docusignapi\/dsapizip"},"/docs/notary-api/":{"title":"DocuSign Notary","titleInlineContent":[{"type":"text","text":"DocuSign Notary"}],"type":"link","identifier":"\/docs\/notary-api\/","url":"\/docs\/notary-api\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmailAddress":{"role":"symbol","title":"DSAPIEmailAddress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEmailAddress"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's email as entered in the recipient information."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEmailAddress"}],"url":"\/documentation\/docusignapi\/dsapiemailaddress"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInitialHere":{"role":"symbol","title":"DSAPIInitialHere","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIInitialHere"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to initial the document. May be optional."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIInitialHere"}],"url":"\/documentation\/docusignapi\/dsapiinitialhere"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionState":{"role":"symbol","title":"DSAPICommissionState","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommissionState"}],"abstract":[{"type":"text","text":"A Commission State tab displays the state in which a notary's commission was granted. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICommissionState"}],"url":"\/documentation\/docusignapi\/dsapicommissionstate"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDraw":{"role":"symbol","title":"DSAPIDraw","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDraw"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to add a free-form drawing to the document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDraw","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDraw"}],"url":"\/documentation\/docusignapi\/dsapidraw"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmail":{"role":"symbol","title":"DSAPIEmail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEmail"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEmail"}],"url":"\/documentation\/docusignapi\/dsapiemail"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPhoneNumber":{"role":"symbol","title":"DSAPIPhoneNumber","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIPhoneNumber"}],"abstract":[{"type":"text","text":"A Phone Number tab enables a recipient to enter a phone number.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPhoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIPhoneNumber"}],"url":"\/documentation\/docusignapi\/dsapiphonenumber"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignerAttachment":{"role":"symbol","title":"DSAPISignerAttachment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISignerAttachment"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to attach supporting documents to an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISignerAttachment"}],"url":"\/documentation\/docusignapi\/dsapisignerattachment"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/":{"title":"`listItem`","titleInlineContent":[{"type":"text","text":"`listItem`"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPrefillTabs":{"role":"symbol","title":"DSAPIPrefillTabs","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIPrefillTabs"}],"abstract":[{"type":"text","text":"Prefill tabs are tabs that the sender can fill in before the envelope is sent. They are sometimes called sender tags or pre-fill fields.  Only the following tab types can be prefill tabs:  - text - check boxes - radio buttons    [Pre-Fill Your Own Document Fields][app] describes how prefill tabs work in the web application.   [Customize your envelopes with pre-fill fields][catblog] shows how to use prefill tabs in your application using the eSignature SDKs.  [app]:      https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-prefill-fields [catblog]:  https:\/\/www.docusign.com\/blog\/developers\/common-api-tasks-customize-your-envelopes-pre-fill-fields"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIPrefillTabs"}],"url":"\/documentation\/docusignapi\/dsapiprefilltabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)":{"role":"symbol","title":"init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"approveTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIApprove","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"checkboxTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commentThreadTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommentThread","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionCountyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionExpiration","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionStateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionState","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"companyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICompany","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateSignedTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDateSigned","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declineTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDecline","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"drawTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDraw","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeIdTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeId","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"formulaTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"fullNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFullName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"initialHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInitialHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lastNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"listTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIList","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarizeTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarySealTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"noteTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINote","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"numberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINumber","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINumber"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"phoneNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPhoneNumber","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"polyLineOverlayTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"prefillTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPrefillTabs","preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRadioGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signerAttachmentTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignerAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"smartSectionTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"ssnTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIText","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"titleTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITitle","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"viewTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"zipTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/init(approvetabs:checkboxtabs:commentthreadtabs:commissioncountytabs:commissionexpirationtabs:commissionnumbertabs:commissionstatetabs:companytabs:currencytabs:datesignedtabs:datetabs:declinetabs:drawtabs:emailaddresstabs:emailtabs:envelope-go8c"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIText":{"role":"symbol","title":"DSAPIText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIText"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to enter any type of text."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIText"}],"url":"\/documentation\/docusignapi\/dsapitext"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotarySeal":{"role":"symbol","title":"DSAPINotarySeal","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotarySeal"}],"abstract":[{"type":"text","text":"A Notary Seal tab enables the recipient to notarize a document. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarySeal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINotarySeal"}],"url":"\/documentation\/docusignapi\/dsapinotaryseal"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFormulaTab":{"role":"symbol","title":"DSAPIFormulaTab","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFormulaTab"}],"abstract":[{"type":"text","text":"The value of a formula tab is calculated from the values of other number or date tabs in the document. When the recipient completes the underlying fields, the formula tab calculates and displays the result.  The `formula` property of the tab contains the references to the underlying tabs. See [Calculated Fields][calculatedfields] in the DocuSign Support Center to learn more about formulas.  If a formula tab contains a `paymentDetails` property, the tab is considered a payment item. See [Requesting Payments Along with Signatures][paymentguide] in the DocuSign Support Center to learn more about payments.  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields [paymentguide]:     https:\/\/support.docusign.com\/en\/guides\/requesting-payments-along-with-signatures"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFormulaTab"}],"url":"\/documentation\/docusignapi\/dsapiformulatab"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommentThread":{"role":"symbol","title":"DSAPICommentThread","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommentThread"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommentThread","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICommentThread"}],"url":"\/documentation\/docusignapi\/dsapicommentthread"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotarize":{"role":"symbol","title":"DSAPINotarize","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotarize"}],"abstract":[{"type":"text","text":"A tab that alerts notary recipients that they must take action on the page. Only one notarize tab can appear on a page."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINotarize"}],"url":"\/documentation\/docusignapi\/dsapinotarize"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINumber":{"role":"symbol","title":"DSAPINumber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINumber"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to enter numbers and decimal (.) points."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINumber"}],"url":"\/documentation\/docusignapi\/dsapinumber"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/":{"title":"`radio`","titleInlineContent":[{"type":"text","text":"`radio`"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionExpiration":{"role":"symbol","title":"DSAPICommissionExpiration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommissionExpiration"}],"abstract":[{"type":"text","text":"A Commission Expiration tab displays the expiration date of a notary's commission. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using "},{"type":"reference","isActive":true,"identifier":"\/docs\/notary-api\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionExpiration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICommissionExpiration"}],"url":"\/documentation\/docusignapi\/dsapicommissionexpiration"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICompany":{"role":"symbol","title":"DSAPICompany","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICompany"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's company name."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICompany"}],"url":"\/documentation\/docusignapi\/dsapicompany"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox":{"role":"symbol","title":"DSAPICheckbox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICheckbox"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to select a yes\/no (on\/off) option."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICheckbox"}],"url":"\/documentation\/docusignapi\/dsapicheckbox"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPolyLineOverlay":{"role":"symbol","title":"DSAPIPolyLineOverlay","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIPolyLineOverlay"}],"abstract":[{"type":"text","text":"This tab enables users to strike through the text of a document. The tab is implemented as a line represented as a pair of x and y coordinates."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPolyLineOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIPolyLineOverlay"}],"url":"\/documentation\/docusignapi\/dsapipolylineoverlay"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIApprove":{"role":"symbol","title":"DSAPIApprove","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIApprove"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to approve documents without placing a signature or initials on the document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIApprove"}],"url":"\/documentation\/docusignapi\/dsapiapprove"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadioGroup":{"role":"symbol","title":"DSAPIRadioGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRadioGroup"}],"abstract":[{"type":"text","text":"This group tab is used to place radio buttons on a document. The `radios` property contains a list of "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"},{"type":"text","text":" objects  associated with the group. Only one radio button can be selected in a group."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRadioGroup"}],"url":"\/documentation\/docusignapi\/dsapiradiogroup"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFullName":{"role":"symbol","title":"DSAPIFullName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFullName"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's full name."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFullName"}],"url":"\/documentation\/docusignapi\/dsapifullname"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFirstName":{"role":"symbol","title":"DSAPIFirstName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFirstName"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's first name. This tab takes the recipient's name as entered in the recipient information, splits it into sections based on spaces and uses the first section as the first name."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFirstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFirstName"}],"url":"\/documentation\/docusignapi\/dsapifirstname"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList":{"role":"symbol","title":"DSAPIList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIList"}],"abstract":[{"type":"text","text":"This tab offers a list of options to choose from. The `listItems` property contains a list of "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/"},{"type":"text","text":" objects to specify the selectable options."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIList"}],"url":"\/documentation\/docusignapi\/dsapilist"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionCounty":{"role":"symbol","title":"DSAPICommissionCounty","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommissionCounty"}],"abstract":[{"type":"text","text":"A Commission County tab displays the county of a notary's commission. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using "},{"type":"reference","isActive":true,"identifier":"\/docs\/notary-api\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionCounty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICommissionCounty"}],"url":"\/documentation\/docusignapi\/dsapicommissioncounty"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDecline":{"role":"symbol","title":"DSAPIDecline","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDecline"}],"abstract":[{"type":"text","text":"A tab that allows the recipient the option of declining an envelope. If the recipient clicks the tab during the signing process, the envelope is voided."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDecline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDecline"}],"url":"\/documentation\/docusignapi\/dsapidecline"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeId":{"role":"symbol","title":"DSAPIEnvelopeId","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeId"}],"abstract":[{"type":"text","text":"A tab that displays the envelope ID. Recipients cannot enter or change the information in this tab."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeId"}],"url":"\/documentation\/docusignapi\/dsapienvelopeid"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILastName":{"role":"symbol","title":"DSAPILastName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILastName"}],"abstract":[{"type":"text","text":"A tab that displays the recipient's last name. This tab takes the recipient's name as entered in the recipient information, splits it into sections based on spaces and uses the last section as the last name."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPILastName"}],"url":"\/documentation\/docusignapi\/dsapilastname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateSigned\/title","value":"DSAPIDateSigned"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateSigned\/fragments","value":[{"kind":"identifier","text":"DSAPIDateSigned"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDate\/title","value":"DSAPIDate"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDate\/fragments","value":[{"kind":"identifier","text":"DSAPIDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle\/title","value":"DSAPITitle"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle\/fragments","value":[{"kind":"identifier","text":"DSAPITitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/title","value":"DSAPITabGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/fragments","value":[{"kind":"identifier","text":"DSAPITabGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINote\/title","value":"DSAPINote"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINote\/fragments","value":[{"kind":"identifier","text":"DSAPINote"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere\/title","value":"DSAPISignHere"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere\/fragments","value":[{"kind":"identifier","text":"DSAPISignHere"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn\/title","value":"DSAPISsn"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn\/fragments","value":[{"kind":"identifier","text":"DSAPISsn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIZip\/title","value":"DSAPIZip"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIZip\/fragments","value":[{"kind":"identifier","text":"DSAPIZip"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailAddress\/title","value":"DSAPIEmailAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailAddress\/fragments","value":[{"kind":"identifier","text":"DSAPIEmailAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere\/title","value":"DSAPIInitialHere"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere\/fragments","value":[{"kind":"identifier","text":"DSAPIInitialHere"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/title","value":"DSAPIEmail"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/fragments","value":[{"kind":"identifier","text":"DSAPIEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment\/title","value":"DSAPISignerAttachment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment\/fragments","value":[{"kind":"identifier","text":"DSAPISignerAttachment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/title","value":"DSAPIText"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/fragments","value":[{"kind":"identifier","text":"DSAPIText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/title","value":"DSAPIFormulaTab"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/fragments","value":[{"kind":"identifier","text":"DSAPIFormulaTab"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINumber\/title","value":"DSAPINumber"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINumber\/fragments","value":[{"kind":"identifier","text":"DSAPINumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany\/title","value":"DSAPICompany"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany\/fragments","value":[{"kind":"identifier","text":"DSAPICompany"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/title","value":"DSAPICheckbox"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/fragments","value":[{"kind":"identifier","text":"DSAPICheckbox"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove\/title","value":"DSAPIApprove"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove\/fragments","value":[{"kind":"identifier","text":"DSAPIApprove"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/title","value":"DSAPIRadioGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/fragments","value":[{"kind":"identifier","text":"DSAPIRadioGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/title","value":"DSAPIFullName"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/fragments","value":[{"kind":"identifier","text":"DSAPIFullName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFirstName\/title","value":"DSAPIFirstName"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFirstName\/fragments","value":[{"kind":"identifier","text":"DSAPIFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/title","value":"DSAPIList"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/fragments","value":[{"kind":"identifier","text":"DSAPIList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDecline\/title","value":"DSAPIDecline"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDecline\/fragments","value":[{"kind":"identifier","text":"DSAPIDecline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeId\/title","value":"DSAPIEnvelopeId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeId\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILastName\/title","value":"DSAPILastName"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILastName\/fragments","value":[{"kind":"identifier","text":"DSAPILastName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}