{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiusersettingsinformation\/locale"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiusersettingsinformation\/locale"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation\/locale","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSettingsInformation(py)locale","role":"symbol","modules":[{"name":"DocuSignAPI"}],"title":"locale","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"locale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"locale"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The user's locale code. Valid values are: - `zh_CN` - `zh_TW` - `nl` - `en` - `fr` - `de` - `it` - `ja` - `ko` - `pt` - `pt_BR` - `ru` - `es`","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locale","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSettingsInformation/locale":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation\/locale","title":"locale","url":"\/documentation\/docusignapi\/dsapiusersettingsinformation\/locale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The user's locale code. Valid values are: - `zh_CN` - `zh_TW` - `nl` - `en` - `fr` - `de` - `it` - `ja` - `ko` - `pt` - `pt_BR` - `ru` - `es`","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"locale","kind":"identifier"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSettingsInformation":{"abstract":[{"text":"Properties that configure the settings for a user. Some elements of this object have a `metadata` property, which includes the following: - `rights`: The calling users permissions to edit this setting (can be `editable` or `read_only`) - `uiHint`: Internally used to build UIs (can be `available` or `hidden`) - `options`: The values supported for this setting (not all settings have this element)","type":"text"}],"url":"\/documentation\/docusignapi\/dsapiusersettingsinformation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIUserSettingsInformation","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSettingsInformation"}],"title":"DSAPIUserSettingsInformation","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"locale","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"locale"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"locale"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation~1locale\/title","value":"locale","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation~1locale\/fragments","value":[{"text":"locale","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation\/title","op":"replace","value":"DSAPIUserSettingsInformation"},{"value":[{"kind":"identifier","text":"DSAPIUserSettingsInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation\/fragments"}]}]}