{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation"]]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiusersettingsinformation\/powerformmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiusersettingsinformation\/powerformmode"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"powerFormMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"powerFormMode","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSettingsInformation(py)powerFormMode","role":"symbol","modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"powerFormMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"powerFormMode","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation\/powerFormMode"},"abstract":[{"type":"text","text":"Indicates the Power Form mode setting for the user: - `none` - `admin` - `user`"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSettingsInformation":{"abstract":[{"text":"Properties that configure the settings for a user. Some elements of this object have a `metadata` property, which includes the following: - `rights`: The calling users permissions to edit this setting (can be `editable` or `read_only`) - `uiHint`: Internally used to build UIs (can be `available` or `hidden`) - `options`: The values supported for this setting (not all settings have this element)","type":"text"}],"url":"\/documentation\/docusignapi\/dsapiusersettingsinformation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIUserSettingsInformation","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSettingsInformation"}],"title":"DSAPIUserSettingsInformation","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSettingsInformation/powerFormMode":{"navigatorTitle":[{"text":"powerFormMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates the Power Form mode setting for the user: - `none` - `admin` - `user`"}],"type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapiusersettingsinformation\/powerformmode","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSettingsInformation\/powerFormMode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"powerFormMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"title":"powerFormMode","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"powerFormMode"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"powerFormMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"powerFormMode","kind":"identifier"}]}]}},{"value":"DSAPIUserSettingsInformation","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation\/title"},{"value":[{"kind":"identifier","text":"DSAPIUserSettingsInformation"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation\/fragments","op":"replace"},{"op":"replace","value":"powerFormMode","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation~1powerFormMode\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSettingsInformation~1powerFormMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"powerFormMode"}]}]}]}