{"variants":[{"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopeunsupportedofflinereciepients(recipientattributes:recipientname:recipientid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopeunsupportedofflinereciepients(recipientattributes:recipientname:recipientid:)"]}],"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:"}],"title":"envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"envelopeUnsupportedOfflineReciepients","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recipientAttributes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"recipientName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipientId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:","roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"envelopeUnsupportedOfflineReciepients","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recipientAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"text":"recipientName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"recipientId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)":{"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:"}],"title":"envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeUnsupportedOfflineReciepients"},{"kind":"text","text":"("},{"text":"recipientAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">, ","kind":"text"},{"text":"recipientName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"recipientId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"url":"\/documentation\/docusignapi\/objectivecnserror\/envelopeunsupportedofflinereciepients(recipientattributes:recipientname:recipientid:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"kind":"identifier","text":"ObjectiveCNSError"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>"},{"kind":"text","text":" *) "},{"text":"recipientAttributes","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"recipientName","kind":"internalParam"},{"kind":"text","text":" "},{"text":"recipientId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"recipientId"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)\/title","value":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"envelopeUnsupportedOfflineReciepientsWithRecipientAttributes:recipientName:recipientId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeUnsupportedOfflineReciepients(recipientAttributes:recipientName:recipientId:)\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title","value":"ObjectiveCNSError","op":"replace"},{"value":[{"text":"ObjectiveCNSError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}