{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopeinvalidcaptivesigningrecipients(envelopeid:clientuserid:recipientsids:recipientsnames:recipientsemails:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopeinvalidcaptivesigningrecipients(envelopeid:clientuserid:recipientsids:recipientsnames:recipientsemails:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"envelopeInvalidCaptiveSigningRecipients"},{"text":"(","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clientUserId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"recipientsIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"recipientsNames"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"recipientsEmails","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"envelopeInvalidCaptiveSigningRecipients","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"clientUserId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"recipientsIds","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"recipientsNames"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?, ","kind":"text"},{"text":"recipientsEmails","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","title":"envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)","externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:"}],"modules":[{"name":"DocuSignAPI"}]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"text":"ObjectiveCNSError","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)":{"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"envelopeInvalidCaptiveSigningRecipients"},{"text":"(","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"recipientsIds","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"recipientsNames"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientsEmails"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:"}],"url":"\/documentation\/docusignapi\/objectivecnserror\/envelopeinvalidcaptivesigningrecipients(envelopeid:clientuserid:recipientsids:recipientsnames:recipientsemails:)","title":"envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"envelopeId"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientUserId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"clientUserId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"recipientsIds:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"recipientsIds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recipientsNames:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"recipientsNames","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsEmails:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"recipientsEmails","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title","value":"ObjectiveCNSError","op":"replace"},{"op":"replace","value":[{"text":"ObjectiveCNSError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments"},{"value":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeInvalidCaptiveSigningRecipients(envelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"envelopeInvalidCaptiveSigningRecipientsWithEnvelopeId:clientUserId:recipientsIds:recipientsNames:recipientsEmails:"}],"op":"replace"}]}]}