{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeUnsupportedOfflineTabAttributes"},{"text":"(","kind":"text"},{"text":"tabAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"tabId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopeunsupportedofflinetabattributes(tabattributes:tabid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopeunsupportedofflinetabattributes(tabattributes:tabid:)"]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"title":"envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)","externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:","role":"symbol","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"envelopeUnsupportedOfflineTabAttributes"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tabAttributes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"text":"tabId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"navigatorTitle":[{"kind":"identifier","text":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:"}],"roleHeading":"Type Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)":{"navigatorTitle":[{"text":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"envelopeUnsupportedOfflineTabAttributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tabAttributes","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">, "},{"text":"tabId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"title":"envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)","url":"\/documentation\/docusignapi\/objectivecnserror\/envelopeunsupportedofflinetabattributes(tabattributes:tabid:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"text":"ObjectiveCNSError","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tabAttributes"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tabId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tabId"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeUnsupportedOfflineTabAttributes(tabAttributes:tabId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"envelopeUnsupportedOfflineTabAttributesWithTabAttributes:tabId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title","value":"ObjectiveCNSError"},{"value":[{"kind":"identifier","text":"ObjectiveCNSError"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments"}]}]}