{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"envelopeReadyForSync","kind":"identifier"},{"kind":"text","text":"("},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeReadyForSync(envelopeId:additionalReason:)"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"kind":"symbol","metadata":{"roleHeading":"Type Method","title":"envelopeReadyForSync(envelopeId:additionalReason:)","role":"symbol","navigatorTitle":[{"text":"envelopeReadyForSyncWithEnvelopeId:additionalReason:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeReadyForSync"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"additionalReason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)envelopeReadyForSyncWithEnvelopeId:additionalReason:","modules":[{"name":"DocuSignAPI"}]},"variants":[{"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopereadyforsync(envelopeid:additionalreason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/objectivecnserror\/envelopereadyforsync(envelopeid:additionalreason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"kind":"identifier","text":"ObjectiveCNSError"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/envelopeReadyForSync(envelopeId:additionalReason:)":{"type":"topic","url":"\/documentation\/docusignapi\/objectivecnserror\/envelopereadyforsync(envelopeid:additionalreason:)","title":"envelopeReadyForSync(envelopeId:additionalReason:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envelopeReadyForSync(envelopeId:additionalReason:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"envelopeReadyForSyncWithEnvelopeId:additionalReason:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeReadyForSync"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"additionalReason"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"envelopeReadyForSyncWithEnvelopeId:additionalReason:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"envelopeReadyForSyncWithEnvelopeId:additionalReason:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"envelopeReadyForSyncWithEnvelopeId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"envelopeId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"additionalReason:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"additionalReason","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"ObjectiveCNSError","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments","op":"replace","value":[{"text":"ObjectiveCNSError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeReadyForSync(envelopeId:additionalReason:)\/title","value":"envelopeReadyForSyncWithEnvelopeId:additionalReason:","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envelopeReadyForSync(envelopeId:additionalReason:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"envelopeReadyForSyncWithEnvelopeId:additionalReason:","kind":"identifier"}],"op":"replace"}]}]}