{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"envleopeSignerCannotSignOnMobile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)envleopeSignerCannotSignOnMobileWithEnvelopeId:","title":"envleopeSignerCannotSignOnMobile(envelopeId:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"envleopeSignerCannotSignOnMobile"},{"text":"(","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"envleopeSignerCannotSignOnMobileWithEnvelopeId:"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/envleopesignercannotsignonmobile(envelopeid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/envleopesignercannotsignonmobile(envelopeid:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envleopeSignerCannotSignOnMobile(envelopeId:)"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/envleopeSignerCannotSignOnMobile(envelopeId:)":{"kind":"symbol","title":"envleopeSignerCannotSignOnMobile(envelopeId:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"envleopeSignerCannotSignOnMobile"},{"text":"(","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"url":"\/documentation\/docusignapi\/objectivecnserror\/envleopesignercannotsignonmobile(envelopeid:)","navigatorTitle":[{"kind":"identifier","text":"envleopeSignerCannotSignOnMobileWithEnvelopeId:"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/envleopeSignerCannotSignOnMobile(envelopeId:)","abstract":[],"role":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"text":"ObjectiveCNSError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"envleopeSignerCannotSignOnMobileWithEnvelopeId:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"envleopeSignerCannotSignOnMobileWithEnvelopeId:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"envleopeSignerCannotSignOnMobileWithEnvelopeId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"envelopeId"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envleopeSignerCannotSignOnMobile(envelopeId:)\/title","value":"envleopeSignerCannotSignOnMobileWithEnvelopeId:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1envleopeSignerCannotSignOnMobile(envelopeId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"envleopeSignerCannotSignOnMobileWithEnvelopeId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title","value":"ObjectiveCNSError","op":"replace"},{"value":[{"text":"ObjectiveCNSError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}