{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/sdkinvalidinput(keys:methodname:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/sdkinvalidinput(keys:methodname:)"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)sdkInvalidInputWithKeys:methodName:","modules":[{"name":"DocuSignAPI"}],"title":"sdkInvalidInput(keys:methodName:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkInvalidInput","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keys"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"text":"methodName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}],"navigatorTitle":[{"text":"sdkInvalidInputWithKeys:methodName:","kind":"identifier"}],"role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/sdkInvalidInput(keys:methodName:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkInvalidInput","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keys"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">, "},{"text":"methodName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/sdkInvalidInput(keys:methodName:)":{"type":"topic","kind":"symbol","title":"sdkInvalidInput(keys:methodName:)","url":"\/documentation\/docusignapi\/objectivecnserror\/sdkinvalidinput(keys:methodname:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/sdkInvalidInput(keys:methodName:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkInvalidInput"},{"text":"(","kind":"text"},{"text":"keys","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"methodName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sdkInvalidInputWithKeys:methodName:","kind":"identifier"}],"abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"text":"ObjectiveCNSError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sdkInvalidInputWithKeys:methodName:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sdkInvalidInputWithKeys:methodName:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"sdkInvalidInputWithKeys:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"kind":"text","text":" *) "},{"text":"keys","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"methodName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"methodName","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"sdkInvalidInputWithKeys:methodName:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1sdkInvalidInput(keys:methodName:)\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1sdkInvalidInput(keys:methodName:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"sdkInvalidInputWithKeys:methodName:","kind":"identifier"}]},{"value":"ObjectiveCNSError","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments","op":"replace","value":[{"kind":"identifier","text":"ObjectiveCNSError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}