{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/templateHasNoRecipients()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/objectivecnserror\/templatehasnorecipients()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/objectivecnserror\/templatehasnorecipients()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateHasNoRecipients"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"templateHasNoRecipients()","navigatorTitle":[{"kind":"identifier","text":"templateHasNoRecipients"}],"externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)templateHasNoRecipients","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"templateHasNoRecipients","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"symbolKind":"method","roleHeading":"Type Method"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/templateHasNoRecipients()":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/templateHasNoRecipients()","title":"templateHasNoRecipients()","abstract":[],"url":"\/documentation\/docusignapi\/objectivecnserror\/templatehasnorecipients()","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"templateHasNoRecipients","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"navigatorTitle":[{"text":"templateHasNoRecipients","kind":"identifier"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"kind":"identifier","text":"ObjectiveCNSError"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"templateHasNoRecipients"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"templateHasNoRecipients"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"templateHasNoRecipients"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"templateHasNoRecipients","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1templateHasNoRecipients()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1templateHasNoRecipients()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"templateHasNoRecipients","kind":"identifier"}]},{"op":"replace","value":"ObjectiveCNSError","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title"},{"value":[{"kind":"identifier","text":"ObjectiveCNSError"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}