{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/templateunsupportedrolenamefornoninpersonrecipient(recipientname:recipientid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objectivecnserror\/templateunsupportedrolenamefornoninpersonrecipient(recipientname:recipientid:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templateUnsupportedRoleNameForNonInPersonRecipient","kind":"identifier"},{"kind":"text","text":"("},{"text":"recipientName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)ObjectiveCNSError(cm)templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"templateUnsupportedRoleNameForNonInPersonRecipient","kind":"identifier"},{"kind":"text","text":"("},{"text":"recipientName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipientId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"title":"templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)","roleHeading":"Type Method"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError":{"title":"ObjectiveCNSError","url":"\/documentation\/docusignapi\/objectivecnserror","navigatorTitle":[{"kind":"identifier","text":"ObjectiveCNSError"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjectiveCNSError","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjectiveCNSError/templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)":{"kind":"symbol","url":"\/documentation\/docusignapi\/objectivecnserror\/templateunsupportedrolenamefornoninpersonrecipient(recipientname:recipientid:)","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjectiveCNSError\/templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)","navigatorTitle":[{"kind":"identifier","text":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"templateUnsupportedRoleNameForNonInPersonRecipient","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recipientName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"}],"title":"templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"recipientName"},{"text":" ","kind":"text"},{"text":"recipientId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"recipientId","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"ObjectiveCNSError","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ObjectiveCNSError"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)\/title","op":"replace","value":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjectiveCNSError~1templateUnsupportedRoleNameForNonInPersonRecipient(recipientName:recipientId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"templateUnsupportedRoleNameForNonInPersonRecipientWithRecipientName:recipientId:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}