{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"name","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo(py)name","navigatorTitle":[{"text":"name","kind":"identifier"}],"modules":[{"name":"DocuSignAPI"}]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/name"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo\/name","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo/name":{"title":"name","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo\/name","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/name"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"title":"DSAPIAccountServerUserInfo","role":"symbol","navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"name","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"name","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"name"}]}],"kind":"declarations"},"op":"replace"},{"value":"name","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo~1name\/title","op":"replace"},{"value":[{"kind":"identifier","text":"name"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo~1name\/fragments"},{"value":"DSAPIAccountServerUserInfo","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments","value":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}