{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/userconsumerdisclosure"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/userconsumerdisclosure"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userConsumerDisclosure","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","text":"DSAPIConsumerDisclosure","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo\/userConsumerDisclosure"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"userConsumerDisclosure","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo(py)userConsumerDisclosure","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","title":"userConsumerDisclosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userConsumerDisclosure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure","text":"DSAPIConsumerDisclosure"},{"text":"?","kind":"text"}],"symbolKind":"property"},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo/userConsumerDisclosure":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/userconsumerdisclosure","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"userConsumerDisclosure"}],"role":"symbol","title":"userConsumerDisclosure","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userConsumerDisclosure","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure","text":"DSAPIConsumerDisclosure","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo\/userConsumerDisclosure"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","abstract":[],"navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"role":"symbol","title":"DSAPIAccountServerUserInfo","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure":{"type":"topic","title":"DSAPIConsumerDisclosure","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"navigatorTitle":[{"text":"DSAPIConsumerDisclosure","kind":"identifier"}],"abstract":[{"type":"text","text":"Details about consumer disclosures."}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"userConsumerDisclosure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userConsumerDisclosure"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIConsumerDisclosure","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure"},{"text":" * ","kind":"text"},{"text":"userConsumerDisclosure","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo~1userConsumerDisclosure\/title","value":"userConsumerDisclosure","op":"replace"},{"op":"replace","value":[{"text":"userConsumerDisclosure","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo~1userConsumerDisclosure\/fragments"},{"value":"DSAPIAccountServerUserInfo","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments","value":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/title","value":"DSAPIConsumerDisclosure"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/fragments","value":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}