{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo(py)userSettings","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"userSettings"}],"symbolKind":"property","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userSettings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation","kind":"typeIdentifier","text":"DSAPIAccountSettingsInformation"},{"text":"?","kind":"text"}],"role":"symbol","title":"userSettings"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/usersettings"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/usersettings"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo\/userSettings","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","text":"DSAPIAccountSettingsInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","abstract":[],"navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"role":"symbol","title":"DSAPIAccountServerUserInfo","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo/userSettings":{"navigatorTitle":[{"kind":"identifier","text":"userSettings"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo\/userSettings","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo\/usersettings","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIAccountSettingsInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation"},{"text":"?","kind":"text"}],"kind":"symbol","title":"userSettings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"userSettings","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"userSettings","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIAccountSettingsInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"userSettings"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","value":"DSAPIAccountSettingsInformation","op":"replace"},{"value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title","value":"DSAPIAccountServerUserInfo"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments","value":[{"kind":"identifier","text":"DSAPIAccountServerUserInfo"}],"op":"replace"},{"op":"replace","value":"userSettings","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo~1userSettings\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo~1userSettings\/fragments","value":[{"text":"userSettings","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}