{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","externalID":"s:11DocuSignAPI11DSAPISignerC10accessCode0eF8Metadata09addAccessF7ToEmail23additionalNotifications012agentCanEditK00noP4Name37allowSystemOverrideForLockedRecipient14autoNavigation0X15RespondedReason17bulkRecipientsUri03canB7Offline12clientUserId14completedCount14creationReason12customFields16declinedDateTime14declinedReason07defaultW011delegatedBy09delegatedJ017deliveredDateTime14deliveryMethod014deliveryMethodG012designatorId16designatorIdGuid18documentVisibility5email05emailG017emailNotification05emailW14PostSigningURL08embeddedW8StartURL12errorDetails17excludedDocuments9faxNumber09faxNumberG005firstQ005firstqG004fullQ004fullqG0020idCheckConfigurationQ0020idCheckConfigurationqG023idCheckInformationInput20identityVerification07inheritK25NotificationConfiguration06isBulkW006isBulkwG004lastQ004lastqG006lockedW17PhoneAuthEditable06lockedW11SmsEditable4name04nameG08notaryId012notarySignerK4Sent4note04noteG017offlineAttributes19phoneAuthentication11phoneNumber9proofFile20recipientAttachments29recipientAuthenticationStatus016recipientFeatureG011recipientId15recipientIdGuid27recipientSignatureProviders21recipientSuppliesTabs13recipientType013recipientTypeG015requireIdLookup015requireIdLookupG024requireSignerCertificate07requireB7OnPaper22requireUploadSignature04roleQ012routingOrder012routingOrderG012sentDateTime13signatureInfo14signedDateTime18signInEachLocation018signInEachLocationG014signingGroupId014signingGroupIdG0012signingGroupQ017signingGroupUsers17smsAuthentication21socialAuthentications6status06statusF014suppressEmails4tabs08templateV016templateRequired13totalTabCount6userIdACSSSg_AA013DSAPIPropertyG0CSgA72_SayAA36DSAPIRecipientAdditionalNotificationCGSgA72_A72_S2bA72_10Foundation3URLVSgSbA72_A72_A72_SaySSGSgA80_4DateVSgA72_SbAA19DSAPIDelegationInfoVSgSayA90_GSgA88_A72_A75_A72_A72_SayAA23DSAPIDocumentVisibilityCGSgA72_A75_AA014DSAPIRecipientK12NotificationCSgA72_A72_AA17DSAPIErrorDetailsCSgA85_A72_A75_A72_A75_A72_A75_A72_A75_AA28DSAPIIdCheckInformationInputVSgAA34DSAPIRecipientIdentityVerificationVSgS2bA75_A72_A75_A72_A72_A72_A75_A72_A72_A72_A75_AA22DSAPIOfflineAttributesCSgAA33DSAPIRecipientPhoneAuthenticationVSgAA25DSAPIRecipientPhoneNumberVSgAA23DSAPIRecipientProofFileVSgSayAA24DSAPIRecipientAttachmentCGSgAA25DSAPIAuthenticationStatusVSgSayAA021DSAPIFeatureAvailableG0VGSgA72_A72_SayAA31DSAPIRecipientSignatureProviderCGSgSbA72_A75_SbA75_A72_S2bA72_A72_A75_A88_AA34DSAPIRecipientSignatureInformationCSgA88_SbA75_A72_A75_A72_SayAA13DSAPIUserInfoCGSgAA31DSAPIRecipientSMSAuthenticationCSgSayAA25DSAPISocialAuthenticationCGSgA72_A72_SbAA9DSAPITabsCSgS2bA72_A72_tcfc","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accessCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"accessCodeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"agentCanEditEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"agentCanEditName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"allowSystemOverrideForLockedRecipient","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoNavigation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoRespondedReason","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"bulkRecipientsUri","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"canSignOffline"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"completedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"creationReason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"customFields","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declinedDateTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"declinedReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"defaultRecipient"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"delegatedBy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIDelegationInfo","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegatedTo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","text":"DSAPIDelegationInfo"},{"text":"]?, ","kind":"text"},{"text":"deliveredDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"deliveryMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"deliveryMethodMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"designatorId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"designatorIdGuid","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"documentVisibility","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","text":"DSAPIDocumentVisibility"},{"text":"]?, ","kind":"text"},{"text":"email","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailNotification"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","text":"DSAPIRecipientEmailNotification"},{"text":"?, ","kind":"text"},{"text":"emailRecipientPostSigningURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"excludedDocuments","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"faxNumberMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"firstName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"firstNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullNameMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"idCheckConfigurationName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"idCheckInformationInput","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"identityVerification"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientIdentityVerification","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inheritEmailNotificationConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isBulkRecipient"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isBulkRecipientMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lastNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lockedRecipientSmsEditable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"notaryId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"notarySignerEmailSent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noteMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"offlineAttributes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes","text":"DSAPIOfflineAttributes"},{"kind":"text","text":"?, "},{"text":"phoneAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication"},{"text":"?, ","kind":"text"},{"text":"phoneNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientPhoneNumber","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV"},{"text":"?, ","kind":"text"},{"text":"proofFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIRecipientProofFileV","text":"DSAPIRecipientProofFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipientAttachments","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientAttachment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"recipientAuthenticationStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV","text":"DSAPIAuthenticationStatus","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipientFeatureMetadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","kind":"typeIdentifier","text":"DSAPIFeatureAvailableMetadata"},{"text":"]?, ","kind":"text"},{"text":"recipientId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientIdGuid"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"recipientSignatureProviders","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientSuppliesTabs"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"recipientType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"recipientTypeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"requireIdLookup","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requireIdLookupMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"requireSignerCertificate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"requireSignOnPaper"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requireUploadSignature","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"roleName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"routingOrder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"routingOrderMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"sentDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"text":"signatureInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIRecipientSignatureInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureInformation"},{"text":"?, ","kind":"text"},{"text":"signedDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signInEachLocation"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"signInEachLocationMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"signingGroupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"signingGroupIdMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"signingGroupUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo"},{"text":"]?, ","kind":"text"},{"text":"smsAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","text":"DSAPISocialAuthentication"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"suppressEmails","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"tabs","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"templateLocked","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateRequired"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"totalTabCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"symbolKind":"init","roleHeading":"Initializer"},"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISigner\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapisigner\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:agentcaneditemail:agentcaneditname:allowsystemoverrideforlockedrecipient:autonavigation:autorespondedreason:bulkrecipientsuri:cansignoffline:clientuserid:comple-2ijfg"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"accessCodeMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"additionalNotifications","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"text":"]? = nil, ","kind":"text"},{"text":"agentCanEditEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"agentCanEditName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"allowSystemOverrideForLockedRecipient"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"autoNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"autoRespondedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"bulkRecipientsUri","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"canSignOffline","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"clientUserId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completedCount"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"creationReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"customFields"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"declinedDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"declinedReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"defaultRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"delegatedBy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDelegationInfo","text":"DSAPIDelegationInfo","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV"},{"text":"? = nil, ","kind":"text"},{"text":"delegatedTo","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDelegationInfo","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","text":"DSAPIDelegationInfo","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"deliveredDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"? = nil, ","kind":"text"},{"text":"deliveryMethod","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"deliveryMethodMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"designatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"designatorIdGuid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"documentVisibility","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","text":"DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"emailMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailNotification"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"text":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"excludedDocuments"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"faxNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faxNumberMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"firstName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"fullName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"fullNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"idCheckInformationInput","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"identityVerification"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","text":"DSAPIRecipientIdentityVerification","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV"},{"kind":"text","text":"? = nil, "},{"text":"inheritEmailNotificationConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"isBulkRecipient","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"isBulkRecipientMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lastName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"lastNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"lockedRecipientPhoneAuthEditable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"lockedRecipientSmsEditable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"nameMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"notaryId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"notarySignerEmailSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"note"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"noteMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"offlineAttributes","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes","text":"DSAPIOfflineAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"phoneAuthentication"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","text":"DSAPIRecipientPhoneAuthentication"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","text":"DSAPIRecipientPhoneNumber","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber"},{"kind":"text","text":"? = nil, "},{"text":"proofFile","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientProofFile","text":"DSAPIRecipientProofFile","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPIRecipientProofFileV"},{"kind":"text","text":"? = nil, "},{"text":"recipientAttachments","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"text":"recipientAuthenticationStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","text":"DSAPIAuthenticationStatus","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"kind":"text","text":"? = nil, "},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","text":"DSAPIFeatureAvailableMetadata"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"recipientIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","text":"DSAPIRecipientSignatureProvider"},{"text":"]? = nil, ","kind":"text"},{"text":"recipientSuppliesTabs","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"recipientType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"recipientTypeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"requireIdLookup"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"requireSignerCertificate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"requireSignOnPaper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"requireUploadSignature","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"roleName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"routingOrder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"routingOrderMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"sentDateTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signatureInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureInformation","text":"DSAPIRecipientSignatureInformation"},{"text":"? = nil, ","kind":"text"},{"text":"signedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signInEachLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"signInEachLocationMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"signingGroupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"signingGroupName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"signingGroupUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","text":"DSAPIUserInfo"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"socialAuthentications"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"text":"]? = nil, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"statusCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"suppressEmails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"tabs"},{"text":": ","kind":"text"},{"text":"DSAPITabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"templateLocked"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"templateRequired","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"totalTabCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISigner"]]},"references":{"/docs/esign-rest-api/reference/accounts/identityverifications/":{"type":"link","title":"IdentityVerifications","titleInlineContent":[{"type":"text","text":"IdentityVerifications"}],"url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/"},"https://support.docusign.com/en/guides/ndse-user-guide-recipient-authentication":{"type":"link","identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","titleInlineContent":[{"type":"text","text":"recipient authentication"}],"title":"recipient authentication","url":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISigner":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISigner","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapisigner","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISigner","kind":"symbol","title":"DSAPISigner","navigatorTitle":[{"kind":"identifier","text":"DSAPISigner"}],"role":"symbol","abstract":[{"text":"A complex type containing information about a signer recipient. A signer is a recipient who must take action on a document, such as sign, initial, date, or add data to form fields on a document.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneNumber":{"abstract":[{"text":"Describes the recipient phone number.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientPhoneNumber","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientphonenumber","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientPhoneNumber","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","role":"symbol","title":"DSAPIRecipientPhoneNumber","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAdditionalNotification":{"abstract":[{"type":"text","text":"Describes an additional notification method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRecipientAdditionalNotification","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientadditionalnotification","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","role":"symbol","title":"DSAPIRecipientAdditionalNotification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientEmailNotification":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientemailnotification","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","role":"symbol","title":"DSAPIRecipientEmailNotification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes":{"abstract":[{"type":"text","text":"Reserved for DocuSign use."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIOfflineAttributes","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiofflineattributes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes","role":"symbol","title":"DSAPIOfflineAttributes","kind":"symbol"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"type":"link","title":"More information","titleInlineContent":[{"type":"text","text":"More information"}],"url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientIdentityVerification":{"abstract":[{"text":"Specifies ID Verification applied on an envelope by workflow ID. See the ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","isActive":true,"type":"reference"},{"text":" method in the ","type":"text"},{"isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","type":"reference"},{"text":" resource for more information on how to retrieve workflow IDs available for an account. This can be used in addition to other ","type":"text"},{"isActive":true,"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","type":"reference"},{"text":" methods.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientIdentityVerification"}],"url":"\/documentation\/docusignapi\/dsapirecipientidentityverification","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientIdentityVerification","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","role":"symbol","title":"DSAPIRecipientIdentityVerification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISigner/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapisigner\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:agentcaneditemail:agentcaneditname:allowsystemoverrideforlockedrecipient:autonavigation:autorespondedreason:bulkrecipientsuri:cansignoffline:clientuserid:comple-2ijfg","title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISigner\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accessCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"accessCodeMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"addAccessCodeToEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"additionalNotifications","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"agentCanEditEmail"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"agentCanEditName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"allowSystemOverrideForLockedRecipient","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoNavigation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"autoRespondedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"bulkRecipientsUri","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"canSignOffline","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"creationReason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customFields"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"declinedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"declinedReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"defaultRecipient"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"delegatedBy","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","text":"DSAPIDelegationInfo"},{"kind":"text","text":"?, "},{"text":"delegatedTo","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIDelegationInfo","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"deliveredDateTime"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"deliveryMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"deliveryMethodMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"designatorId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"designatorIdGuid"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"documentVisibility","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility"},{"kind":"text","text":"]?, "},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"emailMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailNotification"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientEmailNotification","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"text":"?, ","kind":"text"},{"text":"emailRecipientPostSigningURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"excludedDocuments"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"faxNumberMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fullNameMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"idCheckConfigurationName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"idCheckInformationInput","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"identityVerification"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","text":"DSAPIRecipientIdentityVerification","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"inheritEmailNotificationConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"isBulkRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isBulkRecipientMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"lastName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lastNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"notaryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"notarySignerEmailSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"note","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noteMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offlineAttributes"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes","text":"DSAPIOfflineAttributes","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"phoneAuthentication","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","text":"DSAPIRecipientPhoneAuthentication"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"phoneNumber"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"proofFile","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPIRecipientProofFileV","text":"DSAPIRecipientProofFile"},{"kind":"text","text":"?, "},{"text":"recipientAttachments","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","text":"DSAPIRecipientAttachment"},{"text":"]?, ","kind":"text"},{"text":"recipientAuthenticationStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV","kind":"typeIdentifier","text":"DSAPIAuthenticationStatus"},{"text":"?, ","kind":"text"},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","text":"DSAPIFeatureAvailableMetadata"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipientIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"text":"DSAPIRecipientSignatureProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider"},{"text":"]?, ","kind":"text"},{"text":"recipientSuppliesTabs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipientType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientTypeMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"requireIdLookup","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requireSignerCertificate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"requireSignOnPaper","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requireUploadSignature"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"roleName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"routingOrder"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrderMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"sentDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"signatureInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIRecipientSignatureInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureInformation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"signInEachLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signInEachLocationMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"signingGroupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"signingGroupIdMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupUsers"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"smsAuthentication"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"text":"socialAuthentications","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suppressEmails"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"tabs","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"templateLocked"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"templateRequired"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"totalTabCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"title":"DSAPIRecipientSignatureProvider","abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"/docs/esign-rest-api/esign101/concepts/documents/":{"type":"link","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/","titleInlineContent":[{"type":"text","text":"ID Verification"}],"title":"ID Verification","url":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication","type":"topic","navigatorTitle":[{"text":"DSAPISocialAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","role":"symbol","title":"DSAPISocialAuthentication","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAuthenticationStatus":{"title":"DSAPIAuthenticationStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPIAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiauthenticationstatus","abstract":[{"text":"A complex element that contains information about a user's authentication status.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","role":"symbol","navigatorTitle":[{"text":"DSAPIAuthenticationStatus","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIdCheckInformationInput":{"url":"\/documentation\/docusignapi\/dsapiidcheckinformationinput","title":"DSAPIIdCheckInformationInput","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIIdCheckInformationInput","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIIdCheckInformationInput","kind":"identifier"}],"abstract":[{"type":"text","text":"A complex element that contains input information related to a recipient ID check."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDelegationInfo":{"url":"\/documentation\/docusignapi\/dsapidelegationinfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIDelegationInfo","kind":"identifier"}],"title":"DSAPIDelegationInfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIDelegationInfo"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDelegationInfo","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientProofFile":{"abstract":[{"type":"text","text":"The proof file of the recipient. "},{"identifier":"\/docs\/idevidence-api\/","isActive":true,"type":"reference"},{"text":" uses proof files to store the identification data that recipients submit when verifying their ID with ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/","type":"reference","isActive":true}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientProofFile","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientprooffile","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientProofFile","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientProofFile","role":"symbol","title":"DSAPIRecipientProofFile","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneAuthentication":{"abstract":[{"text":"A complex type that contains the elements:  * `recipMayProvideNumber`: A Boolean value that specifies whether the recipient can use the phone number of their choice. * `senderProvidedNumbers`: A list of phone numbers that the recipient can use. * `recordVoicePrint`: Reserved for DocuSign. * `validateRecipProvidedNumber`: Reserved for DocuSign.","type":"text"}],"title":"DSAPIRecipientPhoneAuthentication","url":"\/documentation\/docusignapi\/dsapirecipientphoneauthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"navigatorTitle":[{"text":"DSAPIRecipientPhoneAuthentication","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFeatureAvailableMetadata":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFeatureAvailableMetadata","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapifeatureavailablemetadata","type":"topic","navigatorTitle":[{"text":"DSAPIFeatureAvailableMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","role":"symbol","title":"DSAPIFeatureAvailableMetadata","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureInformation":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureInformation"}],"title":"DSAPIRecipientSignatureInformation","url":"\/documentation\/docusignapi\/dsapirecipientsignatureinformation","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureInformation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientSignatureInformation","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Allows the sender to pre-specify the signature name, signature initials and signature font used in the signature stamp for the recipient.  Used only with recipient types In Person Signers and Signers."}]},"/docs/esign-rest-api/reference/accounts/identityverifications/list/":{"type":"link","title":"list","titleInlineContent":[{"type":"text","text":"list"}],"url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocumentVisibility":{"abstract":[{"type":"text","text":"This object configures a recipient's read\/write access to a document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIDocumentVisibility","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapidocumentvisibility","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocumentVisibility"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","role":"symbol","title":"DSAPIDocumentVisibility","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","role":"symbol","title":"DSAPIRecipientAttachment","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSMSAuthentication":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","type":"topic","title":"DSAPIRecipientSMSAuthentication","role":"symbol","abstract":[{"type":"text","text":"Contains the element senderProvidedNumbers which is an Array  of phone numbers the recipient can use for SMS text authentication."}],"url":"\/documentation\/docusignapi\/dsapirecipientsmsauthentication","navigatorTitle":[{"text":"DSAPIRecipientSMSAuthentication","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"/docs/idevidence-api/":{"type":"link","url":"\/docs\/idevidence-api\/","titleInlineContent":[{"type":"text","text":"ID Evidence"}],"identifier":"\/docs\/idevidence-api\/","title":"ID Evidence"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DSAPISigner","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISigner\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISigner\/fragments","value":[{"text":"DSAPISigner","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/title","value":"DSAPIRecipientAdditionalNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/fragments","value":[{"text":"DSAPIRecipientAdditionalNotification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/title","value":"DSAPIRecipientEmailNotification","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/title","value":"DSAPIOfflineAttributes","op":"replace"},{"op":"replace","value":[{"text":"DSAPIOfflineAttributes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/title","op":"replace","value":"DSAPIRecipientSignatureProvider"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title","value":"DSAPISocialAuthentication","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments","op":"replace","value":[{"text":"DSAPISocialAuthentication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","op":"replace","value":"DSAPIPropertyMetadata"},{"value":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","op":"replace"},{"op":"replace","value":"DSAPIRecipientSignatureInformation","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureInformation\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureInformation\/fragments","value":[{"text":"DSAPIRecipientSignatureInformation","kind":"identifier"}],"op":"replace"},{"value":"DSAPIErrorDetails","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","op":"replace","value":[{"text":"DSAPIErrorDetails","kind":"identifier"}]},{"value":"DSAPIDocumentVisibility","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/title"},{"value":[{"text":"DSAPIDocumentVisibility","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/fragments","op":"replace"},{"op":"replace","value":"DSAPIRecipientAttachment","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/title"},{"value":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/fragments","op":"replace"},{"op":"replace","value":"DSAPIRecipientSMSAuthentication","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/title"},{"op":"replace","value":[{"text":"DSAPIRecipientSMSAuthentication","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/fragments"},{"op":"replace","value":"DSAPIUserInfo","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","value":[{"kind":"identifier","text":"DSAPIUserInfo"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","op":"replace","value":"DSAPITabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"text":"DSAPITabs","kind":"identifier"}]}]}]}