#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESFolderItemV2.h>


@protocol DSESFolderItemResponse
@end

@interface DSESFolderItemResponse : DSESObject

/* The number of results returned in this response. [optional]
 */
@property(nonatomic) NSString* resultSetSize;
/* Starting position of the current result set. [optional]
 */
@property(nonatomic) NSString* startPosition;
/* The last position in the result set. [optional]
 */
@property(nonatomic) NSString* endPosition;
/*  [optional]
 */
@property(nonatomic) NSString* totalRows;
/* The URI to the next chunk of records based on the search request. If the endPosition is the entire results of the search, this is null. [optional]
 */
@property(nonatomic) NSString* nextUri;
/* The postal code for the billing address. [optional]
 */
@property(nonatomic) NSString* previousUri;
/* A list of the envelopes in the specified folder or folders. [optional]
 */
@property(nonatomic) NSArray<DSESFolderItemV2>* folderItems;

@end
