#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESTextCustomField.h>
#import <DocuSignSDK/DSESListCustomField.h>


@protocol DSESCustomFields
@end

@interface DSESCustomFields : DSESObject

/* An array of text custom fields. [optional]
 */
@property(nonatomic) NSArray<DSESTextCustomField>* textCustomFields;
/* An array of list custom fields. [optional]
 */
@property(nonatomic) NSArray<DSESListCustomField>* listCustomFields;

@end
