#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESEventResult
@end

@interface DSESEventResult : DSESObject

/* Indicates the envelope status. Valid values are:\n\n* sent - The envelope is sent to the recipients. \n* created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;
/*  [optional]
 */
@property(nonatomic) NSString* eventTimestamp;
/*  [optional]
 */
@property(nonatomic) NSString* failureDescription;
/*  [optional]
 */
@property(nonatomic) NSString* vendorFailureStatusCode;

@end
