#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESLockInformation.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESBulkEnvelopeStatus.h>


@protocol DSESEnvelopeUpdateSummary
@end

@interface DSESEnvelopeUpdateSummary : DSESObject

/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;

@property(nonatomic) DSESBulkEnvelopeStatus* bulkEnvelopeStatus;

@property(nonatomic) DSESLockInformation* lockInformation;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
