#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESViewLinkRequest
@end

@interface DSESViewLinkRequest : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* returnUrl;
/*  [optional]
 */
@property(nonatomic) NSString* email;

@end
