#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESUserInfo.h>


@protocol DSESLockInformation
@end

@interface DSESLockInformation : DSESObject


@property(nonatomic) DSESUserInfo* lockedByUser;
/* Specifies the friendly name of  the application that is locking the envelope. [optional]
 */
@property(nonatomic) NSString* lockedByApp;
/*  [optional]
 */
@property(nonatomic) NSString* lockedUntilDateTime;
/* Sets the time, in seconds, until the lock expires when there is no activity on the envelope.\n\nIf no value is entered, then the default value of 300 seconds is used. The maximum value is 1,800 seconds.\n\nThe lock duration can be extended. [optional]
 */
@property(nonatomic) NSString* lockDurationInSeconds;
/*  [optional]
 */
@property(nonatomic) NSString* lockType;
/* Reserved for future use.\n\nIndicates whether a scratchpad is used for editing information. [optional]
 */
@property(nonatomic) NSString* useScratchPad;
/*  [optional]
 */
@property(nonatomic) NSString* lockToken;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
