#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESNameValue.h>
#import <DocuSignSDK/DSESSenderEmailNotifications.h>
#import <DocuSignSDK/DSESSignerEmailNotifications.h>


@protocol DSESUserSettingsInformation
@end

@interface DSESUserSettingsInformation : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray<DSESNameValue>* userSettings;

@property(nonatomic) DSESSignerEmailNotifications* signerEmailNotifications;

@property(nonatomic) DSESSenderEmailNotifications* senderEmailNotifications;

- (NSDictionary *)dictionaryRepresentation;

@end
