#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESInlineTemplate.h>
#import <DocuSignSDK/DSESDocument.h>
#import <DocuSignSDK/DSESServerTemplate.h>


@protocol DSESCompositeTemplate
@end

@interface DSESCompositeTemplate : DSESObject

/* Specifies the identify the composite template. It is used as a reference when adding document object information. If used, the document content-disposition must include the composite template ID to which the document should be added. If composite template ID is not specified in the content-disposition, the document is applied based on the value of the `documentId` property only. If no document object is specified, the composite template inherits the first document. [optional]
 */
@property(nonatomic) NSString* compositeTemplateId;
/* 0 or more server-side templates and their position in the overlay. If supplied, they are overlaid into the envelope in the order of their Sequence value [optional]
 */
@property(nonatomic) NSArray<DSESServerTemplate>* serverTemplates;
/* Zero or more inline templates and their position in the overlay. If supplied, they are overlaid into the envelope in the order of their Sequence value. [optional]
 */
@property(nonatomic) NSArray<DSESInlineTemplate>* inlineTemplates;
/*  [optional]
 */
@property(nonatomic) NSString* pdfMetaDataTemplateSequence;

@property(nonatomic) DSESDocument* document;

@end
