#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESMergeField.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESTab.h>

@protocol DSESSignHere
@end

@interface DSESSignHere : DSESTab

/*  [optional]
 */
@property(nonatomic) NSString* scaleValue;
/*  [optional]
 */
@property(nonatomic) NSString* optional;

@property (nonatomic) NSString* imageDataBase64; // base 64 image representation. only used for image based tags (signhere & initialhere).

@property (nonatomic) NSString* stampType;

@end
