#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESNotification.h>
#import <DocuSignSDK/DSESLockInformation.h>
#import <DocuSignSDK/DSESDocument.h>
#import <DocuSignSDK/DSESEventNotification.h>
#import <DocuSignSDK/DSESCustomFields.h>
#import <DocuSignSDK/DSESEmailSettings.h>
#import <DocuSignSDK/DSESRecipients.h>
#import <DocuSignSDK/DSESTemplateRole.h>
#import <DocuSignSDK/DSESCompositeTemplate.h>
#import <DocuSignSDK/DSESAttachment.h>


@protocol DSESEnvelopeDefinition
@end

@interface DSESEnvelopeDefinition : DSESObject

/* Complex element contains the details on the documents in the envelope. [optional]
 */
@property(nonatomic) NSArray<DSESDocument>* documents;

@property(nonatomic) NSArray <DSESAttachment>* attachments;

@property(nonatomic) DSESRecipients* recipients;

@property(nonatomic) DSESCustomFields* customFields;

@property(nonatomic) DSESEventNotification* eventNotification;
/* This sets the brand profile format used for the envelope. The value in the string is the brandId associated with the profile. Account branding must be enabled for the account to use this option. [optional]
 */
@property(nonatomic) NSString* brandId;
/* When set to **true**, this enables the Recursive Recipients feature and allows a recipient to appear more than once in the routing order. [optional]
 */
@property(nonatomic) NSString* allowRecipientRecursion;
/* The unique identifier of the template. If this is not provided, DocuSign will generate a value. [optional]
 */
@property(nonatomic) NSString* templateId;
/* Specifies the template recipients. Each roleName in the template must have a recipient assigned to it. This is made up elements:\n\n* email - The recipient’s email address.\n* name - The recipient’s name.\n* roleName - The template roleName associated with the recipient.\n* clientUserId - Optional, this sets if the signer is This specifies if the recipient is embedded or remote. If the clientUserId is not null then the recipient is embedded. Note that if a ClientUserId is used and the account settings SignerMustHaveAccount or SignerMustLoginToSign are true, an error is generated on sending.\n* defaultRecipient - Optional, When set to **true**, this recipient is the default recipient and any tabs generated by the transformPdfFields option are mapped to this recipient.\n* routingOrder - This specifies the routing order of the recipient in the envelope.\n* accessCode - This optional element specifies the access code a recipient has to enter to validate the identity. This can be a maximum of 50 characters.\n* inPersonSignerName - Optional, if the template role is an in person signer, this is the full legal name of the signer. This can be a maximum of 100 characters.\n* emailNotification - This is an optional complex element that has a role specific emailSubject, emailBody, and language. It follows the same format as the emailNotification node for Recipients.\n* tabs - This allows the tab values to be specified for matching to tabs in the template. [optional]
 */
@property(nonatomic) NSArray<DSESTemplateRole>* templateRoles;
/* A complex type that can be added to create envelopes from a combination of DocuSign templates and PDF forms. The basic envelope remains the same, while the Composite Template adds new document and template overlays into the envelope. There can be any number of Composite Template structures in the envelope. [optional]
 */
@property(nonatomic) NSArray<DSESCompositeTemplate>* compositeTemplates;
/* Sets the document reading zones for screen reader applications.  This element can only be used if Document Accessibility is enabled for the account. \n\n#### Note: This information is currently generated from the DocuSign web console by setting the reading zones when creating a template, exporting the reading zone string information, and adding it here. [optional]
 */
@property(nonatomic) NSString* accessibility;
/* Used to identify an envelope. The id is a sender-generated value and is valid in the DocuSign system for 7 days. It is recommended that a transaction ID is used for offline signing to ensure that an envelope is not sent multiple times. The `transactionId` property can be used determine if an envelope status (i.e. was created or not) for cases where an internet connection was lost before the envelope status could be returned. [optional]
 */
@property(nonatomic) NSString* transactionId;
/* Indicates the envelope status. Valid values are:\n\n* sent - The envelope is sent to the recipients. \n* created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;
/* Contains a URI for an endpoint that you can use to retrieve the documents. [optional]
 */
@property(nonatomic) NSString* documentsUri;
/* Contains a URI for an endpoint that you can use to retrieve the recipients. [optional]
 */
@property(nonatomic) NSString* recipientsUri;
/* When set to **true**, the envelope is queued for processing and the value of the `status` property is set to 'Processing'. Additionally, get status calls return 'Processing' until completed. [optional]
 */
@property(nonatomic) NSString* asynchronous;
/* Contains a URI for an endpoint that you can use to retrieve the envelope or envelopes. [optional]
 */
@property(nonatomic) NSString* envelopeUri;
/* Specifies the subject of the email that is sent to all recipients.\n\nSee [ML:Template Email Subject Merge Fields] for information about adding merge field information to the email subject. [optional]
 */
@property(nonatomic) NSString* emailSubject;
/* Optional element. This is the same as the email body. If specified it is included in email body for all envelope recipients. This can be a maximum of 10000 characters [optional]
 */
@property(nonatomic) NSString* emailBlurb;
/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;
/* Specifies the physical location where the signing takes place. It can have two enumeration values; InPerson and Online. The default value is Online. [optional]
 */
@property(nonatomic) NSString* signingLocation;
/* Contains a URI for an endpoint that you can use to retrieve the custom fields. [optional]
 */
@property(nonatomic) NSString* customFieldsUri;
/* When set to **true**, Envelope ID Stamping is enabled. [optional]
 */
@property(nonatomic) NSString* envelopeIdStamping;
/* Specifies the Authoritative copy feature. If set to true the Authoritative copy feature is enabled. [optional]
 */
@property(nonatomic) NSString* authoritativeCopy;

@property(nonatomic) DSESNotification* notification;
/* Contains a URI for an endpoint that you can use to retrieve the notifications. [optional]
 */
@property(nonatomic) NSString* notificationUri;
/* When set to **true**, documents with tabs can only be viewed by signers that have a tab on that document. Recipients that have an administrative role (Agent, Editor, or Intermediaries) or informational role (Certified Deliveries or Carbon Copies) can always see all the documents in an envelope, unless they are specifically excluded using this setting when an envelope is sent. Documents that do not have tabs are always visible to all recipients, unless they are specifically excluded using this setting when an envelope is sent.\n\nYour account must have Document Visibility enabled to use this. [optional]
 */
@property(nonatomic) NSString* enforceSignerVisibility;
/* When set to **true**, the signer is allowed to print the document and sign it on paper. [optional]
 */
@property(nonatomic) NSString* enableWetSign;
/* When set to **true**, Document Markup is enabled for envelope. Account must have Document Markup enabled to use this [optional]
 */
@property(nonatomic) NSString* allowMarkup;
/* When set to **true**, the recipient can redirect an envelope to a more appropriate recipient. [optional]
 */
@property(nonatomic) NSString* allowReassign;
/* Indicates the date and time the item was created. [optional]
 */
@property(nonatomic) NSString* createdDateTime;
/* The date and time the item was last modified. [optional]
 */
@property(nonatomic) NSString* lastModifiedDateTime;
/* Reserved: For DocuSign use only. [optional]
 */
@property(nonatomic) NSString* deliveredDateTime;
/* The date and time the envelope was sent. [optional]
 */
@property(nonatomic) NSString* sentDateTime;
/* Specifies the date and time this item was completed. [optional]
 */
@property(nonatomic) NSString* completedDateTime;
/* The date and time the envelope or template was voided. [optional]
 */
@property(nonatomic) NSString* voidedDateTime;
/* The reason the envelope or template was voided. [optional]
 */
@property(nonatomic) NSString* voidedReason;
/* Specifies the data and time the item was deleted. [optional]
 */
@property(nonatomic) NSString* deletedDateTime;
/* The date and time the recipient declined the document. [optional]
 */
@property(nonatomic) NSString* declinedDateTime;
/* The data and time the status changed. [optional]
 */
@property(nonatomic) NSString* statusChangedDateTime;
/*  [optional]
 */
@property(nonatomic) NSString* documentsCombinedUri;
/* Retrieves a URI for an endpoint that allows you to easily retrieve certificate information. [optional]
 */
@property(nonatomic) NSString* certificateUri;
/* Contains a URI for an endpoint which you can use to retrieve the templates. [optional]
 */
@property(nonatomic) NSString* templatesUri;
/* When set to **true**, prevents senders from changing the contents of `emailBlurb` and `emailSubject` properties for the envelope. \n\nAdditionally, this prevents users from making changes to the contents of `emailBlurb` and `emailSubject` properties when correcting envelopes. \n\nHowever, if the `messageLock` node is set to true**** and the `emailSubject` property is empty, senders and correctors are able to add a subject to the envelope. [optional]
 */
@property(nonatomic) NSString* messageLock;
/* When set to **true**, prevents senders from changing, correcting, or deleting the recipient information for the envelope. [optional]
 */
@property(nonatomic) NSString* recipientsLock;
/* When set to **true**, the disclosure is shown to recipients in accordance with the account’s Electronic Record and Signature Disclosure frequency setting. When set to **false**, the Electronic Record and Signature Disclosure is not shown to any envelope recipients. \n\nIf the `useDisclosure` property is not set, then the account's normal disclosure setting is used and the value of the `useDisclosure` property is not returned in responses when getting envelope information. [optional]
 */
@property(nonatomic) NSString* useDisclosure;

@property(nonatomic) DSESEmailSettings* emailSettings;
/* Initiates a purge request. Valid values are:\n* documents_queued: Places envelope documents in the purge queue.\n* documents_and_metadata_queued: Places envelope documents and metadata in the purge queue. [optional]
 */
@property(nonatomic) NSString* purgeState;

@property(nonatomic) DSESLockInformation* lockInformation;
/* When set to **true**, indicates that this module is enabled on the account. [optional]
 */
@property(nonatomic) NSString* is21CFRPart11;

@property(nonatomic) NSString* password;

@property(nonatomic) NSString* attachmentsUri;

@property(nonatomic) NSString* initialSentDateTime;

@property(nonatomic) NSString* brandLock;
/* When set to **true**, indicates that responsive documents are disabled while creating. [optional]
 */
@property(nonatomic) NSString* disableResponsiveDocument;

@end
