#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSM_AFNetworking.h>
#import <DocuSignSDK/DSM_ISO8601.h>
#import <DocuSignSDK/DSESJSONResponseSerializer.h>
#import <DocuSignSDK/DSESJSONRequestSerializer.h>
#import <DocuSignSDK/DSESQueryParamCollection.h>
#import <DocuSignSDK/DSESConfiguration.h>
#import <DocuSignSDK/DSESResponseDeserializer.h>
#import <DocuSignSDK/DSESSanitizer.h>
#import <DocuSignSDK/DSESLogger.h>

/**
 * DocuSign REST API
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


//#import <DocuSignSDK/DSESAccountAddress.h>
//#import <DocuSignSDK/DSESAccountBillingPlan.h>
//#import <DocuSignSDK/DSESAccountBillingPlanResponse.h>
#import <DocuSignSDK/DSESAccountInformation.h>
//#import <DocuSignSDK/DSESAccountRoleSettings.h>
#import <DocuSignSDK/DSESAccountSettingsInformation.h>
#import <DocuSignSDK/DSESAccountSharedAccess.h>
//#import <DocuSignSDK/DSESAccountSignatureProvider.h>
//#import <DocuSignSDK/DSESAccountSignatureProviderOption.h>
//#import <DocuSignSDK/DSESAccountSignatureProviders.h>
//#import <DocuSignSDK/DSESAddOn.h>
#import <DocuSignSDK/DSESAddressInformation.h>
#import <DocuSignSDK/DSESAddressInformationInput.h>
//#import <DocuSignSDK/DSESAddressInformationV2.h>
#import <DocuSignSDK/DSESAgent.h>
#import <DocuSignSDK/DSESApiRequestLog.h>
#import <DocuSignSDK/DSESApiRequestLogsResult.h>
//#import <DocuSignSDK/DSESAppStoreProduct.h>
//#import <DocuSignSDK/DSESAppStoreReceipt.h>
#import <DocuSignSDK/DSESApprove.h>
#import <DocuSignSDK/DSESAttachment.h>
//#import <DocuSignSDK/DSESAuthenticationMethod.h>
#import <DocuSignSDK/DSESAuthenticationStatus.h>
#import <DocuSignSDK/DSESBccEmailAddress.h>
//#import <DocuSignSDK/DSESBillingCharge.h>
//#import <DocuSignSDK/DSESBillingChargeResponse.h>
//#import <DocuSignSDK/DSESBillingDiscount.h>
//#import <DocuSignSDK/DSESBillingInvoice.h>
//#import <DocuSignSDK/DSESBillingInvoiceItem.h>
//#import <DocuSignSDK/DSESBillingInvoicesResponse.h>
//#import <DocuSignSDK/DSESBillingInvoicesSummary.h>
//#import <DocuSignSDK/DSESBillingPayment.h>
//#import <DocuSignSDK/DSESBillingPaymentItem.h>
//#import <DocuSignSDK/DSESBillingPaymentRequest.h>
//#import <DocuSignSDK/DSESBillingPaymentResponse.h>
//#import <DocuSignSDK/DSESBillingPaymentsResponse.h>
//#import <DocuSignSDK/DSESBillingPlan.h>
//#import <DocuSignSDK/DSESBillingPlanInformation.h>
//#import <DocuSignSDK/DSESBillingPlanPreview.h>
//#import <DocuSignSDK/DSESBillingPlanResponse.h>
//#import <DocuSignSDK/DSESBillingPlanUpdateResponse.h>
//#import <DocuSignSDK/DSESBillingPlansResponse.h>
//#import <DocuSignSDK/DSESBillingPrice.h>
//#import <DocuSignSDK/DSESBrand.h>
//#import <DocuSignSDK/DSESBrandEmailContent.h>
//#import <DocuSignSDK/DSESBrandLink.h>
//#import <DocuSignSDK/DSESBrandLogos.h>
//#import <DocuSignSDK/DSESBrandRequest.h>
//#import <DocuSignSDK/DSESBrandResourceUrls.h>
//#import <DocuSignSDK/DSESBrandResources.h>
//#import <DocuSignSDK/DSESBrandResourcesList.h>
//#import <DocuSignSDK/DSESBrandsRequest.h>
//#import <DocuSignSDK/DSESBrandsResponse.h>
#import <DocuSignSDK/DSESBulkEnvelope.h>
#import <DocuSignSDK/DSESBulkEnvelopeStatus.h>
//#import <DocuSignSDK/DSESBulkEnvelopesResponse.h>
//#import <DocuSignSDK/DSESBulkRecipient.h>
//#import <DocuSignSDK/DSESBulkRecipientSignatureProvider.h>
//#import <DocuSignSDK/DSESBulkRecipientTabLabel.h>
//#import <DocuSignSDK/DSESBulkRecipientsRequest.h>
//#import <DocuSignSDK/DSESBulkRecipientsResponse.h>
//#import <DocuSignSDK/DSESBulkRecipientsSummaryResponse.h>
//#import <DocuSignSDK/DSESBulkRecipientsUpdateResponse.h>
//#import <DocuSignSDK/DSESCaptiveRecipient.h>
//#import <DocuSignSDK/DSESCaptiveRecipientInformation.h>
#import <DocuSignSDK/DSESCarbonCopy.h>
#import <DocuSignSDK/DSESCertifiedDelivery.h>
#import <DocuSignSDK/DSESCheckbox.h>
//#import <DocuSignSDK/DSESChunkedUploadPart.h>
//#import <DocuSignSDK/DSESChunkedUploadRequest.h>
//#import <DocuSignSDK/DSESChunkedUploadResponse.h>
//#import <DocuSignSDK/DSESCloudStorageProvider.h>
//#import <DocuSignSDK/DSESCloudStorageProviders.h>
#import <DocuSignSDK/DSESCompany.h>
#import <DocuSignSDK/DSESCompositeTemplate.h>
//#import <DocuSignSDK/DSESConnectConfigResults.h>
//#import <DocuSignSDK/DSESConnectCustomConfiguration.h>
//#import <DocuSignSDK/DSESConnectDebugLog.h>
//#import <DocuSignSDK/DSESConnectFailureFilter.h>
//#import <DocuSignSDK/DSESConnectFailureResult.h>
//#import <DocuSignSDK/DSESConnectFailureResults.h>
//#import <DocuSignSDK/DSESConnectLog.h>
//#import <DocuSignSDK/DSESConnectLogs.h>
#import <DocuSignSDK/DSESConsoleViewRequest.h>
#import <DocuSignSDK/DSESConsumerDisclosure.h>
//#import <DocuSignSDK/DSESContact.h>
//#import <DocuSignSDK/DSESContactGetResponse.h>
//#import <DocuSignSDK/DSESContactModRequest.h>
//#import <DocuSignSDK/DSESContactUpdateResponse.h>
#import <DocuSignSDK/DSESCorrectViewRequest.h>
//#import <DocuSignSDK/DSESCountry.h>
//#import <DocuSignSDK/DSESCreditCardInformation.h>
//#import <DocuSignSDK/DSESCreditCardTypes.h>
//#import <DocuSignSDK/DSESCurrencyFeatureSetPrice.h>
//#import <DocuSignSDK/DSESCurrencyPlanPrice.h>
#import <DocuSignSDK/DSESCustomFieldV2.h>
#import <DocuSignSDK/DSESCustomFields.h>
#import <DocuSignSDK/DSESCustomFieldsEnvelope.h>
//#import <DocuSignSDK/DSESCustomSettingsInformation.h>
#import <DocuSignSDK/DSESDateSigned.h>
#import <DocuSignSDK/DSESDecline.h>
#import <DocuSignSDK/DSESDiagnosticsSettingsInformation.h>
#import <DocuSignSDK/DSESDobInformationInput.h>
#import <DocuSignSDK/DSESDocument.h>
#import <DocuSignSDK/DSESDocumentFieldsInformation.h>
#import <DocuSignSDK/DSESDocumentTemplate.h>
#import <DocuSignSDK/DSESDocumentTemplateList.h>
//#import <DocuSignSDK/DSESDocumentVisibility.h>
//#import <DocuSignSDK/DSESDocumentVisibilityList.h>
//#import <DocuSignSDK/DSESENoteConfiguration.h>
#import <DocuSignSDK/DSESEditor.h>
#import <DocuSignSDK/DSESEmail.h>
#import <DocuSignSDK/DSESEmailAddress.h>
#import <DocuSignSDK/DSESEmailSettings.h>
#import <DocuSignSDK/DSESEnvelope.h>
//#import <DocuSignSDK/DSESEnvelopeAttachment.h>
//#import <DocuSignSDK/DSESEnvelopeAttachmentsRequest.h>
//#import <DocuSignSDK/DSESEnvelopeAttachmentsResult.h>
#import <DocuSignSDK/DSESEnvelopeAuditEvent.h>
#import <DocuSignSDK/DSESEnvelopeAuditEventResponse.h>
#import <DocuSignSDK/DSESEnvelopeDefinition.h>
#import <DocuSignSDK/DSESEnvelopeDocument.h>
#import <DocuSignSDK/DSESEnvelopeDocumentsResult.h>
#import <DocuSignSDK/DSESEnvelopeEvent.h>
//#import <DocuSignSDK/DSESEnvelopeFormData.h>
#import <DocuSignSDK/DSESEnvelopeId.h>
#import <DocuSignSDK/DSESEnvelopeIdsRequest.h>
//#import <DocuSignSDK/DSESEnvelopeNotificationRequest.h>
#import <DocuSignSDK/DSESEnvelopeSummary.h>
#import <DocuSignSDK/DSESEnvelopeTemplate.h>
#import <DocuSignSDK/DSESEnvelopeTemplateDefinition.h>
#import <DocuSignSDK/DSESEnvelopeTemplateResult.h>
#import <DocuSignSDK/DSESEnvelopeTemplateResults.h>
#import <DocuSignSDK/DSESEnvelopeTransactionStatus.h>
#import <DocuSignSDK/DSESEnvelopeUpdateSummary.h>
#import <DocuSignSDK/DSESEnvelopesInformation.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESEventNotification.h>
#import <DocuSignSDK/DSESEventResult.h>
#import <DocuSignSDK/DSESExpirations.h>
//#import <DocuSignSDK/DSESExternalDocServiceErrorDetails.h>
//#import <DocuSignSDK/DSESExternalFile.h>
//#import <DocuSignSDK/DSESExternalFolder.h>
//#import <DocuSignSDK/DSESFeatureSet.h>
#import <DocuSignSDK/DSESFileType.h>
#import <DocuSignSDK/DSESFileTypeList.h>
#import <DocuSignSDK/DSESFilter.h>
#import <DocuSignSDK/DSESFirstName.h>
#import <DocuSignSDK/DSESFolder.h>
#import <DocuSignSDK/DSESFolderItem.h>
#import <DocuSignSDK/DSESFolderItemResponse.h>
#import <DocuSignSDK/DSESFolderItemV2.h>
#import <DocuSignSDK/DSESFolderItemsResponse.h>
#import <DocuSignSDK/DSESFoldersRequest.h>
#import <DocuSignSDK/DSESFoldersResponse.h>
//#import <DocuSignSDK/DSESForgottenPasswordInformation.h>
#import <DocuSignSDK/DSESFormulaTab.h>
#import <DocuSignSDK/DSESFullName.h>
#import <DocuSignSDK/DSESGroup.h>
#import <DocuSignSDK/DSESGroupInformation.h>
#import <DocuSignSDK/DSESIdCheckInformationInput.h>
#import <DocuSignSDK/DSESInPersonSigner.h>
#import <DocuSignSDK/DSESInitialHere.h>
#import <DocuSignSDK/DSESInlineTemplate.h>
//#import <DocuSignSDK/DSESIntegratedUserInfoList.h>
#import <DocuSignSDK/DSESIntermediary.h>
#import <DocuSignSDK/DSESLastName.h>
#import <DocuSignSDK/DSESList.h>
#import <DocuSignSDK/DSESListCustomField.h>
#import <DocuSignSDK/DSESListItem.h>
#import <DocuSignSDK/DSESLockInformation.h>
#import <DocuSignSDK/DSESLockRequest.h>
#import <DocuSignSDK/DSESLoginAccount.h>
#import <DocuSignSDK/DSESLoginInformation.h>
#import <DocuSignSDK/DSESMatchBox.h>
//#import <DocuSignSDK/DSESMemberGroupSharedItem.h>
#import <DocuSignSDK/DSESMemberSharedItems.h>
#import <DocuSignSDK/DSESMergeField.h>
//#import <DocuSignSDK/DSESMobileNotifierConfiguration.h>
//#import <DocuSignSDK/DSESMobileNotifierConfigurationInformation.h>
//#import <DocuSignSDK/DSESMoney.h>
#import <DocuSignSDK/DSESNameValue.h>
//#import <DocuSignSDK/DSESNewAccountDefinition.h>
//#import <DocuSignSDK/DSESNewAccountSummary.h>
//#import <DocuSignSDK/DSESNewUser.h>
//#import <DocuSignSDK/DSESNewUsersDefinition.h>
//#import <DocuSignSDK/DSESNewUsersSummary.h>
//#import <DocuSignSDK/DSESNotaryHost.h>
#import <DocuSignSDK/DSESNote.h>
#import <DocuSignSDK/DSESNotification.h>
//#import <DocuSignSDK/DSESOauthAccess.h>
#import <DocuSignSDK/DSESOfflineAttributes.h>
//#import <DocuSignSDK/DSESPage.h>
//#import <DocuSignSDK/DSESPageImages.h>
#import <DocuSignSDK/DSESPageRequest.h>
//#import <DocuSignSDK/DSESPaymentDetails.h>
//#import <DocuSignSDK/DSESPaymentLineItem.h>
//#import <DocuSignSDK/DSESPermissionProfile.h>
//#import <DocuSignSDK/DSESPermissionProfileInformation.h>
//#import <DocuSignSDK/DSESPlanInformation.h>
//#import <DocuSignSDK/DSESPostTransactionsRequest.h>
//#import <DocuSignSDK/DSESPostTransactionsResponse.h>
//#import <DocuSignSDK/DSESPowerForm.h>
//#import <DocuSignSDK/DSESPowerFormFormDataEnvelope.h>
//#import <DocuSignSDK/DSESPowerFormFormDataRecipient.h>
//#import <DocuSignSDK/DSESPowerFormRecipient.h>
//#import <DocuSignSDK/DSESPowerFormSendersResponse.h>
//#import <DocuSignSDK/DSESPowerFormsFormDataResponse.h>
//#import <DocuSignSDK/DSESPowerFormsRequest.h>
//#import <DocuSignSDK/DSESPowerFormsResponse.h>
//#import <DocuSignSDK/DSESPropertyMetadata.h>
//#import <DocuSignSDK/DSESProvince.h>
//#import <DocuSignSDK/DSESProvisioningInformation.h>
//#import <DocuSignSDK/DSESPurchasedEnvelopesInformation.h>
#import <DocuSignSDK/DSESRadio.h>
#import <DocuSignSDK/DSESRadioGroup.h>
//#import <DocuSignSDK/DSESRecipientAttachment.h>
//#import <DocuSignSDK/DSESRecipientDomain.h>
#import <DocuSignSDK/DSESRecipientEmailNotification.h>
#import <DocuSignSDK/DSESRecipientEvent.h>
//#import <DocuSignSDK/DSESRecipientFormData.h>
//#import <DocuSignSDK/DSESRecipientNamesResponse.h>
#import <DocuSignSDK/DSESRecipientPhoneAuthentication.h>
#import <DocuSignSDK/DSESRecipientSAMLAuthentication.h>
#import <DocuSignSDK/DSESRecipientSMSAuthentication.h>
#import <DocuSignSDK/DSESRecipientSignatureInformation.h>
//#import <DocuSignSDK/DSESRecipientSignatureProvider.h>
//#import <DocuSignSDK/DSESRecipientSignatureProviderOptions.h>
#import <DocuSignSDK/DSESRecipientUpdateResponse.h>
#import <DocuSignSDK/DSESRecipientViewRequest.h>
#import <DocuSignSDK/DSESRecipients.h>
#import <DocuSignSDK/DSESRecipientsUpdateSummary.h>
//#import <DocuSignSDK/DSESReferralInformation.h>
#import <DocuSignSDK/DSESReminders.h>
#import <DocuSignSDK/DSESResourceInformation.h>
#import <DocuSignSDK/DSESReturnUrlRequest.h>
#import <DocuSignSDK/DSESSamlAssertionAttribute.h>
//#import <DocuSignSDK/DSESSeatDiscount.h>
#import <DocuSignSDK/DSESSenderEmailNotifications.h>
#import <DocuSignSDK/DSESServerTemplate.h>
#import <DocuSignSDK/DSESServiceInformation.h>
#import <DocuSignSDK/DSESServiceVersion.h>
//#import <DocuSignSDK/DSESSettingsMetadata.h>
#import <DocuSignSDK/DSESSharedItem.h>
#import <DocuSignSDK/DSESSignHere.h>
//#import <DocuSignSDK/DSESSignatureProviderRequiredOption.h>
//#import <DocuSignSDK/DSESSignatureType.h>
#import <DocuSignSDK/DSESSigner.h>
#import <DocuSignSDK/DSESSignerAttachment.h>
#import <DocuSignSDK/DSESSignerEmailNotifications.h>
//#import <DocuSignSDK/DSESSigningGroup.h>
//#import <DocuSignSDK/DSESSigningGroupInformation.h>
//#import <DocuSignSDK/DSESSigningGroupUser.h>
//#import <DocuSignSDK/DSESSigningGroupUsers.h>
//#import <DocuSignSDK/DSESSocialAccountInformation.h>
#import <DocuSignSDK/DSESSocialAuthentication.h>
#import <DocuSignSDK/DSESSsn.h>
#import <DocuSignSDK/DSESSsn4InformationInput.h>
#import <DocuSignSDK/DSESSsn9InformationInput.h>
//#import <DocuSignSDK/DSESTabAccountSettings.h>
#import <DocuSignSDK/DSESTabMetadata.h>
#import <DocuSignSDK/DSESTabMetadataList.h>
#import <DocuSignSDK/DSESTabs.h>
#import <DocuSignSDK/DSESTemplateCustomFields.h>
//#import <DocuSignSDK/DSESTemplateDocumentVisibilityList.h>
#import <DocuSignSDK/DSESTemplateDocumentsResult.h>
#import <DocuSignSDK/DSESTemplateInformation.h>
#import <DocuSignSDK/DSESTemplateMatch.h>
#import <DocuSignSDK/DSESTemplateNotificationRequest.h>
#import <DocuSignSDK/DSESTemplateRecipients.h>
#import <DocuSignSDK/DSESTemplateRole.h>
//#import <DocuSignSDK/DSESTemplateSharedItem.h>
#import <DocuSignSDK/DSESTemplateSummary.h>
#import <DocuSignSDK/DSESTemplateTabs.h>
#import <DocuSignSDK/DSESTemplateUpdateSummary.h>
#import <DocuSignSDK/DSESText.h>
#import <DocuSignSDK/DSESTextCustomField.h>
#import <DocuSignSDK/DSESTitle.h>
//#import <DocuSignSDK/DSESUsageHistory.h>
//#import <DocuSignSDK/DSESUserAccountManagementGranularInformation.h>
#import <DocuSignSDK/DSESUserInfo.h>
//#import <DocuSignSDK/DSESUserInfoList.h>
//#import <DocuSignSDK/DSESUserInformation.h>
//#import <DocuSignSDK/DSESUserInformationList.h>
//#import <DocuSignSDK/DSESUserPasswordInformation.h>
//#import <DocuSignSDK/DSESUserProfile.h>
#import <DocuSignSDK/DSESUserSettingsInformation.h>
//#import <DocuSignSDK/DSESUserSharedItem.h>
//#import <DocuSignSDK/DSESUserSignature.h>
//#import <DocuSignSDK/DSESUserSignatureDefinition.h>
//#import <DocuSignSDK/DSESUserSignaturesInformation.h>
//#import <DocuSignSDK/DSESUserSocialIdResult.h>
//#import <DocuSignSDK/DSESUsersResponse.h>
//#import <DocuSignSDK/DSESView.h>
#import <DocuSignSDK/DSESViewLinkRequest.h>
#import <DocuSignSDK/DSESViewUrl.h>
//#import <DocuSignSDK/DSESWorkspace.h>
//#import <DocuSignSDK/DSESWorkspaceFolderContents.h>
//#import <DocuSignSDK/DSESWorkspaceItem.h>
//#import <DocuSignSDK/DSESWorkspaceItemList.h>
//#import <DocuSignSDK/DSESWorkspaceList.h>
//#import <DocuSignSDK/DSESWorkspaceUser.h>
//#import <DocuSignSDK/DSESWorkspaceUserAuthorization.h>
#import <DocuSignSDK/DSESZip.h>
#import <DocuSignSDK/Date.h>
#import <DocuSignSDK/Number.h>
#import <DocuSignSDK/DSMAccount.h>

@class DSESConfiguration;

/**
 * A key for `NSError` user info dictionaries.
 *
 * The corresponding value is the parsed response body for an HTTP error.
 */
extern NSString *const DSESResponseObjectErrorKey;

@interface DSESApiClient : DSM_AFHTTPSessionManager

@property(nonatomic, assign) NSURLRequestCachePolicy cachePolicy;
@property(nonatomic, assign) NSTimeInterval timeoutInterval;
@property(nonatomic, readonly) NSOperationQueue* queue;

/// In order to ensure the HTTPResponseHeaders are correct, it is recommended to initialize one DSESApiClient instance per thread.
@property(nonatomic, readonly) NSDictionary* HTTPResponseHeaders;

@property(nonatomic, strong) id<DSESResponseDeserializer> responseDeserializer;

@property(nonatomic, strong) id<DSESSanitizer> sanitizer;
/**
 * Clears Cache
 */
+(void)clearCache;

/**
 * Turns on cache
 *
 * @param enabled If the cached is enable, must be `YES` or `NO`
 */
+(void)setCacheEnabled:(BOOL) enabled;

/**
 * Gets the request queue size
 *
 * @return The size of `queuedRequests` static variable.
 */
+(NSUInteger)requestQueueSize;

/**
 * Sets the client unreachable
 *
 * @param state off line state, must be `YES` or `NO`
 */
+(void) setOfflineState:(BOOL) state;

/**
 * Gets if the client is unreachable
 *
 * @return The client offline state
 */
+(BOOL) getOfflineState;

/**
 * Sets the client reachability, this may be overridden by the reachability manager if reachability changes
 *
 * @param status The client reachability status.
 */
+(void) setReachabilityStatus:(DSM_AFNetworkReachabilityStatus) status;

/**
 * Gets the client reachability
 *
 * @return The client reachability.
 */
+(DSM_AFNetworkReachabilityStatus) getReachabilityStatus;

/**
 * Gets the next request id
 *
 * @return The next executed request id.
 */
+(NSNumber*) nextRequestId;

/**
 * Generates request id and add it to the queue
 *
 * @return The next executed request id.
 */
+(NSNumber*) queueRequest;

/**
 * Removes request id from the queue
 *
 * @param requestId The request which will be removed.
 */
+(void) cancelRequest:(NSNumber*)requestId;

/**
 * Customizes the behavior when the reachability changed
 *
 * @param changeBlock The block will be executed when the reachability changed.
 */
+(void) setReachabilityChangeBlock:(void(^)(int))changeBlock;

/**
 * Sets the api client reachability strategy
 */
- (void)configureCacheReachibility;

/**
 * Sets header for request
 *
 * @param value The header value
 * @param forKey The header key
 */
-(void)setHeaderValue:(NSString*) value
               forKey:(NSString*) forKey;

/**
 * Updates header parameters and query parameters for authentication
 *
 * @param headers The header parameter will be updated, passed by pointer to pointer.
 * @param querys The query parameters will be updated, passed by pointer to pointer.
 * @param authSettings The authentication names NSArray.
 */
- (void) updateHeaderParams:(NSDictionary **)headers
                queryParams:(NSDictionary **)querys
           WithAuthSettings:(NSArray *)authSettings;

/**
 * Performs request
 *
 * @param path Request url.
 * @param method Request method.
 * @param pathParams Request path parameters.
 * @param queryParams Request query parameters.
 * @param body Request body.
 * @param headerParams Request header parameters.
 * @param authSettings Request authentication names.
 * @param requestContentType Request content-type.
 * @param responseContentType Response content-type.
 * @param completionBlock The block will be executed when the request completed.
 *
 * @return The request id.
 */
-(NSNumber*) requestWithPath:(NSString*) path
                      method:(NSString*) method
                  pathParams:(NSDictionary *) pathParams
                 queryParams:(NSDictionary*) queryParams
                  formParams:(NSDictionary *) formParams
                       files:(NSDictionary *) files
                        body:(id) body
                headerParams:(NSDictionary*) headerParams
                authSettings:(NSArray *) authSettings
          requestContentType:(NSString*) requestContentType
         responseContentType:(NSString*) responseContentType
                responseType:(NSString *) responseType
             completionBlock:(void (^)(id, NSError *))completionBlock;

-(NSNumber*)  imageWithCompletionBlock:(NSString*) path
                                method:(NSString*) method
                            pathParams:(NSDictionary *) pathParams
                           queryParams:(NSDictionary*) queryParams
                            formParams:(NSDictionary *) formParams
                          headerParams:(NSDictionary*) headerParams
                          authSettings: (NSArray *) authSettings
                    requestContentType:(NSString*) requestContentType
                             imageData: (NSData*)imageData
                   responseContentType:(NSString*) responseContentType
                          responseType:(NSString *) responseType
                       completionBlock:(void (^)(id, NSError *))completionBlock;

/**
 * Performs envelope creation request with custom file and form params. This allows addition of custom headers for multi-part files request.
 *
 * @param path Request url.
 * @param method Request method.
 * @param pathParams Request path parameters.
 * @param queryParams Request query parameters.
 * @param formParams Request formParams parameters.
 * @param files Request files parameters.
 * @param body Request body.
 * @param headerParams Request header parameters.
 * @param authSettings Request authentication names.
 * @param requestContentType Request content-type.
 * @param responseContentType Response content-type.
 * @param completionBlock The block will be executed when the request completed.
 *
 * @return The request id.
 */
-(NSNumber*)  envelopeCreateWithCompletionBlock:(NSString*) path
                                         method:(NSString*) method
                                     pathParams:(NSDictionary *) pathParams
                                    queryParams:(NSDictionary*) queryParams
                                     formParams:(NSDictionary *) formParams
                                          files:(NSDictionary *) files
                                           body:(id) body
                                   headerParams:(NSDictionary*) headerParams
                                   authSettings: (NSArray *) authSettings
                             requestContentType:(NSString*) requestContentType
                            responseContentType:(NSString*) responseContentType
                                   responseType:(NSString *) responseType
                                completionBlock:(void (^)(id, NSError *))completionBlock;

/**
 * Custom security policy
 *
 * @return AFSecurityPolicy
 */
- (DSM_AFSecurityPolicy *) customSecurityPolicy;

/**
 * DSESConfiguration return sharedConfig
 *
 * @return DSESConfiguration
 */
- (DSESConfiguration*) configuration;


+ (NSDictionary *)setUpAuthHeaders;

+ (NSString *)docusignAuthStringForAccount:(DSMAccount *)account;

+ (NSString *)authorizationStringForAccount:(DSMAccount *)account;

@end
