#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESEnvelope.h>
#import <DocuSignSDK/DSESDocument.h>
#import <DocuSignSDK/DSESCustomFields.h>
#import <DocuSignSDK/DSESRecipients.h>


@protocol DSESInlineTemplate
@end

@interface DSESInlineTemplate : DSESObject

/* Specifies the order in which templates are overlaid. [optional]
 */
@property(nonatomic) NSString* sequence;

@property(nonatomic) DSESEnvelope* envelope;
/* Complex element contains the details on the documents in the envelope. [optional]
 */
@property(nonatomic) NSArray<DSESDocument>* documents;

@property(nonatomic) DSESRecipients* recipients;

@property(nonatomic) DSESCustomFields* customFields;

@end
