#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESOfflineAttributes
@end

@interface DSESOfflineAttributes : DSESObject

/* A string containing information about the type of device used for offline signing. [optional]
 */
@property(nonatomic) NSString* deviceName;
/* A string containing information about the model of the device used for offline signing. [optional]
 */
@property(nonatomic) NSString* deviceModel;
/* A string containing the latitude of the device location at the time of signing. [optional]
 */
@property(nonatomic) NSString* gpsLatitude;
/* A string containing the longitude of the device location at the time of signing. [optional]
 */
@property(nonatomic) NSString* gpsLongitude;
/* A string with GUID of the account. This can be retrieved with the [ML:Get Disclosure] call. [optional]
 */
@property(nonatomic) NSString* accountEsignId;
/*  [optional]
 */
@property(nonatomic) NSString* offlineSigningHash;

@end
