#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESAccountInformation
@end

@interface DSESAccountInformation : DSESObject

/* Identifies the plan that was used create this account. [optional]
 */
@property(nonatomic) NSString* currentPlanId;
/* The name of the Billing Plan. [optional]
 */
@property(nonatomic) NSString* planName;
/* Identifies the type of plan. Examples include Business, Corporate, Enterprise, Free. [optional]
 */
@property(nonatomic) NSString* planClassification;
/* The date that the Account started using the current plan. [optional]
 */
@property(nonatomic) NSString* planStartDate;
/* The date that the current plan will end. [optional]
 */
@property(nonatomic) NSString* planEndDate;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* billingPeriodStartDate;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* billingPeriodEndDate;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* billingPeriodEnvelopesSent;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* billingPeriodEnvelopesAllowed;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* billingPeriodDaysRemaining;
/* When set to **true**, specifies that you can upgrade the account through the API. [optional]
 */
@property(nonatomic) NSString* canUpgrade;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* canCancelRenewal;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeSendingBlocked;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeUnitPrice;
/*  [optional]
 */
@property(nonatomic) NSString* suspensionStatus;
/*  [optional]
 */
@property(nonatomic) NSString* suspensionDate;
/* The name of the current account. [optional]
 */
@property(nonatomic) NSString* accountName;
/*  [optional]
 */
@property(nonatomic) NSString* connectPermission;
/*  [optional]
 */
@property(nonatomic) NSString* docuSignLandingUrl;
/* The code that identifies the billing plan groups and plans for the new account. [optional]
 */
@property(nonatomic) NSString* distributorCode;
/* The GUID associated with the account ID. [optional]
 */
@property(nonatomic) NSString* accountIdGuid;
/* Specifies the ISO currency code for the account. [optional]
 */
@property(nonatomic) NSString* currencyCode;
/* A complex element that contains up to four Question/Answer pairs for forgotten password information for a user. [optional]
 */
@property(nonatomic) NSString* forgottenPasswordQuestionsCount;
/*  [optional]
 */
@property(nonatomic) NSString* paymentMethod;
/*  [optional]
 */
@property(nonatomic) NSString* seatsAllowed;
/*  [optional]
 */
@property(nonatomic) NSString* seatsInUse;
/*  [optional]
 */
@property(nonatomic) NSString* createdDate;
/*  [optional]
 */
@property(nonatomic) NSString* isDowngrade;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* billingProfile;
/*  [optional]
 */
@property(nonatomic) NSString* status21CFRPart11;

@end
