#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESSigner.h>
#import <DocuSignSDK/DSESCertifiedDelivery.h>
#import <DocuSignSDK/DSESAgent.h>
#import <DocuSignSDK/DSESEditor.h>
#import <DocuSignSDK/DSESInPersonSigner.h>
#import <DocuSignSDK/DSESCarbonCopy.h>
#import <DocuSignSDK/DSESErrorDetails.h>
#import <DocuSignSDK/DSESIntermediary.h>
#import <DocuSignSDK/DSESWitness.h>

@protocol DSESRecipients
@end

@interface DSESRecipients : DSESObject

/* A complex type containing information about the Signer recipient. [optional]
 */
@property(nonatomic) NSArray<DSESSigner>* signers;
/* A complex type defining the management and access rights of a recipient assigned assigned as an agent on the document. [optional]
 */
@property(nonatomic) NSArray<DSESAgent>* agents;
/* A complex type defining the management and access rights of a recipient assigned assigned as an editor on the document. [optional]
 */
@property(nonatomic) NSArray<DSESEditor>* editors;
/* Identifies a recipient that can, but is not required to, add name and email information for recipients at the same or subsequent level in the routing order (until subsequent Agents, Editors or Intermediaries recipient types are added). [optional]
 */
@property(nonatomic) NSArray<DSESIntermediary>* intermediaries;
/* A complex type containing information about recipients who should receive a copy of the envelope, but does not need to sign it. [optional]
 */
@property(nonatomic) NSArray<DSESCarbonCopy>* carbonCopies;
/* A complex type containing information on a recipient the must receive the completed documents for the envelope to be completed, but the recipient does not need to sign, initial, date, or add information to any of the documents. [optional]
 */
@property(nonatomic) NSArray<DSESCertifiedDelivery>* certifiedDeliveries;
/* Specifies a signer that is in the same physical location as a DocuSign user who will act as a Signing Host for the transaction. The recipient added is the Signing Host and new separate Signer Name field appears after Sign in person is selected. [optional]
 */
@property(nonatomic) NSArray<DSESInPersonSigner>* inPersonSigners;

/* Reference [witnesses](https://developers.docusign.com/esign-rest-api/reference/Templates/TemplateRecipients/list)
 */
@property(nonatomic) NSArray<DSESWitness>* witnesses;

/*  [optional]
 */
@property(nonatomic) NSString* recipientCount;
/*  [optional]
 */
@property(nonatomic) NSString* currentRoutingOrder;

@property(nonatomic) DSESErrorDetails* errorDetails;

@end
