#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESSocialAuthentication
@end

@interface DSESSocialAuthentication : DSESObject

/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* authentication;

@end
