#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESServiceVersion
@end

@interface DSESServiceVersion : DSESObject

/* The version of the rest API. [optional]
 */
@property(nonatomic) NSString* version;
/*  [optional]
 */
@property(nonatomic) NSString* versionUrl;

@end
