#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSESErrorDetails
@end

@interface DSESErrorDetails : DSESObject

/* An error code associated with the error. [optional]
 */
@property(nonatomic) NSString* errorCode;
/* A short error message. [optional]
 */
@property(nonatomic) NSString* message;

@end
