#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESReminders.h>
#import <DocuSignSDK/DSESExpirations.h>


@protocol DSESTemplateNotificationRequest
@end

@interface DSESTemplateNotificationRequest : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* password;
/* When set to **true**, the account default notification settings are used for the envelope. [optional]
 */
@property(nonatomic) NSString* useAccountDefaults;

@property(nonatomic) DSESReminders* reminders;

@property(nonatomic) DSESExpirations* expirations;

@end
