#import <Foundation/Foundation.h>
#import <DocuSignSDK/DSESObject.h>

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import <DocuSignSDK/DSESSsn9InformationInput.h>
#import <DocuSignSDK/DSESDobInformationInput.h>
#import <DocuSignSDK/DSESAddressInformationInput.h>
#import <DocuSignSDK/DSESSsn4InformationInput.h>


@protocol DSESIdCheckInformationInput
@end

@interface DSESIdCheckInformationInput : DSESObject


@property(nonatomic) DSESAddressInformationInput* addressInformationInput;

@property(nonatomic) DSESDobInformationInput* dobInformationInput;

@property(nonatomic) DSESSsn4InformationInput* ssn4InformationInput;

@property(nonatomic) DSESSsn9InformationInput* ssn9InformationInput;

@end
