{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","text":"DSAPIDateStampProperties"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"externalID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureInitials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiusersignaturedefinition\/init(datestampproperties:disallowuserresizestamp:externalid:imagetype:isdefault:nrdsid:nrdslastname:phoneticname:signaturefont:signatureid:signatureinitials:signaturename:signaturetype:stampformat:stampsizemm:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiusersignaturedefinition\/init(datestampproperties:disallowuserresizestamp:externalid:imagetype:isdefault:nrdsid:nrdslastname:phoneticname:signaturefont:signatureid:signatureinitials:signaturename:signaturetype:stampformat:stampsizemm:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"externalID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureInitials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition(im)initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties":{"role":"symbol","title":"DSAPIDateStampProperties","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"}],"abstract":[{"type":"text","text":"Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.  This property contains the following information about the central rectangle:  - `DateAreaX`: The X axis position of the top-left corner. - `DateAreaY`: The Y axis position of the top-left corner. - `DateAreaWidth`: The width of the rectangle. - `DateAreaHeight`: The height of the rectangle."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDateStampProperties"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)":{"role":"symbol","title":"init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"externalID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureInitials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/init(datestampproperties:disallowuserresizestamp:externalid:imagetype:isdefault:nrdsid:nrdslastname:phoneticname:signaturefont:signatureid:signatureinitials:signaturename:signaturetype:stampformat:stampsizemm:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition":{"role":"symbol","title":"DSAPIUserSignatureDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDateStampProperties:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","text":"DSAPIDateStampProperties"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dateStampProperties"},{"kind":"text","text":" "},{"kind":"identifier","text":"disallowUserResizeStamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"externalID"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageType"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDefault:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"isDefault"},{"kind":"text","text":" "},{"kind":"identifier","text":"nrdsId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nrdsId"},{"kind":"text","text":" "},{"kind":"identifier","text":"nrdsLastName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nrdsLastName"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneticName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"phoneticName"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureFont:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureFont"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureId"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureInitials:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureInitials"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureName"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureType"},{"kind":"text","text":" "},{"kind":"identifier","text":"stampFormat:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"stampFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"stampSizeMM:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"stampSizeMM"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/title","value":"DSAPIDateStampProperties"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/fragments","value":[{"kind":"identifier","text":"DSAPIDateStampProperties"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)\/title","value":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/title","value":"DSAPIUserSignatureDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}