{"sections":[],"abstract":[{"text":"The phonetic spelling of the `signatureName`.","type":"text"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/phoneticName","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiusersignaturedefinition\/phoneticname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiusersignaturedefinition\/phoneticname"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"phoneticName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"phoneticName"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"phoneticName","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition(py)phoneticName"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneticName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/phoneticName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"phoneticName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/phoneticname","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/phoneticName","type":"topic","role":"symbol","title":"phoneticName","navigatorTitle":[{"text":"phoneticName","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The phonetic spelling of the `signatureName`.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition":{"role":"symbol","navigatorTitle":[{"text":"DSAPIUserSignatureDefinition","kind":"identifier"}],"kind":"symbol","title":"DSAPIUserSignatureDefinition","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"phoneticName","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"phoneticName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"phoneticName","kind":"identifier"}]}]}},{"value":"phoneticName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1phoneticName\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1phoneticName\/fragments","value":[{"kind":"identifier","text":"phoneticName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/title","value":"DSAPIUserSignatureDefinition"},{"value":[{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/fragments"}]}]}