{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateTabs\/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"approveTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove","kind":"typeIdentifier","text":"DSAPIApprove","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"checkboxTabs"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox","text":"DSAPICheckbox","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"commentThreadTabs"},{"text":": [","kind":"text"},{"text":"DSAPICommentThread","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommentThread","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionCountyTabs"},{"kind":"text","text":": ["},{"text":"DSAPICommissionCounty","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionExpiration","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionExpiration","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"commissionNumberTabs"},{"text":": [","kind":"text"},{"text":"DSAPICommissionNumber","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"commissionStateTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionState","text":"DSAPICommissionState"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"companyTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany","text":"DSAPICompany","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICurrency","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"kind":"text","text":"]? = nil, "},{"text":"dateSignedTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIDateSigned","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateSigned"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"dateTabs"},{"text":": [","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"declineTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDecline","text":"DSAPIDecline","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"drawTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIDraw","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDraw","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV"},{"text":"]? = nil, ","kind":"text"},{"text":"emailAddressTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailAddress","kind":"typeIdentifier","text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"emailTabs"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail","text":"DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"envelopeIdTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeId","text":"DSAPIEnvelopeId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"kind":"text","text":"]? = nil, "},{"text":"firstNameTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFirstName"},{"text":"]? = nil, ","kind":"text"},{"text":"formulaTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab","kind":"typeIdentifier","text":"DSAPIFormulaTab"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"fullNameTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName","kind":"typeIdentifier","text":"DSAPIFullName"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"initialHereTabs"},{"kind":"text","text":": ["},{"text":"DSAPIInitialHere","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"lastNameTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILastName","text":"DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"kind":"text","text":"]? = nil, "},{"text":"listTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList","text":"DSAPIList"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"notarizeTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarize","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV"},{"kind":"text","text":"]? = nil, "},{"text":"notarySealTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarySeal"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"noteTabs"},{"text":": [","kind":"text"},{"text":"DSAPINote","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINote","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote"},{"text":"]? = nil, ","kind":"text"},{"text":"numberTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]? = nil, "},{"text":"phoneNumberTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIPhoneNumber","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPhoneNumber"},{"text":"]? = nil, ","kind":"text"},{"text":"polyLineOverlayTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPolyLineOverlay","text":"DSAPIPolyLineOverlay","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"prefillTabs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPrefillTabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV"},{"kind":"text","text":"? = nil, "},{"text":"radioGroupTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","kind":"typeIdentifier","text":"DSAPIRadioGroup"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"signerAttachmentTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment","text":"DSAPISignerAttachment","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment"},{"kind":"text","text":"]? = nil, "},{"text":"signHereTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere","text":"DSAPISignHere","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"smartSectionTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISmartSection","kind":"typeIdentifier","text":"DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"ssnTabs"},{"text":": [","kind":"text"},{"text":"DSAPISsn","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"tabGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","text":"DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"textTabs"},{"kind":"text","text":": ["},{"text":"DSAPIText","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText"},{"text":"]? = nil, ","kind":"text"},{"text":"titleTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPITitle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle"},{"text":"]? = nil, ","kind":"text"},{"text":"viewTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIView","text":"DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"zipTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIZip","text":"DSAPIZip","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateTabs"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapitemplatetabs\/init(approvetabs:checkboxtabs:commentthreadtabs:commissioncountytabs:commissionexpirationtabs:commissionnumbertabs:commissionstatetabs:companytabs:currencytabs:datesignedtabs:datetabs:declinetabs:drawtabs:emailaddresstabs:emailtabs:envelope-go8c"]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"approveTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove","text":"DSAPIApprove","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"checkboxTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox","kind":"typeIdentifier","text":"DSAPICheckbox"},{"text":"]?, ","kind":"text"},{"text":"commentThreadTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV","text":"DSAPICommentThread"},{"text":"]?, ","kind":"text"},{"text":"commissionCountyTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPICommissionCounty","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV","kind":"typeIdentifier","text":"DSAPICommissionExpiration"},{"text":"]?, ","kind":"text"},{"text":"commissionNumberTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"commissionStateTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV","text":"DSAPICommissionState"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"companyTabs"},{"kind":"text","text":": ["},{"text":"DSAPICompany","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"text":"]?, ","kind":"text"},{"text":"dateSignedTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned","text":"DSAPIDateSigned","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"dateTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declineTabs"},{"text":": [","kind":"text"},{"text":"DSAPIDecline","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"kind":"text","text":"]?, "},{"text":"drawTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIDraw","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"emailTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIEmail","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"envelopeIdTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIEnvelopeId","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"text":"]?, ","kind":"text"},{"text":"formulaTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"fullNameTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName","text":"DSAPIFullName","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"initialHereTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere","kind":"typeIdentifier","text":"DSAPIInitialHere"},{"kind":"text","text":"]?, "},{"text":"lastNameTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPILastName","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"listTabs"},{"text":": [","kind":"text"},{"text":"DSAPIList","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList"},{"text":"]?, ","kind":"text"},{"text":"notarizeTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"notarySealTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"noteTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote","kind":"typeIdentifier","text":"DSAPINote"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"numberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"phoneNumberTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV","kind":"typeIdentifier","text":"DSAPIPhoneNumber"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"polyLineOverlayTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"prefillTabs"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV","text":"DSAPIPrefillTabs","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"radioGroupTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup","text":"DSAPIRadioGroup","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"signerAttachmentTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPISignerAttachment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment"},{"text":"]?, ","kind":"text"},{"text":"signHereTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISignHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere"},{"kind":"text","text":"]?, "},{"text":"smartSectionTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPISmartSection","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"ssnTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn","text":"DSAPISsn"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"tabGroups"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup","text":"DSAPITabGroup","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"textTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText","text":"DSAPIText","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"titleTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle","kind":"typeIdentifier","text":"DSAPITitle"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"viewTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"zipTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip"},{"text":"]?)","kind":"text"}],"externalID":"s:11DocuSignAPI17DSAPITemplateTabsV07approveE008checkboxE0013commentThreadE0016commissionCountyE00j10ExpirationE00j6NumberE00j5StateE007companyE008currencyE0010dateSignedE00qE007declineE004drawE0012emailAddressE00uE0010envelopeIdE009firstNameE007formulaE004fullzE0011initialHereE004lastzE004listE008notarizeE0010notarySealE004noteE006numberE005phonemE0015polyLineOverlayE007prefillE0010radioGroupE0016signerAttachmentE008signHereE0012smartSectionE003ssnE09tabGroups04textE005titleE004viewE003zipE0ACSayAA12DSAPIApproveCGSg_SayAA13DSAPICheckboxCGSgSayAA012DSAPICommentI0VGSgSayAA015DSAPICommissionK0VGSgSayAA015DSAPICommissionL0VGSgSayAA015DSAPICommissionM0VGSgSayAA015DSAPICommissionN0VGSgSayAA12DSAPICompanyCGSgSayAA13DSAPICurrencyVGSgSayAA09DSAPIDateR0CGSgSay10Foundation4DateVGSgSayAA12DSAPIDeclineCGSgSayAA9DSAPIDrawVGSgSayAA010DSAPIEmailV0CGSgSayAA10DSAPIEmailCGSgSayAA013DSAPIEnvelopeX0CGSgSayAA010DSAPIFirstZ0CGSgSayAA15DSAPIFormulaTabCGSgSayAA09DSAPIFullZ0CGSgSayAA16DSAPIInitialHereCGSgSayAA09DSAPILastZ0CGSgSayAA9DSAPIListCGSgSayAA13DSAPINotarizeVGSgSayAA15DSAPINotarySealVGSgSayAA9DSAPINoteCGSgSaySdGSgSayAA010DSAPIPhoneM0VGSgSayAA20DSAPIPolyLineOverlayVGSgAA012DSAPIPrefillE0VSgSayAA15DSAPIRadioGroupCGSgSayAA21DSAPISignerAttachmentCGSgSayAA13DSAPISignHereCGSgSayAA17DSAPISmartSectionVGSgSayAA8DSAPISsnCGSgSayAA13DSAPITabGroupCGSgSayAA9DSAPITextCGSgSayAA10DSAPITitleCGSgSayAA9DSAPIViewVGSgSayAA8DSAPIZipCGSgtcfc"},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignerAttachment":{"title":"DSAPISignerAttachment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignerAttachment","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignerAttachment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPISignerAttachment"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to attach supporting documents to an envelope."}],"url":"\/documentation\/docusignapi\/dsapisignerattachment"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionExpiration":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionExpiration","url":"\/documentation\/docusignapi\/dsapicommissionexpiration","abstract":[{"type":"text","text":"A Commission Expiration tab displays the expiration date of a notary's commission. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using "},{"type":"reference","isActive":true,"identifier":"\/docs\/notary-api\/"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPICommissionExpiration"}],"title":"DSAPICommissionExpiration","navigatorTitle":[{"text":"DSAPICommissionExpiration","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPrefillTabs":{"kind":"symbol","title":"DSAPIPrefillTabs","abstract":[{"text":"Prefill tabs are tabs that the sender can fill in before the envelope is sent. They are sometimes called sender tags or pre-fill fields.  Only the following tab types can be prefill tabs:  - text - check boxes - radio buttons    [Pre-Fill Your Own Document Fields][app] describes how prefill tabs work in the web application.   [Customize your envelopes with pre-fill fields][catblog] shows how to use prefill tabs in your application using the eSignature SDKs.  [app]:      https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-prefill-fields [catblog]:  https:\/\/www.docusign.com\/blog\/developers\/common-api-tasks-customize-your-envelopes-pre-fill-fields","type":"text"}],"url":"\/documentation\/docusignapi\/dsapiprefilltabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPrefillTabs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIPrefillTabs"}],"navigatorTitle":[{"text":"DSAPIPrefillTabs","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignHere":{"navigatorTitle":[{"text":"DSAPISignHere","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignHere","kind":"identifier"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to sign a document. May be optional."}],"type":"topic","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisignhere","title":"DSAPISignHere"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionCounty":{"abstract":[{"type":"text","text":"A Commission County tab displays the county of a notary's commission. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using "},{"identifier":"\/docs\/notary-api\/","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionCounty","type":"topic","url":"\/documentation\/docusignapi\/dsapicommissioncounty","navigatorTitle":[{"text":"DSAPICommissionCounty","kind":"identifier"}],"title":"DSAPICommissionCounty","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommissionCounty"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICompany":{"type":"topic","abstract":[{"type":"text","text":"A tab that displays the recipient's company name."}],"title":"DSAPICompany","url":"\/documentation\/docusignapi\/dsapicompany","navigatorTitle":[{"kind":"identifier","text":"DSAPICompany"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPICompany","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFirstName":{"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFirstName","url":"\/documentation\/docusignapi\/dsapifirstname","abstract":[{"type":"text","text":"A tab that displays the recipient's first name. This tab takes the recipient's name as entered in the recipient information, splits it into sections based on spaces and uses the first section as the first name."}],"title":"DSAPIFirstName","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIFirstName"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFirstName"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateSigned":{"url":"\/documentation\/docusignapi\/dsapidatesigned","role":"symbol","abstract":[{"text":"A tab that displays the date that the recipient signed the document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIDateSigned"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateSigned","title":"DSAPIDateSigned","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIDateSigned","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICurrency":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICurrency","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPICurrency","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapicurrency","title":"DSAPICurrency","abstract":[],"type":"topic","navigatorTitle":[{"text":"DSAPICurrency","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateTabs/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateTabs\/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"approveTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove","kind":"typeIdentifier","text":"DSAPIApprove"},{"kind":"text","text":"]?, "},{"text":"checkboxTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox","text":"DSAPICheckbox"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"commentThreadTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV","text":"DSAPICommentThread"},{"text":"]?, ","kind":"text"},{"text":"commissionCountyTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"text":": [","kind":"text"},{"text":"DSAPICommissionExpiration","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionNumberTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV","text":"DSAPICommissionNumber","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"commissionStateTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPICommissionState","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"companyTabs"},{"text":": [","kind":"text"},{"text":"DSAPICompany","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany"},{"kind":"text","text":"]?, "},{"text":"currencyTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPICurrency","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"kind":"text","text":"]?, "},{"text":"dateSignedTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned","text":"DSAPIDateSigned"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"declineTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline","text":"DSAPIDecline","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"drawTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV","text":"DSAPIDraw"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress"},{"kind":"text","text":"]?, "},{"text":"emailTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIEmail","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"text":"]?, ","kind":"text"},{"text":"envelopeIdTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIEnvelopeId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"text":"]?, ","kind":"text"},{"text":"firstNameTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIFirstName","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"text":"]?, ","kind":"text"},{"text":"formulaTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab","text":"DSAPIFormulaTab","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"fullNameTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName","text":"DSAPIFullName"},{"text":"]?, ","kind":"text"},{"text":"initialHereTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIInitialHere","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"lastNameTabs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"listTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList","kind":"typeIdentifier","text":"DSAPIList"},{"kind":"text","text":"]?, "},{"text":"notarizeTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV","kind":"typeIdentifier","text":"DSAPINotarize"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarySealTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV","kind":"typeIdentifier","text":"DSAPINotarySeal"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"noteTabs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote","kind":"typeIdentifier","text":"DSAPINote"},{"kind":"text","text":"]?, "},{"text":"numberTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":"]?, ","kind":"text"},{"text":"phoneNumberTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV","text":"DSAPIPhoneNumber"},{"text":"]?, ","kind":"text"},{"text":"polyLineOverlayTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV"},{"text":"]?, ","kind":"text"},{"text":"prefillTabs","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV","kind":"typeIdentifier","text":"DSAPIPrefillTabs"},{"kind":"text","text":"?, "},{"text":"radioGroupTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIRadioGroup","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signerAttachmentTabs"},{"text":": [","kind":"text"},{"text":"DSAPISignerAttachment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signHereTabs"},{"kind":"text","text":": ["},{"text":"DSAPISignHere","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"smartSectionTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"kind":"text","text":"]?, "},{"text":"ssnTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn"},{"text":"]?, ","kind":"text"},{"text":"tabGroups","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup","text":"DSAPITabGroup","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"textTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIText","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"text":"]?, ","kind":"text"},{"text":"titleTabs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle","text":"DSAPITitle","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"viewTabs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV","text":"DSAPIView","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"zipTabs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapitemplatetabs\/init(approvetabs:checkboxtabs:commentthreadtabs:commissioncountytabs:commissionexpirationtabs:commissionnumbertabs:commissionstatetabs:companytabs:currencytabs:datesignedtabs:datetabs:declinetabs:drawtabs:emailaddresstabs:emailtabs:envelope-go8c","title":"init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","kind":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadioGroup":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIRadioGroup"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiradiogroup","role":"symbol","abstract":[{"text":"This group tab is used to place radio buttons on a document. The `radios` property contains a list of ","type":"text"},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","isActive":true},{"text":" objects  associated with the group. Only one radio button can be selected in a group.","type":"text"}],"title":"DSAPIRadioGroup","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIRadioGroup","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDecline":{"navigatorTitle":[{"text":"DSAPIDecline","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A tab that allows the recipient the option of declining an envelope. If the recipient clicks the tab during the signing process, the envelope is voided."}],"title":"DSAPIDecline","kind":"symbol","url":"\/documentation\/docusignapi\/dsapidecline","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIDecline","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDecline"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIView":{"url":"\/documentation\/docusignapi\/dsapiview","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIView"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIView"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIView","abstract":[{"text":"This tab is used with the Approve tab to handle supplemental documents.","type":"text"}],"title":"DSAPIView","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateTabs":{"kind":"symbol","title":"DSAPITemplateTabs","abstract":[],"url":"\/documentation\/docusignapi\/dsapitemplatetabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateTabs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITemplateTabs"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateTabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionNumber":{"abstract":[{"type":"text","text":"A Commission Number tab displays a notary's commission number. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPICommissionNumber","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapicommissionnumber","type":"topic","navigatorTitle":[{"text":"DSAPICommissionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionNumber","role":"symbol","title":"DSAPICommissionNumber","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITitle":{"url":"\/documentation\/docusignapi\/dsapititle","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITitle"}],"navigatorTitle":[{"text":"DSAPITitle","kind":"identifier"}],"title":"DSAPITitle","abstract":[{"type":"text","text":"A tab that displays the recipient's title."}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInitialHere":{"navigatorTitle":[{"text":"DSAPIInitialHere","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiinitialhere","role":"symbol","title":"DSAPIInitialHere","abstract":[{"type":"text","text":"A tab that allows the recipient to initial the document. May be optional."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIInitialHere"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIApprove":{"type":"topic","title":"DSAPIApprove","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIApprove","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIApprove","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIApprove"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to approve documents without placing a signature or initials on the document."}],"role":"symbol","kind":"symbol","url":"\/documentation\/docusignapi\/dsapiapprove"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISmartSection":{"url":"\/documentation\/docusignapi\/dsapismartsection","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISmartSection","title":"DSAPISmartSection","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPISmartSection","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPISmartSection","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommentThread":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommentThread","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicommentthread","abstract":[],"title":"DSAPICommentThread","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICommentThread"}],"navigatorTitle":[{"text":"DSAPICommentThread","kind":"identifier"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICommissionState":{"url":"\/documentation\/docusignapi\/dsapicommissionstate","navigatorTitle":[{"kind":"identifier","text":"DSAPICommissionState"}],"abstract":[{"type":"text","text":"A Commission State tab displays the state in which a notary's commission was granted. The tab is populated with the notary's commission information, but the recipient can also edit the value when notarizing. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICommissionState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPICommissionState","kind":"identifier"}],"title":"DSAPICommissionState"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicheckbox","abstract":[{"type":"text","text":"A tab that allows the recipient to select a yes\/no (on\/off) option."}],"title":"DSAPICheckbox","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPICheckbox","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICheckbox"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmail":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEmail"}],"type":"topic","title":"DSAPIEmail","url":"\/documentation\/docusignapi\/dsapiemail","abstract":[{"type":"text","text":"A tab that allows the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIEmail"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINote":{"navigatorTitle":[{"kind":"identifier","text":"DSAPINote"}],"kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapinote","title":"DSAPINote","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINote","abstract":[{"text":"A tab that displays additional information, in the form of a note, for the recipient.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPINote","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeId":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeId"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeId","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIEnvelopeId","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopeid","title":"DSAPIEnvelopeId","abstract":[{"type":"text","text":"A tab that displays the envelope ID. Recipients cannot enter or change the information in this tab."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIText":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIText"}],"url":"\/documentation\/docusignapi\/dsapitext","title":"DSAPIText","abstract":[{"text":"A tab that allows the recipient to enter any type of text.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIText"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList":{"title":"DSAPIList","abstract":[{"text":"This tab offers a list of options to choose from. The `listItems` property contains a list of ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","isActive":true,"type":"reference"},{"text":" objects to specify the selectable options.","type":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapilist","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIList"}],"navigatorTitle":[{"text":"DSAPIList","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIZip":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIZip","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIZip"}],"navigatorTitle":[{"text":"DSAPIZip","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapizip","title":"DSAPIZip","kind":"symbol","abstract":[{"text":"A tab that allows the recipient to enter a ZIP code. The ZIP code can be five digits or nine digits in the ZIP+4 format. The zip code can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for ZIP code information.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFullName":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName","title":"DSAPIFullName","url":"\/documentation\/docusignapi\/dsapifullname","abstract":[{"text":"A tab that displays the recipient's full name.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFullName","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFullName"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPhoneNumber":{"abstract":[{"type":"text","text":"A Phone Number tab enables a recipient to enter a phone number.  "},{"inlineContent":[{"text":"Note:","type":"text"}],"type":"strong"},{"type":"text","text":" This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPhoneNumber","kind":"symbol","type":"topic","title":"DSAPIPhoneNumber","url":"\/documentation\/docusignapi\/dsapiphonenumber","navigatorTitle":[{"text":"DSAPIPhoneNumber","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIPhoneNumber","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDraw":{"navigatorTitle":[{"text":"DSAPIDraw","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapidraw","title":"DSAPIDraw","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDraw","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDraw"}],"kind":"symbol","abstract":[{"text":"A tab that allows the recipient to add a free-form drawing to the document.","type":"text"}]},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/":{"titleInlineContent":[{"text":"`listItem`","type":"text"}],"title":"`listItem`","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISsn":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISsn"}],"abstract":[{"type":"text","text":"A one-line field that allows the recipient to enter a Social Security Number. The SSN can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for SSN information."}],"url":"\/documentation\/docusignapi\/dsapissn","navigatorTitle":[{"kind":"identifier","text":"DSAPISsn"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISsn","kind":"symbol","role":"symbol","type":"topic","title":"DSAPISsn"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotarize":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPINotarize"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapinotarize","navigatorTitle":[{"kind":"identifier","text":"DSAPINotarize"}],"title":"DSAPINotarize","role":"symbol","abstract":[{"type":"text","text":"A tab that alerts notary recipients that they must take action on the page. Only one notarize tab can appear on a page."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarize"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabGroup":{"navigatorTitle":[{"kind":"identifier","text":"DSAPITabGroup"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","type":"topic","title":"DSAPITabGroup","url":"\/documentation\/docusignapi\/dsapitabgroup","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabGroup"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmailAddress":{"title":"DSAPIEmailAddress","abstract":[{"text":"A tab that displays the recipient's email as entered in the recipient information.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapiemailaddress","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIEmailAddress"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmailAddress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIEmailAddress","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotarySeal":{"kind":"symbol","title":"DSAPINotarySeal","navigatorTitle":[{"kind":"identifier","text":"DSAPINotarySeal"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotarySeal","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotarySeal"}],"abstract":[{"type":"text","text":"A Notary Seal tab enables the recipient to notarize a document. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"url":"\/documentation\/docusignapi\/dsapinotaryseal"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILastName":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILastName","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPILastName","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapilastname","title":"DSAPILastName","navigatorTitle":[{"text":"DSAPILastName","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A tab that displays the recipient's last name. This tab takes the recipient's name as entered in the recipient information, splits it into sections based on spaces and uses the last section as the last name.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPolyLineOverlay":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPolyLineOverlay","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIPolyLineOverlay","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIPolyLineOverlay"}],"title":"DSAPIPolyLineOverlay","url":"\/documentation\/docusignapi\/dsapipolylineoverlay","abstract":[{"type":"text","text":"This tab enables users to strike through the text of a document. The tab is implemented as a line represented as a pair of x and y coordinates."}]},"/docs/notary-api/":{"identifier":"\/docs\/notary-api\/","titleInlineContent":[{"text":"DocuSign Notary","type":"text"}],"title":"DocuSign Notary","type":"link","url":"\/docs\/notary-api\/"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/":{"titleInlineContent":[{"text":"`radio`","type":"text"}],"title":"`radio`","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFormulaTab":{"kind":"symbol","title":"DSAPIFormulaTab","type":"topic","role":"symbol","abstract":[{"text":"The value of a formula tab is calculated from the values of other number or date tabs in the document. When the recipient completes the underlying fields, the formula tab calculates and displays the result.  The `formula` property of the tab contains the references to the underlying tabs. See [Calculated Fields][calculatedfields] in the DocuSign Support Center to learn more about formulas.  If a formula tab contains a `paymentDetails` property, the tab is considered a payment item. See [Requesting Payments Along with Signatures][paymentguide] in the DocuSign Support Center to learn more about payments.  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields [paymentguide]:     https:\/\/support.docusign.com\/en\/guides\/requesting-payments-along-with-signatures","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab","url":"\/documentation\/docusignapi\/dsapiformulatab","navigatorTitle":[{"kind":"identifier","text":"DSAPIFormulaTab"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFormulaTab","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment\/title","op":"replace","value":"DSAPISignerAttachment"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignerAttachment\/fragments","value":[{"kind":"identifier","text":"DSAPISignerAttachment"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere\/title","op":"replace","value":"DSAPISignHere"},{"value":[{"text":"DSAPISignHere","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany\/title","value":"DSAPICompany","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany\/fragments","value":[{"kind":"identifier","text":"DSAPICompany"}],"op":"replace"},{"value":"DSAPIFirstName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFirstName\/title","op":"replace"},{"op":"replace","value":[{"text":"DSAPIFirstName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFirstName\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateSigned\/title","op":"replace","value":"DSAPIDateSigned"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPIDateSigned"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateSigned\/fragments"},{"value":"DSAPIRadioGroup","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/fragments","value":[{"text":"DSAPIRadioGroup","kind":"identifier"}]},{"op":"replace","value":"DSAPIDecline","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDecline\/title"},{"op":"replace","value":[{"text":"DSAPIDecline","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDecline\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle\/title","value":"DSAPITitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle\/fragments","value":[{"text":"DSAPITitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere\/title","value":"DSAPIInitialHere","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIInitialHere"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove\/title","value":"DSAPIApprove"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIApprove\/fragments","value":[{"text":"DSAPIApprove","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/title","value":"DSAPICheckbox"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPICheckbox"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/title","value":"DSAPIEmail"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/fragments","value":[{"kind":"identifier","text":"DSAPIEmail"}]},{"value":"DSAPINote","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINote\/title"},{"value":[{"kind":"identifier","text":"DSAPINote"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINote\/fragments"},{"value":"DSAPIEnvelopeId","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeId\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeId\/fragments","value":[{"text":"DSAPIEnvelopeId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/title","value":"DSAPIText","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/fragments","value":[{"text":"DSAPIText","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/title","value":"DSAPIList"},{"value":[{"kind":"identifier","text":"DSAPIList"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/fragments"},{"value":"DSAPIZip","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIZip\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIZip\/fragments","value":[{"text":"DSAPIZip","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DSAPIFullName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/fragments","value":[{"text":"DSAPIFullName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn\/title","op":"replace","value":"DSAPISsn"},{"value":[{"kind":"identifier","text":"DSAPISsn"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISsn\/fragments"},{"op":"replace","value":"DSAPITabGroup","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/fragments","value":[{"text":"DSAPITabGroup","kind":"identifier"}]},{"op":"replace","value":"DSAPIEmailAddress","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailAddress\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmailAddress\/fragments","value":[{"text":"DSAPIEmailAddress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILastName\/title","op":"replace","value":"DSAPILastName"},{"value":[{"kind":"identifier","text":"DSAPILastName"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILastName\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/title","value":"DSAPIFormulaTab","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/fragments","value":[{"kind":"identifier","text":"DSAPIFormulaTab"}],"op":"replace"}]}]}