{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"declinedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopetemplate\/declineddatetime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopetemplate\/declineddatetime"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate\/declinedDateTime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The date and time the recipient declined the document. This property is read-only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"declinedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"title":"declinedDateTime","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate(py)declinedDateTime","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"declinedDateTime"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplate":{"role":"symbol","title":"DSAPIEnvelopeTemplate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplate"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplate/declinedDateTime":{"role":"symbol","title":"declinedDateTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"declinedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The date and time the recipient declined the document. This property is read-only."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate\/declinedDateTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"declinedDateTime"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplate\/declineddatetime"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"declinedDateTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"declinedDateTime"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"declinedDateTime"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate\/title","value":"DSAPIEnvelopeTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate~1declinedDateTime\/title","value":"declinedDateTime"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate~1declinedDateTime\/fragments","value":[{"kind":"identifier","text":"declinedDateTime"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}