{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expireAfter"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"expireAfter","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate(py)expireAfter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"expireAfter"}],"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","symbolKind":"property"},"abstract":[{"text":"Not used. Use the ","type":"text"},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","isActive":true},{"type":"text","text":" property in the "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","isActive":true,"type":"reference"},{"text":" object instead.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate\/expireAfter"},"kind":"symbol","variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopetemplate\/expireafter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopetemplate\/expireafter"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expireAfter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplate":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate","kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopetemplate","abstract":[],"title":"DSAPIEnvelopeTemplate","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}],"navigatorTitle":[{"text":"DSAPIEnvelopeTemplate","kind":"identifier"}],"type":"topic"},"/docs/esign-rest-api/reference/envelopes/envelopes/create/#definition__envelopedefinition_notification":{"titleInlineContent":[{"text":"`notification`","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","title":"`notification`","type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplate/expireAfter":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expireAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate\/expireAfter","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopetemplate\/expireafter","role":"symbol","title":"expireAfter","navigatorTitle":[{"kind":"identifier","text":"expireAfter"}],"kind":"symbol","abstract":[{"text":"Not used. Use the ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","type":"reference","isActive":true},{"type":"text","text":" property in the "},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","isActive":true},{"type":"text","text":" object instead."}]},"/docs/esign-rest-api/reference/envelopes/envelopes/create/#definition__envelopedefinition_notification_expirations":{"titleInlineContent":[{"type":"text","text":"`expirations`"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","title":"`expirations`","type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"expireAfter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expireAfter"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"expireAfter","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DSAPIEnvelopeTemplate","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate~1expireAfter\/title","op":"replace","value":"expireAfter"},{"op":"replace","value":[{"text":"expireAfter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate~1expireAfter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}