{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere"]]},"sections":[],"abstract":[{"text":"Reserved for DocuSign.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere\/mergeFieldXml"},"metadata":{"symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere(py)mergeFieldXml","title":"mergeFieldXml","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mergeFieldXml","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"mergeFieldXml"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mergeFieldXml"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/dsapisignhere\/mergefieldxml"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapisignhere\/mergefieldxml"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignHere/mergeFieldXml":{"navigatorTitle":[{"text":"mergeFieldXml","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere\/mergeFieldXml","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mergeFieldXml","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Reserved for DocuSign."}],"type":"topic","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisignhere\/mergefieldxml","title":"mergeFieldXml"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","abstract":[],"title":"DocuSignAPI","kind":"symbol","url":"\/documentation\/docusignapi","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignHere":{"navigatorTitle":[{"text":"DSAPISignHere","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignHere","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignHere","kind":"identifier"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to sign a document. May be optional."}],"type":"topic","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisignhere","title":"DSAPISignHere"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"mergeFieldXml","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mergeFieldXml"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mergeFieldXml"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"mergeFieldXml","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere~1mergeFieldXml\/title"},{"value":[{"text":"mergeFieldXml","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere~1mergeFieldXml\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere\/title","op":"replace","value":"DSAPISignHere"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignHere\/fragments","value":[{"text":"DSAPISignHere","kind":"identifier"}],"op":"replace"}]}]}