{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"accessCodeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"allowSystemOverrideForLockedRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"autoRespondedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"declinedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"declinedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"deliveredDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"deliveryMethodMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"designatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"designatorIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"documentVisibility"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","text":"DSAPIDocumentVisibility"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","text":"DSAPIRecipientEmailNotification"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"excludedDocuments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faxNumberMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"firstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"fullNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckConfigurationNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","text":"DSAPIIdCheckInformationInput"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"identityVerification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","text":"DSAPIRecipientIdentityVerification"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"inheritEmailNotificationConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lastNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"noteMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","text":"DSAPIRecipientPhoneAuthentication"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","text":"DSAPIRecipientPhoneNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientAttachments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","text":"DSAPIRecipientAttachment"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recipientAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV","text":"DSAPIAuthenticationStatus"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientFeatureMetadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","text":"DSAPIFeatureAvailableMetadata"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientTypeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"requireIdLookup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"routingOrderMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"sentDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","text":"DSAPISocialAuthentication"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"suppressEmails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"templateLocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"templateRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"totalTabCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiintermediary\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:allowsystemoverrideforlockedrecipient:autorespondedreason:clientuserid:completedcount:customfields:declineddatetime:declinedreason:delivereddatetime:deliverymet-5pq19"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accessCodeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"allowSystemOverrideForLockedRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoRespondedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declinedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"declinedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveredDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethodMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"designatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"designatorIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"documentVisibility"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"excludedDocuments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faxNumberMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"identityVerification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientIdentityVerification","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inheritEmailNotificationConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lastNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"noteMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientAttachments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIAuthenticationStatus","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientFeatureMetadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFeatureAvailableMetadata","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientTypeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requireIdLookup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrderMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sentDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suppressEmails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateLocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalTabCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI17DSAPIIntermediaryC10accessCode0eF8Metadata09addAccessF7ToEmail23additionalNotifications37allowSystemOverrideForLockedRecipient19autoRespondedReason12clientUserId14completedCount12customFields16declinedDateTime08declinedV017deliveredDateTime14deliveryMethod014deliveryMethodG0010designatorY0010designatorY4Guid18documentVisibility5email05emailG017emailNotification05emailS14PostSigningURL08embeddedS8StartURL12errorDetails17excludedDocuments9faxNumber09faxNumberG09firstName09firstNameG08fullName08fullNameG024idCheckConfigurationName024idCheckConfigurationNameG023idCheckInformationInput20identityVerification07inheritK25NotificationConfiguration8lastName08lastNameG006lockedS17PhoneAuthEditable06lockedS11SmsEditable4name04nameG04note04noteG019phoneAuthentication11phoneNumber20recipientAttachments29recipientAuthenticationStatus016recipientFeatureG009recipientY009recipientY4Guid13recipientType013recipientTypeG007requireY6Lookup07requirey6LookupG08roleName12routingOrder012routingOrderG012sentDateTime14signedDateTime012signingGroupY0012signingGroupyG016signingGroupName17signingGroupUsers17smsAuthentication21socialAuthentications6status06statusF014suppressEmails08templateR016templateRequired13totalTabCount04userY0ACSSSg_AA013DSAPIPropertyG0CSgA48_SayAA36DSAPIRecipientAdditionalNotificationCGSgSbA48_A48_A48_SaySSGSg10Foundation4DateVSgA48_A61_A48_A51_A48_A48_SayAA23DSAPIDocumentVisibilityCGSgA48_A51_AA014DSAPIRecipientK12NotificationCSgA48_A48_AA17DSAPIErrorDetailsCSgA57_A48_A51_A48_A51_A48_A51_A48_A51_AA28DSAPIIdCheckInformationInputVSgAA34DSAPIRecipientIdentityVerificationVSgSbA48_A51_A48_A48_A48_A51_A48_A51_AA33DSAPIRecipientPhoneAuthenticationVSgAA25DSAPIRecipientPhoneNumberVSgSayAA24DSAPIRecipientAttachmentCGSgAA25DSAPIAuthenticationStatusVSgSayAA021DSAPIFeatureAvailableG0VGSgA48_A48_A48_A51_SbA51_A48_A48_A51_A61_A61_A48_A51_A48_SayAA13DSAPIUserInfoCGSgAA31DSAPIRecipientSMSAuthenticationCSgSayAA25DSAPISocialAuthenticationCGSgA48_A48_S3bA48_A48_tcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"role":"symbol","title":"DSAPIErrorDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIErrorDetails"}],"abstract":[{"type":"text","text":"This object describes errors that occur. It is only valid for responses and ignored in requests."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"url":"\/documentation\/docusignapi\/dsapierrordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocumentVisibility":{"role":"symbol","title":"DSAPIDocumentVisibility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDocumentVisibility"}],"abstract":[{"type":"text","text":"This object configures a recipient's read\/write access to a document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocumentVisibility"}],"url":"\/documentation\/docusignapi\/dsapidocumentvisibility"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneAuthentication":{"role":"symbol","title":"DSAPIRecipientPhoneAuthentication","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"abstract":[{"type":"text","text":"A complex type that contains the elements:  * `recipMayProvideNumber`: A Boolean value that specifies whether the recipient can use the phone number of their choice. * `senderProvidedNumbers`: A list of phone numbers that the recipient can use. * `recordVoicePrint`: Reserved for DocuSign. * `validateRecipProvidedNumber`: Reserved for DocuSign."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"url":"\/documentation\/docusignapi\/dsapirecipientphoneauthentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientEmailNotification":{"role":"symbol","title":"DSAPIRecipientEmailNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"url":"\/documentation\/docusignapi\/dsapirecipientemailnotification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment":{"role":"symbol","title":"DSAPIRecipientAttachment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientAttachment"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAttachment"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment"},"/docs/esign-rest-api/reference/accounts/identityverifications/list/":{"title":"list","titleInlineContent":[{"type":"text","text":"list"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"role":"symbol","title":"DSAPISocialAuthentication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientIdentityVerification":{"role":"symbol","title":"DSAPIRecipientIdentityVerification","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientIdentityVerification"}],"abstract":[{"type":"text","text":"Specifies ID Verification applied on an envelope by workflow ID. See the "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/"},{"type":"text","text":" method in the "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/"},{"type":"text","text":" resource for more information on how to retrieve workflow IDs available for an account. This can be used in addition to other "},{"type":"reference","isActive":true,"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication"},{"type":"text","text":" methods."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientIdentityVerification"}],"url":"\/documentation\/docusignapi\/dsapirecipientidentityverification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneNumber":{"role":"symbol","title":"DSAPIRecipientPhoneNumber","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneNumber"}],"abstract":[{"type":"text","text":"Describes the recipient phone number."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientPhoneNumber"}],"url":"\/documentation\/docusignapi\/dsapirecipientphonenumber"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIdCheckInformationInput":{"role":"symbol","title":"DSAPIIdCheckInformationInput","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIIdCheckInformationInput"}],"abstract":[{"type":"text","text":"A complex element that contains input information related to a recipient ID check."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIIdCheckInformationInput"}],"url":"\/documentation\/docusignapi\/dsapiidcheckinformationinput"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAuthenticationStatus":{"role":"symbol","title":"DSAPIAuthenticationStatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAuthenticationStatus"}],"abstract":[{"type":"text","text":"A complex element that contains information about a user's authentication status."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIAuthenticationStatus"}],"url":"\/documentation\/docusignapi\/dsapiauthenticationstatus"},"https://support.docusign.com/en/guides/ndse-user-guide-recipient-authentication":{"title":"recipient authentication","titleInlineContent":[{"type":"text","text":"recipient authentication"}],"type":"link","identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","url":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication"},"/docs/esign-rest-api/reference/accounts/identityverifications/":{"title":"IdentityVerifications","titleInlineContent":[{"type":"text","text":"IdentityVerifications"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary":{"role":"symbol","title":"DSAPIIntermediary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIIntermediary"}],"abstract":[{"type":"text","text":"Contains information about an intermediary recipient. An intermediary is a recipient who can, but is not required to, add name and email information for recipients at the same or subsequent level in the routing order, unless subsequent agents, editors or intermediaries are added."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIIntermediary"}],"url":"\/documentation\/docusignapi\/dsapiintermediary"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"role":"symbol","title":"DSAPIUserInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"url":"\/documentation\/docusignapi\/dsapiuserinfo"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAdditionalNotification":{"role":"symbol","title":"DSAPIRecipientAdditionalNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"abstract":[{"type":"text","text":"Describes an additional notification method."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"url":"\/documentation\/docusignapi\/dsapirecipientadditionalnotification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"role":"symbol","title":"DSAPIPropertyMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"abstract":[{"type":"text","text":"Metadata about a property."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"url":"\/documentation\/docusignapi\/dsapipropertymetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)":{"role":"symbol","title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accessCodeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"allowSystemOverrideForLockedRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoRespondedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declinedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"declinedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveredDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethodMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"designatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"designatorIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"documentVisibility"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"excludedDocuments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faxNumberMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"identityVerification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientIdentityVerification","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inheritEmailNotificationConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lastNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"noteMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientAttachments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIAuthenticationStatus","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientFeatureMetadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFeatureAvailableMetadata","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientTypeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requireIdLookup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrderMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sentDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suppressEmails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateLocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalTabCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiintermediary\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:allowsystemoverrideforlockedrecipient:autorespondedreason:clientuserid:completedcount:customfields:declineddatetime:declinedreason:delivereddatetime:deliverymet-5pq19"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFeatureAvailableMetadata":{"role":"symbol","title":"DSAPIFeatureAvailableMetadata","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFeatureAvailableMetadata"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFeatureAvailableMetadata"}],"url":"\/documentation\/docusignapi\/dsapifeatureavailablemetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSMSAuthentication":{"role":"symbol","title":"DSAPIRecipientSMSAuthentication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"abstract":[{"type":"text","text":"Contains the element senderProvidedNumbers which is an Array  of phone numbers the recipient can use for SMS text authentication."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"url":"\/documentation\/docusignapi\/dsapirecipientsmsauthentication"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/title","value":"DSAPIDocumentVisibility"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/fragments","value":[{"kind":"identifier","text":"DSAPIDocumentVisibility"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/title","value":"DSAPIRecipientEmailNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/title","value":"DSAPIRecipientAttachment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientAttachment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title","value":"DSAPISocialAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments","value":[{"kind":"identifier","text":"DSAPISocialAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/title","value":"DSAPIIntermediary"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/fragments","value":[{"kind":"identifier","text":"DSAPIIntermediary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title","value":"DSAPIUserInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","value":[{"kind":"identifier","text":"DSAPIUserInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/title","value":"DSAPIRecipientAdditionalNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","value":"DSAPIPropertyMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/title","value":"DSAPIRecipientSMSAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}