{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary(py)lockedRecipientPhoneAuthEditable","title":"lockedRecipientPhoneAuthEditable","role":"symbol","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lockedRecipientPhoneAuthEditable","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"lockedRecipientPhoneAuthEditable"}]},"abstract":[{"type":"text","text":"Reserved for DocuSign."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockedRecipientPhoneAuthEditable"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary\/lockedRecipientPhoneAuthEditable","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiintermediary\/lockedrecipientphoneautheditable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiintermediary\/lockedrecipientphoneautheditable"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary":{"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary","url":"\/documentation\/docusignapi\/dsapiintermediary","title":"DSAPIIntermediary","abstract":[{"text":"Contains information about an intermediary recipient. An intermediary is a recipient who can, but is not required to, add name and email information for recipients at the same or subsequent level in the routing order, unless subsequent agents, editors or intermediaries are added.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIIntermediary","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIIntermediary","kind":"identifier"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary/lockedRecipientPhoneAuthEditable":{"navigatorTitle":[{"kind":"identifier","text":"lockedRecipientPhoneAuthEditable"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiintermediary\/lockedrecipientphoneautheditable","role":"symbol","abstract":[{"type":"text","text":"Reserved for DocuSign."}],"title":"lockedRecipientPhoneAuthEditable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary\/lockedRecipientPhoneAuthEditable","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lockedRecipientPhoneAuthEditable"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"lockedRecipientPhoneAuthEditable"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"lockedRecipientPhoneAuthEditable","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DSAPIIntermediary","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/title"},{"value":[{"kind":"identifier","text":"DSAPIIntermediary"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/fragments"},{"value":"lockedRecipientPhoneAuthEditable","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary~1lockedRecipientPhoneAuthEditable\/title","op":"replace"},{"op":"replace","value":[{"text":"lockedRecipientPhoneAuthEditable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary~1lockedRecipientPhoneAuthEditable\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}