{"metadata":{"title":"signingGroupUsers","role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary(py)signingGroupUsers","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signingGroupUsers"},{"text":": [","kind":"text"},{"text":"DSAPIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"text":"]?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"signingGroupUsers"}],"modules":[{"name":"DocuSignAPI"}]},"abstract":[{"type":"text","text":"A complex type that contains information about users in the signing group."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary\/signingGroupUsers","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signingGroupUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiintermediary\/signinggroupusers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiintermediary\/signinggroupusers"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary":{"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary","url":"\/documentation\/docusignapi\/dsapiintermediary","title":"DSAPIIntermediary","abstract":[{"text":"Contains information about an intermediary recipient. An intermediary is a recipient who can, but is not required to, add name and email information for recipients at the same or subsequent level in the routing order, unless subsequent agents, editors or intermediaries are added.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIIntermediary","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIIntermediary","kind":"identifier"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIntermediary/signingGroupUsers":{"title":"signingGroupUsers","url":"\/documentation\/docusignapi\/dsapiintermediary\/signinggroupusers","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIntermediary\/signingGroupUsers","abstract":[{"type":"text","text":"A complex type that contains information about users in the signing group."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signingGroupUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo"},{"kind":"text","text":"]?"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"signingGroupUsers"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"signingGroupUsers","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"signingGroupUsers"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<DSAPIUserInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"signingGroupUsers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DSAPIIntermediary","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/title"},{"value":[{"text":"DSAPIIntermediary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title","value":"DSAPIUserInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIUserInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary~1signingGroupUsers\/title","value":"signingGroupUsers"},{"value":[{"text":"signingGroupUsers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIIntermediary~1signingGroupUsers\/fragments"}]}]}