{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:11DocuSignAPI21DSAPIFolderSharedItemV12errorDetails8folderId4name5owner012parentFolderJ00mN3Uri6shared0P6Groups0P5Users3uri4userAcA010DSAPIErrorH0CSg_SSSgArA13DSAPIUserInfoCSgAR10Foundation3URLVSgARSayAA016DSAPIMemberGroupeF0VGSgSayAA0veF0VGSgAyUtcfc","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"text":"DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"owner","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier","text":"DSAPIUserInfo"},{"text":"?, ","kind":"text"},{"text":"parentFolderId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"parentFolderUri","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"sharedGroups","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI26DSAPIMemberGroupSharedItemV","text":"DSAPIMemberGroupSharedItem","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"sharedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIUserSharedItemV","text":"DSAPIUserSharedItem"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(errorDetails:folderId:name:owner:parentFolderId:parentFolderUri:shared:sharedGroups:sharedUsers:uri:user:)","role":"symbol","modules":[{"name":"DocuSignAPI"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderSharedItem"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderSharedItem\/init(errorDetails:folderId:name:owner:parentFolderId:parentFolderUri:shared:sharedGroups:sharedUsers:uri:user:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","text":"DSAPIErrorDetails","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"folderId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"owner"},{"text":": ","kind":"text"},{"text":"DSAPIUserInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"? = nil, "},{"text":"parentFolderId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"parentFolderUri","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"sharedGroups"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIMemberGroupSharedItem","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIMemberGroupSharedItem","preciseIdentifier":"s:11DocuSignAPI26DSAPIMemberGroupSharedItemV"},{"kind":"text","text":"]? = nil, "},{"text":"sharedUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSharedItem","preciseIdentifier":"s:11DocuSignAPI19DSAPIUserSharedItemV","kind":"typeIdentifier","text":"DSAPIUserSharedItem"},{"text":"]? = nil, ","kind":"text"},{"text":"uri","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapifoldershareditem\/init(errordetails:folderid:name:owner:parentfolderid:parentfolderuri:shared:sharedgroups:sharedusers:uri:user:)"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolderSharedItem":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderSharedItem","type":"topic","url":"\/documentation\/docusignapi\/dsapifoldershareditem","navigatorTitle":[{"kind":"identifier","text":"DSAPIFolderSharedItem"}],"title":"DSAPIFolderSharedItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIFolderSharedItem","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolderSharedItem/init(errorDetails:folderId:name:owner:parentFolderId:parentFolderUri:shared:sharedGroups:sharedUsers:uri:user:)":{"type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","kind":"typeIdentifier","text":"DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"text":"folderId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"owner","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"parentFolderId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parentFolderUri"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"shared"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"sharedGroups"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI26DSAPIMemberGroupSharedItemV","text":"DSAPIMemberGroupSharedItem"},{"text":"]?, ","kind":"text"},{"text":"sharedUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI19DSAPIUserSharedItemV","kind":"typeIdentifier","text":"DSAPIUserSharedItem"},{"text":"]?, ","kind":"text"},{"text":"uri","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapifoldershareditem\/init(errordetails:folderid:name:owner:parentfolderid:parentfolderuri:shared:sharedgroups:sharedusers:uri:user:)","title":"init(errorDetails:folderId:name:owner:parentFolderId:parentFolderUri:shared:sharedGroups:sharedUsers:uri:user:)","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderSharedItem\/init(errorDetails:folderId:name:owner:parentFolderId:parentFolderUri:shared:sharedGroups:sharedUsers:uri:user:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSharedItem":{"abstract":[{"text":"Information about a shared item.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapiusershareditem","role":"symbol","title":"DSAPIUserSharedItem","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserSharedItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSharedItem"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSharedItem","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIMemberGroupSharedItem":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIMemberGroupSharedItem","kind":"identifier"}],"title":"DSAPIMemberGroupSharedItem","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Information about items shared among groups."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIMemberGroupSharedItem","url":"\/documentation\/docusignapi\/dsapimembergroupshareditem","navigatorTitle":[{"text":"DSAPIMemberGroupSharedItem","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DSAPIUserInfo","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","value":[{"kind":"identifier","text":"DSAPIUserInfo"}],"op":"replace"},{"value":"DSAPIErrorDetails","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"op":"replace"}]}]}