{"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/authenticationservice\/oauthlogin(environment:accountid:redirecturl:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/authenticationservice\/oauthlogin(environment:accountid:redirecturl:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"OAuthLogin","kind":"identifier"},{"kind":"text","text":"("},{"text":"environment","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment","text":"ObjcEnviromment"},{"kind":"text","text":", "},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"redirectURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","kind":"typeIdentifier","text":"DSAPIAccountServerUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService\/OAuthLogin(environment:accountId:redirectURL:completion:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService"]]},"kind":"symbol","metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)AuthenticationService(im)OAuthLoginWithEnvironment:accountId:redirectURL:completion:","platforms":[{"name":"iOS","introducedAt":"12.0","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"method","title":"OAuthLogin(environment:accountId:redirectURL:completion:)","modules":[{"name":"DocuSignAPI"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OAuthLoginWithEnvironment:accountId:redirectURL:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"OAuthLogin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"environment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ObjcEnviromment","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment"},{"kind":"text","text":", "},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURL"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","text":"DSAPIAccountServerUserInfo"},{"kind":"text","text":"?, "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObjcEnviromment"}],"abstract":[],"type":"topic","title":"ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","kind":"symbol","url":"\/documentation\/docusignapi\/objcenviromment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcEnviromment"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","abstract":[],"navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"role":"symbol","title":"DSAPIAccountServerUserInfo","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AuthenticationService":{"title":"AuthenticationService","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService","role":"symbol","navigatorTitle":[{"text":"AuthenticationService","kind":"identifier"}],"url":"\/documentation\/docusignapi\/authenticationservice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationService"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AuthenticationService/OAuthLogin(environment:accountId:redirectURL:completion:)":{"navigatorTitle":[{"text":"OAuthLoginWithEnvironment:accountId:redirectURL:completion:","kind":"identifier"}],"url":"\/documentation\/docusignapi\/authenticationservice\/oauthlogin(environment:accountid:redirecturl:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OAuthLogin","kind":"identifier"},{"kind":"text","text":"("},{"text":"environment","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment","text":"ObjcEnviromment"},{"text":", ","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"redirectURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","kind":"typeIdentifier","text":"DSAPIAccountServerUserInfo"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"title":"OAuthLogin(environment:accountId:redirectURL:completion:)","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService\/OAuthLogin(environment:accountId:redirectURL:completion:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"OAuthLoginWithEnvironment:accountId:redirectURL:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"OAuthLoginWithEnvironment:accountId:redirectURL:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"OAuthLoginWithEnvironment:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","preciseIdentifier":"c:@M@DocuSignAPI@E@ObjcEnviromment"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"environment"},{"kind":"text","text":" "},{"text":"accountId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectURL:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"redirectURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo#*$objc(cs)NSError)","text":"void (^)(DSAPIAccountServerUserInfo *, NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/title","value":"ObjcEnviromment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/fragments","value":[{"kind":"identifier","text":"ObjcEnviromment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title","value":"DSAPIAccountServerUserInfo"},{"value":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments","op":"replace"},{"op":"replace","value":"AuthenticationService","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService\/title"},{"value":[{"text":"AuthenticationService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService~1OAuthLogin(environment:accountId:redirectURL:completion:)\/title","value":"OAuthLoginWithEnvironment:accountId:redirectURL:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService~1OAuthLogin(environment:accountId:redirectURL:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"OAuthLoginWithEnvironment:accountId:redirectURL:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}