{"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService\/OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthLogin"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customeAuthURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"redirectURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","text":"DSAPIAccountServerUserInfo","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)AuthenticationService(im)OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:","modules":[{"name":"DocuSignAPI"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"OAuthLogin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customeAuthURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"redirectURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DSAPIAccountServerUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)","roleHeading":"Instance Method","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"12.0"}],"navigatorTitle":[{"kind":"identifier","text":"OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/authenticationservice\/oauthlogin(customeauthurl:accountid:redirecturl:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/authenticationservice\/oauthlogin(customeauthurl:accountid:redirecturl:completion:)"]}],"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AuthenticationService":{"title":"AuthenticationService","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService","role":"symbol","navigatorTitle":[{"text":"AuthenticationService","kind":"identifier"}],"url":"\/documentation\/docusignapi\/authenticationservice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationService"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountServerUserInfo":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountServerUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountserveruserinfo","abstract":[],"navigatorTitle":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"role":"symbol","title":"DSAPIAccountServerUserInfo","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AuthenticationService/OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)":{"navigatorTitle":[{"text":"OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:","kind":"identifier"}],"url":"\/documentation\/docusignapi\/authenticationservice\/oauthlogin(customeauthurl:accountid:redirecturl:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OAuthLogin"},{"text":"(","kind":"text"},{"text":"customeAuthURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"redirectURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo","kind":"typeIdentifier","text":"DSAPIAccountServerUserInfo"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"title":"OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService\/OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"OAuthLoginWithCustomeAuthURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"customeAuthURL"},{"kind":"text","text":" "},{"text":"accountId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accountId"},{"text":" ","kind":"text"},{"text":"redirectURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"redirectURL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void (^)(DSAPIAccountServerUserInfo *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIAccountServerUserInfo#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService\/title","value":"AuthenticationService"},{"value":[{"kind":"identifier","text":"AuthenticationService"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/title","value":"DSAPIAccountServerUserInfo"},{"op":"replace","value":[{"text":"DSAPIAccountServerUserInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountServerUserInfo\/fragments"},{"value":"OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService~1OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService~1OAuthLogin(customeAuthURL:accountId:redirectURL:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"OAuthLoginWithCustomeAuthURL:accountId:redirectURL:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}