{"abstract":[{"type":"text","text":"Inherited from "},{"code":"ASWebAuthenticationPresentationContextProviding.presentationAnchor(for:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/authenticationservice\/presentationanchor(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/authenticationservice\/presentationanchor(for:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService\/presentationAnchor(for:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ASWebAuthenticationSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASPresentationAnchor","preciseIdentifier":"c:@T@ASPresentationAnchor"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"12.0"}],"navigatorTitle":[{"kind":"identifier","text":"presentationAnchorForWebAuthenticationSession:"}],"title":"presentationAnchor(for:)","modules":[{"name":"DocuSignAPI"}],"externalID":"c:@M@DocuSignAPI@objc(cs)AuthenticationService(im)presentationAnchorForWebAuthenticationSession:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASWebAuthenticationSession","preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession"},{"kind":"text","text":") -> "},{"text":"ASPresentationAnchor","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASPresentationAnchor"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AuthenticationService/presentationAnchor(for:)":{"navigatorTitle":[{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"}],"url":"\/documentation\/docusignapi\/authenticationservice\/presentationanchor(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession","text":"ASWebAuthenticationSession"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@ASPresentationAnchor","text":"ASPresentationAnchor","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"title":"presentationAnchor(for:)","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService\/presentationAnchor(for:)","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AuthenticationService":{"title":"AuthenticationService","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AuthenticationService","role":"symbol","navigatorTitle":[{"text":"AuthenticationService","kind":"identifier"}],"url":"\/documentation\/docusignapi\/authenticationservice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationService"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"presentationAnchorForWebAuthenticationSession:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"presentationAnchorForWebAuthenticationSession:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession","kind":"typeIdentifier","text":"ASWebAuthenticationSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService~1presentationAnchor(for:)\/title","value":"presentationAnchorForWebAuthenticationSession:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService~1presentationAnchor(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"}],"op":"replace"},{"value":"AuthenticationService","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AuthenticationService\/fragments","value":[{"text":"AuthenticationService","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}