{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail\/boldMetadata","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"boldMetadata","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail(py)boldMetadata","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","title":"boldMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"boldMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail"]]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiemail\/boldmetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiemail\/boldmetadata"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boldMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmail":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEmail"}],"type":"topic","title":"DSAPIEmail","url":"\/documentation\/docusignapi\/dsapiemail","abstract":[{"type":"text","text":"A tab that allows the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIEmail"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEmail/boldMetadata":{"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"boldMetadata","kind":"identifier"}],"title":"boldMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEmail\/boldMetadata","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"boldMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiemail\/boldmetadata","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"boldMetadata","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"boldMetadata"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":" * "},{"kind":"identifier","text":"boldMetadata"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","op":"replace","value":"DSAPIPropertyMetadata"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}]},{"value":"DSAPIEmail","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail\/fragments","value":[{"kind":"identifier","text":"DSAPIEmail"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail~1boldMetadata\/title","op":"replace","value":"boldMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEmail~1boldMetadata\/fragments","value":[{"kind":"identifier","text":"boldMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}