{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accountCustomFieldsPostAccountCustomFields","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"DSAPICustomField","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI16DSAPICustomFieldV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomField"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"applyToTemplates"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DSAPICustomFields","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}]},{"name":"body","content":[{"inlineContent":[{"type":"text","text":"(body)  (optional)"}],"type":"paragraph"}]},{"name":"applyToTemplates","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountCustomFieldsPostAccountCustomFields(accountId:body:applyToTemplates:completion:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI"]]},"abstract":[{"type":"text","text":"Creates an account custom field."}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"title":"accountCustomFieldsPostAccountCustomFields(accountId:body:applyToTemplates:completion:)","roleHeading":"Type Method","symbolKind":"method","role":"symbol","externalID":"s:11DocuSignAPI08AccountsC0C030accountCustomFieldsPostAccountfG00E2Id4body16applyToTemplates10completionySS_AA16DSAPICustomFieldVSgSSSgyAA0pG0CSg_s5Error_pSgtctFZ","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accountCustomFieldsPostAccountCustomFields","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"DSAPICustomField","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI16DSAPICustomFieldV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"applyToTemplates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","kind":"typeIdentifier","text":"DSAPICustomFields"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/accountsapi\/accountcustomfieldspostaccountcustomfields(accountid:body:applytotemplates:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomField":{"type":"topic","title":"DSAPICustomField","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomField","role":"symbol","navigatorTitle":[{"text":"DSAPICustomField","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapicustomfield","abstract":[{"type":"text","text":"This object provides details about a custom field."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPICustomField"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI":{"url":"\/documentation\/docusignapi\/accountsapi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountsAPI","kind":"identifier"}],"title":"AccountsAPI","navigatorTitle":[{"kind":"identifier","text":"AccountsAPI"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI/accountCustomFieldsPostAccountCustomFields(accountId:body:applyToTemplates:completion:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountCustomFieldsPostAccountCustomFields(accountId:body:applyToTemplates:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountCustomFieldsPostAccountCustomFields"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPICustomField","preciseIdentifier":"s:11DocuSignAPI16DSAPICustomFieldV"},{"text":"?, ","kind":"text"},{"text":"applyToTemplates","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","text":"DSAPICustomFields"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"abstract":[{"type":"text","text":"Creates an account custom field."}],"title":"accountCustomFieldsPostAccountCustomFields(accountId:body:applyToTemplates:completion:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/accountsapi\/accountcustomfieldspostaccountcustomfields(accountid:body:applytotemplates:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicustomfields","abstract":[{"type":"text","text":"Contains information about custom fields."}],"title":"DSAPICustomFields","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/title","value":"AccountsAPI","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/fragments","op":"replace","value":[{"text":"AccountsAPI","kind":"identifier"}]},{"op":"replace","value":"DSAPICustomFields","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments","value":[{"text":"DSAPICustomFields","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}