{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI"]]},"kind":"symbol","abstract":[{"type":"text","text":"Creates an account custom field."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/accountsapi\/accountcustomfieldspostaccountcustomfieldswithrequestbuilder(accountid:body:applytotemplates:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder(accountId:body:applyToTemplates:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"s:11DocuSignAPI08AccountsC0C030accountCustomFieldsPostAccountfG18WithRequestBuilder0E2Id4body16applyToTemplatesAA0kL0CyAA011DSAPICustomG0CGSS_AA0R5FieldVSgSSSgtFZ","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPICustomField","preciseIdentifier":"s:11DocuSignAPI16DSAPICustomFieldV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"applyToTemplates"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","text":"DSAPICustomFields"},{"kind":"text","text":">"}],"title":"accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder(accountId:body:applyToTemplates:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomField","preciseIdentifier":"s:11DocuSignAPI16DSAPICustomFieldV","kind":"typeIdentifier","text":"DSAPICustomField"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"applyToTemplates"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"kind":"typeIdentifier","text":"RequestBuilder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"kind":"text","text":">"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}],"name":"accountId"},{"name":"body","content":[{"inlineContent":[{"type":"text","text":"(body)  (optional)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(query)  (optional)","type":"text"}]}],"name":"applyToTemplates"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"POST \/v2.1\/accounts\/{accountId}\/custom_fields","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"OAuth:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"type: oauth2"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}]}]}],"type":"unorderedList"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicustomfields","abstract":[{"type":"text","text":"Contains information about custom fields."}],"title":"DSAPICustomFields","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomField":{"type":"topic","title":"DSAPICustomField","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomField","role":"symbol","navigatorTitle":[{"text":"DSAPICustomField","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapicustomfield","abstract":[{"type":"text","text":"This object provides details about a custom field."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPICustomField"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI":{"url":"\/documentation\/docusignapi\/accountsapi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountsAPI","kind":"identifier"}],"title":"AccountsAPI","navigatorTitle":[{"kind":"identifier","text":"AccountsAPI"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI/accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder(accountId:body:applyToTemplates:)":{"role":"symbol","title":"accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder(accountId:body:applyToTemplates:)","type":"topic","abstract":[{"type":"text","text":"Creates an account custom field."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI16DSAPICustomFieldV","text":"DSAPICustomField","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"applyToTemplates","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPICustomFields","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":">","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountCustomFieldsPostAccountCustomFieldsWithRequestBuilder(accountId:body:applyToTemplates:)","url":"\/documentation\/docusignapi\/accountsapi\/accountcustomfieldspostaccountcustomfieldswithrequestbuilder(accountid:body:applytotemplates:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DSAPICustomFields","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title"},{"value":[{"text":"DSAPICustomFields","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/title","value":"AccountsAPI"},{"value":[{"kind":"identifier","text":"AccountsAPI"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}