{"metadata":{"roleHeading":"Type Method","symbolKind":"method","externalID":"s:11DocuSignAPI08AccountsC0C047accountSignatureAdoptionConfigurationGetaccountfG32ConfigurationnWithRequestBuilder0E2IdAA0lM0CyAA014DSAPISignatureG14ConfigurationsCGSS_tFZ","title":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder(accountId:)","modules":[{"name":"DocuSignAPI"}],"role":"symbol","extendedModule":"DocuSignAPI","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","text":"RequestBuilder"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISignatureAdoptionConfigurations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations"},{"text":">","kind":"text"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/accountsapi\/accountsignatureadoptionconfigurationgetaccountsignatureadoptionconfigurationnwithrequestbuilder(accountid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Gets the Account Signatrue Adoption configuration for an account.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","text":"RequestBuilder"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations","text":"DSAPISignatureAdoptionConfigurations","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}],"name":"accountId"}]},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"RequestBuilder","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"GET \/v2.1\/accounts\/{accountId}\/settings\/signature_adoption_configurations"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OAuth:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]}],"type":"unorderedList"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder(accountId:)"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI/accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder(accountId:)":{"kind":"symbol","type":"topic","title":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder(accountId:)","abstract":[{"text":"Gets the Account Signatrue Adoption configuration for an account.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations","text":"DSAPISignatureAdoptionConfigurations"},{"kind":"text","text":">"}],"url":"\/documentation\/docusignapi\/accountsapi\/accountsignatureadoptionconfigurationgetaccountsignatureadoptionconfigurationnwithrequestbuilder(accountid:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationnWithRequestBuilder(accountId:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureAdoptionConfigurations":{"url":"\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignatureAdoptionConfigurations","kind":"identifier"}],"title":"DSAPISignatureAdoptionConfigurations","navigatorTitle":[{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}],"abstract":[{"text":"Contains information about the current envelope purge configuration for an account, which enables account administrators to purge documents from completed and voided envelopes after a set number of days (`retentionDays`).","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations","kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI":{"url":"\/documentation\/docusignapi\/accountsapi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountsAPI","kind":"identifier"}],"title":"AccountsAPI","navigatorTitle":[{"kind":"identifier","text":"AccountsAPI"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DSAPISignatureAdoptionConfigurations","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/fragments","value":[{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/title","value":"AccountsAPI","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/fragments","value":[{"kind":"identifier","text":"AccountsAPI"}],"op":"replace"}]}]}