{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"DSAPISignatureAdoptionConfigurations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}],"name":"completion"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/accountsapi\/accountsignatureadoptionconfigurationgetaccountsignatureadoptionconfiguration(accountid:completion:)"]},{"paths":["\/documentation\/docusignapi\/accountsapi\/accountsignatureadoptionconfigurationgetaccountsignatureadoptionconfiguration(accountid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:"}],"roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations","kind":"typeIdentifier","text":"DSAPISignatureAdoptionConfigurations"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)","externalID":"c:@CM@DocuSignAPI@objc(cs)AccountsAPI(cm)accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:"},"abstract":[{"text":"Gets the Account Signatrue Adoption configuration for an account.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI":{"url":"\/documentation\/docusignapi\/accountsapi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountsAPI","kind":"identifier"}],"title":"AccountsAPI","navigatorTitle":[{"kind":"identifier","text":"AccountsAPI"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI/accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"text":"DSAPISignatureAdoptionConfigurations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"type":"topic","title":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)","abstract":[{"text":"Gets the Account Signatrue Adoption configuration for an account.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:"}],"url":"\/documentation\/docusignapi\/accountsapi\/accountsignatureadoptionconfigurationgetaccountsignatureadoptionconfiguration(accountid:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureAdoptionConfigurations":{"url":"\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignatureAdoptionConfigurations","kind":"identifier"}],"title":"DSAPISignatureAdoptionConfigurations","navigatorTitle":[{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}],"abstract":[{"text":"Contains information about the current envelope purge configuration for an account, which enables account administrators to purge documents from completed and voided envelopes after a set number of days (`retentionDays`).","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accountId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void (^)(DSAPISignatureAdoptionConfigurations *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"AccountsAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/fragments","value":[{"text":"AccountsAPI","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI~1accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)\/title","value":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfigurationWithAccountId:completion:"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI~1accountSignatureAdoptionConfigurationGetaccountSignatureAdoptionConfiguration(accountId:completion:)\/fragments"},{"op":"replace","value":"DSAPISignatureAdoptionConfigurations","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/fragments","value":[{"text":"DSAPISignatureAdoptionConfigurations","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}