{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder(accountId:)","symbolKind":"method","role":"symbol","roleHeading":"Type Method","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":">","kind":"text"}],"externalID":"s:11DocuSignAPI08AccountsC0C029accountCustomFieldsGetAccountfG18WithRequestBuilder0E2IdAA0kL0CyAA011DSAPICustomG0CGSS_tFZ"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},{"text":"<","kind":"text"},{"text":"DSAPICustomFields","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"kind":"text","text":">"}]}],"kind":"declarations"},{"parameters":[{"name":"accountId","content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"GET \/v2.1\/accounts\/{accountId}\/custom_fields","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OAuth:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"type: oauth2","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"sections":[],"abstract":[{"text":"Gets a list of custom fields.","type":"text"}],"variants":[{"paths":["\/documentation\/docusignapi\/accountsapi\/accountcustomfieldsgetaccountcustomfieldswithrequestbuilder(accountid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder(accountId:)"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI":{"url":"\/documentation\/docusignapi\/accountsapi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountsAPI","kind":"identifier"}],"title":"AccountsAPI","navigatorTitle":[{"kind":"identifier","text":"AccountsAPI"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicustomfields","abstract":[{"type":"text","text":"Contains information about custom fields."}],"title":"DSAPICustomFields","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/AccountsAPI/accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder(accountId:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/AccountsAPI\/accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder(accountId:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","text":"DSAPICustomFields"},{"text":">","kind":"text"}],"type":"topic","title":"accountCustomFieldsGetAccountCustomFieldsWithRequestBuilder(accountId:)","abstract":[{"type":"text","text":"Gets a list of custom fields."}],"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/accountsapi\/accountcustomfieldsgetaccountcustomfieldswithrequestbuilder(accountid:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"AccountsAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/title"},{"value":[{"text":"AccountsAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1AccountsAPI\/fragments"},{"op":"replace","value":"DSAPICustomFields","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPICustomFields"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}