{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateCustomFields\/init(listCustomFields:textCustomFields:)"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateCustomFields"]]},"kind":"symbol","metadata":{"title":"init(listCustomFields:textCustomFields:)","externalID":"s:11DocuSignAPI25DSAPITemplateCustomFieldsV04listeF004texteF0ACSayAA09DSAPIListE5FieldCGSg_SayAA09DSAPITexteJ0CGSgtcfc","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listCustomFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField","text":"DSAPIListCustomField","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"textCustomFields","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"text":"]?)","kind":"text"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"listCustomFields","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","text":"DSAPITextCustomField"},{"kind":"text","text":"]? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitemplatecustomfields\/init(listcustomfields:textcustomfields:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","role":"symbol","navigatorTitle":[{"text":"DSAPIListCustomField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIListCustomField","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This object represents a list custom field from which envelope creators and senders can select custom data.","type":"text"}],"title":"DSAPIListCustomField","url":"\/documentation\/docusignapi\/dsapilistcustomfield","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITextCustomField":{"navigatorTitle":[{"text":"DSAPITextCustomField","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapitextcustomfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITextCustomField"}],"role":"symbol","abstract":[{"type":"text","text":"This object represents a free text custom field where envelope creators and senders can enter custom data."}],"title":"DSAPITextCustomField","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateCustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateCustomFields","kind":"symbol","title":"DSAPITemplateCustomFields","abstract":[],"url":"\/documentation\/docusignapi\/dsapitemplatecustomfields","role":"symbol","navigatorTitle":[{"text":"DSAPITemplateCustomFields","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITemplateCustomFields"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateCustomFields/init(listCustomFields:textCustomFields:)":{"type":"topic","role":"symbol","abstract":[],"title":"init(listCustomFields:textCustomFields:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateCustomFields\/init(listCustomFields:textCustomFields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"listCustomFields","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIListCustomField","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"text":"textCustomFields","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/docusignapi\/dsapitemplatecustomfields\/init(listcustomfields:textcustomfields:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DSAPIListCustomField","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/fragments","value":[{"text":"DSAPIListCustomField","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DSAPITextCustomField","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPITextCustomField"}]}]}]}