{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature\/errorDetails","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DSAPIErrorDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"errorDetails"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature(py)errorDetails","title":"errorDetails","modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDetails","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiusersignature\/errordetails"]},{"paths":["\/documentation\/docusignapi\/dsapiusersignature\/errordetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature":{"url":"\/documentation\/docusignapi\/dsapiusersignature","title":"DSAPIUserSignature","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserSignature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignature"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature/errorDetails":{"abstract":[],"navigatorTitle":[{"text":"errorDetails","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"errorDetails","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature\/errorDetails","url":"\/documentation\/docusignapi\/dsapiusersignature\/errordetails","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDetails","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"errorDetails"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"errorDetails"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","kind":"typeIdentifier","text":"DSAPIErrorDetails"},{"text":" * ","kind":"text"},{"text":"errorDetails","kind":"identifier"}]}]}},{"op":"replace","value":"DSAPIErrorDetails","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title"},{"value":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments"},{"op":"replace","value":"DSAPIUserSignature","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/fragments","value":[{"text":"DSAPIUserSignature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature~1errorDetails\/title","op":"replace","value":"errorDetails"},{"value":[{"kind":"identifier","text":"errorDetails"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature~1errorDetails\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}