{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"adoptedDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"createdDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customField"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"dateStampProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","text":"DSAPIDateStampProperties"},{"kind":"text","text":"?, "},{"text":"disallowUserResizeStamp","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"externalID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageBase64"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"imageType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"initials150ImageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"initialsImageUri","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lastModifiedDateTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nrdsLastName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nrdsStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"phoneticName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"signature150ImageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"signatureFont","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signatureId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureImageUri"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"signatureInitials","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"signatureName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"signatureRights","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"stampFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"stampImageUri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?, ","kind":"text"},{"text":"stampSizeMM","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"stampType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"title":"init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature(im)initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:","navigatorTitle":[{"kind":"identifier","text":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","modules":[{"name":"DocuSignAPI"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiusersignature\/init(adopteddatetime:createddatetime:customfield:datestampproperties:disallowuserresizestamp:errordetails:externalid:imagebase64:imagetype:initials150imageid:initialsimageuri:isdefault:lastmodifieddatetime:nrdsid:nrdslastname:nrdsstatus:pho-34t6t"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiusersignature\/init(adopteddatetime:createddatetime:customfield:datestampproperties:disallowuserresizestamp:errordetails:externalid:imagebase64:imagetype:initials150imageid:initialsimageuri:isdefault:lastmodifieddatetime:nrdsid:nrdslastname:nrdsstatus:pho-34t6t"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"adoptedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"createdDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"customField"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","text":"DSAPIDateStampProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"text":"? = nil, ","kind":"text"},{"text":"disallowUserResizeStamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"externalID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"imageBase64","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"imageType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"initials150ImageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"initialsImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"isDefault","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lastModifiedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"nrdsStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"phoneticName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signature150ImageId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"signatureFont","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"signatureId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"signatureImageUri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"? = nil, "},{"text":"signatureInitials","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"signatureName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"signatureRights","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"stampFormat"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"stampImageUri","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"text":"stampSizeMM","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"stampType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties":{"url":"\/documentation\/docusignapi\/dsapidatestampproperties","title":"DSAPIDateStampProperties","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIDateStampProperties"}],"abstract":[{"type":"text","text":"Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.  This property contains the following information about the central rectangle:  - `DateAreaX`: The X axis position of the top-left corner. - `DateAreaY`: The Y axis position of the top-left corner. - `DateAreaWidth`: The width of the rectangle. - `DateAreaHeight`: The height of the rectangle."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)":{"type":"topic","title":"init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adoptedDateTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"text":"createdDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customField"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"dateStampProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIDateStampProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"kind":"text","text":"?, "},{"text":"disallowUserResizeStamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"externalID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"imageBase64","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"imageType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"initials150ImageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"initialsImageUri"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"isDefault","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"lastModifiedDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nrdsId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nrdsStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signature150ImageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureFont"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureImageUri"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"signatureInitials","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signatureName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureRights"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"signatureType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"stampFormat","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"stampImageUri","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"text":"stampSizeMM","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/docusignapi\/dsapiusersignature\/init(adopteddatetime:createddatetime:customfield:datestampproperties:disallowuserresizestamp:errordetails:externalid:imagebase64:imagetype:initials150imageid:initialsimageuri:isdefault:lastmodifieddatetime:nrdsid:nrdslastname:nrdsstatus:pho-34t6t"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature":{"url":"\/documentation\/docusignapi\/dsapiusersignature","title":"DSAPIUserSignature","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserSignature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignature"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAdoptedDateTime:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"adoptedDateTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"createdDateTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createdDateTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"customField:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"customField","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateStampProperties:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","text":"DSAPIDateStampProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"text":" *) ","kind":"text"},{"text":"dateStampProperties","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"disallowUserResizeStamp:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":" "},{"text":"errorDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":" *) ","kind":"text"},{"text":"errorDetails","kind":"internalParam"},{"kind":"text","text":" "},{"text":"externalID:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"externalID","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageBase64:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageBase64"},{"kind":"text","text":" "},{"text":"imageType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"imageType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initials150ImageId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"initials150ImageId"},{"text":" ","kind":"text"},{"text":"initialsImageUri:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"text":"initialsImageUri","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDefault:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"isDefault","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lastModifiedDateTime:"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"text":"lastModifiedDateTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nrdsId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nrdsId"},{"text":" ","kind":"text"},{"text":"nrdsLastName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nrdsLastName"},{"text":" ","kind":"text"},{"text":"nrdsStatus:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"nrdsStatus","kind":"internalParam"},{"kind":"text","text":" "},{"text":"phoneticName:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"phoneticName"},{"kind":"text","text":" "},{"text":"signature150ImageId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"signature150ImageId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureFont:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"signatureFont"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"signatureId"},{"text":" ","kind":"text"},{"text":"signatureImageUri:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"signatureImageUri","kind":"internalParam"},{"kind":"text","text":" "},{"text":"signatureInitials:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"signatureInitials"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signatureName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"signatureName"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signatureRights:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"signatureRights","kind":"internalParam"},{"kind":"text","text":" "},{"text":"signatureType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"signatureType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stampFormat:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"stampFormat"},{"text":" ","kind":"text"},{"text":"stampImageUri:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"stampImageUri"},{"kind":"text","text":" "},{"text":"stampSizeMM:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stampSizeMM","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stampType:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"stampType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/title","value":"DSAPIDateStampProperties","op":"replace"},{"value":[{"text":"DSAPIDateStampProperties","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature~1init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)\/title","op":"replace","value":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature~1init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:stampFormat:stampImageUri:stampSizeMM:stampType:status:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/title","value":"DSAPIUserSignature"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/fragments","value":[{"text":"DSAPIUserSignature","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DSAPIErrorDetails","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title"},{"value":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments"}]}]}