{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"formula","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab\/formula","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab"]]},"abstract":[{"type":"text","text":"Contains the formula for calculating the value of this tab.  Use a tab's `tabLabel`, enclosed in brackets, to refer to it.  For example, you want to present the total cost of two items, tax included.  The cost of each item is stored in number tabs labeled Item1 and Item2. The tax rate is in a number tab labeled TaxRate.  The formula string for this property would be: `([Item1] + [Item2]) * (1 + [TaxRate])`  See [Calculated Fields][calculatedfields] in the DocuSign Support Center to learn more about formulas.  Maximum Length: 2000 characters  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields"}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formula","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","title":"formula","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab(py)formula","roleHeading":"Instance Property","navigatorTitle":[{"text":"formula","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiformulatab\/formula"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiformulatab\/formula"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFormulaTab":{"kind":"symbol","title":"DSAPIFormulaTab","type":"topic","role":"symbol","abstract":[{"text":"The value of a formula tab is calculated from the values of other number or date tabs in the document. When the recipient completes the underlying fields, the formula tab calculates and displays the result.  The `formula` property of the tab contains the references to the underlying tabs. See [Calculated Fields][calculatedfields] in the DocuSign Support Center to learn more about formulas.  If a formula tab contains a `paymentDetails` property, the tab is considered a payment item. See [Requesting Payments Along with Signatures][paymentguide] in the DocuSign Support Center to learn more about payments.  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields [paymentguide]:     https:\/\/support.docusign.com\/en\/guides\/requesting-payments-along-with-signatures","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab","url":"\/documentation\/docusignapi\/dsapiformulatab","navigatorTitle":[{"kind":"identifier","text":"DSAPIFormulaTab"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFormulaTab","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFormulaTab/formula":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiformulatab\/formula","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab\/formula","navigatorTitle":[{"text":"formula","kind":"identifier"}],"abstract":[{"text":"Contains the formula for calculating the value of this tab.  Use a tab's `tabLabel`, enclosed in brackets, to refer to it.  For example, you want to present the total cost of two items, tax included.  The cost of each item is stored in number tabs labeled Item1 and Item2. The tax rate is in a number tab labeled TaxRate.  The formula string for this property would be: `([Item1] + [Item2]) * (1 + [TaxRate])`  See [Calculated Fields][calculatedfields] in the DocuSign Support Center to learn more about formulas.  Maximum Length: 2000 characters  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formula","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"formula","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"formula","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"formula","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"formula"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/title","value":"DSAPIFormulaTab","op":"replace"},{"value":[{"text":"DSAPIFormulaTab","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab~1formula\/title","value":"formula"},{"value":[{"text":"formula","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab~1formula\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}