{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab\/pageNumber"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab"]]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiformulatab\/pagenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiformulatab\/pagenumber"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"pageNumber","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab(py)pageNumber","roleHeading":"Instance Property","modules":[{"name":"DocuSignAPI"}],"title":"pageNumber","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"text":"The page number on which the tab is located. For supplemental documents, this value must be `1`.","type":"text"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFormulaTab/pageNumber":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab\/pageNumber","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiformulatab\/pagenumber","title":"pageNumber","kind":"symbol","abstract":[{"text":"The page number on which the tab is located. For supplemental documents, this value must be `1`.","type":"text"}],"navigatorTitle":[{"text":"pageNumber","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFormulaTab":{"kind":"symbol","title":"DSAPIFormulaTab","type":"topic","role":"symbol","abstract":[{"text":"The value of a formula tab is calculated from the values of other number or date tabs in the document. When the recipient completes the underlying fields, the formula tab calculates and displays the result.  The `formula` property of the tab contains the references to the underlying tabs. See [Calculated Fields][calculatedfields] in the DocuSign Support Center to learn more about formulas.  If a formula tab contains a `paymentDetails` property, the tab is considered a payment item. See [Requesting Payments Along with Signatures][paymentguide] in the DocuSign Support Center to learn more about payments.  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields [paymentguide]:     https:\/\/support.docusign.com\/en\/guides\/requesting-payments-along-with-signatures","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFormulaTab","url":"\/documentation\/docusignapi\/dsapiformulatab","navigatorTitle":[{"kind":"identifier","text":"DSAPIFormulaTab"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFormulaTab","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"pageNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pageNumber"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pageNumber"}],"languages":["occ"]}]},"op":"replace"},{"value":"pageNumber","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab~1pageNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab~1pageNumber\/fragments","value":[{"text":"pageNumber","kind":"identifier"}]},{"value":"DSAPIFormulaTab","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFormulaTab\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIFormulaTab"}]}]}]}