{"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelope\/expireafter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapienvelope\/expireafter"]}],"abstract":[{"type":"text","text":"Not used. Use the "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","isActive":true,"type":"reference"},{"type":"text","text":" property in the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification"},{"text":" object instead.","type":"text"}],"sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"expireAfter"}],"title":"expireAfter","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"expireAfter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope(py)expireAfter","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"expireAfter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope\/expireAfter"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope"]]},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope":{"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelope","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIEnvelope","kind":"identifier"}],"abstract":[],"title":"DSAPIEnvelope","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelope"}],"type":"topic"},"/docs/esign-rest-api/reference/envelopes/envelopes/create/#definition__envelopedefinition_notification_expirations":{"titleInlineContent":[{"text":"`expirations`","type":"text"}],"title":"`expirations`","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","type":"link"},"/docs/esign-rest-api/reference/envelopes/envelopes/create/#definition__envelopedefinition_notification":{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","type":"link","titleInlineContent":[{"text":"`notification`","type":"text"}],"title":"`notification`","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope/expireAfter":{"type":"topic","role":"symbol","abstract":[{"text":"Not used. Use the ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","isActive":true,"type":"reference"},{"text":" property in the ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","isActive":true,"type":"reference"},{"text":" object instead.","type":"text"}],"navigatorTitle":[{"text":"expireAfter","kind":"identifier"}],"title":"expireAfter","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope\/expireAfter","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expireAfter","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapienvelope\/expireafter","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"expireAfter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expireAfter"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"expireAfter","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DSAPIEnvelope","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelope"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope~1expireAfter\/title","op":"replace","value":"expireAfter"},{"value":[{"kind":"identifier","text":"expireAfter"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope~1expireAfter\/fragments"}]}]}