{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapienvelope\/lastmodifieddatetime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapienvelope\/lastmodifieddatetime"]}],"abstract":[{"type":"text","text":"The date and time that the item was last modified."}],"sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"lastModifiedDateTime"}],"title":"lastModifiedDateTime","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastModifiedDateTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope(py)lastModifiedDateTime","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lastModifiedDateTime"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope\/lastModifiedDateTime"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope"]]},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope":{"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelope","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIEnvelope","kind":"identifier"}],"abstract":[],"title":"DSAPIEnvelope","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelope"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope/lastModifiedDateTime":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The date and time that the item was last modified."}],"navigatorTitle":[{"kind":"identifier","text":"lastModifiedDateTime"}],"title":"lastModifiedDateTime","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope\/lastModifiedDateTime","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lastModifiedDateTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapienvelope\/lastmodifieddatetime","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"lastModifiedDateTime","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"lastModifiedDateTime"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"text":" * ","kind":"text"},{"text":"lastModifiedDateTime","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/title","value":"DSAPIEnvelope"},{"value":[{"text":"DSAPIEnvelope","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope~1lastModifiedDateTime\/title","value":"lastModifiedDateTime","op":"replace"},{"value":[{"text":"lastModifiedDateTime","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope~1lastModifiedDateTime\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}