{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapicheckbox\/anchorxoffset"]},{"paths":["\/documentation\/docusignapi\/dsapicheckbox\/anchorxoffset"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"anchorXOffset","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox\/anchorXOffset"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Specifies the X axis location of the tab in `anchorUnits` relative to the `anchorString`.","type":"text"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"text":"anchorXOffset","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox(py)anchorXOffset","title":"anchorXOffset","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorXOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicheckbox","abstract":[{"type":"text","text":"A tab that allows the recipient to select a yes\/no (on\/off) option."}],"title":"DSAPICheckbox","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPICheckbox","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICheckbox"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox/anchorXOffset":{"url":"\/documentation\/docusignapi\/dsapicheckbox\/anchorxoffset","kind":"symbol","type":"topic","navigatorTitle":[{"text":"anchorXOffset","kind":"identifier"}],"abstract":[{"text":"Specifies the X axis location of the tab in `anchorUnits` relative to the `anchorString`.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorXOffset"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox\/anchorXOffset","title":"anchorXOffset"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"anchorXOffset","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"anchorXOffset"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"anchorXOffset","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/title","op":"replace","value":"DSAPICheckbox"},{"value":[{"text":"DSAPICheckbox","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox~1anchorXOffset\/title","value":"anchorXOffset"},{"op":"replace","value":[{"text":"anchorXOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox~1anchorXOffset\/fragments"}]}]}