{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapicheckbox\/required"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapicheckbox\/required"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox\/required","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This property does not apply to `checkbox` tabs.  To require users to check at least one, or at most some number of checkboxes, associate the checkbox tabs with a [`tabGroup`][tabGroup]. Then set the following `tabGroup` properties:  - [`maximumAllowed`][maximumAllowed] - [`minimumRequired`][minimumRequired] - [`groupRule`][groupRule] specifies how the other two properties are interpreted.  You can find an example at [Stack Overflow][so].  [so]:               https:\/\/stackoverflow.com\/questions\/58209376\/checkbox-validation-using-docusign-rest-api\/58210277#58210277 [tabGroup]:         \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups [groupRule]:        \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups_grouprule [maximumAllowed]:   \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups_maximumallowed [minimumRequired]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups_minimumrequired"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"required","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox(py)required","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"required"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox/required":{"role":"symbol","title":"required","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This property does not apply to `checkbox` tabs.  To require users to check at least one, or at most some number of checkboxes, associate the checkbox tabs with a [`tabGroup`][tabGroup]. Then set the following `tabGroup` properties:  - [`maximumAllowed`][maximumAllowed] - [`minimumRequired`][minimumRequired] - [`groupRule`][groupRule] specifies how the other two properties are interpreted.  You can find an example at [Stack Overflow][so].  [so]:               https:\/\/stackoverflow.com\/questions\/58209376\/checkbox-validation-using-docusign-rest-api\/58210277#58210277 [tabGroup]:         \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups [groupRule]:        \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups_grouprule [maximumAllowed]:   \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups_maximumallowed [minimumRequired]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#definition__enveloperecipienttabs_tabgroups_minimumrequired"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox\/required","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"required"}],"url":"\/documentation\/docusignapi\/dsapicheckbox\/required"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICheckbox":{"role":"symbol","title":"DSAPICheckbox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICheckbox"}],"abstract":[{"type":"text","text":"A tab that allows the recipient to select a yes\/no (on\/off) option."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICheckbox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICheckbox"}],"url":"\/documentation\/docusignapi\/dsapicheckbox"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"required"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"required"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox~1required\/title","value":"required"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox~1required\/fragments","value":[{"kind":"identifier","text":"required"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/title","value":"DSAPICheckbox"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICheckbox\/fragments","value":[{"kind":"identifier","text":"DSAPICheckbox"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}