{"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/allowSignDocumentFromHomePage","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowsigndocumentfromhomepage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowsigndocumentfromhomepage"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"allowSignDocumentFromHomePage","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)allowSignDocumentFromHomePage","roleHeading":"Instance Property","title":"allowSignDocumentFromHomePage","modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowSignDocumentFromHomePage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property"},"abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"type":"text","text":"true,"}],"type":"strong"},{"text":" recipients can sign documents from the home page.  ","type":"text"},{"inlineContent":[{"text":"Note:","type":"text"}],"type":"strong"},{"type":"text","text":" Only Admin users can change this setting."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"BoolFromString","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowSignDocumentFromHomePage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/allowSignDocumentFromHomePage":{"type":"topic","role":"symbol","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" recipients can sign documents from the home page.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Only Admin users can change this setting."}],"navigatorTitle":[{"text":"allowSignDocumentFromHomePage","kind":"identifier"}],"title":"allowSignDocumentFromHomePage","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/allowSignDocumentFromHomePage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowSignDocumentFromHomePage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowsigndocumentfromhomepage","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"allowSignDocumentFromHomePage"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"allowSignDocumentFromHomePage","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"allowSignDocumentFromHomePage","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"BoolFromString","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments","value":[{"text":"BoolFromString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","value":"DSAPIAccountSettingsInformation"},{"value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","op":"replace"},{"value":"allowSignDocumentFromHomePage","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1allowSignDocumentFromHomePage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1allowSignDocumentFromHomePage\/fragments","value":[{"text":"allowSignDocumentFromHomePage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}