{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowENoteEOriginalMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"text":"allowENoteEOriginalMetadata","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)allowENoteEOriginalMetadata","title":"allowENoteEOriginalMetadata"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowENoteEOriginalMetadata"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/allowENoteEOriginalMetadata"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowenoteeoriginalmetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowenoteeoriginalmetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/allowENoteEOriginalMetadata":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowenoteeoriginalmetadata","navigatorTitle":[{"text":"allowENoteEOriginalMetadata","kind":"identifier"}],"title":"allowENoteEOriginalMetadata","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/allowENoteEOriginalMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowENoteEOriginalMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowENoteEOriginalMetadata","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowENoteEOriginalMetadata"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"allowENoteEOriginalMetadata","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1allowENoteEOriginalMetadata\/title","value":"allowENoteEOriginalMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1allowENoteEOriginalMetadata\/fragments","value":[{"text":"allowENoteEOriginalMetadata","kind":"identifier"}]},{"value":"DSAPIAccountSettingsInformation","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","op":"replace","value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title","value":"DSAPISettingsMetadata"},{"op":"replace","value":[{"text":"DSAPISettingsMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}