{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/allowAutoTaggingMetadata"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowAutoTaggingMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allowAutoTaggingMetadata"}],"symbolKind":"property","title":"allowAutoTaggingMetadata","modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)allowAutoTaggingMetadata","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowAutoTaggingMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowautotaggingmetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowautotaggingmetadata"]}],"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/allowAutoTaggingMetadata":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/allowAutoTaggingMetadata","role":"symbol","title":"allowAutoTaggingMetadata","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowAutoTaggingMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"allowAutoTaggingMetadata","kind":"identifier"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/allowautotaggingmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"allowAutoTaggingMetadata","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowAutoTaggingMetadata"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":" * ","kind":"text"},{"text":"allowAutoTaggingMetadata","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"allowAutoTaggingMetadata","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1allowAutoTaggingMetadata\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1allowAutoTaggingMetadata\/fragments","value":[{"text":"allowAutoTaggingMetadata","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","value":"DSAPIAccountSettingsInformation"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","op":"replace","value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title","op":"replace","value":"DSAPISettingsMetadata"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPISettingsMetadata"}]}]}]}