{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/enablesigningordersettingsforaccountmetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/enablesigningordersettingsforaccountmetadata"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSigningOrderSettingsForAccountMetadata"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)enableSigningOrderSettingsForAccountMetadata","title":"enableSigningOrderSettingsForAccountMetadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableSigningOrderSettingsForAccountMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"enableSigningOrderSettingsForAccountMetadata"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/enableSigningOrderSettingsForAccountMetadata"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/enableSigningOrderSettingsForAccountMetadata":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/enablesigningordersettingsforaccountmetadata","navigatorTitle":[{"text":"enableSigningOrderSettingsForAccountMetadata","kind":"identifier"}],"title":"enableSigningOrderSettingsForAccountMetadata","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/enableSigningOrderSettingsForAccountMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableSigningOrderSettingsForAccountMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"enableSigningOrderSettingsForAccountMetadata"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"enableSigningOrderSettingsForAccountMetadata","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"enableSigningOrderSettingsForAccountMetadata","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title","value":"DSAPISettingsMetadata","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments","value":[{"text":"DSAPISettingsMetadata","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1enableSigningOrderSettingsForAccountMetadata\/title","op":"replace","value":"enableSigningOrderSettingsForAccountMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1enableSigningOrderSettingsForAccountMetadata\/fragments","value":[{"kind":"identifier","text":"enableSigningOrderSettingsForAccountMetadata"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","value":"DSAPIAccountSettingsInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"op":"replace"}]}]}