{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString","kind":"attribute","text":"BoolFromString"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableSendToAgent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/enablesendtoagent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/enablesendtoagent"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/enableSendToAgent","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSendToAgent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)enableSendToAgent","title":"enableSendToAgent","modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"enableSendToAgent"}]},"abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"type":"text","text":" this account can use the Agent recipient type.  "},{"inlineContent":[{"type":"text","text":"Note:"}],"type":"strong"},{"type":"text","text":" Only SysAdmin users can change this setting."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/enableSendToAgent":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/enablesendtoagent","navigatorTitle":[{"text":"enableSendToAgent","kind":"identifier"}],"title":"enableSendToAgent","type":"topic","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" this account can use the Agent recipient type.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"text":" Only SysAdmin users can change this setting.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/enableSendToAgent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"enableSendToAgent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"enableSendToAgent"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"enableSendToAgent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableSendToAgent"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","value":"DSAPIAccountSettingsInformation"},{"value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1enableSendToAgent\/title","value":"enableSendToAgent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1enableSendToAgent\/fragments","value":[{"text":"enableSendToAgent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title","op":"replace","value":"BoolFromString"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments","value":[{"text":"BoolFromString","kind":"identifier"}],"op":"replace"}]}]}