{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/sendingTagsFontNameMetadata"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/sendingtagsfontnamemetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/sendingtagsfontnamemetadata"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendingTagsFontNameMetadata"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendingTagsFontNameMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"sendingTagsFontNameMetadata"}],"symbolKind":"property","title":"sendingTagsFontNameMetadata","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)sendingTagsFontNameMetadata"},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/sendingTagsFontNameMetadata":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/sendingtagsfontnamemetadata","navigatorTitle":[{"text":"sendingTagsFontNameMetadata","kind":"identifier"}],"title":"sendingTagsFontNameMetadata","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/sendingTagsFontNameMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendingTagsFontNameMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"sendingTagsFontNameMetadata"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"sendingTagsFontNameMetadata","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sendingTagsFontNameMetadata"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1sendingTagsFontNameMetadata\/title","value":"sendingTagsFontNameMetadata"},{"value":[{"text":"sendingTagsFontNameMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1sendingTagsFontNameMetadata\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","op":"replace","value":"DSAPIAccountSettingsInformation"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title","value":"DSAPISettingsMetadata","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}