{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationsReportMetadata"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/validationsReportMetadata","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"text":"validationsReportMetadata","kind":"identifier"}],"title":"validationsReportMetadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationsReportMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?","kind":"text"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation(py)validationsReportMetadata","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/validationsreportmetadata"]},{"paths":["\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/validationsreportmetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation/validationsReportMetadata":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation\/validationsreportmetadata","navigatorTitle":[{"text":"validationsReportMetadata","kind":"identifier"}],"title":"validationsReportMetadata","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation\/validationsReportMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"validationsReportMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}],"title":"DSAPIAccountSettingsInformation","abstract":[{"text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"validationsReportMetadata"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"validationsReportMetadata"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},{"kind":"text","text":" * "},{"kind":"identifier","text":"validationsReportMetadata"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1validationsReportMetadata\/title","value":"validationsReportMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation~1validationsReportMetadata\/fragments","value":[{"text":"validationsReportMetadata","kind":"identifier"}]},{"value":"DSAPIAccountSettingsInformation","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","value":[{"text":"DSAPIAccountSettingsInformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title","value":"DSAPISettingsMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments","value":[{"text":"DSAPISettingsMetadata","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}