{"variants":[{"paths":["\/documentation\/docusignapi\/dsapiinitialhere\/recipientid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiinitialhere\/recipientid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"recipientId"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recipientId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"recipientId","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere(py)recipientId"},"abstract":[{"type":"text","text":"Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document."}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere\/recipientId","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recipientId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInitialHere/recipientId":{"navigatorTitle":[{"text":"recipientId","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiinitialhere\/recipientid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recipientId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document."}],"title":"recipientId","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere\/recipientId","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInitialHere":{"navigatorTitle":[{"text":"DSAPIInitialHere","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiinitialhere","role":"symbol","title":"DSAPIInitialHere","abstract":[{"type":"text","text":"A tab that allows the recipient to initial the document. May be optional."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInitialHere","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIInitialHere"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"recipientId","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"recipientId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recipientId"}]}]}},{"op":"replace","value":"recipientId","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere~1recipientId\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere~1recipientId\/fragments","value":[{"text":"recipientId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere\/title","value":"DSAPIInitialHere","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInitialHere\/fragments","value":[{"kind":"identifier","text":"DSAPIInitialHere"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}