{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"authenticationMethod","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest(py)authenticationMethod","title":"authenticationMethod","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"abstract":[{"text":"Required. Choose a value that most closely matches the technique your application used to authenticate the recipient \/ signer.   Choose a value from this list:  * Biometric  * Email * HTTPBasicAuth * Kerberos * KnowledgeBasedAuth * None * PaperDocuments * Password * RSASecureID * SingleSignOn_CASiteminder * SingleSignOn_InfoCard * SingleSignOn_MicrosoftActiveDirectory * SingleSignOn_Other * SingleSignOn_Passport * SingleSignOn_SAML * Smartcard * SSLMutualAuth * X509Certificate  This information is included in the Certificate of Completion.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest\/authenticationmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest\/authenticationmethod"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationMethod","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsharedrecipient/":{"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","title":"EnvelopeViews: createSharedRecipient","type":"link","titleInlineContent":[{"text":"EnvelopeViews: createSharedRecipient","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest":{"title":"DSAPIRecipientViewRequest","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest","abstract":[{"type":"text","text":"The request body for the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","type":"reference","isActive":true},{"type":"text","text":" methods."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/authenticationMethod":{"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationMethod","title":"authenticationMethod","abstract":[{"text":"Required. Choose a value that most closely matches the technique your application used to authenticate the recipient \/ signer.   Choose a value from this list:  * Biometric  * Email * HTTPBasicAuth * Kerberos * KnowledgeBasedAuth * None * PaperDocuments * Password * RSASecureID * SingleSignOn_CASiteminder * SingleSignOn_InfoCard * SingleSignOn_MicrosoftActiveDirectory * SingleSignOn_Other * SingleSignOn_Passport * SingleSignOn_SAML * Smartcard * SSLMutualAuth * X509Certificate  This information is included in the Certificate of Completion.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"authenticationMethod","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationMethod"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/authenticationmethod","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/":{"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","title":"EnvelopeViews: createRecipient","type":"link","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createRecipient"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"authenticationMethod"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"authenticationMethod"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"authenticationMethod","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/title","op":"replace","value":"DSAPIRecipientViewRequest"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1authenticationMethod\/title","op":"replace","value":"authenticationMethod"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1authenticationMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"authenticationMethod"}]}]}]}