{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/frameAncestors","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest\/frameancestors"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest\/frameancestors"]}],"sections":[],"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest(py)frameAncestors","title":"frameAncestors","navigatorTitle":[{"kind":"identifier","text":"frameAncestors"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameAncestors"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameAncestors","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsharedrecipient/":{"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createSharedRecipient"}],"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","type":"link","title":"EnvelopeViews: createSharedRecipient"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/":{"titleInlineContent":[{"text":"EnvelopeViews: createRecipient","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","title":"EnvelopeViews: createRecipient","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest":{"title":"DSAPIRecipientViewRequest","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest","abstract":[{"type":"text","text":"The request body for the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","type":"reference","isActive":true},{"type":"text","text":" methods."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/frameAncestors":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/frameAncestors","title":"frameAncestors","abstract":[],"navigatorTitle":[{"text":"frameAncestors","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameAncestors"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/frameancestors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"frameAncestors","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frameAncestors"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"frameAncestors","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/title","value":"DSAPIRecipientViewRequest"},{"value":[{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1frameAncestors\/title","value":"frameAncestors","op":"replace"},{"value":[{"kind":"identifier","text":"frameAncestors"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1frameAncestors\/fragments"}]}]}