{"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageOrigins","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest(py)messageOrigins","navigatorTitle":[{"kind":"identifier","text":"messageOrigins"}],"title":"messageOrigins"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest\/messageorigins"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest\/messageorigins"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/messageOrigins","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageOrigins","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/messageOrigins":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/messageorigins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageOrigins"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"messageOrigins","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/messageOrigins","title":"messageOrigins","type":"topic"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/":{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","title":"EnvelopeViews: createRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createRecipient"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest":{"title":"DSAPIRecipientViewRequest","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest","abstract":[{"type":"text","text":"The request body for the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","type":"reference","isActive":true},{"type":"text","text":" methods."}]},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsharedrecipient/":{"title":"EnvelopeViews: createSharedRecipient","type":"link","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","titleInlineContent":[{"text":"EnvelopeViews: createSharedRecipient","type":"text"}],"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"messageOrigins","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"messageOrigins"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"messageOrigins"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"messageOrigins","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1messageOrigins\/title"},{"value":[{"kind":"identifier","text":"messageOrigins"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1messageOrigins\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/title","op":"replace","value":"DSAPIRecipientViewRequest"},{"value":[{"text":"DSAPIRecipientViewRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/fragments","op":"replace"}]}]}