{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent\/init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapitelemetryevent\/init(appversion:identity:tracetoken:eventcategory:eventname:eventtype:applications:clientcontext:data:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapitelemetryevent\/init(appversion:identity:tracetoken:eventcategory:eventname:eventtype:applications:clientcontext:data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent"]]},"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvent(im)initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","title":"init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"appVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"identity"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"traceToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventCategory"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"eventName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"eventType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"applications","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"clientContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIClientContext","kind":"typeIdentifier","text":"DSAPIClientContext"},{"text":"?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"modules":[{"name":"DocuSignAPI"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"appVersion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"identity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"traceToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"eventCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"eventName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"eventType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"applications","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"text":"clientContext","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext","kind":"typeIdentifier","text":"DSAPIClientContext","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIClientContext"},{"kind":"text","text":"? = nil, "},{"text":"data","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEvent":{"navigatorTitle":[{"text":"DSAPITelemetryEvent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapitelemetryevent","role":"symbol","title":"DSAPITelemetryEvent","abstract":[{"text":"The telemetry event model.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPITelemetryEvent","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEvent/init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)":{"url":"\/documentation\/docusignapi\/dsapitelemetryevent\/init(appversion:identity:tracetoken:eventcategory:eventname:eventtype:applications:clientcontext:data:)","navigatorTitle":[{"text":"initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","kind":"identifier"}],"kind":"symbol","title":"init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvent\/init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"identity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"traceToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"eventName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"eventType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"applications","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"clientContext"},{"text":": ","kind":"text"},{"text":"DSAPIClientContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIClientContext"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?)","kind":"text"}],"type":"topic","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext":{"abstract":[{"text":"This client specific details for the telemetry events.","type":"text"}],"title":"DSAPIClientContext","url":"\/documentation\/docusignapi\/dsapiclientcontext","role":"symbol","navigatorTitle":[{"text":"DSAPIClientContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIClientContext"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAppVersion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appVersion"},{"text":" ","kind":"text"},{"text":"identity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identity","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"traceToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"traceToken"},{"text":" ","kind":"text"},{"text":"eventCategory:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"eventCategory","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"eventName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"eventType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eventType"},{"kind":"text","text":" "},{"text":"applications:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"applications","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext","text":"DSAPIClientContext","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIClientContext"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"clientContext"},{"kind":"text","text":" "},{"text":"data:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"DSAPITelemetryEvent","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvent\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvent\/fragments","value":[{"text":"DSAPITelemetryEvent","kind":"identifier"}]},{"value":"initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvent~1init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvent~1init(appVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAppVersion:identity:traceToken:eventCategory:eventName:eventType:applications:clientContext:data:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext\/title","value":"DSAPIClientContext","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIClientContext"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}