{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"expirations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","text":"DSAPIExpirations"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"reminders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","text":"DSAPIReminders"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"useAccountDefaults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitemplatenotificationrequest\/init(expirations:password:reminders:useaccountdefaults:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateNotificationRequest\/init(expirations:password:reminders:useAccountDefaults:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"expirations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reminders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIReminders","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useAccountDefaults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(expirations:password:reminders:useAccountDefaults:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI32DSAPITemplateNotificationRequestV11expirations8password9reminders18useAccountDefaultsAcA16DSAPIExpirationsCSg_SSSgAA14DSAPIRemindersCSgSbtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateNotificationRequest"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations":{"role":"symbol","title":"DSAPIExpirations","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIExpirations"}],"abstract":[{"type":"text","text":"A complex element that specifies the expiration settings for the envelope. When an envelope expires, it is voided and no longer available for signing. "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" there is a short delay between when the envelope expires and when it is voided."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIExpirations"}],"url":"\/documentation\/docusignapi\/dsapiexpirations"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateNotificationRequest/init(expirations:password:reminders:useAccountDefaults:)":{"role":"symbol","title":"init(expirations:password:reminders:useAccountDefaults:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"expirations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reminders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIReminders","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useAccountDefaults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateNotificationRequest\/init(expirations:password:reminders:useAccountDefaults:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitemplatenotificationrequest\/init(expirations:password:reminders:useaccountdefaults:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIReminders":{"role":"symbol","title":"DSAPIReminders","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIReminders"}],"abstract":[{"type":"text","text":"A complex element that specifies reminder settings for the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIReminders"}],"url":"\/documentation\/docusignapi\/dsapireminders"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateNotificationRequest":{"role":"symbol","title":"DSAPITemplateNotificationRequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITemplateNotificationRequest"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateNotificationRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateNotificationRequest"}],"url":"\/documentation\/docusignapi\/dsapitemplatenotificationrequest"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/title","value":"DSAPIExpirations"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/fragments","value":[{"kind":"identifier","text":"DSAPIExpirations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/title","value":"DSAPIReminders"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/fragments","value":[{"kind":"identifier","text":"DSAPIReminders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}