{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue","text":"DSAPINameValue","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument\/documentFields","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopedocument\/documentfields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapienvelopedocument\/documentfields"]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","navigatorTitle":[{"text":"documentFields","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"documentFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPINameValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"text":"]?","kind":"text"}],"title":"documentFields","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument(py)documentFields"},"abstract":[{"text":"An object containing information about the custom fields on the document.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue":{"role":"symbol","abstract":[{"text":"A name-value pair that describes an item and provides a value for the item.","type":"text"}],"kind":"symbol","title":"DSAPINameValue","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue","url":"\/documentation\/docusignapi\/dsapinamevalue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPINameValue","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DSAPINameValue","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocument":{"navigatorTitle":[{"text":"DSAPIEnvelopeDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopedocument","role":"symbol","abstract":[{"type":"text","text":"This object contains details about the envelope document."}],"title":"DSAPIEnvelopeDocument","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIEnvelopeDocument"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocument/documentFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument\/documentFields","title":"documentFields","url":"\/documentation\/docusignapi\/dsapienvelopedocument\/documentfields","abstract":[{"type":"text","text":"An object containing information about the custom fields on the document."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPINameValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"documentFields"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"documentFields"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"documentFields","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DSAPINameValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"documentFields"}],"platforms":["iOS"]}]}},{"value":"DSAPINameValue","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue\/fragments","value":[{"text":"DSAPINameValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument\/title","value":"DSAPIEnvelopeDocument"},{"value":[{"text":"DSAPIEnvelopeDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument~1documentFields\/title","value":"documentFields"},{"value":[{"text":"documentFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument~1documentFields\/fragments","op":"replace"}]}]}