{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"anchorTabProcessorVersionMetadata"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICompany(py)anchorTabProcessorVersionMetadata","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","title":"anchorTabProcessorVersionMetadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorTabProcessorVersionMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany\/anchorTabProcessorVersionMetadata","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapicompany\/anchortabprocessorversionmetadata"]},{"paths":["\/documentation\/docusignapi\/dsapicompany\/anchortabprocessorversionmetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorTabProcessorVersionMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICompany/anchorTabProcessorVersionMetadata":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany\/anchorTabProcessorVersionMetadata","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"anchorTabProcessorVersionMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapicompany\/anchortabprocessorversionmetadata","title":"anchorTabProcessorVersionMetadata","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"anchorTabProcessorVersionMetadata"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICompany":{"type":"topic","abstract":[{"type":"text","text":"A tab that displays the recipient's company name."}],"title":"DSAPICompany","url":"\/documentation\/docusignapi\/dsapicompany","navigatorTitle":[{"kind":"identifier","text":"DSAPICompany"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICompany","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPICompany","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"anchorTabProcessorVersionMetadata"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"anchorTabProcessorVersionMetadata"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":" * ","kind":"text"},{"text":"anchorTabProcessorVersionMetadata","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany~1anchorTabProcessorVersionMetadata\/title","op":"replace","value":"anchorTabProcessorVersionMetadata"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany~1anchorTabProcessorVersionMetadata\/fragments","value":[{"kind":"identifier","text":"anchorTabProcessorVersionMetadata"}],"op":"replace"},{"value":"DSAPICompany","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPICompany"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICompany\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","value":"DSAPIPropertyMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"text":"DSAPIPropertyMetadata","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}