{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesPutUserSignatureImageData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transparentPng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","text":"DSAPIUserSignature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"imageType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) One of "},{"type":"strong","inlineContent":[{"type":"text","text":"signature_image"}]},{"type":"text","text":" or "},{"type":"strong","inlineContent":[{"type":"text","text":"initials_image"}]},{"type":"text","text":"."}]}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) Image of the signature or initials. ."}]}]},{"name":"signatureId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The ID of the signature being accessed."}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing."}]}]},{"name":"transparentPng","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturesputusersignatureimagedata(accountid:imagetype:image:signatureid:userid:transparentpng:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturesputusersignatureimagedata(accountid:imagetype:image:signatureid:userid:transparentpng:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the user signature image or user initials image for the specified user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesPutUserSignatureImageData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transparentPng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DocuSignAPI@objc(cs)UsersAPI(cm)userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI/userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)":{"role":"symbol","title":"userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesPutUserSignatureImageData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transparentPng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Updates the user signature image or user initials image for the specified user."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:"}],"url":"\/documentation\/docusignapi\/usersapi\/usersignaturesputusersignatureimagedata(accountid:imagetype:image:signatureid:userid:transparentpng:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature":{"role":"symbol","title":"DSAPIUserSignature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignature"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignature"}],"url":"\/documentation\/docusignapi\/dsapiusersignature"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI":{"role":"symbol","title":"UsersAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsersAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsersAPI"}],"url":"\/documentation\/docusignapi\/usersapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userSignaturesPutUserSignatureImageDataWithAccountId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageType"},{"kind":"text","text":" "},{"kind":"identifier","text":"image:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"transparentPng:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"transparentPng"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DSAPIUserSignature *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIUserSignature#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)\/title","value":"userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesPutUserSignatureImageData(accountId:imageType:image:signatureId:userId:transparentPng:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"userSignaturesPutUserSignatureImageDataWithAccountId:imageType:image:signatureId:userId:transparentPng:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/title","value":"DSAPIUserSignature"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/fragments","value":[{"kind":"identifier","text":"DSAPIUserSignature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/title","value":"UsersAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/fragments","value":[{"kind":"identifier","text":"UsersAPI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}