{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesPutUserSignatureById"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition","text":"DSAPIUserSignatureDefinition"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"closeExistingSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","text":"DSAPIUserSignature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"signatureId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The ID of the signature being accessed."}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing."}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]},{"name":"closeExistingSignature","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) When set to "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":", closes the current signature. (optional)"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturesputusersignaturebyid(accountid:signatureid:userid:body:closeexistingsignature:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturesputusersignaturebyid(accountid:signatureid:userid:body:closeexistingsignature:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the user signature for a specified user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesPutUserSignatureById"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserSignatureDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"closeExistingSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)UsersAPI(cm)userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition":{"role":"symbol","title":"DSAPIUserSignatureDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI/userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)":{"role":"symbol","title":"userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesPutUserSignatureById"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserSignatureDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"closeExistingSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Updates the user signature for a specified user."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:"}],"url":"\/documentation\/docusignapi\/usersapi\/usersignaturesputusersignaturebyid(accountid:signatureid:userid:body:closeexistingsignature:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI":{"role":"symbol","title":"UsersAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsersAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsersAPI"}],"url":"\/documentation\/docusignapi\/usersapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature":{"role":"symbol","title":"DSAPIUserSignature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignature"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignature"}],"url":"\/documentation\/docusignapi\/dsapiusersignature"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userSignaturesPutUserSignatureByIdWithAccountId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signatureId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"body:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition","text":"DSAPIUserSignatureDefinition"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"body"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeExistingSignature:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"closeExistingSignature"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DSAPIUserSignature *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIUserSignature#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/title","value":"DSAPIUserSignatureDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)\/title","value":"userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesPutUserSignatureById(accountId:signatureId:userId:body:closeExistingSignature:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"userSignaturesPutUserSignatureByIdWithAccountId:signatureId:userId:body:closeExistingSignature:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/title","value":"UsersAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/fragments","value":[{"kind":"identifier","text":"UsersAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/title","value":"DSAPIUserSignature"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/fragments","value":[{"kind":"identifier","text":"DSAPIUserSignature"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}