{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"text":"userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:","kind":"identifier"}],"title":"userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userSignaturesGetUserSignature","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"signatureId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","text":"DSAPIUserSignature","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"externalID":"c:@M@DocuSignAPI@objc(cs)UsersAPI(cm)userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:","role":"symbol"},"abstract":[{"text":"Gets the user signature information for the specified user.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesGetUserSignature"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"signatureId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","kind":"typeIdentifier","text":"DSAPIUserSignature"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}],"name":"accountId"},{"name":"signatureId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The ID of the signature being accessed.","type":"text"}]}]},{"name":"userId","content":[{"inlineContent":[{"text":"(path) The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"completion handler to receive the data and the error objects","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturesgetusersignature(accountid:signatureid:userid:completion:)"]},{"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturesgetusersignature(accountid:signatureid:userid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature":{"url":"\/documentation\/docusignapi\/dsapiusersignature","title":"DSAPIUserSignature","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserSignature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignature"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UsersAPI","kind":"identifier"}],"url":"\/documentation\/docusignapi\/usersapi","title":"UsersAPI","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UsersAPI"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI/userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Gets the user signature information for the specified user.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:"}],"title":"userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSignaturesGetUserSignature"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"signatureId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","text":"DSAPIUserSignature","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"url":"\/documentation\/docusignapi\/usersapi\/usersignaturesgetusersignature(accountid:signatureid:userid:completion:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"userSignaturesGetUserSignatureWithAccountId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accountId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"signatureId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"userId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIUserSignature#*$objc(cs)NSError)","text":"void (^)(DSAPIUserSignature *, NSError *)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DSAPIUserSignature","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/title"},{"value":[{"text":"DSAPIUserSignature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/title","op":"replace","value":"UsersAPI"},{"value":[{"text":"UsersAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)\/title","value":"userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesGetUserSignature(accountId:signatureId:userId:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"userSignaturesGetUserSignatureWithAccountId:signatureId:userId:completion:"}]}]}]}