{"metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"externalID":"c:@CM@DocuSignAPI@objc(cs)UsersAPI(cm)userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userSignaturesPostUserSignatureImages","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation","text":"DSAPIUserSignaturesInformation","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"multiParts"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]>?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation","text":"DSAPIUserSignaturesInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"extendedModule":"DocuSignAPI","roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:"}],"title":"userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Upload the user signature image and\/or user initials image for the specified user.","type":"text"}],"variants":[{"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturespostusersignatureimages(accountid:userid:body:multiparts:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/usersapi\/usersignaturespostusersignatureimages(accountid:userid:body:multiparts:completion:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userSignaturesPostUserSignatureImages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation","text":"DSAPIUserSignaturesInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"multiParts"},{"text":": ","kind":"text"},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]>?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DSAPIUserSignaturesInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}],"type":"paragraph"}],"name":"accountId"},{"content":[{"inlineContent":[{"type":"text","text":"(path) The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing."}],"type":"paragraph"}],"name":"userId"},{"content":[{"inlineContent":[{"type":"text","text":"(body)  (optional)"}],"type":"paragraph"}],"name":"body"},{"name":"multiParts","content":[{"inlineContent":[{"type":"text","text":"(path) multipart dictionary containing Images for respective keys representing initials or signature images."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"completion handler to receive the data and the error objects","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UsersAPI","kind":"identifier"}],"url":"\/documentation\/docusignapi\/usersapi","title":"UsersAPI","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UsersAPI"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIUserSignaturesInformation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation","type":"topic","role":"symbol","title":"DSAPIUserSignaturesInformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/UsersAPI/userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/UsersAPI\/userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)","abstract":[{"text":"Upload the user signature image and\/or user initials image for the specified user.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userSignaturesPostUserSignatureImages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIUserSignaturesInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"multiParts"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SD","kind":"typeIdentifier","text":"Dictionary"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]>?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation","text":"DSAPIUserSignaturesInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"navigatorTitle":[{"text":"userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:","kind":"identifier"}],"url":"\/documentation\/docusignapi\/usersapi\/usersignaturespostusersignatureimages(accountid:userid:body:multiparts:completion:)","type":"topic","role":"symbol","title":"userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"userSignaturesPostUserSignatureImagesWithAccountId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"body:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSAPIUserSignaturesInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"body"},{"kind":"text","text":" "},{"text":"multiParts:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSArray *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"multiParts","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(DSAPIUserSignaturesInformation *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"UsersAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/title","op":"replace"},{"value":[{"text":"UsersAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation\/title","op":"replace","value":"DSAPIUserSignaturesInformation"},{"value":[{"text":"DSAPIUserSignaturesInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation\/fragments"},{"value":"userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1UsersAPI~1userSignaturesPostUserSignatureImages(accountId:userId:body:multiParts:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"userSignaturesPostUserSignatureImagesWithAccountId:userId:body:multiParts:completion:","kind":"identifier"}],"op":"replace"}]}]}