{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","text":"DSAPIEnvelopeDefinition"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/converttoobject(jsonstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/converttoobject(jsonstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/convertToObject(jsonString:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition"},{"kind":"text","text":"?"}],"title":"convertToObject(jsonString:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition(im)convertToObjectWithJsonString:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"convertToObjectWithJsonString:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition/convertToObject(jsonString:)":{"role":"symbol","title":"convertToObject(jsonString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/convertToObject(jsonString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertToObjectWithJsonString:"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition\/converttoobject(jsonstring:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"role":"symbol","title":"DSAPIEnvelopeDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"type":"text","text":"Envelope object definition."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"convertToObjectWithJsonString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertToObjectWithJsonString:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","text":"DSAPIEnvelopeDefinition"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"convertToObjectWithJsonString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"jsonString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1convertToObject(jsonString:)\/title","value":"convertToObjectWithJsonString:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1convertToObject(jsonString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertToObjectWithJsonString:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}