{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"envelopeId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/envelopeId","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/envelopeid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/envelopeid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"envelopeId","navigatorTitle":[{"text":"envelopeId","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition(py)envelopeId","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"envelopeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The envelope ID.  When used as a request body in "},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/","isActive":true},{"text":", this is the ID of the envelope to clone.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"/docs/esign-rest-api/reference/envelopes/envelopes/create/":{"type":"link","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/","titleInlineContent":[{"type":"text","text":"Envelopes: create"}],"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/","title":"Envelopes: create"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"title":"DSAPIEnvelopeDefinition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"text":"Envelope object definition.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopedefinition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition/envelopeId":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/envelopeId","abstract":[{"type":"text","text":"The envelope ID.  When used as a request body in "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/","type":"reference","isActive":true},{"type":"text","text":", this is the ID of the envelope to clone."}],"title":"envelopeId","navigatorTitle":[{"text":"envelopeId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"envelopeId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopedefinition\/envelopeid","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"envelopeId"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"envelopeId"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"envelopeId"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1envelopeId\/title","op":"replace","value":"envelopeId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1envelopeId\/fragments","value":[{"text":"envelopeId","kind":"identifier"}]}]}]}