{"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expireDateTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"expireDateTime","kind":"identifier"}],"modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition(py)expireDateTime","role":"symbol","title":"expireDateTime"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/expireDateTime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Not used. Use the "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","type":"reference","isActive":true},{"type":"text","text":" property in the "},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","isActive":true},{"type":"text","text":" object instead."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expireDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/expiredatetime"]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/expiredatetime"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"title":"DSAPIEnvelopeDefinition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"text":"Envelope object definition.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopedefinition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},"/docs/esign-rest-api/reference/envelopes/envelopes/create/#definition__envelopedefinition_notification":{"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","title":"`notification`","titleInlineContent":[{"text":"`notification`","type":"text"}],"type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition/expireDateTime":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/expireDateTime","abstract":[{"type":"text","text":"Not used. Use the "},{"isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","type":"reference"},{"type":"text","text":" property in the "},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification","type":"reference","isActive":true},{"type":"text","text":" object instead."}],"title":"expireDateTime","navigatorTitle":[{"text":"expireDateTime","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"expireDateTime","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopedefinition\/expiredatetime","type":"topic","kind":"symbol"},"/docs/esign-rest-api/reference/envelopes/envelopes/create/#definition__envelopedefinition_notification_expirations":{"title":"`expirations`","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","titleInlineContent":[{"text":"`expirations`","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopes\/create\/#definition__envelopedefinition_notification_expirations","type":"link"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"expireDateTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"expireDateTime"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"expireDateTime"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition"},{"op":"replace","value":[{"text":"DSAPIEnvelopeDefinition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments"},{"value":"expireDateTime","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1expireDateTime\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1expireDateTime\/fragments","value":[{"text":"expireDateTime","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}