{"metadata":{"symbolKind":"property","role":"symbol","title":"hasComments","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasComments"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition(py)hasComments","navigatorTitle":[{"kind":"identifier","text":"hasComments"}]},"abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"type":"text","text":" indicates that users have added comments to the envelope."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/hascomments"]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/hascomments"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","text":"BoolFromString","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasComments","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/hasComments","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition/hasComments":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/hasComments","abstract":[{"type":"text","text":"When "},{"inlineContent":[{"type":"text","text":"true,"}],"type":"strong"},{"text":" indicates that users have added comments to the envelope.","type":"text"}],"title":"hasComments","navigatorTitle":[{"kind":"identifier","text":"hasComments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasComments","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopedefinition\/hascomments","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"title":"DSAPIEnvelopeDefinition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"text":"Envelope object definition.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopedefinition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hasComments"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hasComments"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasComments"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"BoolFromString","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title"},{"op":"replace","value":[{"text":"BoolFromString","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments"},{"value":"hasComments","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1hasComments\/title"},{"value":[{"kind":"identifier","text":"hasComments"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1hasComments\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","op":"replace","value":"DSAPIEnvelopeDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"text":"DSAPIEnvelopeDefinition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}