{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/purgestate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/purgestate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/purgeState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initiates a purge request. Valid values are:  - `documents_queued`: Places envelope documents in the purge queue. - `documents_and_metadata_queued`: Places envelope documents    and metadata in the purge queue. - `documents_and_metadata_and_redact_queued`: Places envelope documents    and metadata in the purge queue and redacts personal information.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Related topics"}]},{"type":"text","text":"  - "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/purging\/"},{"type":"text","text":" - "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.docusign.com\/blog\/developers\/purging-documents-envelope"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"purgeState","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition(py)purgeState","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"purgeState"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"role":"symbol","title":"DSAPIEnvelopeDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"type":"text","text":"Envelope object definition."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition"},"https://www.docusign.com/blog/developers/purging-documents-envelope":{"title":"Purging documents in an envelope (blog post)","titleInlineContent":[{"type":"text","text":"Purging documents in an envelope (blog post)"}],"type":"link","identifier":"https:\/\/www.docusign.com\/blog\/developers\/purging-documents-envelope","url":"https:\/\/www.docusign.com\/blog\/developers\/purging-documents-envelope"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition/purgeState":{"role":"symbol","title":"purgeState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Initiates a purge request. Valid values are:  - `documents_queued`: Places envelope documents in the purge queue. - `documents_and_metadata_queued`: Places envelope documents    and metadata in the purge queue. - `documents_and_metadata_and_redact_queued`: Places envelope documents    and metadata in the purge queue and redacts personal information.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Related topics"}]},{"type":"text","text":"  - "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/purging\/"},{"type":"text","text":" - "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.docusign.com\/blog\/developers\/purging-documents-envelope"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/purgeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"purgeState"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition\/purgestate"},"/docs/esign-rest-api/esign101/concepts/documents/purging/":{"title":"Purging documents (eSingature Concepts)","titleInlineContent":[{"type":"text","text":"Purging documents (eSingature Concepts)"}],"type":"link","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/purging\/","url":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/purging\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"purgeState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"purgeState"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"purgeState"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1purgeState\/title","value":"purgeState"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1purgeState\/fragments","value":[{"kind":"identifier","text":"purgeState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}