{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientViewRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest","text":"DSAPIRecipientViewRequest"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/recipientviewrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedefinition\/recipientviewrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/recipientViewRequest","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientViewRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest"},{"kind":"text","text":"?"}],"title":"recipientViewRequest","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition(py)recipientViewRequest","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"recipientViewRequest"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"role":"symbol","title":"DSAPIEnvelopeDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"type":"text","text":"Envelope object definition."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest":{"role":"symbol","title":"DSAPIRecipientViewRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"abstract":[{"type":"text","text":"The request body for the "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},{"type":"text","text":" methods."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition/recipientViewRequest":{"role":"symbol","title":"recipientViewRequest","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientViewRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition\/recipientViewRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recipientViewRequest"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition\/recipientviewrequest"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsharedrecipient/":{"title":"EnvelopeViews: createSharedRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createSharedRecipient"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/":{"title":"EnvelopeViews: createRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createRecipient"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recipientViewRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recipientViewRequest"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest","text":"DSAPIRecipientViewRequest"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recipientViewRequest"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/title","value":"DSAPIRecipientViewRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1recipientViewRequest\/title","value":"recipientViewRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition~1recipientViewRequest\/fragments","value":[{"kind":"identifier","text":"recipientViewRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}