{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiconsumerdisclosure"]},{"paths":["\/documentation\/docusignapi\/dsapiconsumerdisclosure"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure","modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"DSAPIConsumerDisclosure","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"symbolKind":"class"},"sections":[],"abstract":[{"text":"Details about consumer disclosures.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/accountEsignId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/allowCDWithdraw","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/allowCDWithdrawMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/changeEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/changeEmailOther","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/companyName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/companyPhone","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyCostPerPage","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyFeeCollectionMethod","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyRequestEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/custom","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/enableEsign","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/esignAgreement","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/esignText","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/languageCode","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/mustAgreeToEsign","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/pdfId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useBrand","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useConsumerDisclosureWithinAccount","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useConsumerDisclosureWithinAccountMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawAddressLine1","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawAddressLine2","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByMail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByPhone","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawCity","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawConsequences","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawOther","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawPhone","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawPostalCode","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawState"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/languageCode":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/languageCode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"languageCode"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"languageCode","abstract":[{"text":"The code for the language version of the disclosure. The following languages are supported:  - Arabic (`ar`) - Bulgarian (`bg`) - Czech (`cs`) - Chinese Simplified (`zh_CN`) - Chinese Traditional (`zh_TW`) - Croatian (`hr`) - Danish (`da`) - Dutch (`nl`) - English US (`en`) - English UK (`en_GB`) - Estonian (`et`) - Farsi (`fa`) - Finnish (`fi`) - French (`fr`) - French Canadian (`fr_CA`) - German (`de`) - Greek (`el`) - Hebrew (`he`) - Hindi (`hi`) - Hungarian (`hu`) - Bahasa Indonesian (`id`) - Italian (`it`) - Japanese (`ja`) - Korean (`ko`) - Latvian (`lv`) - Lithuanian (`lt`) - Bahasa Melayu (`ms`) - Norwegian (`no`) - Polish (`pl`) - Portuguese (`pt`) - Portuguese Brazil (`pt_BR`) - Romanian (`ro`) - Russian (`ru`) - Serbian (`sr`) - Slovak (`sk`) - Slovenian (`sl`) - Spanish (`es`) - Spanish Latin America (`es_MX`) - Swedish (`sv`) - Thai (`th`) - Turkish (`tr`) - Ukrainian (`uk`)  - Vietnamese (`vi`)  Additionally, you can automatically detect the browser language being used by the viewer and display the disclosure in that language by setting the value to `browser`.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"languageCode","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/languagecode"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawOther":{"type":"topic","role":"symbol","abstract":[{"text":"Contains any other information needed to withdraw consent.  Maximum length: 255 characters.  Example:  `We do not need any other information from you to withdraw consent.`","type":"text"}],"navigatorTitle":[{"text":"withdrawOther","kind":"identifier"}],"title":"withdrawOther","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawOther","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"withdrawOther","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawother","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawPostalCode":{"kind":"symbol","type":"topic","title":"withdrawPostalCode","abstract":[{"type":"text","text":"Contains the postal code of the postal address to which a customer can send a consent withdrawal notification.  Maximum length: 20 characters."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"withdrawPostalCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"withdrawPostalCode","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawpostalcode","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawPostalCode"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/copyCostPerPage":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/copycostperpage","navigatorTitle":[{"text":"copyCostPerPage","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCostPerPage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"copyCostPerPage","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyCostPerPage","abstract":[{"type":"text","text":"The cost per page if the customer requests paper copies.  Example:   `0.0000`"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawAddressLine1":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawAddressLine1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"withdrawAddressLine1","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","title":"withdrawAddressLine1","abstract":[{"text":"Contains the first address line of the postal address to which a customer can send a consent withdrawal notification.  Maximum length: 100 characters.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"withdrawAddressLine1","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawaddressline1"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/esignText":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"esignText"}],"kind":"symbol","title":"esignText","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"esignText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/esigntext","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/esignText","abstract":[{"text":"The template for the Electronic Record and Signature Disclosure, which contains placeholders for information such as the `companyName`. It also includes the HTML tags used for formatting.  ","type":"text"},{"inlineContent":[{"type":"text","text":"Note:"}],"type":"strong"},{"text":" If you are switching to or updating a custom disclosure, you can edit both the text and the HTML formatting.","type":"text"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure":{"type":"topic","title":"DSAPIConsumerDisclosure","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"navigatorTitle":[{"text":"DSAPIConsumerDisclosure","kind":"identifier"}],"abstract":[{"type":"text","text":"Details about consumer disclosures."}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/changeEmail":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/changeemail","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/changeEmail","navigatorTitle":[{"text":"changeEmail","kind":"identifier"}],"abstract":[{"text":"If the customer needs to change their email address, this is the email address to which they should the change request.  Maximum length: 100 characters.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeEmail"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"changeEmail","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)":{"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/init(accountesignid:allowcdwithdraw:allowcdwithdrawmetadata:changeemail:changeemailother:companyname:companyphone:copycostperpage:copyfeecollectionmethod:copyrequestemail:custom:enableesign:esignagreement:esigntext:languagecode:mustagreetoe-8ulkh","title":"init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountEsignId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowCDWithdraw"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowCDWithdrawMetadata"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"changeEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"changeEmailOther"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"companyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"companyPhone","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"copyCostPerPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"copyFeeCollectionMethod","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"copyRequestEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"custom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"enableEsign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"esignAgreement"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"esignText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"languageCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mustAgreeToEsign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pdfId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"useBrand"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useConsumerDisclosureWithinAccount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"useConsumerDisclosureWithinAccountMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawAddressLine1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"withdrawAddressLine2","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawByEmail"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawByMail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withdrawByPhone"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"withdrawCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawConsequences","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"withdrawEmail","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawOther","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"withdrawPhone","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawPostalCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"withdrawState","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/changeEmailOther":{"kind":"symbol","type":"topic","title":"changeEmailOther","abstract":[{"text":"Other information about the requirements for the user to change their email address.  Maximum length: 255 characters.  Example:   `We do not require any other information from you to change your email address.`","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeEmailOther"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"changeEmailOther"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/changeemailother","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/changeEmailOther"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawState":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawState","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawState"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"withdrawState","abstract":[{"text":"Contains the state of the postal address to which a customer can send a consent withdrawal notification.  Example: `PA`","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withdrawState"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawstate"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/useBrand":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useBrand","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"useBrand","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"useBrand","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"type":"text","text":" specifies that the company name in the signing brand is used for the disclosure. Whenever an envelope is sent from the account that uses a signing brand with a specified company name, that value is used in email notifications and in the signing experience.    When "},{"inlineContent":[{"type":"text","text":"false"}],"type":"strong"},{"text":" (default), or if the signing brand does not specify a company name, the account name is used instead.  ","type":"text"},{"inlineContent":[{"text":"Note:","type":"text"}],"type":"strong"},{"type":"text","text":" This substitution only works if you use the default legal disclosure or if you apply the `companyName` to the merge fields in a custom ERSD."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"useBrand","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/usebrand"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawPhone":{"type":"topic","role":"symbol","abstract":[{"text":"Contains the phone number that a customer can call to register consent withdrawal notification as a free-formatted string.  Maximum length: 20 characters.","type":"text"}],"navigatorTitle":[{"text":"withdrawPhone","kind":"identifier"}],"title":"withdrawPhone","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawPhone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"withdrawPhone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawphone","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/accountEsignId":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/accountEsignId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accountEsignId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"accountEsignId","abstract":[{"type":"text","text":"The GUID of the account associated with the consumer disclosure."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"accountEsignId","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/accountesignid"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/allowCDWithdrawMetadata":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/allowCDWithdrawMetadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowCDWithdrawMetadata"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?","kind":"text"}],"abstract":[],"title":"allowCDWithdrawMetadata","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowCDWithdrawMetadata"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/allowcdwithdrawmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/mustAgreeToEsign":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/mustAgreeToEsign","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mustAgreeToEsign","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"mustAgreeToEsign","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"type":"text","text":" the  recipient must agree to the consumer disclosure. The value of this property is read-only. It is calculated based on the account setting `consumerDisclosureFrequency` and the user's actions."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"mustAgreeToEsign","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/mustagreetoesign"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawByMail":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByMail","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"withdrawByMail","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","title":"withdrawByMail","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" indicates that the customer can withdraw consent by postal mail. The default is ","type":"text"},{"type":"strong","inlineContent":[{"text":"false.","type":"text"}]}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withdrawByMail"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawbymail"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/copyRequestEmail":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyRequestEmail","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"copyRequestEmail","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","title":"copyRequestEmail","abstract":[{"type":"text","text":"The email address to which the customer should send a request for copies of a document.  Maximum length: 100 characters."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyRequestEmail"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/copyrequestemail"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/useConsumerDisclosureWithinAccount":{"type":"topic","role":"symbol","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" specifies that recipients in the same account as the sender must agree to eSign an Electronic Record and Signature Disclosure Statement.","type":"text"}],"navigatorTitle":[{"text":"useConsumerDisclosureWithinAccount","kind":"identifier"}],"title":"useConsumerDisclosureWithinAccount","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useConsumerDisclosureWithinAccount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useConsumerDisclosureWithinAccount","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/useconsumerdisclosurewithinaccount","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/custom":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/custom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"custom","abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"type":"text","text":"true,"}],"type":"strong"},{"type":"text","text":" indicates that the consumer disclosure is a custom disclosure. The default is "},{"inlineContent":[{"text":"false.","type":"text"}],"type":"strong"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"custom"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/custom"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/enableEsign":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/enableEsign","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableEsign"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"text":"true","type":"text"}]},{"type":"text","text":" (default), indicates that eSign is enabled."}],"title":"enableEsign","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableEsign"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/enableesign"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawByPhone":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByPhone","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawByPhone"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"withdrawByPhone","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" indicates that the customer can withdraw consent by phone. The default is ","type":"text"},{"inlineContent":[{"type":"text","text":"false."}],"type":"strong"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withdrawByPhone"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawbyphone"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/allowCDWithdraw":{"navigatorTitle":[{"kind":"identifier","text":"allowCDWithdraw"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/allowcdwithdraw","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowCDWithdraw"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"text":" indicates that the customer can withdraw their consent to the consumer disclosure when they decline to sign documents. If these recipients sign documents sent to them from your account in the future, they will be required to agree to the terms in the disclosure. The default value is ","type":"text"},{"type":"strong","inlineContent":[{"text":"false.","type":"text"}]},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Only Admin users can change this setting."}],"title":"allowCDWithdraw","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/allowCDWithdraw","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/esignAgreement":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/esignAgreement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"esignAgreement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"esignAgreement","abstract":[{"text":"The final, assembled text of the Electronic Record and Signature Disclosure that includes the appropriate `companyName` and other specifics. It also includes the HTML tags used for formatting.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"esignAgreement","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/esignagreement"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawEmail":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawEmail","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"withdrawEmail"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"withdrawEmail","abstract":[{"text":"Contains the email address to which a customer can send a consent withdrawal notification.  Maximum length: 100 characters.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withdrawEmail"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawemail"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawCity":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Contains the city of the postal address to which a customer can send a consent withdrawal notification.  Maximum length: 50 characters."}],"navigatorTitle":[{"kind":"identifier","text":"withdrawCity"}],"title":"withdrawCity","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawCity","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"withdrawCity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawcity","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/companyPhone":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/companyPhone","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"companyPhone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The phone number of the company associated with the consumer disclosure, as a free-formatted string."}],"title":"companyPhone","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"companyPhone"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/companyphone"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawConsequences":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawConsequences","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"withdrawConsequences"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"withdrawConsequences","abstract":[{"text":"Text indicating the consequences of withdrawing consent.  Maximum length: 255 characters.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"withdrawConsequences","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawconsequences"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawAddressLine2":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawAddressLine2","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"withdrawAddressLine2","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"withdrawAddressLine2","abstract":[{"text":"Contains the second address line of the postal address to which a customer can send a consent withdrawal notification.  Maximum length: 100 characters.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withdrawAddressLine2"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawaddressline2"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/init(from:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"title":"init(from:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/withdrawByEmail":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByEmail","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawByEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"withdrawByEmail","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"text":"true","type":"text"}]},{"type":"text","text":" (default), indicates that the customer can withdraw consent by email."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"withdrawByEmail","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/withdrawbyemail"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","title":"Swift.Encodable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/copyFeeCollectionMethod":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyFeeCollectionMethod","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"copyFeeCollectionMethod","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","title":"copyFeeCollectionMethod","abstract":[{"type":"text","text":"Specifies the fee collection method for cases in which the customer requires paper copies of the document.  Maximum length: 255 characters.  Example:   `We will bill you for any fees at that time, if any.`"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyFeeCollectionMethod"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/copyfeecollectionmethod"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/useConsumerDisclosureWithinAccountMetadata":{"navigatorTitle":[{"kind":"identifier","text":"useConsumerDisclosureWithinAccountMetadata"}],"title":"useConsumerDisclosureWithinAccountMetadata","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/useconsumerdisclosurewithinaccountmetadata","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useConsumerDisclosureWithinAccountMetadata","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useConsumerDisclosureWithinAccountMetadata","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/companyName":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/companyName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"companyName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","title":"companyName","abstract":[{"text":"Specifies the company name used in the disclosure. The default value is the account name.  However, if your account uses signing brands that specify a company name, you can substitute the brand's company name by setting the `useBrand` property to ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true."}]},{"text":" Whenever an envelope is sent from the account that uses a signing brand with a specified `companyName`, that value is used in email notifications and in the signing experience.  ","type":"text"},{"inlineContent":[{"type":"text","text":"Note:"}],"type":"strong"},{"text":" This substitution only works if you use the default legal disclosure or if you apply the `companyName` to the merge fields in a custom ERSD. You must also set the value of the `useBrand` property to ","type":"text"},{"inlineContent":[{"type":"text","text":"true."}],"type":"strong"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"companyName"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/companyname"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/pdfId":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/pdfId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pdfId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"inlineContent":[{"type":"text","text":"Deprecated."}],"type":"strong"},{"type":"text","text":"   The `pdfId` property in the consumer_disclosure PUT request is deprecated. For security reasons going forward, any value provided in the request packet must be ignored."}],"title":"pdfId","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pdfId"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/pdfid"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"DSAPIConsumerDisclosure","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/accountEsignId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/allowCDWithdraw","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/allowCDWithdrawMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/changeEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/changeEmailOther","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/companyName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/companyPhone","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyCostPerPage","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyFeeCollectionMethod","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/copyRequestEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/custom","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/enableEsign","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/esignAgreement","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/esignText","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/languageCode","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/mustAgreeToEsign","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/pdfId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useBrand","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useConsumerDisclosureWithinAccount","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/useConsumerDisclosureWithinAccountMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawAddressLine1","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawAddressLine2","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByMail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawByPhone","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawCity","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawConsequences","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawOther","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawPhone","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawPostalCode","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/withdrawState"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DSAPIConsumerDisclosure","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"languageCode","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1languageCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1languageCode\/fragments","value":[{"text":"languageCode","kind":"identifier"}]},{"value":"withdrawOther","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawOther\/title","op":"replace"},{"op":"replace","value":[{"text":"withdrawOther","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawOther\/fragments"},{"value":"withdrawPostalCode","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawPostalCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"withdrawPostalCode"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawPostalCode\/fragments"},{"op":"replace","value":"copyCostPerPage","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1copyCostPerPage\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1copyCostPerPage\/fragments","op":"replace","value":[{"kind":"identifier","text":"copyCostPerPage"}]},{"op":"replace","value":"withdrawAddressLine1","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawAddressLine1\/title"},{"op":"replace","value":[{"kind":"identifier","text":"withdrawAddressLine1"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawAddressLine1\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1esignText\/title","op":"replace","value":"esignText"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1esignText\/fragments","value":[{"text":"esignText","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/title","value":"DSAPIConsumerDisclosure","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1changeEmail\/title","op":"replace","value":"changeEmail"},{"value":[{"text":"changeEmail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1changeEmail\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)\/title","value":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1changeEmailOther\/title","op":"replace","value":"changeEmailOther"},{"value":[{"text":"changeEmailOther","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1changeEmailOther\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawState\/title","value":"withdrawState","op":"replace"},{"value":[{"text":"withdrawState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawState\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1useBrand\/title","op":"replace","value":"useBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1useBrand\/fragments","value":[{"text":"useBrand","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawPhone\/title","value":"withdrawPhone","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawPhone\/fragments","value":[{"kind":"identifier","text":"withdrawPhone"}]},{"value":"accountEsignId","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1accountEsignId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1accountEsignId\/fragments","value":[{"text":"accountEsignId","kind":"identifier"}]},{"value":"allowCDWithdrawMetadata","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1allowCDWithdrawMetadata\/title"},{"value":[{"text":"allowCDWithdrawMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1allowCDWithdrawMetadata\/fragments"},{"value":"mustAgreeToEsign","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1mustAgreeToEsign\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1mustAgreeToEsign\/fragments","value":[{"kind":"identifier","text":"mustAgreeToEsign"}]},{"op":"replace","value":"withdrawByMail","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawByMail\/title"},{"value":[{"text":"withdrawByMail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawByMail\/fragments"},{"value":"copyRequestEmail","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1copyRequestEmail\/title"},{"value":[{"kind":"identifier","text":"copyRequestEmail"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1copyRequestEmail\/fragments"},{"value":"useConsumerDisclosureWithinAccount","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1useConsumerDisclosureWithinAccount\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1useConsumerDisclosureWithinAccount\/fragments","op":"replace","value":[{"kind":"identifier","text":"useConsumerDisclosureWithinAccount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1custom\/title","value":"custom"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1custom\/fragments","op":"replace","value":[{"text":"custom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1enableEsign\/title","value":"enableEsign"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1enableEsign\/fragments","value":[{"text":"enableEsign","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawByPhone\/title","value":"withdrawByPhone","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawByPhone\/fragments","value":[{"kind":"identifier","text":"withdrawByPhone"}],"op":"replace"},{"value":"allowCDWithdraw","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1allowCDWithdraw\/title"},{"op":"replace","value":[{"kind":"identifier","text":"allowCDWithdraw"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1allowCDWithdraw\/fragments"},{"value":"esignAgreement","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1esignAgreement\/title","op":"replace"},{"value":[{"text":"esignAgreement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1esignAgreement\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawEmail\/title","op":"replace","value":"withdrawEmail"},{"value":[{"kind":"identifier","text":"withdrawEmail"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawEmail\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawCity\/title","value":"withdrawCity"},{"op":"replace","value":[{"text":"withdrawCity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawCity\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1companyPhone\/title","op":"replace","value":"companyPhone"},{"value":[{"text":"companyPhone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1companyPhone\/fragments","op":"replace"},{"value":"withdrawConsequences","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawConsequences\/title"},{"op":"replace","value":[{"kind":"identifier","text":"withdrawConsequences"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawConsequences\/fragments"},{"value":"withdrawAddressLine2","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawAddressLine2\/title"},{"value":[{"kind":"identifier","text":"withdrawAddressLine2"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawAddressLine2\/fragments"},{"value":"withdrawByEmail","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawByEmail\/title"},{"value":[{"text":"withdrawByEmail","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1withdrawByEmail\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1copyFeeCollectionMethod\/title","value":"copyFeeCollectionMethod"},{"value":[{"kind":"identifier","text":"copyFeeCollectionMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1copyFeeCollectionMethod\/fragments"},{"value":"useConsumerDisclosureWithinAccountMetadata","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1useConsumerDisclosureWithinAccountMetadata\/title"},{"value":[{"kind":"identifier","text":"useConsumerDisclosureWithinAccountMetadata"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1useConsumerDisclosureWithinAccountMetadata\/fragments","op":"replace"},{"value":"companyName","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1companyName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"companyName"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1companyName\/fragments"},{"value":"pdfId","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1pdfId\/title"},{"value":[{"kind":"identifier","text":"pdfId"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1pdfId\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}