{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDocument"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapidocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapidocument"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A document object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDocument"}],"title":"DSAPIDocument","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIDocument","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init(applyAnchorTabs:assignTabsToRecipientId:display:documentBase64:documentFields:documentId:encryptedWithKeyManager:fileExtension:fileFormatHint:htmlDefinition:includeInDownload:matchBoxes:name:order:pages:password:pdfFormFieldOption:remoteUrl:signerMustAcknowledge:signerMustAcknowledgeUseAccountDefault:tabs:templateLocked:templateRequired:transformPdfFields:uri:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/applyAnchorTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/assignTabsToRecipientId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/display","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentBase64","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentFields","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/encryptedWithKeyManager","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileExtension","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileFormatHint","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileSandboxURL","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/htmlDefinition","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/includeInDownload","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/matchBoxes","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/name","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/order","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/pages","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/password","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/pdfFormFieldOption","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/remoteUrl","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/signerMustAcknowledge","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/signerMustAcknowledgeUseAccountDefault","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/tabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/templateLocked","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/templateRequired","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/transformPdfFields","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/uri"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The name of the document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/docusignapi\/dsapidocument\/name"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/assignTabsToRecipientId":{"role":"symbol","title":"assignTabsToRecipientId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"assignTabsToRecipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/assignTabsToRecipientId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"assignTabsToRecipientId"}],"url":"\/documentation\/docusignapi\/dsapidocument\/assigntabstorecipientid"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"/docs/esign-rest-api/reference/cloudstorage/cloudstorage/list/":{"title":"CloudStorage: list","titleInlineContent":[{"type":"text","text":"CloudStorage: list"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/","url":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/uri":{"role":"symbol","title":"uri","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A URI containing the user ID."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/uri","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uri"}],"url":"\/documentation\/docusignapi\/dsapidocument\/uri"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/pages":{"role":"symbol","title":"pages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The number of pages in the document. This property is read-only."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/pages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pages"}],"url":"\/documentation\/docusignapi\/dsapidocument\/pages"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The order in which to sort the results.  Valid values are:    * `asc`: Ascending order. * `desc`: Descending order."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/order","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/docusignapi\/dsapidocument\/order"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/fileExtension":{"role":"symbol","title":"fileExtension","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileExtension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The file extension type of the document. Non-PDF documents are converted to PDF.  If the document is not a PDF, `fileExtension` is required.  If you try to upload a non-PDF document without a `fileExtension`, you will receive an &quot;unable to load document&quot; error message."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileExtension","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileExtension"}],"url":"\/documentation\/docusignapi\/dsapidocument\/fileextension"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/fileSandboxURL":{"role":"symbol","title":"fileSandboxURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSandboxURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileSandboxURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileSandboxURL"}],"url":"\/documentation\/docusignapi\/dsapidocument\/filesandboxurl"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument":{"role":"symbol","title":"DSAPIDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDocument"}],"abstract":[{"type":"text","text":"A document object."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocument"}],"url":"\/documentation\/docusignapi\/dsapidocument"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/transformPdfFields":{"role":"symbol","title":"transformPdfFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformPdfFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" PDF form field data is transformed into document tab values when the PDF form field name matches the DocuSign custom tab tabLabel. The resulting PDF form data is also returned in the PDF meta data when requesting the document PDF."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/transformPdfFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transformPdfFields"}],"url":"\/documentation\/docusignapi\/dsapidocument\/transformpdffields"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/password":{"role":"symbol","title":"password","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user's encrypted password hash."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/password","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"password"}],"url":"\/documentation\/docusignapi\/dsapidocument\/password"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/matchBoxes":{"role":"symbol","title":"matchBoxes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIMatchBox","preciseIdentifier":"s:11DocuSignAPI13DSAPIMatchBoxV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Matchboxes define areas in a document for document matching when you are creating envelopes. They are only used when you upload and edit a template.   A matchbox consists of 5 elements:  * pageNumber - The document page number  on which the matchbox will appear.  * xPosition - The x position of the matchbox on a page.  * yPosition - The y position of the matchbox on a page. * width - The width of the matchbox.  * height - The height of the matchbox."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/matchBoxes","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapidocument\/matchboxes"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/documentBase64":{"role":"symbol","title":"documentBase64","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentBase64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The document's bytes. This field can be used to include a base64 version of the document bytes within an envelope definition instead of sending the document using a multi-part HTTP request. The maximum document size is smaller if this field is used due to the overhead of the base64 encoding."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentBase64","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentBase64"}],"url":"\/documentation\/docusignapi\/dsapidocument\/documentbase64"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/applyAnchorTabs":{"role":"symbol","title":"applyAnchorTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyAnchorTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Reserved for DocuSign."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/applyAnchorTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyAnchorTabs"}],"url":"\/documentation\/docusignapi\/dsapidocument\/applyanchortabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/templateRequired":{"role":"symbol","title":"templateRequired","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the sender may not remove the recipient. Used only when working with template recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/templateRequired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateRequired"}],"url":"\/documentation\/docusignapi\/dsapidocument\/templaterequired"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/remoteUrl":{"role":"symbol","title":"remoteUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The file ID from the cloud storage service where the document is located. This information is returned using "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/remoteUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteUrl"}],"url":"\/documentation\/docusignapi\/dsapidocument\/remoteurl"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/docusignapi\/dsapidocument\/init()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/tabs":{"role":"symbol","title":"tabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/tabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabs"}],"url":"\/documentation\/docusignapi\/dsapidocument\/tabs"},"/docs/esign-rest-api/reference/cloudstorage/cloudstorage/listfolders/":{"title":"CloudStorage: listFolders","titleInlineContent":[{"type":"text","text":"CloudStorage: listFolders"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/","url":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/documentFields":{"role":"symbol","title":"documentFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The array of name\/value custom data strings to be added to a document. Custom document field information is returned in the status, but otherwise is not used by DocuSign. The array contains the elements:   * `name`: A string that can be a maximum of 50 characters.  * `value`: A string that can be a maximum of 200 characters.  If you are using XML, the name\/value pair is contained in a `nameValue` element."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentFields"}],"url":"\/documentation\/docusignapi\/dsapidocument\/documentfields"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/fileFormatHint":{"role":"symbol","title":"fileFormatHint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormatHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileFormatHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileFormatHint"}],"url":"\/documentation\/docusignapi\/dsapidocument\/fileformathint"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/init(applyAnchorTabs:assignTabsToRecipientId:display:documentBase64:documentFields:documentId:encryptedWithKeyManager:fileExtension:fileFormatHint:htmlDefinition:includeInDownload:matchBoxes:name:order:pages:password:pdfFormFieldOption:remoteUrl:signerMustAcknowledge:signerMustAcknowledgeUseAccountDefault:tabs:templateLocked:templateRequired:transformPdfFields:uri:)":{"role":"symbol","title":"init(applyAnchorTabs:assignTabsToRecipientId:display:documentBase64:documentFields:documentId:encryptedWithKeyManager:fileExtension:fileFormatHint:htmlDefinition:includeInDownload:matchBoxes:name:order:pages:password:pdfFormFieldOption:remoteUrl:signerMustAcknowledge:signerMustAcknowledgeUseAccountDefault:tabs:templateLocked:templateRequired:transformPdfFields:uri:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applyAnchorTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"assignTabsToRecipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"display"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"documentBase64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"documentFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"documentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"encryptedWithKeyManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileExtension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormatHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"htmlDefinition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIDocumentHtmlDefinition","preciseIdentifier":"s:11DocuSignAPI27DSAPIDocumentHtmlDefinitionV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeInDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"matchBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIMatchBox","preciseIdentifier":"s:11DocuSignAPI13DSAPIMatchBoxV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pdfFormFieldOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signerMustAcknowledge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signerMustAcknowledgeUseAccountDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"templateLocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformPdfFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init(applyAnchorTabs:assignTabsToRecipientId:display:documentBase64:documentFields:documentId:encryptedWithKeyManager:fileExtension:fileFormatHint:htmlDefinition:includeInDownload:matchBoxes:name:order:pages:password:pdfFormFieldOption:remoteUrl:signerMustAcknowledge:signerMustAcknowledgeUseAccountDefault:tabs:templateLocked:templateRequired:transformPdfFields:uri:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapidocument\/init(applyanchortabs:assigntabstorecipientid:display:documentbase64:documentfields:documentid:encryptedwithkeymanager:fileextension:fileformathint:htmldefinition:includeindownload:matchboxes:name:order:pages:password:pdfformfieldoption:remo-dog6"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/encryptedWithKeyManager":{"role":"symbol","title":"encryptedWithKeyManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptedWithKeyManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the document is been already encrypted by the sender for use with the DocuSign Key Manager Security Appliance."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/encryptedWithKeyManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encryptedWithKeyManager"}],"url":"\/documentation\/docusignapi\/dsapidocument\/encryptedwithkeymanager"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/signerMustAcknowledgeUseAccountDefault":{"role":"symbol","title":"signerMustAcknowledgeUseAccountDefault","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signerMustAcknowledgeUseAccountDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the account default setting for the required recipient option is used. If this property is set, `signerMustAcknowledge` cannot be set (and vice versa)."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/signerMustAcknowledgeUseAccountDefault","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signerMustAcknowledgeUseAccountDefault"}],"url":"\/documentation\/docusignapi\/dsapidocument\/signermustacknowledgeuseaccountdefault"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/display":{"role":"symbol","title":"display","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This string sets the display and behavior properties of the document during signing. Valid values:  * `modal`<br>   The document is shown as a supplement action strip   and can be viewed, downloaded, or printed in a modal window.   This is the recommended value for supplemental documents.   * `inline`<br>   The document is shown in the normal signing window.   This value is not used with supplemental documents,   but is the default value for all other documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/display","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"display"}],"url":"\/documentation\/docusignapi\/dsapidocument\/display"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/includeInDownload":{"role":"symbol","title":"includeInDownload","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeInDownload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the document is included in the combined document download (`documentsCombinedUri`).  The default value is "},{"type":"strong","inlineContent":[{"type":"text","text":"true."}]}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/includeInDownload","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeInDownload"}],"url":"\/documentation\/docusignapi\/dsapidocument\/includeindownload"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/pdfFormFieldOption":{"role":"symbol","title":"pdfFormFieldOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfFormFieldOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/pdfFormFieldOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pdfFormFieldOption"}],"url":"\/documentation\/docusignapi\/dsapidocument\/pdfformfieldoption"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapidocument\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/documentId":{"role":"symbol","title":"documentId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Specifies the document ID of this document. This value is used by tabs to determine which document they appear in."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentId"}],"url":"\/documentation\/docusignapi\/dsapidocument\/documentid"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/templateLocked":{"role":"symbol","title":"templateLocked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateLocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the sender cannot change any attributes of the recipient. Used only when working with template recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/templateLocked","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateLocked"}],"url":"\/documentation\/docusignapi\/dsapidocument\/templatelocked"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/htmlDefinition":{"role":"symbol","title":"htmlDefinition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"htmlDefinition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIDocumentHtmlDefinition","preciseIdentifier":"s:11DocuSignAPI27DSAPIDocumentHtmlDefinitionV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/htmlDefinition","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapidocument\/htmldefinition"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/signerMustAcknowledge":{"role":"symbol","title":"signerMustAcknowledge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signerMustAcknowledge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets how the signer interacts with the supplemental document. Valid values:   * `no_interaction`<br>   No recipient action is required.   * `view`<br>   The recipient is required to view the document.   * `accept`<br>   The recipient is required to accept the document by selecting accept during signing, but is not required to view the document.   * `view_accept`<br>   The recipient is required to view and accept the document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/signerMustAcknowledge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signerMustAcknowledge"}],"url":"\/documentation\/docusignapi\/dsapidocument\/signermustacknowledge"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIDocument"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIDocument"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIDocument"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/applyAnchorTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/assignTabsToRecipientId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/display","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentBase64","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentFields","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/documentId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/encryptedWithKeyManager","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileExtension","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileFormatHint","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/fileSandboxURL","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/includeInDownload","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/name","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/order","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/pages","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/password","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/pdfFormFieldOption","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/remoteUrl","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/signerMustAcknowledge","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/signerMustAcknowledgeUseAccountDefault","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/tabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/templateLocked","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/templateRequired","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/transformPdfFields","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/uri"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDocument"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1assignTabsToRecipientId\/title","value":"assignTabsToRecipientId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1assignTabsToRecipientId\/fragments","value":[{"kind":"identifier","text":"assignTabsToRecipientId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1uri\/title","value":"uri"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1uri\/fragments","value":[{"kind":"identifier","text":"uri"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1pages\/title","value":"pages"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1pages\/fragments","value":[{"kind":"identifier","text":"pages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1order\/title","value":"order"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1order\/fragments","value":[{"kind":"identifier","text":"order"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1fileExtension\/title","value":"fileExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1fileExtension\/fragments","value":[{"kind":"identifier","text":"fileExtension"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1fileSandboxURL\/title","value":"fileSandboxURL"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1fileSandboxURL\/fragments","value":[{"kind":"identifier","text":"fileSandboxURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument\/title","value":"DSAPIDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument\/fragments","value":[{"kind":"identifier","text":"DSAPIDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1transformPdfFields\/title","value":"transformPdfFields"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1transformPdfFields\/fragments","value":[{"kind":"identifier","text":"transformPdfFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1password\/title","value":"password"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1password\/fragments","value":[{"kind":"identifier","text":"password"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1documentBase64\/title","value":"documentBase64"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1documentBase64\/fragments","value":[{"kind":"identifier","text":"documentBase64"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1applyAnchorTabs\/title","value":"applyAnchorTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1applyAnchorTabs\/fragments","value":[{"kind":"identifier","text":"applyAnchorTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1templateRequired\/title","value":"templateRequired"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1templateRequired\/fragments","value":[{"kind":"identifier","text":"templateRequired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1remoteUrl\/title","value":"remoteUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1remoteUrl\/fragments","value":[{"kind":"identifier","text":"remoteUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1tabs\/title","value":"tabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1tabs\/fragments","value":[{"kind":"identifier","text":"tabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1documentFields\/title","value":"documentFields"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1documentFields\/fragments","value":[{"kind":"identifier","text":"documentFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1fileFormatHint\/title","value":"fileFormatHint"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1fileFormatHint\/fragments","value":[{"kind":"identifier","text":"fileFormatHint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1encryptedWithKeyManager\/title","value":"encryptedWithKeyManager"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1encryptedWithKeyManager\/fragments","value":[{"kind":"identifier","text":"encryptedWithKeyManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1signerMustAcknowledgeUseAccountDefault\/title","value":"signerMustAcknowledgeUseAccountDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1signerMustAcknowledgeUseAccountDefault\/fragments","value":[{"kind":"identifier","text":"signerMustAcknowledgeUseAccountDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1display\/title","value":"display"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1display\/fragments","value":[{"kind":"identifier","text":"display"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1includeInDownload\/title","value":"includeInDownload"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1includeInDownload\/fragments","value":[{"kind":"identifier","text":"includeInDownload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1pdfFormFieldOption\/title","value":"pdfFormFieldOption"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1pdfFormFieldOption\/fragments","value":[{"kind":"identifier","text":"pdfFormFieldOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1documentId\/title","value":"documentId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1documentId\/fragments","value":[{"kind":"identifier","text":"documentId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1templateLocked\/title","value":"templateLocked"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1templateLocked\/fragments","value":[{"kind":"identifier","text":"templateLocked"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1signerMustAcknowledge\/title","value":"signerMustAcknowledge"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1signerMustAcknowledge\/fragments","value":[{"kind":"identifier","text":"signerMustAcknowledge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}