{"metadata":{"modules":[{"name":"DocuSignAPI"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignatureDefinition","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIUserSignatureDefinition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"role":"symbol","title":"DSAPIUserSignatureDefinition","roleHeading":"Class"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/dateStampProperties","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/disallowUserResizeStamp","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/externalID","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/imageType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/isDefault","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/nrdsId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/nrdsLastName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/phoneticName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureFont","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureInitials","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/stampFormat","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/stampSizeMM"]}],"kind":"symbol","variants":[{"paths":["\/documentation\/docusignapi\/dsapiusersignaturedefinition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiusersignaturedefinition"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/signatureFont":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/signaturefont","abstract":[{"text":"The font type to use for the signature if the signature is not drawn. The following font styles  are supported. The quotes are to indicate that these values are strings, not `enums`.  - `&quot;1_DocuSign&quot;` - `&quot;2_DocuSign&quot;` - `&quot;3_DocuSign&quot;` - `&quot;4_DocuSign&quot;` - `&quot;5_DocuSign&quot;` - `&quot;6_DocuSign&quot;` - `&quot;7_DocuSign&quot;` - `&quot;8_DocuSign&quot;` - `&quot;Mistral&quot;` - `&quot;Rage Italic&quot;`","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"signatureFont","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureFont","navigatorTitle":[{"kind":"identifier","text":"signatureFont"}],"role":"symbol","title":"signatureFont"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/signatureInitials":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/signatureinitials","abstract":[{"type":"text","text":"Specifies the user's signature in initials format."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signatureInitials"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureInitials","navigatorTitle":[{"text":"signatureInitials","kind":"identifier"}],"role":"symbol","title":"signatureInitials"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/imageType":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/imagetype","abstract":[{"text":"Specificies the type of image. Valid values are:  - `signature_image` - `initials_image`","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/imageType","navigatorTitle":[{"kind":"identifier","text":"imageType"}],"role":"symbol","title":"imageType"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","title":"Swift.Encodable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition":{"role":"symbol","navigatorTitle":[{"text":"DSAPIUserSignatureDefinition","kind":"identifier"}],"kind":"symbol","title":"DSAPIUserSignatureDefinition","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIUserSignatureDefinition"}]},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","title":"Swift.Hashable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/stampSizeMM":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/stampsizemm","abstract":[{"type":"text","text":"The physical height of the stamp image (in millimeters) that the stamp vendor recommends for displaying the image in PDF documents."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stampSizeMM"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/stampSizeMM","navigatorTitle":[{"text":"stampSizeMM","kind":"identifier"}],"role":"symbol","title":"stampSizeMM"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/disallowUserResizeStamp":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/disallowuserresizestamp","abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"type":"text","text":" users may not resize the stamp."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"disallowUserResizeStamp","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/disallowUserResizeStamp","navigatorTitle":[{"text":"disallowUserResizeStamp","kind":"identifier"}],"role":"symbol","title":"disallowUserResizeStamp"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/dateStampProperties":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/datestampproperties","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateStampProperties"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","text":"DSAPIDateStampProperties","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/dateStampProperties","navigatorTitle":[{"text":"dateStampProperties","kind":"identifier"}],"role":"symbol","title":"dateStampProperties"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/isDefault":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/isdefault","abstract":[{"type":"text","text":"Boolean that specifies whether the signature is the default signature for the user."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isDefault","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/isDefault","navigatorTitle":[{"kind":"identifier","text":"isDefault"}],"role":"symbol","title":"isDefault"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/signatureType":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/signaturetype","abstract":[{"text":"Specifies the type of signature.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signatureType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureType","navigatorTitle":[{"text":"signatureType","kind":"identifier"}],"role":"symbol","title":"signatureType"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/phoneticName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"phoneticName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/phoneticname","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/phoneticName","type":"topic","role":"symbol","title":"phoneticName","navigatorTitle":[{"text":"phoneticName","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The phonetic spelling of the `signatureName`.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/init(from:)":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(from:)","role":"symbol","title":"init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/signatureId":{"role":"symbol","navigatorTitle":[{"text":"signatureId","kind":"identifier"}],"kind":"symbol","title":"signatureId","type":"topic","abstract":[{"type":"text","text":"Specifies the signature ID associated with the signature name. You can use the signature ID in the URI in place of the signature name, and the value stored in the `signatureName` property in the body is used. This allows the use of special characters (such as &quot;&&quot;, &quot;<&quot;, &quot;>&quot;) in a the signature name. Note that with each update to signatures, the returned signature ID might change, so the caller will need to trigger off the signature name to get the new signature ID."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureId","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/signatureid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signatureId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/init(datestampproperties:disallowuserresizestamp:externalid:imagetype:isdefault:nrdsid:nrdslastname:phoneticname:signaturefont:signatureid:signatureinitials:signaturename:signaturetype:stampformat:stampsizemm:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"dateStampProperties"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","text":"DSAPIDateStampProperties","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"disallowUserResizeStamp","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"externalID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"imageType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"isDefault","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nrdsId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nrdsLastName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"phoneticName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signatureInitials","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"signatureType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)","navigatorTitle":[{"text":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:","kind":"identifier"}],"role":"symbol","title":"init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/nrdsLastName":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/nrdslastname","abstract":[{"type":"text","text":"The realtor's last name."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nrdsLastName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/nrdsLastName","navigatorTitle":[{"kind":"identifier","text":"nrdsLastName"}],"role":"symbol","title":"nrdsLastName"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/externalID":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/externalid","abstract":[{"type":"text","text":"Optionally specify an external identifier for the user's signature."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/externalID","navigatorTitle":[{"text":"externalID","kind":"identifier"}],"role":"symbol","title":"externalID"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/signatureName":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/signaturename","abstract":[{"type":"text","text":"Specifies the user's signature name."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"signatureName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureName","navigatorTitle":[{"text":"signatureName","kind":"identifier"}],"role":"symbol","title":"signatureName"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject","title":"NSObject"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/stampFormat":{"title":"stampFormat","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stampFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"The format of a stamp. Valid values are:  - `NameHanko`: The stamp represents only the signer's name. - `NameDateHanko`: The stamp represents the signer's name and the date.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/stampFormat","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/stampformat","navigatorTitle":[{"kind":"identifier","text":"stampFormat"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignatureDefinition/nrdsId":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiusersignaturedefinition\/nrdsid","abstract":[{"text":"The National Association of Realtors (NAR) membership ID for a user who is a realtor.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nrdsId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/nrdsId","navigatorTitle":[{"kind":"identifier","text":"nrdsId"}],"role":"symbol","title":"nrdsId"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DSAPIUserSignatureDefinition","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"DSAPIUserSignatureDefinition","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DSAPIUserSignatureDefinition","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/dateStampProperties","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/disallowUserResizeStamp","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/externalID","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/imageType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/isDefault","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/nrdsId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/nrdsLastName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/phoneticName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureFont","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureInitials","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/signatureType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/stampFormat","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/stampSizeMM"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignatureDefinition\/init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignatureDefinition"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"signatureFont","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureFont\/title","op":"replace"},{"value":[{"text":"signatureFont","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureFont\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureInitials\/title","value":"signatureInitials"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureInitials\/fragments","value":[{"text":"signatureInitials","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1imageType\/title","op":"replace","value":"imageType"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1imageType\/fragments","value":[{"text":"imageType","kind":"identifier"}]},{"value":"DSAPIUserSignatureDefinition","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition\/fragments","value":[{"text":"DSAPIUserSignatureDefinition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1stampSizeMM\/title","value":"stampSizeMM","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1stampSizeMM\/fragments","value":[{"kind":"identifier","text":"stampSizeMM"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1disallowUserResizeStamp\/title","value":"disallowUserResizeStamp","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1disallowUserResizeStamp\/fragments","value":[{"kind":"identifier","text":"disallowUserResizeStamp"}],"op":"replace"},{"value":"dateStampProperties","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1dateStampProperties\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1dateStampProperties\/fragments","value":[{"kind":"identifier","text":"dateStampProperties"}]},{"value":"isDefault","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1isDefault\/title"},{"value":[{"kind":"identifier","text":"isDefault"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1isDefault\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureType\/title","op":"replace","value":"signatureType"},{"op":"replace","value":[{"kind":"identifier","text":"signatureType"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureType\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1phoneticName\/title","value":"phoneticName","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1phoneticName\/fragments","op":"replace","value":[{"text":"phoneticName","kind":"identifier"}]},{"value":"signatureId","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureId\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureId\/fragments","value":[{"text":"signatureId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)\/title","op":"replace","value":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1init(dateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDateStampProperties:disallowUserResizeStamp:externalID:imageType:isDefault:nrdsId:nrdsLastName:phoneticName:signatureFont:signatureId:signatureInitials:signatureName:signatureType:stampFormat:stampSizeMM:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1nrdsLastName\/title","op":"replace","value":"nrdsLastName"},{"value":[{"kind":"identifier","text":"nrdsLastName"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1nrdsLastName\/fragments"},{"value":"externalID","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1externalID\/title"},{"value":[{"kind":"identifier","text":"externalID"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1externalID\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureName\/title","value":"signatureName"},{"value":[{"text":"signatureName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1signatureName\/fragments","op":"replace"},{"value":"stampFormat","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1stampFormat\/title"},{"value":[{"text":"stampFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1stampFormat\/fragments"},{"value":"nrdsId","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1nrdsId\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignatureDefinition~1nrdsId\/fragments","op":"replace","value":[{"text":"nrdsId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}