{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIViewUrl"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiviewurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiviewurl"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/init(from:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/init(url:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/url"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIViewUrl"}],"title":"DSAPIViewUrl","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIViewUrl"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"URL to the Review ID page."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/url","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/docusignapi\/dsapiviewurl\/url"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl":{"role":"symbol","title":"DSAPIViewUrl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIViewUrl"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIViewUrl"}],"url":"\/documentation\/docusignapi\/dsapiviewurl"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiviewurl\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl/init(url:)":{"role":"symbol","title":"init(url:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/init(url:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUrl:"}],"url":"\/documentation\/docusignapi\/dsapiviewurl\/init(url:)"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIViewUrl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIViewUrl"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIViewUrl"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl\/init(url:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIViewUrl"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/title","value":"DSAPIViewUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/fragments","value":[{"kind":"identifier","text":"DSAPIViewUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl~1init(url:)\/title","value":"initWithUrl:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl~1init(url:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUrl:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}