{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"title":"DSAPIUserSignaturesInformation","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Class","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(from:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(userSignatures:)"]},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/userSignatures"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIUserSignaturesInformation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiusersignaturesinformation"]},{"paths":["\/documentation\/docusignapi\/dsapiusersignaturesinformation"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/Se":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation/userSignatures":{"url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation\/usersignatures","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userSignatures"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","text":"DSAPIUserSignature"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"userSignatures","kind":"identifier"}],"abstract":[{"type":"text","text":"An array of  `userSignature` objects."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/userSignatures","title":"userSignatures"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation/init(from:)":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation\/init(from:)","role":"symbol","title":"init(from:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.DocuSign.DocuSIgnAPI/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation/init(userSignatures:)":{"url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation\/init(usersignatures:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userSignatures"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"text":"]?)","kind":"text"}],"title":"init(userSignatures:)","navigatorTitle":[{"text":"initWithUserSignatures:","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(userSignatures:)","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIUserSignaturesInformation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation","type":"topic","role":"symbol","title":"DSAPIUserSignaturesInformation"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DSAPIUserSignaturesInformation","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DSAPIUserSignaturesInformation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/userSignatures"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(userSignatures:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignaturesInformation"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"userSignatures","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation~1userSignatures\/title"},{"op":"replace","value":[{"text":"userSignatures","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation~1userSignatures\/fragments"},{"value":"initWithUserSignatures:","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation~1init(userSignatures:)\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation~1init(userSignatures:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithUserSignatures:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation\/title","value":"DSAPIUserSignaturesInformation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation\/fragments","value":[{"text":"DSAPIUserSignaturesInformation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}