{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"type":"conformsTo"}],"metadata":{"symbolKind":"class","roleHeading":"Class","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPINameValue"}],"title":"DSAPINameValue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPINameValue","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue","role":"symbol"},"abstract":[{"text":"A name-value pair that describes an item and provides a value for the item.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPINameValue","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init(errorDetails:name:originalValue:value:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/name","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/originalValue","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/value"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapinamevalue"]},{"paths":["\/documentation\/docusignapi\/dsapinamevalue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/init(errorDetails:name:originalValue:value:)":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapinamevalue\/init(errordetails:name:originalvalue:value:)","navigatorTitle":[{"kind":"identifier","text":"initWithErrorDetails:name:originalValue:value:"}],"title":"init(errorDetails:name:originalValue:value:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init(errorDetails:name:originalValue:value:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"originalValue"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/originalValue":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapinamevalue\/originalvalue","navigatorTitle":[{"kind":"identifier","text":"originalValue"}],"title":"originalValue","type":"topic","abstract":[{"type":"text","text":"The initial value of the item."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/originalValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/init(from:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"title":"init(from:)","type":"topic","url":"\/documentation\/docusignapi\/dsapinamevalue\/init(from:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/init()":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init()","abstract":[],"title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapinamevalue\/init()","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/value":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/value","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"value","abstract":[{"type":"text","text":"The current value of the item."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapinamevalue\/value"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/name":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/name","title":"name","url":"\/documentation\/docusignapi\/dsapinamevalue\/name","abstract":[{"text":"The name of the item.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"name","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue":{"role":"symbol","abstract":[{"text":"A name-value pair that describes an item and provides a value for the item.","type":"text"}],"kind":"symbol","title":"DSAPINameValue","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue","url":"\/documentation\/docusignapi\/dsapinamevalue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPINameValue","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DSAPINameValue","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINameValue/errorDetails":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapinamevalue\/errordetails","navigatorTitle":[{"kind":"identifier","text":"errorDetails"}],"title":"errorDetails","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/errorDetails","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDetails"},{"text":": ","kind":"text"},{"text":"DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DSAPINameValue","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DSAPINameValue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPINameValue"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/name","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/originalValue","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINameValue\/init(errorDetails:name:originalValue:value:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DSAPINameValue","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1init(errorDetails:name:originalValue:value:)\/title","value":"initWithErrorDetails:name:originalValue:value:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithErrorDetails:name:originalValue:value:"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1init(errorDetails:name:originalValue:value:)\/fragments"},{"value":"originalValue","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1originalValue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"originalValue"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1originalValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1init()\/title","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1value\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue\/title","value":"DSAPINameValue"},{"value":[{"kind":"identifier","text":"DSAPINameValue"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue\/fragments","op":"replace"},{"value":"errorDetails","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1errorDetails\/title","op":"replace"},{"value":[{"text":"errorDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINameValue~1errorDetails\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}