{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiexpirations"]},{"paths":["\/documentation\/docusignapi\/dsapiexpirations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init(expireAfter:expireEnabled:expireWarn:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init(from:)"]},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireAfter","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireEnabled","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireWarn"],"title":"Instance Properties"}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DSAPIExpirations"}],"title":"DSAPIExpirations","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIExpirations"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","role":"symbol"},"abstract":[{"text":"A complex element that specifies the expiration settings for the envelope. When an envelope expires, it is voided and no longer available for signing. ","type":"text"},{"type":"strong","inlineContent":[{"text":"Note:","type":"text"}]},{"type":"text","text":" there is a short delay between when the envelope expires and when it is voided."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIExpirations"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations/expireWarn":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"expireWarn"}],"abstract":[{"text":"An integer that specifying the number of days before the envelope expires that an expiration warning email is sent to the recipient. When 0 (zero), no warning email is sent.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireWarn","title":"expireWarn","url":"\/documentation\/docusignapi\/dsapiexpirations\/expirewarn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expireWarn","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations":{"type":"topic","role":"symbol","abstract":[{"text":"A complex element that specifies the expiration settings for the envelope. When an envelope expires, it is voided and no longer available for signing. ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" there is a short delay between when the envelope expires and when it is voided."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIExpirations"}],"title":"DSAPIExpirations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIExpirations","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiexpirations","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations/init()":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiexpirations\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject","title":"NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations/init(from:)":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiexpirations\/init(from:)","title":"init(from:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations/init(expireAfter:expireEnabled:expireWarn:)":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiexpirations\/init(expireafter:expireenabled:expirewarn:)","navigatorTitle":[{"text":"initWithExpireAfter:expireEnabled:expireWarn:","kind":"identifier"}],"title":"init(expireAfter:expireEnabled:expireWarn:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init(expireAfter:expireEnabled:expireWarn:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"expireAfter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"expireEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expireWarn"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations/expireAfter":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiexpirations\/expireafter","navigatorTitle":[{"kind":"identifier","text":"expireAfter"}],"title":"expireAfter","type":"topic","abstract":[{"text":"An integer that sets the number of days the envelope is active. For this value to be used, `expireEnabled` must be explicitly set to ","type":"text"},{"inlineContent":[{"type":"text","text":"true."}],"type":"strong"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireAfter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expireAfter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"https://support.docusign.com/en/guides/ndse-admin-guide-reminders-and-expirations":{"type":"link","title":"default expiration account setting","identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-admin-guide-reminders-and-expirations","titleInlineContent":[{"type":"text","text":"default expiration account setting"}],"url":"https:\/\/support.docusign.com\/en\/guides\/ndse-admin-guide-reminders-and-expirations"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations/expireEnabled":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiexpirations\/expireenabled","navigatorTitle":[{"text":"expireEnabled","kind":"identifier"}],"title":"expireEnabled","type":"topic","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"type":"text","text":" the envelope expires in the number of days set by `expireAfter`. When "},{"inlineContent":[{"type":"text","text":"false"}],"type":"strong"},{"text":" or not set, the envelope expires in the number of days specified by the ","type":"text"},{"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-admin-guide-reminders-and-expirations","type":"reference","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expireEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DSAPIExpirations","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIExpirations"}]},{"value":[{"text":"DSAPIExpirations","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireAfter","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireEnabled","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/expireWarn"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations\/init(expireAfter:expireEnabled:expireWarn:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIExpirations","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"expireWarn","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1expireWarn\/title"},{"value":[{"kind":"identifier","text":"expireWarn"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1expireWarn\/fragments"},{"value":"DSAPIExpirations","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/fragments","value":[{"text":"DSAPIExpirations","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1init()\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1init(expireAfter:expireEnabled:expireWarn:)\/title","value":"initWithExpireAfter:expireEnabled:expireWarn:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1init(expireAfter:expireEnabled:expireWarn:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithExpireAfter:expireEnabled:expireWarn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1expireAfter\/title","value":"expireAfter"},{"value":[{"text":"expireAfter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1expireAfter\/fragments","op":"replace"},{"value":"expireEnabled","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1expireEnabled\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations~1expireEnabled\/fragments","value":[{"text":"expireEnabled","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}