{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipientviewrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The request body for the "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},{"type":"text","text":" methods."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"title":"DSAPIRecipientViewRequest","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init(assertionId:authenticationInstant:authenticationMethod:clientURLs:clientUserId:email:frameAncestors:messageOrigins:pingFrequency:pingUrl:recipientId:returnUrl:securityDomain:userId:userName:xFrameOptions:xFrameOptionsAllowFromUrl:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/assertionId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationInstant","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationMethod","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/clientURLs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/clientUserId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/email","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/frameAncestors","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/messageOrigins","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/pingFrequency","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/pingUrl","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/recipientId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/returnUrl","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/securityDomain","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/userId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/userName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/xFrameOptions","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/xFrameOptionsAllowFromUrl"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/authenticationMethod":{"role":"symbol","title":"authenticationMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Required. Choose a value that most closely matches the technique your application used to authenticate the recipient \/ signer.   Choose a value from this list:  * Biometric  * Email * HTTPBasicAuth * Kerberos * KnowledgeBasedAuth * None * PaperDocuments * Password * RSASecureID * SingleSignOn_CASiteminder * SingleSignOn_InfoCard * SingleSignOn_MicrosoftActiveDirectory * SingleSignOn_Other * SingleSignOn_Passport * SingleSignOn_SAML * Smartcard * SSLMutualAuth * X509Certificate  This information is included in the Certificate of Completion."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationMethod"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/authenticationmethod"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/":{"title":"EnvelopeViews: createRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createRecipient"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/recipientId":{"role":"symbol","title":"recipientId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/recipientId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recipientId"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/recipientid"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/clientUserId":{"role":"symbol","title":"clientUserId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A sender-created value. If provided, the recipient is treated as an embedded (captive) recipient or signer.  Use your application's client ID (user ID) for the recipient. Doing so enables the details of your application's authentication of the recipient to be connected to the recipient's signature if the signature is disputed or repudiated.  Maximum length: 100 characters."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/clientUserId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientUserId"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/clientuserid"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsharedrecipient/":{"title":"EnvelopeViews: createSharedRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createSharedRecipient"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/init(assertionId:authenticationInstant:authenticationMethod:clientURLs:clientUserId:email:frameAncestors:messageOrigins:pingFrequency:pingUrl:recipientId:returnUrl:securityDomain:userId:userName:xFrameOptions:xFrameOptionsAllowFromUrl:)":{"role":"symbol","title":"init(assertionId:authenticationInstant:authenticationMethod:clientURLs:clientUserId:email:frameAncestors:messageOrigins:pingFrequency:pingUrl:recipientId:returnUrl:securityDomain:userId:userName:xFrameOptions:xFrameOptionsAllowFromUrl:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"assertionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"authenticationInstant"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"authenticationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientURLs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientTokenClientURLs","preciseIdentifier":"s:11DocuSignAPI29DSAPIRecipientTokenClientURLsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"frameAncestors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"messageOrigins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"pingFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pingUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"returnUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"securityDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"xFrameOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"xFrameOptionsAllowFromUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init(assertionId:authenticationInstant:authenticationMethod:clientURLs:clientUserId:email:frameAncestors:messageOrigins:pingFrequency:pingUrl:recipientId:returnUrl:securityDomain:userId:userName:xFrameOptions:xFrameOptionsAllowFromUrl:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/init(assertionid:authenticationinstant:authenticationmethod:clienturls:clientuserid:email:frameancestors:messageorigins:pingfrequency:pingurl:recipientid:returnurl:securitydomain:userid:username:xframeoptions:xframeoptionsallowfromurl:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/pingUrl":{"role":"symbol","title":"pingUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pingUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The client URL that the DocuSign Signing experience should ping to indicate to the client that Signing is active. An HTTP GET call is executed against the client. The response from the client is ignored. The intent is for the client to reset its session timer when the request is received."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/pingUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pingUrl"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/pingurl"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/pingFrequency":{"role":"symbol","title":"pingFrequency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pingFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Only used if `pingUrl` is specified. This is the interval, in seconds, between pings on the `pingUrl`.  The default is `300` seconds. Valid values are 60-1200 seconds."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/pingFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pingFrequency"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/pingfrequency"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/returnUrl":{"role":"symbol","title":"returnUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"(Required) The URL to which the user should be redirected after the signing session has ended.  Maximum Length: 470 characters. If the `returnUrl` exceeds this limit, the user is redirected to a truncated URL Be sure to include `https:\/\/` in the URL or redirecting might fail on some browsers.   When DocuSign redirects to this URL, it will include an `event` query parameter that your app can use:  * `access_code_failed`: Recipient used incorrect access code. * `cancel`: Recipient canceled the signing operation,   possibly by using the "},{"type":"strong","inlineContent":[{"type":"text","text":"Finish Later"}]},{"type":"text","text":" option. * `decline`: Recipient declined to sign. * `exception`: A system error occurred during the signing process. * `fax_pending`: Recipient has a fax pending. * `id_check_failed`: Recipient failed an ID check. * `session_timeout`: The session timed out. An account can control this timeout by using the "},{"type":"strong","inlineContent":[{"type":"text","text":"Signer Session Timeout"}]},{"type":"text","text":" option. * `signing_complete`: The recipient completed the signing ceremony. * `ttl_expired`: The Time To Live token for the envelope has expired.   After being successfully invoked, these tokens expire   after 5 minutes or if the envelope is voided. * `viewing_complete`: The recipient completed viewing an envelope   that is in a read-only\/terminal state,   such as completed, declined, or voided."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/returnUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"returnUrl"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/returnurl"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/xFrameOptions":{"role":"symbol","title":"xFrameOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"xFrameOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Specifies whether a browser should be allowed to render a page in a frame or IFrame. Setting this property ensures that your content is not embedded into unauthorized pages or frames.  Valid values are:  - `deny`: The page cannot be displayed in a frame. - `same_origin`: The page can only be displayed in a frame on the same origin as the page itself. - `allow_from`: The page can only be displayed in a frame on the origin specified by the `xFrameOptionsAllowFromUrl` property."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/xFrameOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"xFrameOptions"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/xframeoptions"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/securityDomain":{"role":"symbol","title":"securityDomain","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"securityDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The domain in which the user authenticated."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/securityDomain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"securityDomain"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/securitydomain"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/userName":{"role":"symbol","title":"userName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The username of the recipient. You can use either `email` and `userName` or `userId` to identify the recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/userName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userName"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/username"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/userId":{"role":"symbol","title":"userId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user ID of the recipient. You can use either the user ID or email and user name to identify the recipient.   If `userId` is used and a `clientUserId` is provided, the value in the `userId` property must match a `recipientId` (which you can retrieve with a GET recipients call) for the envelope.   If a `userId` is used and a `clientUserId` is not provided, the `userId` must match the user ID of the authenticating user."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/userId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userId"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/userid"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/xFrameOptionsAllowFromUrl":{"role":"symbol","title":"xFrameOptionsAllowFromUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"xFrameOptionsAllowFromUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"When the value of `xFrameOptions` is `allow_from`, this property specifies the origin on which the page is allowed to display in a frame. If the value of `xFrameOptions` is `allow_from`, you must include a value for this property."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/xFrameOptionsAllowFromUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"xFrameOptionsAllowFromUrl"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/xframeoptionsallowfromurl"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/assertionId":{"role":"symbol","title":"assertionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"assertionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A unique identifier of the authentication event executed by the client application."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/assertionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"assertionId"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/assertionid"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/authenticationInstant":{"role":"symbol","title":"authenticationInstant","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationInstant"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A sender-generated value that indicates the date and time that the signer was authenticated."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationInstant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationInstant"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/authenticationinstant"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/clientURLs":{"role":"symbol","title":"clientURLs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientURLs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientTokenClientURLs","preciseIdentifier":"s:11DocuSignAPI29DSAPIRecipientTokenClientURLsV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/clientURLs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/clienturls"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/messageOrigins":{"role":"symbol","title":"messageOrigins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageOrigins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/messageOrigins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageOrigins"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/messageorigins"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/init()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest":{"role":"symbol","title":"DSAPIRecipientViewRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"abstract":[{"type":"text","text":"The request body for the "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},{"type":"text","text":" methods."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/frameAncestors":{"role":"symbol","title":"frameAncestors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameAncestors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/frameAncestors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameAncestors"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/frameancestors"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"(Required) Specifies the email of the recipient. You can use either `email` and `userName` or `userId` to identify the recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/email","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"email"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest\/email"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIRecipientViewRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/assertionId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationInstant","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/authenticationMethod","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/clientUserId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/email","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/frameAncestors","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/messageOrigins","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/pingFrequency","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/pingUrl","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/recipientId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/returnUrl","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/securityDomain","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/userId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/userName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/xFrameOptions","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/xFrameOptionsAllowFromUrl"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientViewRequest"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1authenticationMethod\/title","value":"authenticationMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1authenticationMethod\/fragments","value":[{"kind":"identifier","text":"authenticationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1recipientId\/title","value":"recipientId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1recipientId\/fragments","value":[{"kind":"identifier","text":"recipientId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1clientUserId\/title","value":"clientUserId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1clientUserId\/fragments","value":[{"kind":"identifier","text":"clientUserId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1pingUrl\/title","value":"pingUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1pingUrl\/fragments","value":[{"kind":"identifier","text":"pingUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1pingFrequency\/title","value":"pingFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1pingFrequency\/fragments","value":[{"kind":"identifier","text":"pingFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1returnUrl\/title","value":"returnUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1returnUrl\/fragments","value":[{"kind":"identifier","text":"returnUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1xFrameOptions\/title","value":"xFrameOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1xFrameOptions\/fragments","value":[{"kind":"identifier","text":"xFrameOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1securityDomain\/title","value":"securityDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1securityDomain\/fragments","value":[{"kind":"identifier","text":"securityDomain"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1userName\/title","value":"userName"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1userName\/fragments","value":[{"kind":"identifier","text":"userName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1userId\/title","value":"userId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1userId\/fragments","value":[{"kind":"identifier","text":"userId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1xFrameOptionsAllowFromUrl\/title","value":"xFrameOptionsAllowFromUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1xFrameOptionsAllowFromUrl\/fragments","value":[{"kind":"identifier","text":"xFrameOptionsAllowFromUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1assertionId\/title","value":"assertionId"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1assertionId\/fragments","value":[{"kind":"identifier","text":"assertionId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1authenticationInstant\/title","value":"authenticationInstant"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1authenticationInstant\/fragments","value":[{"kind":"identifier","text":"authenticationInstant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1messageOrigins\/title","value":"messageOrigins"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1messageOrigins\/fragments","value":[{"kind":"identifier","text":"messageOrigins"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/title","value":"DSAPIRecipientViewRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1frameAncestors\/title","value":"frameAncestors"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1frameAncestors\/fragments","value":[{"kind":"identifier","text":"frameAncestors"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1email\/title","value":"email"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest~1email\/fragments","value":[{"kind":"identifier","text":"email"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}