{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Describes which account management capabilities a user has."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}],"title":"DSAPIUserAccountManagementGranularInformation","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserAccountManagementGranularInformation","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSecuritySettings","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSecuritySettingsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSettings","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSettingsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAdmins","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAdminsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageConnect","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageConnectMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageDocumentRetention","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageDocumentRetentionMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageEnvelopeTransfer","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageEnvelopeTransferMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsers","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsersMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageReporting","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageReportingMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharing","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharingMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSigningGroups","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSigningGroupsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageUsers","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageUsersMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canViewUsers"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageGroupsButNotUsersMetadata":{"role":"symbol","title":"canManageGroupsButNotUsersMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageGroupsButNotUsersMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsersMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageGroupsButNotUsersMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagegroupsbutnotusersmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageAdmins":{"role":"symbol","title":"canManageAdmins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAdmins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage administrators."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAdmins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageAdmins"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageadmins"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageDocumentRetention":{"role":"symbol","title":"canManageDocumentRetention","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageDocumentRetention"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageDocumentRetention","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageDocumentRetention"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagedocumentretention"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageAccountSecuritySettings":{"role":"symbol","title":"canManageAccountSecuritySettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAccountSecuritySettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage account security settings."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSecuritySettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageAccountSecuritySettings"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageaccountsecuritysettings"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canViewUsers":{"role":"symbol","title":"canViewUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canViewUsers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canViewUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canViewUsers"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canviewusers"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageConnect":{"role":"symbol","title":"canManageConnect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageConnect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageConnect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageConnect"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageconnect"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageAccountSettings":{"role":"symbol","title":"canManageAccountSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAccountSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage account settings."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageAccountSettings"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageaccountsettings"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageAccountSecuritySettingsMetadata":{"role":"symbol","title":"canManageAccountSecuritySettingsMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAccountSecuritySettingsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSecuritySettingsMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageAccountSecuritySettingsMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageaccountsecuritysettingsmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageSigningGroups":{"role":"symbol","title":"canManageSigningGroups","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageSigningGroups"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage signing groups."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSigningGroups","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageSigningGroups"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesigninggroups"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation":{"role":"symbol","title":"DSAPIUserAccountManagementGranularInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}],"abstract":[{"type":"text","text":"Describes which account management capabilities a user has."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageConnectMetadata":{"role":"symbol","title":"canManageConnectMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageConnectMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageConnectMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageConnectMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageconnectmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageUsers":{"role":"symbol","title":"canManageUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageUsers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage users."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageUsers"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageusers"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageAccountSettingsMetadata":{"role":"symbol","title":"canManageAccountSettingsMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAccountSettingsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSettingsMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageAccountSettingsMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageaccountsettingsmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageSharing":{"role":"symbol","title":"canManageSharing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageSharing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage sharing."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageSharing"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesharing"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageGroupsButNotUsers":{"role":"symbol","title":"canManageGroupsButNotUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageGroupsButNotUsers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageGroupsButNotUsers"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagegroupsbutnotusers"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageAdminsMetadata":{"role":"symbol","title":"canManageAdminsMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageAdminsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAdminsMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageAdminsMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageadminsmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageEnvelopeTransfer":{"role":"symbol","title":"canManageEnvelopeTransfer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageEnvelopeTransfer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageEnvelopeTransfer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageEnvelopeTransfer"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageenvelopetransfer"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageEnvelopeTransferMetadata":{"role":"symbol","title":"canManageEnvelopeTransferMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageEnvelopeTransferMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageEnvelopeTransferMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageEnvelopeTransferMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageenvelopetransfermetadata"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageSigningGroupsMetadata":{"role":"symbol","title":"canManageSigningGroupsMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageSigningGroupsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSigningGroupsMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageSigningGroupsMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesigninggroupsmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageSharingMetadata":{"role":"symbol","title":"canManageSharingMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageSharingMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharingMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageSharingMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagesharingmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageUsersMetadata":{"role":"symbol","title":"canManageUsersMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageUsersMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageUsersMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageUsersMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanageusersmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageReporting":{"role":"symbol","title":"canManageReporting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageReporting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"True"}]},{"type":"text","text":" if the user can manage reporting."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageReporting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageReporting"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagereporting"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageReportingMetadata":{"role":"symbol","title":"canManageReportingMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageReportingMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageReportingMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageReportingMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagereportingmetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)":{"role":"symbol","title":"init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"canManageAccountSecuritySettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageAccountSecuritySettingsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageAccountSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageAccountSettingsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageAdmins"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageAdminsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageConnect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageConnectMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageDocumentRetention"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageDocumentRetentionMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageEnvelopeTransfer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageEnvelopeTransferMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageGroupsButNotUsers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageGroupsButNotUsersMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageReporting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageReportingMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSharing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSharingMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSigningGroups"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageSigningGroupsMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageUsers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canManageUsersMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canViewUsers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/init(canmanageaccountsecuritysettings:canmanageaccountsecuritysettingsmetadata:canmanageaccountsettings:canmanageaccountsettingsmetadata:canmanageadmins:canmanageadminsmetadata:canmanageconnect:canmanageconnectmetadata:canmanagedocumentrete-56knj"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserAccountManagementGranularInformation/canManageDocumentRetentionMetadata":{"role":"symbol","title":"canManageDocumentRetentionMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canManageDocumentRetentionMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageDocumentRetentionMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canManageDocumentRetentionMetadata"}],"url":"\/documentation\/docusignapi\/dsapiuseraccountmanagementgranularinformation\/canmanagedocumentretentionmetadata"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIUserAccountManagementGranularInformation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSecuritySettings","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSecuritySettingsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSettings","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAccountSettingsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAdmins","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageAdminsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageConnect","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageConnectMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageDocumentRetention","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageDocumentRetentionMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageEnvelopeTransfer","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageEnvelopeTransferMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsers","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageGroupsButNotUsersMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageReporting","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageReportingMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharing","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSharingMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSigningGroups","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageSigningGroupsMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageUsers","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canManageUsersMetadata","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/canViewUsers"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserAccountManagementGranularInformation\/init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageGroupsButNotUsersMetadata\/title","value":"canManageGroupsButNotUsersMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageGroupsButNotUsersMetadata\/fragments","value":[{"kind":"identifier","text":"canManageGroupsButNotUsersMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAdmins\/title","value":"canManageAdmins"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAdmins\/fragments","value":[{"kind":"identifier","text":"canManageAdmins"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageDocumentRetention\/title","value":"canManageDocumentRetention"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageDocumentRetention\/fragments","value":[{"kind":"identifier","text":"canManageDocumentRetention"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSecuritySettings\/title","value":"canManageAccountSecuritySettings"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSecuritySettings\/fragments","value":[{"kind":"identifier","text":"canManageAccountSecuritySettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canViewUsers\/title","value":"canViewUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canViewUsers\/fragments","value":[{"kind":"identifier","text":"canViewUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageConnect\/title","value":"canManageConnect"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageConnect\/fragments","value":[{"kind":"identifier","text":"canManageConnect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSettings\/title","value":"canManageAccountSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSettings\/fragments","value":[{"kind":"identifier","text":"canManageAccountSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSecuritySettingsMetadata\/title","value":"canManageAccountSecuritySettingsMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSecuritySettingsMetadata\/fragments","value":[{"kind":"identifier","text":"canManageAccountSecuritySettingsMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSigningGroups\/title","value":"canManageSigningGroups"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSigningGroups\/fragments","value":[{"kind":"identifier","text":"canManageSigningGroups"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/title","value":"DSAPIUserAccountManagementGranularInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation\/fragments","value":[{"kind":"identifier","text":"DSAPIUserAccountManagementGranularInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageConnectMetadata\/title","value":"canManageConnectMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageConnectMetadata\/fragments","value":[{"kind":"identifier","text":"canManageConnectMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageUsers\/title","value":"canManageUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageUsers\/fragments","value":[{"kind":"identifier","text":"canManageUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSettingsMetadata\/title","value":"canManageAccountSettingsMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAccountSettingsMetadata\/fragments","value":[{"kind":"identifier","text":"canManageAccountSettingsMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSharing\/title","value":"canManageSharing"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSharing\/fragments","value":[{"kind":"identifier","text":"canManageSharing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageGroupsButNotUsers\/title","value":"canManageGroupsButNotUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageGroupsButNotUsers\/fragments","value":[{"kind":"identifier","text":"canManageGroupsButNotUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAdminsMetadata\/title","value":"canManageAdminsMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageAdminsMetadata\/fragments","value":[{"kind":"identifier","text":"canManageAdminsMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageEnvelopeTransfer\/title","value":"canManageEnvelopeTransfer"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageEnvelopeTransfer\/fragments","value":[{"kind":"identifier","text":"canManageEnvelopeTransfer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageEnvelopeTransferMetadata\/title","value":"canManageEnvelopeTransferMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageEnvelopeTransferMetadata\/fragments","value":[{"kind":"identifier","text":"canManageEnvelopeTransferMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSigningGroupsMetadata\/title","value":"canManageSigningGroupsMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSigningGroupsMetadata\/fragments","value":[{"kind":"identifier","text":"canManageSigningGroupsMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSharingMetadata\/title","value":"canManageSharingMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageSharingMetadata\/fragments","value":[{"kind":"identifier","text":"canManageSharingMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageUsersMetadata\/title","value":"canManageUsersMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageUsersMetadata\/fragments","value":[{"kind":"identifier","text":"canManageUsersMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageReporting\/title","value":"canManageReporting"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageReporting\/fragments","value":[{"kind":"identifier","text":"canManageReporting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageReportingMetadata\/title","value":"canManageReportingMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageReportingMetadata\/fragments","value":[{"kind":"identifier","text":"canManageReportingMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)\/title","value":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1init(canManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCanManageAccountSecuritySettings:canManageAccountSecuritySettingsMetadata:canManageAccountSettings:canManageAccountSettingsMetadata:canManageAdmins:canManageAdminsMetadata:canManageConnect:canManageConnectMetadata:canManageDocumentRetention:canManageDocumentRetentionMetadata:canManageEnvelopeTransfer:canManageEnvelopeTransferMetadata:canManageGroupsButNotUsers:canManageGroupsButNotUsersMetadata:canManageReporting:canManageReportingMetadata:canManageSharing:canManageSharingMetadata:canManageSigningGroups:canManageSigningGroupsMetadata:canManageUsers:canManageUsersMetadata:canViewUsers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageDocumentRetentionMetadata\/title","value":"canManageDocumentRetentionMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserAccountManagementGranularInformation~1canManageDocumentRetentionMetadata\/fragments","value":[{"kind":"identifier","text":"canManageDocumentRetentionMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}