{"kind":"symbol","metadata":{"symbolKind":"class","title":"DSAPIStamp","modules":[{"name":"DocuSignAPI"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIStamp","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIStamp"}],"navigatorTitle":[{"text":"DSAPIStamp","kind":"identifier"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/adoptedDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/createdDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/customField","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/dateStampProperties","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/disallowUserResizeStamp","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/externalID","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/imageBase64","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/imageType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/lastModifiedDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/phoneticName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/signatureName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampFormat","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampImageUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampSizeMM","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/status"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIStamp","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapistamp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapistamp"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/customField":{"navigatorTitle":[{"text":"customField","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/customfield","role":"symbol","abstract":[],"title":"customField","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/customField","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customField"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/errorDetails":{"navigatorTitle":[{"text":"errorDetails","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/errordetails","role":"symbol","abstract":[],"title":"errorDetails","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/errorDetails","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDetails","kind":"identifier"},{"kind":"text","text":": "},{"text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","title":"Swift.Equatable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/imageBase64":{"type":"topic","url":"\/documentation\/docusignapi\/dsapistamp\/imagebase64","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageBase64","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/imageBase64","navigatorTitle":[{"text":"imageBase64","kind":"identifier"}],"role":"symbol","title":"imageBase64"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","title":"Swift.Encodable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/stampSizeMM":{"navigatorTitle":[{"text":"stampSizeMM","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/stampsizemm","role":"symbol","abstract":[{"type":"text","text":"The physical height of the stamp image (in millimeters) that the stamp vendor recommends for displaying the image in PDF documents."}],"title":"stampSizeMM","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampSizeMM","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stampSizeMM","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/lastModifiedDateTime":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/lastModifiedDateTime","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastModifiedDateTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapistamp\/lastmodifieddatetime","title":"lastModifiedDateTime","kind":"symbol","abstract":[{"type":"text","text":"The date and time that the item was last modified."}],"navigatorTitle":[{"text":"lastModifiedDateTime","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/status":{"navigatorTitle":[{"text":"status","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/status","role":"symbol","abstract":[{"text":"Indicates the envelope status. Valid values are:  * sent - The envelope is sent to the recipients.  * created - The envelope is saved as a draft and can be modified and sent later.","type":"text"}],"title":"status","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/status","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/init(from:)":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/init(from:)","url":"\/documentation\/docusignapi\/dsapistamp\/init(from:)","title":"init(from:)","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","title":"Swift.Hashable"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/adoptedDateTime":{"navigatorTitle":[{"text":"adoptedDateTime","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/adopteddatetime","role":"symbol","abstract":[{"type":"text","text":"The UTC date and time when the user adopted the signature."}],"title":"adoptedDateTime","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/adoptedDateTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adoptedDateTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/stampFormat":{"navigatorTitle":[{"text":"stampFormat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/stampformat","role":"symbol","abstract":[{"text":"The format of a stamp. Valid values are:  - `NameHanko`: The stamp represents only the signer's name. - `NameDateHanko`: The stamp represents the signer's name and the date.","type":"text"}],"title":"stampFormat","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampFormat","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stampFormat","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/phoneticName":{"navigatorTitle":[{"text":"phoneticName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/phoneticname","role":"symbol","abstract":[{"type":"text","text":"The phonetic spelling of the `signatureName`."}],"title":"phoneticName","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/phoneticName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"phoneticName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp":{"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp","url":"\/documentation\/docusignapi\/dsapistamp","title":"DSAPIStamp","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIStamp","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIStamp"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/stampImageUri":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampImageUri","kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/stampimageuri","abstract":[{"type":"text","text":"The URI for retrieving the image of the user's stamp."}],"title":"stampImageUri","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stampImageUri","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stampImageUri"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/createdDateTime":{"navigatorTitle":[{"text":"createdDateTime","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/createddatetime","role":"symbol","abstract":[{"text":"The UTC DateTime when the item was created.","type":"text"}],"title":"createdDateTime","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/createdDateTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"createdDateTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/dateStampProperties":{"navigatorTitle":[{"text":"dateStampProperties","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/datestampproperties","role":"symbol","abstract":[],"title":"dateStampProperties","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/dateStampProperties","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateStampProperties"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/disallowUserResizeStamp":{"navigatorTitle":[{"text":"disallowUserResizeStamp","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/disallowuserresizestamp","role":"symbol","abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"type":"text","text":" users may not resize the stamp."}],"title":"disallowUserResizeStamp","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/disallowUserResizeStamp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disallowUserResizeStamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)":{"navigatorTitle":[{"text":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/init(adopteddatetime:createddatetime:customfield:datestampproperties:disallowuserresizestamp:errordetails:externalid:imagebase64:imagetype:lastmodifieddatetime:phoneticname:signaturename:stampformat:stampimageuri:stampsizemm:status:)","role":"symbol","abstract":[],"title":"init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adoptedDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"createdDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"customField","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"dateStampProperties"},{"text":": ","kind":"text"},{"text":"DSAPIDateStampProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"text":"?, ","kind":"text"},{"text":"disallowUserResizeStamp","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"externalID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageBase64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"imageType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"lastModifiedDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"phoneticName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"stampFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"stampImageUri","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"text":"stampSizeMM","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","title":"Swift.Decodable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/externalID":{"navigatorTitle":[{"text":"externalID","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/externalid","role":"symbol","abstract":[{"type":"text","text":"Optionally specify an external identifier for the user's signature."}],"title":"externalID","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/externalID","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/signatureName":{"type":"topic","url":"\/documentation\/docusignapi\/dsapistamp\/signaturename","abstract":[{"type":"text","text":"Specifies the user's signature name."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signatureName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/signatureName","navigatorTitle":[{"text":"signatureName","kind":"identifier"}],"role":"symbol","title":"signatureName"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIStamp/imageType":{"navigatorTitle":[{"text":"imageType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapistamp\/imagetype","role":"symbol","abstract":[{"text":"Specificies the type of image. Valid values are:  - `signature_image` - `initials_image`","type":"text"}],"title":"imageType","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/imageType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DSAPIStamp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIStamp"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DSAPIStamp","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/adoptedDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/createdDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/customField","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/dateStampProperties","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/disallowUserResizeStamp","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/externalID","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/imageBase64","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/imageType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/lastModifiedDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/phoneticName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/signatureName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampFormat","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampImageUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/stampSizeMM","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/status"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIStamp\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIStamp","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"customField","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1customField\/title","op":"replace"},{"value":[{"text":"customField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1customField\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1errorDetails\/title","op":"replace","value":"errorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1errorDetails\/fragments","value":[{"kind":"identifier","text":"errorDetails"}]},{"value":"imageBase64","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1imageBase64\/title"},{"op":"replace","value":[{"text":"imageBase64","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1imageBase64\/fragments"},{"value":"stampSizeMM","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1stampSizeMM\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1stampSizeMM\/fragments","op":"replace","value":[{"text":"stampSizeMM","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1lastModifiedDateTime\/title","value":"lastModifiedDateTime","op":"replace"},{"value":[{"kind":"identifier","text":"lastModifiedDateTime"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1lastModifiedDateTime\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1status\/title","op":"replace","value":"status"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1status\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1adoptedDateTime\/title","op":"replace","value":"adoptedDateTime"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1adoptedDateTime\/fragments","value":[{"text":"adoptedDateTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1stampFormat\/title","value":"stampFormat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1stampFormat\/fragments","value":[{"kind":"identifier","text":"stampFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1phoneticName\/title","value":"phoneticName"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1phoneticName\/fragments","value":[{"text":"phoneticName","kind":"identifier"}],"op":"replace"},{"value":"DSAPIStamp","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp\/title"},{"value":[{"text":"DSAPIStamp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1stampImageUri\/title","op":"replace","value":"stampImageUri"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1stampImageUri\/fragments","value":[{"kind":"identifier","text":"stampImageUri"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1createdDateTime\/title","op":"replace","value":"createdDateTime"},{"value":[{"text":"createdDateTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1createdDateTime\/fragments"},{"value":"dateStampProperties","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1dateStampProperties\/title"},{"value":[{"text":"dateStampProperties","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1dateStampProperties\/fragments"},{"op":"replace","value":"disallowUserResizeStamp","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1disallowUserResizeStamp\/title"},{"value":[{"kind":"identifier","text":"disallowUserResizeStamp"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1disallowUserResizeStamp\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)\/title","value":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAdoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:lastModifiedDateTime:phoneticName:signatureName:stampFormat:stampImageUri:stampSizeMM:status:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1externalID\/title","value":"externalID"},{"value":[{"kind":"identifier","text":"externalID"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1externalID\/fragments","op":"replace"},{"value":"signatureName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1signatureName\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1signatureName\/fragments","value":[{"kind":"identifier","text":"signatureName"}],"op":"replace"},{"value":"imageType","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1imageType\/title","op":"replace"},{"op":"replace","value":[{"text":"imageType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIStamp~1imageType\/fragments"}]}]}