{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiofflineattributes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiofflineattributes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes"},"metadata":{"modules":[{"name":"DocuSignAPI"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"role":"symbol","title":"DSAPIOfflineAttributes","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}]},"topicSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/accountEsignId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/deviceModel","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/deviceName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/gpsLatitude","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/gpsLongitude","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/offlineSigningHash"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Reserved for DocuSign use.","type":"text"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/offlineSigningHash":{"url":"\/documentation\/docusignapi\/dsapiofflineattributes\/offlinesigninghash","navigatorTitle":[{"kind":"identifier","text":"offlineSigningHash"}],"kind":"symbol","title":"offlineSigningHash","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/offlineSigningHash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offlineSigningHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"A signing hash used for offline signing.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/init(from:)":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiofflineattributes\/init(from:)","title":"init(from:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/deviceName":{"navigatorTitle":[{"kind":"identifier","text":"deviceName"}],"url":"\/documentation\/docusignapi\/dsapiofflineattributes\/devicename","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"A string containing information about the type of device used for offline signing.","type":"text"}],"title":"deviceName","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/deviceName","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/accountEsignId":{"url":"\/documentation\/docusignapi\/dsapiofflineattributes\/accountesignid","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/accountEsignId","abstract":[{"text":"The GUID of the account associated with the consumer disclosure.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"accountEsignId","kind":"identifier"}],"title":"accountEsignId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accountEsignId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/deviceModel":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/deviceModel","abstract":[{"type":"text","text":"A string containing information about the model of the device used for offline signing."}],"title":"deviceModel","navigatorTitle":[{"kind":"identifier","text":"deviceModel"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"deviceModel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapiofflineattributes\/devicemodel","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/gpsLongitude":{"url":"\/documentation\/docusignapi\/dsapiofflineattributes\/gpslongitude","navigatorTitle":[{"kind":"identifier","text":"gpsLongitude"}],"kind":"symbol","title":"gpsLongitude","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/gpsLongitude","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gpsLongitude"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"A string containing the longitude of the device location at the time of signing.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/gpsLatitude":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/gpsLatitude","title":"gpsLatitude","url":"\/documentation\/docusignapi\/dsapiofflineattributes\/gpslatitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gpsLatitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"A string containing the latitude of the device location at the time of signing."}],"role":"symbol","navigatorTitle":[{"text":"gpsLatitude","kind":"identifier"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes":{"abstract":[{"type":"text","text":"Reserved for DocuSign use."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIOfflineAttributes","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiofflineattributes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes","role":"symbol","title":"DSAPIOfflineAttributes","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)":{"navigatorTitle":[{"text":"initWithAccountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)","url":"\/documentation\/docusignapi\/dsapiofflineattributes\/init(accountesignid:devicemodel:devicename:gpslatitude:gpslongitude:offlinesigninghash:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountEsignId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"deviceModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"deviceName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"gpsLatitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"gpsLongitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offlineSigningHash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","title":"init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/init()":{"url":"\/documentation\/docusignapi\/dsapiofflineattributes\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init()","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"DSAPIOfflineAttributes","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/accountEsignId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/deviceModel","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/deviceName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/gpsLatitude","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/gpsLongitude","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/offlineSigningHash"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)"]}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIOfflineAttributes"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1offlineSigningHash\/title","value":"offlineSigningHash","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1offlineSigningHash\/fragments","op":"replace","value":[{"text":"offlineSigningHash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1deviceName\/title","op":"replace","value":"deviceName"},{"op":"replace","value":[{"kind":"identifier","text":"deviceName"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1deviceName\/fragments"},{"op":"replace","value":"accountEsignId","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1accountEsignId\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1accountEsignId\/fragments","value":[{"text":"accountEsignId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1deviceModel\/title","op":"replace","value":"deviceModel"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1deviceModel\/fragments","value":[{"kind":"identifier","text":"deviceModel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1gpsLongitude\/title","value":"gpsLongitude"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1gpsLongitude\/fragments","op":"replace","value":[{"kind":"identifier","text":"gpsLongitude"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1gpsLatitude\/title","value":"gpsLatitude","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1gpsLatitude\/fragments","value":[{"text":"gpsLatitude","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/title","value":"DSAPIOfflineAttributes"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/fragments","op":"replace","value":[{"text":"DSAPIOfflineAttributes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)\/title","op":"replace","value":"initWithAccountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1init(accountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAccountEsignId:deviceModel:deviceName:gpsLatitude:gpsLongitude:offlineSigningHash:","kind":"identifier"}],"op":"replace"},{"value":"init","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1init()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}