{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapidatestampproperties"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapidatestampproperties"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.  This property contains the following information about the central rectangle:  - `DateAreaX`: The X axis position of the top-left corner. - `DateAreaY`: The Y axis position of the top-left corner. - `DateAreaWidth`: The width of the rectangle. - `DateAreaHeight`: The height of the rectangle."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"}],"title":"DSAPIDateStampProperties","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIDateStampProperties"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaHeight","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaWidth","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaX","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaY"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties":{"role":"symbol","title":"DSAPIDateStampProperties","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"}],"abstract":[{"type":"text","text":"Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.  This property contains the following information about the central rectangle:  - `DateAreaX`: The X axis position of the top-left corner. - `DateAreaY`: The Y axis position of the top-left corner. - `DateAreaWidth`: The width of the rectangle. - `DateAreaHeight`: The height of the rectangle."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDateStampProperties"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties/dateAreaY":{"role":"symbol","title":"dateAreaY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateAreaY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The Y axis position of the top-left corner."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateAreaY"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties\/dateareay"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties/dateAreaWidth":{"role":"symbol","title":"dateAreaWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateAreaWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The width of the rectangle."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateAreaWidth"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties\/dateareawidth"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties/dateAreaX":{"role":"symbol","title":"dateAreaX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateAreaX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The X axis position of the top-left corner."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateAreaX"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties\/dateareax"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapidatestampproperties\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties/dateAreaHeight":{"role":"symbol","title":"dateAreaHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateAreaHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The height of the rectangle."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateAreaHeight"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties\/dateareaheight"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties/init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)":{"role":"symbol","title":"init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dateAreaHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateAreaWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateAreaX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateAreaY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties\/init(dateareaheight:dateareawidth:dateareax:dateareay:)"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIDateStampProperties"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIDateStampProperties"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIDateStampProperties"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaHeight","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaWidth","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaX","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/dateAreaY"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties\/init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/title","value":"DSAPIDateStampProperties"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/fragments","value":[{"kind":"identifier","text":"DSAPIDateStampProperties"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaY\/title","value":"dateAreaY"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaY\/fragments","value":[{"kind":"identifier","text":"dateAreaY"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaWidth\/title","value":"dateAreaWidth"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaWidth\/fragments","value":[{"kind":"identifier","text":"dateAreaWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaX\/title","value":"dateAreaX"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaX\/fragments","value":[{"kind":"identifier","text":"dateAreaX"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaHeight\/title","value":"dateAreaHeight"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1dateAreaHeight\/fragments","value":[{"kind":"identifier","text":"dateAreaHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)\/title","value":"initWithDateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties~1init(dateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDateAreaHeight:dateAreaWidth:dateAreaX:dateAreaY:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}