{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation"},"topicSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init(activationAccessCode:company:connectConfigurations:countryCode:createdDateTime:customSettings:defaultAccountId:email:enableConnectForUser:errorDetails:firstName:forgottenPasswordInfo:groupList:hasRemoteNotary:homeAddress:initialsImageUri:isAdmin:isNAREnabled:jobTitle:lastLogin:lastName:loginStatus:middleName:password:passwordExpiration:permissionProfileId:permissionProfileName:profileImageUri:sendActivationEmail:sendActivationOnInvalidLogin:signatureImageUri:subscribe:suffixName:title:uri:userAddedToAccountDateTime:userId:userName:userProfileLastModifiedDate:userSettings:userStatus:userType:workAddress:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/activationAccessCode","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/company","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/connectConfigurations","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/countryCode","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/createdDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/customSettings","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/defaultAccountId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/email","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/enableConnectForUser","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/firstName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/forgottenPasswordInfo","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/groupList","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/hasRemoteNotary","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/homeAddress","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/initialsImageUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/isAdmin","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/isNAREnabled","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/jobTitle","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/lastLogin","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/lastName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/loginStatus","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/middleName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/password","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/passwordExpiration","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/permissionProfileId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/permissionProfileName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/profileImageUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/sendActivationEmail","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/sendActivationOnInvalidLogin","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/signatureImageUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/subscribe","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/suffixName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/title","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/uri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userAddedToAccountDateTime","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userId","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userName","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userProfileLastModifiedDate","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userSettings","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userStatus","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userType","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/workAddress"]}],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiuserinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiuserinformation"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInformation"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"User information.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"DSAPIUserInformation","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Class","title":"DSAPIUserInformation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIUserInformation","kind":"identifier"}],"symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/password":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The user's encrypted password hash."}],"title":"password","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/password","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"password"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/password","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/hasRemoteNotary":{"type":"topic","role":"symbol","abstract":[],"title":"hasRemoteNotary","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/hasRemoteNotary","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasRemoteNotary","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/hasremotenotary","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userStatus":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userStatus","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"userStatus","abstract":[{"type":"text","text":"Status of the user's account. One of:  - `ActivationRequired` - `ActivationSent` - `Active` - `Closed` - `Disabled`"}],"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/userstatus"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userType":{"type":"topic","role":"symbol","abstract":[{"text":"The type of user, for example `CompanyUser`.","type":"text"}],"title":"userType","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/usertype","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userAddedToAccountDateTime":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinformation\/useraddedtoaccountdatetime","abstract":[{"text":"The date and time that the user was added to the account.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userAddedToAccountDateTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userAddedToAccountDateTime","role":"symbol","title":"userAddedToAccountDateTime"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/subscribe":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/subscribe","role":"symbol","title":"subscribe","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/subscribe","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"/docs/esign-rest-api/reference/accounts/accountpermissionprofiles/list/":{"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountpermissionprofiles\/list\/","title":"AccountPermissionProfiles: list","titleInlineContent":[{"text":"AccountPermissionProfiles: list","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/accounts\/accountpermissionprofiles\/list\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/init()":{"type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinformation\/init()","title":"init()","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/defaultAccountId":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/defaultaccountid","role":"symbol","abstract":[{"type":"text","text":"The default account ID associated with the user."}],"title":"defaultAccountId","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/defaultAccountId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultAccountId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/homeAddress":{"type":"topic","role":"symbol","abstract":[],"title":"homeAddress","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/homeAddress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"homeAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIAddressInformation","preciseIdentifier":"s:11DocuSignAPI23DSAPIAddressInformationV"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/homeaddress","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/isNAREnabled":{"role":"symbol","type":"topic","abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"type":"text","text":" National Association of Realtors (NAR) signature logos are enabled for the user."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNAREnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/isnarenabled","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/isNAREnabled","title":"isNAREnabled"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/permissionProfileId":{"type":"topic","role":"symbol","abstract":[{"text":"The ID of the permission profile.  Use ","type":"text"},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountpermissionprofiles\/list\/"},{"text":" to get a list of permission profiles and their IDs.  You can also download a CSV file of all permission profiles and their IDs from the ","type":"text"},{"type":"strong","inlineContent":[{"text":"Settings > Permission Profiles","type":"text"}]},{"text":" page of your eSignature account page.","type":"text"}],"title":"permissionProfileId","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/permissionProfileId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionProfileId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/permissionprofileid","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/passwordExpiration":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/passwordExpiration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passwordExpiration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"passwordExpiration","abstract":[{"type":"text","text":"If password expiration is enabled, the date-time when the user's password expires."}],"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/passwordexpiration"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/title":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The title of the user."}],"title":"title","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/title","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/title","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/permissionProfileName":{"type":"topic","role":"symbol","abstract":[{"text":"The name of the account permission profile.   Example: `Account Administrator`","type":"text"}],"title":"permissionProfileName","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/permissionProfileName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionProfileName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/permissionprofilename","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/signatureImageUri":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"signatureImageUri","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/signatureImageUri","abstract":[{"text":"An endpoint URI that you can use to retrieve the user's signature image.","type":"text"}],"title":"signatureImageUri","role":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/signatureimageuri","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/customSettings":{"url":"\/documentation\/docusignapi\/dsapiuserinformation\/customsettings","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customSettings","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPINameValue","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"kind":"text","text":"]?"}],"title":"customSettings","abstract":[{"type":"text","text":"The name\/value pair information for the user custom setting."}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/customSettings","kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/activationAccessCode":{"kind":"symbol","type":"topic","title":"activationAccessCode","abstract":[{"text":"Access code provided to the user to activate the account.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"activationAccessCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/activationaccesscode","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/activationAccessCode"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/profileImageUri":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The URL for retrieving the user's profile image."}],"title":"profileImageUri","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/profileImageUri","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileImageUri"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/profileimageuri","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/workAddress":{"type":"topic","role":"symbol","abstract":[],"title":"workAddress","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/workAddress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"workAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIAddressInformationV","kind":"typeIdentifier","text":"DSAPIAddressInformation"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/workaddress","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/suffixName":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/suffixName","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"suffixName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"suffixName","url":"\/documentation\/docusignapi\/dsapiuserinformation\/suffixname","abstract":[{"type":"text","text":"The suffix for the user's name, such as Jr, IV, PhD, etc.  Limit: 50 characters."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userSettings":{"type":"topic","role":"symbol","abstract":[],"title":"userSettings","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userSettings","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userSettings"},{"kind":"text","text":": "},{"text":"DSAPIUserSettingsInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSettingsInformation"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/usersettings","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/createdDateTime":{"type":"topic","role":"symbol","abstract":[{"text":"The UTC DateTime when the item was created.","type":"text"}],"title":"createdDateTime","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/createdDateTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdDateTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/createddatetime","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/connectConfigurations":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Object representing the user's custom Connect configuration."}],"title":"connectConfigurations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/connectConfigurations","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectConfigurations"},{"kind":"text","text":": ["},{"text":"DSAPIConnectUserObject","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI22DSAPIConnectUserObjectV"},{"text":"]?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/connectconfigurations","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"/docs/admin-api/how-to/create-active-user/":{"identifier":"\/docs\/admin-api\/how-to\/create-active-user\/","title":"these steps","titleInlineContent":[{"text":"these steps","type":"text"}],"url":"\/docs\/admin-api\/how-to\/create-active-user\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/company":{"type":"topic","role":"symbol","abstract":[{"text":"The name of the user's company.","type":"text"}],"title":"company","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/company","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"company"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/company","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/isAdmin":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Determines if the feature set is actively set as part of the plan."}],"title":"isAdmin","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/isAdmin","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAdmin"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/isadmin","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userId":{"kind":"symbol","title":"userId","type":"topic","abstract":[{"type":"text","text":"The ID of the user to access.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Users can only access their own information. A user, even one with Admin rights, cannot access another user's settings."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/userid","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userId"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/middleName":{"type":"topic","role":"symbol","abstract":[{"text":"The user's middle name.  Limit: 50 characters.","type":"text"}],"title":"middleName","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/middleName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"middleName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/middlename","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/countryCode":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The three-letter code for the user's country."}],"title":"countryCode","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/countryCode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/countrycode","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/init(from:)":{"title":"init(from:)","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init(from:)","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/jobTitle":{"type":"topic","role":"symbol","abstract":[{"text":"The user's job title.","type":"text"}],"title":"jobTitle","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/jobTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jobTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/jobtitle","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/loginStatus":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Boolean value that indicates whether the user is currently logged in or not."}],"title":"loginStatus","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/loginStatus","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginStatus"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/loginstatus","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/sendActivationEmail":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/sendActivationEmail","abstract":[{"text":"This field is no longer supported for most accounts. To create an eSignature user without sending an activation email, use the Admin API by following ","type":"text"},{"identifier":"\/docs\/admin-api\/how-to\/create-active-user\/","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinformation\/sendactivationemail","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendActivationEmail"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"sendActivationEmail","kind":"symbol"},"/docs/esign-rest-api/reference/usergroups/groups/list/":{"identifier":"\/docs\/esign-rest-api\/reference\/usergroups\/groups\/list\/","type":"link","titleInlineContent":[{"text":"UserGroups: listGroups","type":"text"}],"title":"UserGroups: listGroups","url":"\/docs\/esign-rest-api\/reference\/usergroups\/groups\/list\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/init(activationAccessCode:company:connectConfigurations:countryCode:createdDateTime:customSettings:defaultAccountId:email:enableConnectForUser:errorDetails:firstName:forgottenPasswordInfo:groupList:hasRemoteNotary:homeAddress:initialsImageUri:isAdmin:isNAREnabled:jobTitle:lastLogin:lastName:loginStatus:middleName:password:passwordExpiration:permissionProfileId:permissionProfileName:profileImageUri:sendActivationEmail:sendActivationOnInvalidLogin:signatureImageUri:subscribe:suffixName:title:uri:userAddedToAccountDateTime:userId:userName:userProfileLastModifiedDate:userSettings:userStatus:userType:workAddress:)":{"type":"topic","role":"symbol","abstract":[],"title":"init(activationAccessCode:company:connectConfigurations:countryCode:createdDateTime:customSettings:defaultAccountId:email:enableConnectForUser:errorDetails:firstName:forgottenPasswordInfo:groupList:hasRemoteNotary:homeAddress:initialsImageUri:isAdmin:isNAREnabled:jobTitle:lastLogin:lastName:loginStatus:middleName:password:passwordExpiration:permissionProfileId:permissionProfileName:profileImageUri:sendActivationEmail:sendActivationOnInvalidLogin:signatureImageUri:subscribe:suffixName:title:uri:userAddedToAccountDateTime:userId:userName:userProfileLastModifiedDate:userSettings:userStatus:userType:workAddress:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init(activationAccessCode:company:connectConfigurations:countryCode:createdDateTime:customSettings:defaultAccountId:email:enableConnectForUser:errorDetails:firstName:forgottenPasswordInfo:groupList:hasRemoteNotary:homeAddress:initialsImageUri:isAdmin:isNAREnabled:jobTitle:lastLogin:lastName:loginStatus:middleName:password:passwordExpiration:permissionProfileId:permissionProfileName:profileImageUri:sendActivationEmail:sendActivationOnInvalidLogin:signatureImageUri:subscribe:suffixName:title:uri:userAddedToAccountDateTime:userId:userName:userProfileLastModifiedDate:userSettings:userStatus:userType:workAddress:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"activationAccessCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"company"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"connectConfigurations","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11DocuSignAPI22DSAPIConnectUserObjectV","kind":"typeIdentifier","text":"DSAPIConnectUserObject"},{"text":"]?, ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"createdDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"text":"customSettings","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPINameValue","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINameValue"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"defaultAccountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"email","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"enableConnectForUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"text":"DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"firstName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"forgottenPasswordInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI33DSAPIForgottenPasswordInformationV","text":"DSAPIForgottenPasswordInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"groupList"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11DocuSignAPI10DSAPIGroupV","text":"DSAPIGroup","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"hasRemoteNotary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"homeAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIAddressInformationV","text":"DSAPIAddressInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"initialsImageUri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"isNAREnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"jobTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"lastLogin","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"lastName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"loginStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"middleName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"password"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"passwordExpiration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"permissionProfileId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"permissionProfileName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"profileImageUri"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sendActivationEmail"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"sendActivationOnInvalidLogin","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signatureImageUri"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"subscribe","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"suffixName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"uri","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"userAddedToAccountDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"userName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"userProfileLastModifiedDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"userSettings"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSettingsInformation","text":"DSAPIUserSettingsInformation"},{"text":"?, ","kind":"text"},{"text":"userStatus","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"workAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIAddressInformationV","text":"DSAPIAddressInformation","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/init(activationaccesscode:company:connectconfigurations:countrycode:createddatetime:customsettings:defaultaccountid:email:enableconnectforuser:errordetails:firstname:forgottenpasswordinfo:grouplist:hasremotenotary:homeaddress:initialsimageu-4yo2u","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/initialsImageUri":{"url":"\/documentation\/docusignapi\/dsapiuserinformation\/initialsimageuri","kind":"symbol","title":"initialsImageUri","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/initialsImageUri","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialsImageUri","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The URI for retrieving the image of the user's initials."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/firstName":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The user's first name.  Maximum Length: 50 characters."}],"title":"firstName","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/firstName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/firstname","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userProfileLastModifiedDate":{"type":"topic","role":"symbol","abstract":[{"text":"The date and time that the user's profile was last modified.","type":"text"}],"title":"userProfileLastModifiedDate","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userProfileLastModifiedDate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userProfileLastModifiedDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/userprofilelastmodifieddate","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/userName":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/username","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/userName","abstract":[{"text":"The name of the user.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"userName","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/lastName":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The user's last name.  Maximum Length: 50 characters."}],"title":"lastName","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/lastName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/lastname","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/enableConnectForUser":{"type":"topic","role":"symbol","abstract":[{"text":"Boolean value that specifies whether the user is enabled for updates from DocuSign Connect.","type":"text"}],"title":"enableConnectForUser","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/enableConnectForUser","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableConnectForUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/enableconnectforuser","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/groupList":{"url":"\/documentation\/docusignapi\/dsapiuserinformation\/grouplist","kind":"symbol","title":"groupList","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/groupList","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIGroup","preciseIdentifier":"s:11DocuSignAPI10DSAPIGroupV"},{"text":"]?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"A list of the group information for groups to add the user to. Use "},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/usergroups\/groups\/list\/","isActive":true},{"type":"text","text":" to get information about groups.  When setting a user's group, only the `groupId` is required."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/forgottenPasswordInfo":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/forgottenpasswordinfo","kind":"symbol","title":"forgottenPasswordInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/forgottenPasswordInfo","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"forgottenPasswordInfo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIForgottenPasswordInformation","preciseIdentifier":"s:11DocuSignAPI33DSAPIForgottenPasswordInformationV"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/email":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"email","abstract":[{"type":"text","text":"The user's email address."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/email","url":"\/documentation\/docusignapi\/dsapiuserinformation\/email"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/errorDetails":{"url":"\/documentation\/docusignapi\/dsapiuserinformation\/errordetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDetails","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[],"title":"errorDetails","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/errorDetails","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/uri":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A URI containing the user ID."}],"title":"uri","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/uri","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uri","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/uri","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/lastLogin":{"type":"topic","role":"symbol","abstract":[{"text":"The date and time when the user last logged in to the system.","type":"text"}],"title":"lastLogin","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/lastLogin","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lastLogin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapiuserinformation\/lastlogin","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIUserInformation","kind":"identifier"}],"type":"topic","title":"DSAPIUserInformation","abstract":[{"type":"text","text":"User information."}],"url":"\/documentation\/docusignapi\/dsapiuserinformation","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInformation"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","title":"Swift.Decodable"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","title":"Swift.Encodable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation/sendActivationOnInvalidLogin":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiuserinformation\/sendactivationoninvalidlogin","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/sendActivationOnInvalidLogin","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" specifies that an additional activation email be sent if user's log on fails before the account is activated.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendActivationOnInvalidLogin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"sendActivationOnInvalidLogin","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DSAPIUserInformation","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIUserInformation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIUserInformation"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation\/init()"],"title":"Instance Methods"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIUserInformation"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInformation~1init()\/title","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInformation~1init()\/fragments"},{"value":"DSAPIUserInformation","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInformation\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInformation\/fragments","value":[{"text":"DSAPIUserInformation","kind":"identifier"}],"op":"replace"}]}]}