{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeTemplateResults"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapienvelopetemplateresults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapienvelopetemplateresults"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/init(from:)"]},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/endPosition","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/envelopeTemplates","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/folders","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/nextUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/previousUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/resultSetSize","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/startPosition","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/totalSetSize"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"sections":[],"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplateResults","roleHeading":"Class","title":"DSAPIEnvelopeTemplateResults","navigatorTitle":[{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"modules":[{"name":"DocuSignAPI"}]},"kind":"symbol","abstract":[{"text":"Information about templates.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults"},"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults","title":"DSAPIEnvelopeTemplateResults","type":"topic","abstract":[{"text":"Information about templates.","type":"text"}],"navigatorTitle":[{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","title":"Swift.Encodable"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","title":"Swift.Equatable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"endPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"envelopeTemplates","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIEnvelopeTemplate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"folders","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"nextUri"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"previousUri","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"resultSetSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"startPosition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"totalSetSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/init(endposition:envelopetemplates:folders:nexturi:previousuri:resultsetsize:startposition:totalsetsize:)","title":"init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithEndPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:"}]},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","title":"Swift.Hashable"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/folders":{"navigatorTitle":[{"text":"folders","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/folders","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"folders","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPIFolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"text":"]?","kind":"text"}],"role":"symbol","abstract":[{"text":"A list of folder objects.","type":"text"}],"title":"folders","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/folders","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/init(from:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/init(from:)","title":"init(from:)","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/resultSetSize":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resultSetSize"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"resultSetSize","kind":"identifier"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/resultsetsize","kind":"symbol","title":"resultSetSize","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/resultSetSize","abstract":[{"text":"The number of results in this response. Because you can filter which entries are included in the response, this value is always less than or equal to the `totalSetSize`.","type":"text"}],"role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject","title":"NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/previousUri":{"type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/previousuri","navigatorTitle":[{"text":"previousUri","kind":"identifier"}],"title":"previousUri","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/previousUri","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"previousUri","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The URI for the prior chunk of records based on the search request. It is `null` if this is the first set of results for the search."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/startPosition":{"navigatorTitle":[{"text":"startPosition","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/startposition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"The starting index position of the current result set.","type":"text"}],"title":"startPosition","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/startPosition","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/endPosition":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/endPosition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endPosition","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/endposition","title":"endPosition","navigatorTitle":[{"text":"endPosition","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The last index position in the result set."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/totalSetSize":{"navigatorTitle":[{"text":"totalSetSize","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/totalsetsize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"totalSetSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"The total number of items in the result set. This value is always greater than or equal to the value of `resultSetSize`.","type":"text"}],"title":"totalSetSize","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/totalSetSize","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/nextUri":{"navigatorTitle":[{"text":"nextUri","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/nexturi","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextUri","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"The URI for the next chunk of records based on the search request. It is `null` if this is the last set of results for the search.","type":"text"}],"title":"nextUri","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/nextUri","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/envelopeTemplates":{"navigatorTitle":[{"text":"envelopeTemplates","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/envelopetemplates","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"envelopeTemplates","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPIEnvelopeTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate"},{"text":"]?","kind":"text"}],"role":"symbol","abstract":[{"text":"The list of requested templates.","type":"text"}],"title":"envelopeTemplates","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/envelopeTemplates","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","title":"Swift.Decodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIEnvelopeTemplateResults"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/endPosition","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/envelopeTemplates","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/folders","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/nextUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/previousUri","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/resultSetSize","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/startPosition","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/totalSetSize"]},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults\/title","value":"DSAPIEnvelopeTemplateResults"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeTemplateResults"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)\/title","value":"initWithEndPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1init(endPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithEndPosition:envelopeTemplates:folders:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1folders\/title","op":"replace","value":"folders"},{"value":[{"kind":"identifier","text":"folders"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1folders\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1resultSetSize\/title","op":"replace","value":"resultSetSize"},{"value":[{"kind":"identifier","text":"resultSetSize"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1resultSetSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1previousUri\/title","value":"previousUri"},{"value":[{"kind":"identifier","text":"previousUri"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1previousUri\/fragments"},{"value":"startPosition","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1startPosition\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1startPosition\/fragments","op":"replace","value":[{"text":"startPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1endPosition\/title","value":"endPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1endPosition\/fragments","value":[{"text":"endPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1totalSetSize\/title","op":"replace","value":"totalSetSize"},{"value":[{"kind":"identifier","text":"totalSetSize"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1totalSetSize\/fragments"},{"value":"nextUri","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1nextUri\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1nextUri\/fragments","value":[{"kind":"identifier","text":"nextUri"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1envelopeTemplates\/title","value":"envelopeTemplates"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1envelopeTemplates\/fragments","value":[{"text":"envelopeTemplates","kind":"identifier"}]}]}]}