{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitabs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapitabs"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"title":"DSAPITabs","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/approveTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/checkboxTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commentThreadTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionCountyTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionExpirationTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionNumberTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionStateTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/companyTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/currencyTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/dateSignedTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/dateTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/declineTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/drawTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailAddressTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/envelopeIdTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/firstNameTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/formulaTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/fullNameTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/initialHereTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/lastNameTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/listTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/notarizeTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/notarySealTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/noteTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/numberTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/phoneNumberTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/polyLineOverlayTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/prefillTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/radioGroupTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/signHereTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/signerAttachmentTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/smartSectionTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/ssnTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/tabGroups","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/textTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/titleTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/viewTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/zipTabs"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/commissionStateTabs":{"role":"symbol","title":"commissionStateTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commissionStateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionState","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Commission State tabs][cc].   A Commission County tab displays the state in which a notary's commission was granted. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary]. The tab's value can be edited by the recipient.   [cc]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/ [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionStateTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/commissionstatetabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/checkboxTabs":{"role":"symbol","title":"checkboxTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkboxTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Checkbox tabs][checkbox].   A Checkbox tab enables the recipient to select a yes\/no (on\/off) option. This value can be set.   [checkbox]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/checkboxTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkboxTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/checkboxtabs"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/drawTabs":{"role":"symbol","title":"drawTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDraw","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of Draw Tabs.  A Draw Tab allows the recipient to add a free-form drawing to the document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/drawTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/drawtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/noteTabs":{"role":"symbol","title":"noteTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noteTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINote","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Note tabs][note].  A Note tab displays additional information to the recipient in the form of a note. This value can be set.  [note]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/noteTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"noteTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/notetabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/ssnTabs":{"role":"symbol","title":"ssnTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ssnTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [SSN tabs][ssn].  An SSN tab contains a one-line field that enables the recipient to enter a Social Security Number (SSN) with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for SSN information. This value can be set.   [ssn]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/ssnTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ssnTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/ssntabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/initialHereTabs":{"role":"symbol","title":"initialHereTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInitialHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Initial Here tabs][initialHere].  This type of tab enables the recipient to initial the document. May be optional. This value can't be set.  [initialHere]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/initialHereTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialHereTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/initialheretabs"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/radioGroupTabs":{"role":"symbol","title":"radioGroupTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRadioGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Radio Group tabs][radioGroup].  A Radio Group tab places a group of radio buttons on a document. The `radios` property is used to add and place the radio buttons associated with the group. Only one radio button can be selected in a group. This value can be set.   [radioGroup]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/radioGroupTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"radioGroupTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/radiogrouptabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/formulaTabs":{"role":"symbol","title":"formulaTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formulaTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Formula tabs][formulaTab].  The value of a Formula tab is calculated from the values of other number or date tabs in the document. When the recipient completes the underlying fields, the Formula tab calculates and displays the result. This value can be set.  The `formula` property of the tab contains the references to the underlying tabs. To learn more about formulas, see [Calculated Fields][calculatedfields].  If a Formula tab contains a `paymentDetails` property, the tab is considered a payment item. To learn more about payments, see [Requesting Payments Along with Signatures][paymentguide].  [calculatedfields]: https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-calculated-fields [paymentguide]:     https:\/\/support.docusign.com\/en\/guides\/requesting-payments-along-with-signatures [formulaTab]:      \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/formulaTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formulaTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/formulatabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/lastNameTabs":{"role":"symbol","title":"lastNameTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Last Name tabs][lastName].  A Last Name tab displays the recipient's last name. The system automatically populates this field by splitting the name in the recipient information on spaces. This value can't be set.   [lastName]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/lastNameTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastNameTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/lastnametabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/commissionNumberTabs":{"role":"symbol","title":"commissionNumberTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commissionNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Commission Number tabs][tabref].   A Commission Number tab displays a notary's commission number. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary]. The tab's value can be edited by the recipient.   [tabref]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/ [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionNumberTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/commissionnumbertabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/currencyTabs":{"role":"symbol","title":"currencyTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/currencyTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/currencytabs"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"https://www.docusign.com/blog/dsdev-deep-dive-responsive-smart-sections":{"title":"Smart Section","titleInlineContent":[{"type":"text","text":"Smart Section"}],"type":"link","identifier":"https:\/\/www.docusign.com\/blog\/dsdev-deep-dive-responsive-smart-sections","url":"https:\/\/www.docusign.com\/blog\/dsdev-deep-dive-responsive-smart-sections"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)":{"role":"symbol","title":"init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"approveTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIApprove","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"checkboxTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICheckbox","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICheckbox"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commentThreadTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommentThread","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionCountyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionExpirationTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionExpiration","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionNumber","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionNumberV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"commissionStateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionState","preciseIdentifier":"s:11DocuSignAPI20DSAPICommissionStateV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"companyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICompany","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"currencyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICurrency","preciseIdentifier":"s:11DocuSignAPI13DSAPICurrencyV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateSignedTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDateSigned","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"dateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDate"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declineTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDecline","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"drawTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDraw","preciseIdentifier":"s:11DocuSignAPI9DSAPIDrawV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"emailTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeIdTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeId","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"formulaTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFormulaTab","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFormulaTab"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"fullNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFullName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"initialHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInitialHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInitialHere"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lastNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPILastName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILastName"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"listTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIList","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarizeTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notarySealTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"noteTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINote","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINote"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"numberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINumber","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINumber"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"phoneNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPhoneNumber","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"polyLineOverlayTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"prefillTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPrefillTabs","preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"radioGroupTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRadioGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signerAttachmentTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignerAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"smartSectionTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"ssnTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISsn","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISsn"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIText","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"titleTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITitle","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"viewTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"zipTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init(approveTabs:checkboxTabs:commentThreadTabs:commissionCountyTabs:commissionExpirationTabs:commissionNumberTabs:commissionStateTabs:companyTabs:currencyTabs:dateSignedTabs:dateTabs:declineTabs:drawTabs:emailAddressTabs:emailTabs:envelopeIdTabs:firstNameTabs:formulaTabs:fullNameTabs:initialHereTabs:lastNameTabs:listTabs:notarizeTabs:notarySealTabs:noteTabs:numberTabs:phoneNumberTabs:polyLineOverlayTabs:prefillTabs:radioGroupTabs:signerAttachmentTabs:signHereTabs:smartSectionTabs:ssnTabs:tabGroups:textTabs:titleTabs:viewTabs:zipTabs:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/init(approvetabs:checkboxtabs:commentthreadtabs:commissioncountytabs:commissionexpirationtabs:commissionnumbertabs:commissionstatetabs:companytabs:currencytabs:datesignedtabs:datetabs:declinetabs:drawtabs:emailaddresstabs:emailtabs:envelope-go8c"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","title":"DSAPITabs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}],"url":"\/documentation\/docusignapi\/dsapitabs"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/notarySealTabs":{"role":"symbol","title":"notarySealTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notarySealTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarySeal","preciseIdentifier":"s:11DocuSignAPI15DSAPINotarySealV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of Notary Seal tabs.  A Notary Seal tab enables the recipient to notarize a document. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/notarySealTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/notarysealtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/fullNameTabs":{"role":"symbol","title":"fullNameTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFullName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Full Name tabs][fullName].  A Full Name tab displays the recipient's full name. This value can't be set.   [fullName]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/fullNameTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fullNameTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/fullnametabs"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/phoneNumberTabs":{"role":"symbol","title":"phoneNumberTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPhoneNumber","preciseIdentifier":"s:11DocuSignAPI16DSAPIPhoneNumberV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Phone Number tabs][cc].   A Phone Number tab enables a recipient to enter a phone number.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary].  [cc]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/ [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/phoneNumberTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/phonenumbertabs"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/declineTabs":{"role":"symbol","title":"declineTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"declineTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDecline","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDecline"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Decline tabs][decline].  A Decline tab enables the recipient to decline the envelope. If the recipient clicks the tab during the signing process, the envelope is voided. The value of this tab can't be set.   [decline]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/declineTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"declineTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/declinetabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/signerAttachmentTabs":{"role":"symbol","title":"signerAttachmentTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signerAttachmentTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignerAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignerAttachment"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Signer Attachment tabs][signerAttachment].  This type of tab enables the recipient to attach supporting documents to an envelope. This value can't be set.   [signerAttachment]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/signerAttachmentTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signerAttachmentTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/signerattachmenttabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/emailTabs":{"role":"symbol","title":"emailTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmail","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmail"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Email tabs][email].  An Email tab enables the recipient to enter an email address. This is a one-line field that checks that a valid email address is entered. It uses the same parameters as a Text tab, with the validation message and pattern set for email information. This value can be set.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response.  [email]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emailTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/emailtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/firstNameTabs":{"role":"symbol","title":"firstNameTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstNameTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFirstName","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFirstName"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [First Name tabs][firstName].  A First Name tab displays the recipient's first name. The system automatically populates this field by splitting the name in the recipient information on spaces. This value can't be set.   [firstName]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#parameters_firstname"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/firstNameTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstNameTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/firstnametabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/smartSectionTabs":{"role":"symbol","title":"smartSectionTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smartSectionTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISmartSection","preciseIdentifier":"s:11DocuSignAPI17DSAPISmartSectionV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.docusign.com\/blog\/dsdev-deep-dive-responsive-smart-sections"},{"type":"text","text":" tabs.  Smart Section tabs enhance responsive signing on mobile devices by enabling collapsible sections, page breaks, custom formatting options, and other advanced functionality.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Smart Sections are a premium feature. Responsive signing must also be enabled for your account."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/smartSectionTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/smartsectiontabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/approveTabs":{"role":"symbol","title":"approveTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"approveTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIApprove","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIApprove"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Approve tabs][approve].  An Approve tab enables the recipient to approve documents without placing a signature or initials on the document. If the recipient clicks the tab during the signing process, the recipient is considered to have signed the document. No information is shown on the document of the approval, but it is recorded as a signature in the envelope history. The value of an approve tab can't be set.  [approve]:        \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/approveTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"approveTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/approvetabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/commissionExpirationTabs":{"role":"symbol","title":"commissionExpirationTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commissionExpirationTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionExpiration","preciseIdentifier":"s:11DocuSignAPI25DSAPICommissionExpirationV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Commission Expiration tabs][tabref].   A Commission Expiration tab displays the expiration date of a notary's commission. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary]. The tab's value can be edited by the recipient.   [tabref]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/ [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionExpirationTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/commissionexpirationtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/textTabs":{"role":"symbol","title":"textTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIText","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIText"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of Text tabs.  A text tab enables the recipient to enter free text. This value can be set.  Find descriptions of all tab types in the [tabs Resource][ert].  [ert]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/textTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/texttabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/titleTabs":{"role":"symbol","title":"titleTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITitle","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITitle"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Title tabs][title].  A Title tab displays the recipient's title.  This value can't be set.   [title]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/titleTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/titletabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/envelopeIdTabs":{"role":"symbol","title":"envelopeIdTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeIdTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeId","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeId"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Envelope ID tabs][envelopeId].  An Envelope ID tab  displays the envelope ID. Recipients cannot enter or change the information in this tab. This value can't be set.   [envelopeId]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#response201_envelopeid"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/envelopeIdTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"envelopeIdTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/envelopeidtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/zipTabs":{"role":"symbol","title":"zipTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIZip","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIZip"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Zip tabs][zip].  A Zip tab enables the recipient to enter a ZIP code. The ZIP code can be five digits or nine digits ( in ZIP+4 format), and can be entered with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for ZIP code information.  This value can be set.   [zip]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/zipTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zipTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/ziptabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/polyLineOverlayTabs":{"role":"symbol","title":"polyLineOverlayTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polyLineOverlayTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIPolyLineOverlay","preciseIdentifier":"s:11DocuSignAPI20DSAPIPolyLineOverlayV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"This type of tab enables the recipient to strike through document text. This value can't be set."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/polyLineOverlayTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/polylineoverlaytabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/prefillTabs":{"role":"symbol","title":"prefillTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefillTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPrefillTabs","preciseIdentifier":"s:11DocuSignAPI16DSAPIPrefillTabsV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/prefillTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/prefilltabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/listTabs":{"role":"symbol","title":"listTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIList","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIList"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array of List tabs.  A List tab enables the recipient to choose from a list of options. You specify the options in the `listItems` property. This value can't be set.  Find descriptions of all tab types in the [tabs Resource][ert].  [ert]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/listTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/listtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/notarizeTabs":{"role":"symbol","title":"notarizeTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notarizeTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotarize","preciseIdentifier":"s:11DocuSignAPI13DSAPINotarizeV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of  [Notarize tabs][notarize].  A Notarize tab alerts notary recipients that they must take action on the page. This value can be set.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Only one notarize tab can appear on a page.  [notarize]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/notarizeTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/notarizetabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/commissionCountyTabs":{"role":"symbol","title":"commissionCountyTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commissionCountyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommissionCounty","preciseIdentifier":"s:11DocuSignAPI21DSAPICommissionCountyV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Commission County tabs][cc].   A Commission County tab displays the county of a notary's commission. This tab can only be assigned to a remote notary recipient using [DocuSign Notary][notary]. The tab's value can be edited by the recipient.   [cc]:  \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/ [notary]: \/docs\/notary-api\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commissionCountyTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/commissioncountytabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/dateTabs":{"role":"symbol","title":"dateTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDate"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Date tabs][date].  A Date tab enables the recipient to enter a date. This value can't be set. The tooltip for this tab recommends the date format MM\/DD\/YYYY, but several other date formats are also accepted. The system retains the format that the recipient enters.  "},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" If you need to enforce a specific date format, DocuSign recommends that you use a Text tab with a validation pattern and validation message.   [date]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/dateTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/datetabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/tabGroups":{"role":"symbol","title":"tabGroups","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITabGroup","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array of `tabGroup` items.  To associate a tab with a tab group, add the tab group's `groupLabel` to the tab's `tabGroupLabels` array."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/tabGroups","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabGroups"}],"url":"\/documentation\/docusignapi\/dsapitabs\/tabgroups"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/docusignapi\/dsapitabs\/init()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/signHereTabs":{"role":"symbol","title":"signHereTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signHereTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignHere","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISignHere"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Sign Here tabs][signHere].  This type of tab enables the recipient to sign a document. May be optional. This value can't be set.  [signHere]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/signHereTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signHereTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/signheretabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/commentThreadTabs":{"role":"symbol","title":"commentThreadTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commentThreadTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICommentThread","preciseIdentifier":"s:11DocuSignAPI18DSAPICommentThreadV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array of tabs that represents a collection of comments in a comment thread. For example, if a recipient has questions about the content of a document, they can add a comment to the document and control who else can see the comment. This value can't be set."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/commentThreadTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/commentthreadtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/emailAddressTabs":{"role":"symbol","title":"emailAddressTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailAddressTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEmailAddress","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEmailAddress"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Email Address tabs][emailAddress].  An Email Address tab displays the recipient's email as entered in the recipient information. This value can't be set.   [emailAddress]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailAddressTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emailAddressTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/emailaddresstabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/viewTabs":{"role":"symbol","title":"viewTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIView","preciseIdentifier":"s:11DocuSignAPI9DSAPIViewV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [View tabs][view].  A View tab is used with an Approve tab to handle supplemental documents.  This value can be set.  [view]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/viewTabs","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitabs\/viewtabs"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/companyTabs":{"role":"symbol","title":"companyTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICompany","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICompany"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Company tabs][company].  A Company tab displays a field for the name of the recipient's company. This value can't be set.  [company]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/#parameters_company"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/companyTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"companyTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/companytabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/dateSignedTabs":{"role":"symbol","title":"dateSignedTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateSignedTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDateSigned","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateSigned"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Date Signed tabs][dateSigned].   A Date Signed tab displays the date that the recipient signed the document. This value can't be set.  [dateSigned]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/dateSignedTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateSignedTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/datesignedtabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs/numberTabs":{"role":"symbol","title":"numberTabs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberTabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINumber","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINumber"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of [Number tabs][number].  A Number tab enables the recipient to enter numbers and decimal points (.). This value can be set.    [number]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/numberTabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberTabs"}],"url":"\/documentation\/docusignapi\/dsapitabs\/numbertabs"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPITabs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/approveTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/checkboxTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/companyTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/dateSignedTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/dateTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/declineTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailAddressTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/emailTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/envelopeIdTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/firstNameTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/formulaTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/fullNameTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/initialHereTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/lastNameTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/listTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/noteTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/numberTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/radioGroupTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/signHereTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/signerAttachmentTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/ssnTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/tabGroups","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/textTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/titleTabs","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/zipTabs"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1checkboxTabs\/title","value":"checkboxTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1checkboxTabs\/fragments","value":[{"kind":"identifier","text":"checkboxTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1noteTabs\/title","value":"noteTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1noteTabs\/fragments","value":[{"kind":"identifier","text":"noteTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1ssnTabs\/title","value":"ssnTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1ssnTabs\/fragments","value":[{"kind":"identifier","text":"ssnTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1initialHereTabs\/title","value":"initialHereTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1initialHereTabs\/fragments","value":[{"kind":"identifier","text":"initialHereTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1radioGroupTabs\/title","value":"radioGroupTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1radioGroupTabs\/fragments","value":[{"kind":"identifier","text":"radioGroupTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1formulaTabs\/title","value":"formulaTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1formulaTabs\/fragments","value":[{"kind":"identifier","text":"formulaTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1lastNameTabs\/title","value":"lastNameTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1lastNameTabs\/fragments","value":[{"kind":"identifier","text":"lastNameTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1fullNameTabs\/title","value":"fullNameTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1fullNameTabs\/fragments","value":[{"kind":"identifier","text":"fullNameTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1declineTabs\/title","value":"declineTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1declineTabs\/fragments","value":[{"kind":"identifier","text":"declineTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1signerAttachmentTabs\/title","value":"signerAttachmentTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1signerAttachmentTabs\/fragments","value":[{"kind":"identifier","text":"signerAttachmentTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1emailTabs\/title","value":"emailTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1emailTabs\/fragments","value":[{"kind":"identifier","text":"emailTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1firstNameTabs\/title","value":"firstNameTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1firstNameTabs\/fragments","value":[{"kind":"identifier","text":"firstNameTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1approveTabs\/title","value":"approveTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1approveTabs\/fragments","value":[{"kind":"identifier","text":"approveTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1textTabs\/title","value":"textTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1textTabs\/fragments","value":[{"kind":"identifier","text":"textTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1titleTabs\/title","value":"titleTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1titleTabs\/fragments","value":[{"kind":"identifier","text":"titleTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1envelopeIdTabs\/title","value":"envelopeIdTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1envelopeIdTabs\/fragments","value":[{"kind":"identifier","text":"envelopeIdTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1zipTabs\/title","value":"zipTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1zipTabs\/fragments","value":[{"kind":"identifier","text":"zipTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1listTabs\/title","value":"listTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1listTabs\/fragments","value":[{"kind":"identifier","text":"listTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1dateTabs\/title","value":"dateTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1dateTabs\/fragments","value":[{"kind":"identifier","text":"dateTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1tabGroups\/title","value":"tabGroups"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1tabGroups\/fragments","value":[{"kind":"identifier","text":"tabGroups"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1signHereTabs\/title","value":"signHereTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1signHereTabs\/fragments","value":[{"kind":"identifier","text":"signHereTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1emailAddressTabs\/title","value":"emailAddressTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1emailAddressTabs\/fragments","value":[{"kind":"identifier","text":"emailAddressTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1companyTabs\/title","value":"companyTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1companyTabs\/fragments","value":[{"kind":"identifier","text":"companyTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1dateSignedTabs\/title","value":"dateSignedTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1dateSignedTabs\/fragments","value":[{"kind":"identifier","text":"dateSignedTabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1numberTabs\/title","value":"numberTabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs~1numberTabs\/fragments","value":[{"kind":"identifier","text":"numberTabs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}