{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIClientContext"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiclientcontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiclientcontext"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This client specific details for the telemetry events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIClientContext"}],"title":"DSAPIClientContext","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIClientContext","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIClientContext"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init(application:environment:site:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/application","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/environment","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/site"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext/init(application:environment:site:)":{"role":"symbol","title":"init(application:environment:site:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"environment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"site"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init(application:environment:site:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithApplication:environment:site:"}],"url":"\/documentation\/docusignapi\/dsapiclientcontext\/init(application:environment:site:)"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext/environment":{"role":"symbol","title":"environment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"environment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The name of environment."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/environment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"environment"}],"url":"\/documentation\/docusignapi\/dsapiclientcontext\/environment"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext/application":{"role":"symbol","title":"application","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The name of application."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/application","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application"}],"url":"\/documentation\/docusignapi\/dsapiclientcontext\/application"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext/site":{"role":"symbol","title":"site","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"site"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The name of site."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/site","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"site"}],"url":"\/documentation\/docusignapi\/dsapiclientcontext\/site"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiclientcontext\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/docusignapi\/dsapiclientcontext\/init()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIClientContext":{"role":"symbol","title":"DSAPIClientContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIClientContext"}],"abstract":[{"type":"text","text":"This client specific details for the telemetry events."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIClientContext"}],"url":"\/documentation\/docusignapi\/dsapiclientcontext"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIClientContext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIClientContext"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIClientContext"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/application","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/environment","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/site"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIClientContext\/init(application:environment:site:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIClientContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1init(application:environment:site:)\/title","value":"initWithApplication:environment:site:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1init(application:environment:site:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApplication:environment:site:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1environment\/title","value":"environment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1environment\/fragments","value":[{"kind":"identifier","text":"environment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1application\/title","value":"application"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1application\/fragments","value":[{"kind":"identifier","text":"application"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1site\/title","value":"site"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1site\/fragments","value":[{"kind":"identifier","text":"site"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext\/title","value":"DSAPIClientContext"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIClientContext\/fragments","value":[{"kind":"identifier","text":"DSAPIClientContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}