{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipients"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipients"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipients"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/Se","doc:\/\/com.DocuSign.DocuSIgnAPI\/SE","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies the envelope recipients."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipients"}],"title":"DSAPIRecipients","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipients"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/agents","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/carbonCopies","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/certifiedDeliveries","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/currentRoutingOrder","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/editors","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/inPersonSigners","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/intermediaries","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/notaries","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/recipientCount","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/seals","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/signers","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/witnesses"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/toDictionary()"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/seals":{"role":"symbol","title":"seals","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"seals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISealSign","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISealSign"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of electronic seals to apply to documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/seals","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"seals"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/seals"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/editors":{"role":"symbol","title":"editors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"editors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEditor","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEditor"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of users who can edit the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/editors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editors"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/editors"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/certifiedDeliveries":{"role":"symbol","title":"certifiedDeliveries","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"certifiedDeliveries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICertifiedDelivery","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A complex type containing information on a recipient the must receive the completed documents for the envelope to be completed, but the recipient does not need to sign, initial, date, or add information to any of the documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/certifiedDeliveries","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"certifiedDeliveries"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/certifieddeliveries"},"doc://com.DocuSign.DocuSIgnAPI/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/Se"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/carbonCopies":{"role":"symbol","title":"carbonCopies","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"carbonCopies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICarbonCopy","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICarbonCopy"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of carbon copy recipients assigned to the documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/carbonCopies","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"carbonCopies"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/carboncopies"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/toDictionary()":{"role":"symbol","title":"toDictionary()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toDictionary"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/toDictionary()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toDictionary"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/todictionary()"},"doc://com.DocuSign.DocuSIgnAPI/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SE"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)":{"role":"symbol","title":"init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIAgent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAgent"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"carbonCopies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICarbonCopy","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICarbonCopy"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"certifiedDeliveries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPICertifiedDelivery","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICertifiedDelivery"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"currentRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"editors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEditor","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEditor"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inPersonSigners"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInPersonSigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"intermediaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIIntermediary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotaryRecipient","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seals"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISealSign","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISealSign"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISigner"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"witnesses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIWitness","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIWitness"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/init(agents:carboncopies:certifieddeliveries:currentroutingorder:editors:errordetails:inpersonsigners:intermediaries:notaries:recipientcount:seals:signers:witnesses:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/signers":{"role":"symbol","title":"signers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISigner"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of signers on the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/signers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signers"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/signers"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/errorDetails":{"role":"symbol","title":"errorDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/errorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorDetails"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/errordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/inPersonSigners":{"role":"symbol","title":"inPersonSigners","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inPersonSigners"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIInPersonSigner","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Specifies a signer that is in the same physical location as a DocuSign user who will act as a Signing Host for the transaction. The recipient added is the Signing Host and new separate Signer Name field appears after Sign in person is selected."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/inPersonSigners","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inPersonSigners"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/inpersonsigners"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/init()"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/agents":{"role":"symbol","title":"agents","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"agents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIAgent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAgent"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of agent recipients assigned to the documents."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/agents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"agents"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/agents"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/recipientCount":{"role":"symbol","title":"recipientCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The number of recipients in the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/recipientCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recipientCount"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/recipientcount"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/intermediaries":{"role":"symbol","title":"intermediaries","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intermediaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIIntermediary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIIntermediary"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Identifies a recipient that can, but is not required to, add name and email information for recipients at the same or subsequent level in the routing order (until subsequent Agents, Editors or Intermediaries recipient types are added)."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/intermediaries","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intermediaries"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/intermediaries"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/currentRoutingOrder":{"role":"symbol","title":"currentRoutingOrder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The routing order of the current recipient. If this value equals a particular signer's routing order, it indicates that the envelope has been sent to that recipient, but he or she has not completed the required actions."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/currentRoutingOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentRoutingOrder"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/currentroutingorder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapirecipients\/init(from:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"role":"symbol","title":"DSAPIRecipients","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipients"}],"abstract":[{"type":"text","text":"Specifies the envelope recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipients"}],"url":"\/documentation\/docusignapi\/dsapirecipients"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/witnesses":{"role":"symbol","title":"witnesses","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"witnesses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIWitness","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIWitness"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of signers who act as witnesses on the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/witnesses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"witnesses"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/witnesses"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients/notaries":{"role":"symbol","title":"notaries","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notaries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPINotaryRecipient","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A list of notary recipients on the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/notaries","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notaries"}],"url":"\/documentation\/docusignapi\/dsapirecipients\/notaries"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSAPIRecipients"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipients"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DSAPIRecipients"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/agents","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/carbonCopies","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/certifiedDeliveries","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/currentRoutingOrder","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/editors","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/errorDetails","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/inPersonSigners","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/intermediaries","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/notaries","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/recipientCount","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/seals","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/signers","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/witnesses"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init()","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients\/toDictionary()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipients"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1seals\/title","value":"seals"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1seals\/fragments","value":[{"kind":"identifier","text":"seals"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1editors\/title","value":"editors"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1editors\/fragments","value":[{"kind":"identifier","text":"editors"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1certifiedDeliveries\/title","value":"certifiedDeliveries"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1certifiedDeliveries\/fragments","value":[{"kind":"identifier","text":"certifiedDeliveries"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1carbonCopies\/title","value":"carbonCopies"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1carbonCopies\/fragments","value":[{"kind":"identifier","text":"carbonCopies"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1toDictionary()\/title","value":"toDictionary"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1toDictionary()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)\/title","value":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1init(agents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAgents:carbonCopies:certifiedDeliveries:currentRoutingOrder:editors:errorDetails:inPersonSigners:intermediaries:notaries:recipientCount:seals:signers:witnesses:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1signers\/title","value":"signers"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1signers\/fragments","value":[{"kind":"identifier","text":"signers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1errorDetails\/title","value":"errorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1errorDetails\/fragments","value":[{"kind":"identifier","text":"errorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1inPersonSigners\/title","value":"inPersonSigners"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1inPersonSigners\/fragments","value":[{"kind":"identifier","text":"inPersonSigners"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1agents\/title","value":"agents"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1agents\/fragments","value":[{"kind":"identifier","text":"agents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1recipientCount\/title","value":"recipientCount"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1recipientCount\/fragments","value":[{"kind":"identifier","text":"recipientCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1intermediaries\/title","value":"intermediaries"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1intermediaries\/fragments","value":[{"kind":"identifier","text":"intermediaries"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1currentRoutingOrder\/title","value":"currentRoutingOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1currentRoutingOrder\/fragments","value":[{"kind":"identifier","text":"currentRoutingOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title","value":"DSAPIRecipients"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipients"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1witnesses\/title","value":"witnesses"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1witnesses\/fragments","value":[{"kind":"identifier","text":"witnesses"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1notaries\/title","value":"notaries"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients~1notaries\/fragments","value":[{"kind":"identifier","text":"notaries"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}