{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsclientapi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsclientapi"]}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSClientAPI","kind":"identifier"}],"navigatorTitle":[{"text":"DSClientAPI","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSClientAPI","title":"DSClientAPI","modules":[{"name":"DocuSignAPI"}],"role":"symbol","symbolKind":"class"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/init(basePath:customHeaders:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/basePath","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/customHeaders","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/mockRequestBuilderFactory","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/requestBuilderFactory"],"title":"Type Properties"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSClientAPI","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI/requestBuilderFactory":{"url":"\/documentation\/docusignapi\/dsclientapi\/requestbuilderfactory","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/requestBuilderFactory","type":"topic","role":"symbol","title":"requestBuilderFactory","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestBuilderFactory","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI21RequestBuilderFactoryP","text":"RequestBuilderFactory","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI/customHeaders":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customHeaders","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI11HeadersDicta","text":"HeadersDict","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/customHeaders","navigatorTitle":[{"text":"customHeaders","kind":"identifier"}],"abstract":[],"title":"customHeaders","kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsclientapi\/customheaders"},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI/mockRequestBuilderFactory":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mockRequestBuilderFactory","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI21RequestBuilderFactoryP","text":"RequestBuilderFactory"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/mockRequestBuilderFactory","role":"symbol","url":"\/documentation\/docusignapi\/dsclientapi\/mockrequestbuilderfactory","type":"topic","kind":"symbol","title":"mockRequestBuilderFactory"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI/init(basePath:customHeaders:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/init(basePath:customHeaders:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"basePath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"customHeaders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeadersDict","preciseIdentifier":"s:11DocuSignAPI11HeadersDicta","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"init(basePath:customHeaders:)","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBasePath:customHeaders:"}],"url":"\/documentation\/docusignapi\/dsclientapi\/init(basepath:customheaders:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI":{"navigatorTitle":[{"text":"DSClientAPI","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsclientapi","role":"symbol","title":"DSClientAPI","abstract":[],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSClientAPI"}]},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSClientAPI/basePath":{"navigatorTitle":[{"kind":"identifier","text":"basePath"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsclientapi\/basepath","role":"symbol","abstract":[],"title":"basePath","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/basePath","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"basePath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DSClientAPI"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DSClientAPI","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DSClientAPI","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/init(basePath:customHeaders:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/basePath","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSClientAPI\/customHeaders"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSClientAPI","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1customHeaders\/title","value":"customHeaders"},{"value":[{"kind":"identifier","text":"customHeaders"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1customHeaders\/fragments","op":"replace"},{"value":"initWithBasePath:customHeaders:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1init(basePath:customHeaders:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1init(basePath:customHeaders:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBasePath:customHeaders:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI\/title","value":"DSClientAPI"},{"value":[{"text":"DSClientAPI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI\/fragments","op":"replace"},{"value":"basePath","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1basePath\/title","op":"replace"},{"op":"replace","value":[{"text":"basePath","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSClientAPI~1basePath\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}