{"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","doc:\/\/com.DocuSign.DocuSIgnAPI\/SY"],"kind":"relationships","type":"conformsTo"}],"metadata":{"symbolKind":"enum","navigatorTitle":[{"text":"ObjcEnviromment","kind":"identifier"}],"title":"ObjcEnviromment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ObjcEnviromment","kind":"identifier"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"c:@M@DocuSignAPI@E@ObjcEnviromment","roleHeading":"Enumeration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/demo","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/prod","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/stage"]},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/Equatable-Implementations","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/RawRepresentable-Implementations"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"variants":[{"paths":["\/documentation\/docusignapi\/objcenviromment"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objcenviromment"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ObjcEnviromment","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/Equatable-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/Equatable-Implementations","url":"\/documentation\/docusignapi\/objcenviromment\/equatable-implementations","kind":"article"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObjcEnviromment"}],"abstract":[],"type":"topic","title":"ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","kind":"symbol","url":"\/documentation\/docusignapi\/objcenviromment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcEnviromment"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/docusignapi\/objcenviromment\/rawrepresentable-implementations"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/demo":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/demo","abstract":[],"title":"ObjcEnviromment.demo","navigatorTitle":[{"text":"ObjcEnvirommentDemo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"demo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/docusignapi\/objcenviromment\/demo","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SY","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/stage":{"navigatorTitle":[{"text":"ObjcEnvirommentStage","kind":"identifier"}],"url":"\/documentation\/docusignapi\/objcenviromment\/stage","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"stage","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ObjcEnviromment.stage","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/stage","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/init(rawValue:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","title":"init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/objcenviromment\/init(rawvalue:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/prod":{"kind":"symbol","url":"\/documentation\/docusignapi\/objcenviromment\/prod","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/prod","navigatorTitle":[{"text":"ObjcEnvirommentProd","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"prod","kind":"identifier"}],"title":"ObjcEnviromment.prod","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"ObjcEnviromment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"ObjcEnviromment","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ObjcEnviromment","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/demo","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/prod","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/stage"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ObjcEnviromment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/title","value":"ObjcEnviromment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/fragments","value":[{"text":"ObjcEnviromment","kind":"identifier"}]},{"value":"ObjcEnvirommentDemo","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1demo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1demo\/fragments","value":[{"text":"ObjcEnvirommentDemo","kind":"identifier"}]},{"value":"ObjcEnvirommentStage","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1stage\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1stage\/fragments","op":"replace","value":[{"text":"ObjcEnvirommentStage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1prod\/title","value":"ObjcEnvirommentProd","op":"replace"},{"value":[{"text":"ObjcEnvirommentProd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1prod\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}