{"kind":"symbol","topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients\/same(recipientName:recipientEmail:accountName:accountEmail:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/validaterecipients"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/validaterecipients"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidateRecipients","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"title":"ValidateRecipients","externalID":"c:@M@DocuSignAPI@objc(cs)ValidateRecipients","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidateRecipients","kind":"identifier"}],"navigatorTitle":[{"text":"ValidateRecipients","kind":"identifier"}],"roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ","doc:\/\/com.DocuSign.DocuSIgnAPI\/SH"],"type":"conformsTo"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SQ"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ValidateRecipients":{"role":"symbol","url":"\/documentation\/docusignapi\/validaterecipients","abstract":[],"type":"topic","title":"ValidateRecipients","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidateRecipients"}],"navigatorTitle":[{"kind":"identifier","text":"ValidateRecipients"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ValidateRecipients/same(recipientName:recipientEmail:accountName:accountEmail:)":{"abstract":[],"url":"\/documentation\/docusignapi\/validaterecipients\/same(recipientname:recipientemail:accountname:accountemail:)","type":"topic","kind":"symbol","title":"same(recipientName:recipientEmail:accountName:accountEmail:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients\/same(recipientName:recipientEmail:accountName:accountEmail:)","role":"symbol","navigatorTitle":[{"text":"sameWithRecipientName:recipientEmail:accountName:accountEmail:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"same"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recipientName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"accountName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accountEmail","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.DocuSign.DocuSIgnAPI/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s7CVarArgP"},"doc://com.DocuSign.DocuSIgnAPI/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s28CustomDebugStringConvertibleP"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"},"doc://com.DocuSign.DocuSIgnAPI/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ValidateRecipients/init":{"kind":"symbol","title":"init","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients\/init","type":"topic","url":"\/documentation\/docusignapi\/validaterecipients\/init","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.DocuSign.DocuSIgnAPI/SH":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"ValidateRecipients","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ValidateRecipients","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ValidateRecipients","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients\/init"]},{"identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ValidateRecipients\/same(recipientName:recipientEmail:accountName:accountEmail:)"],"title":"Type Methods"}],"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.DocuSign.DocuSIgnAPI\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidateRecipients"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ValidateRecipients","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ValidateRecipients\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ValidateRecipients"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ValidateRecipients\/fragments"},{"value":"sameWithRecipientName:recipientEmail:accountName:accountEmail:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ValidateRecipients~1same(recipientName:recipientEmail:accountName:accountEmail:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ValidateRecipients~1same(recipientName:recipientEmail:accountName:accountEmail:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sameWithRecipientName:recipientEmail:accountName:accountEmail:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}