{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapilistcustomfield\/listitems"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapilistcustomfield\/listitems"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField\/listItems","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An array of strings that represents the options in a list.  Maximum length: 2048 characters, but each individual option string can only be a maximum of 100 characters."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"title":"listItems","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField(py)listItems","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"listItems"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField/listItems":{"role":"symbol","title":"listItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array of strings that represents the options in a list.  Maximum length: 2048 characters, but each individual option string can only be a maximum of 100 characters."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField\/listItems","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listItems"}],"url":"\/documentation\/docusignapi\/dsapilistcustomfield\/listitems"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField":{"role":"symbol","title":"DSAPIListCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIListCustomField"}],"abstract":[{"type":"text","text":"This object represents a list custom field from which envelope creators and senders can select custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIListCustomField"}],"url":"\/documentation\/docusignapi\/dsapilistcustomfield"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"listItems"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"listItems"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"listItems"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField~1listItems\/title","value":"listItems"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField~1listItems\/fragments","value":[{"kind":"identifier","text":"listItems"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/title","value":"DSAPIListCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPIListCustomField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}