{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"envelopeDocuments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument","text":"DSAPIEnvelopeDocument"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopedocumentsresult\/init(envelopedocuments:envelopeid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapienvelopedocumentsresult\/init(envelopedocuments:envelopeid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocumentsResult\/init(envelopeDocuments:envelopeId:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"envelopeDocuments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(envelopeDocuments:envelopeId:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocumentsResult(im)initWithEnvelopeDocuments:envelopeId:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEnvelopeDocuments:envelopeId:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocumentsResult"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocumentsResult":{"role":"symbol","title":"DSAPIEnvelopeDocumentsResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDocumentsResult"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocumentsResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDocumentsResult"}],"url":"\/documentation\/docusignapi\/dsapienvelopedocumentsresult"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocumentsResult/init(envelopeDocuments:envelopeId:)":{"role":"symbol","title":"init(envelopeDocuments:envelopeId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"envelopeDocuments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDocument","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocument"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocumentsResult\/init(envelopeDocuments:envelopeId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithEnvelopeDocuments:envelopeId:"}],"url":"\/documentation\/docusignapi\/dsapienvelopedocumentsresult\/init(envelopedocuments:envelopeid:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocument":{"role":"symbol","title":"DSAPIEnvelopeDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDocument"}],"abstract":[{"type":"text","text":"This object contains details about the envelope document."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDocument"}],"url":"\/documentation\/docusignapi\/dsapienvelopedocument"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithEnvelopeDocuments:envelopeId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnvelopeDocuments:envelopeId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEnvelopeDocuments:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIEnvelopeDocument *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"envelopeDocuments"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"envelopeId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocumentsResult\/title","value":"DSAPIEnvelopeDocumentsResult"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocumentsResult\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDocumentsResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocumentsResult~1init(envelopeDocuments:envelopeId:)\/title","value":"initWithEnvelopeDocuments:envelopeId:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocumentsResult~1init(envelopeDocuments:envelopeId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnvelopeDocuments:envelopeId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument\/title","value":"DSAPIEnvelopeDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocument\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}