{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider(im)initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:","roleHeading":"Initializer","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sealDocumentsWithTabsOnly","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"sealName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"signatureProviderName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"signatureProviderNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signatureProviderOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProviderOptions","kind":"typeIdentifier","text":"DSAPIRecipientSignatureProviderOptions"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:"}],"role":"symbol","symbolKind":"init","title":"init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider\/init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientsignatureprovider\/init(sealdocumentswithtabsonly:sealname:signatureprovidername:signatureprovidernamemetadata:signatureprovideroptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapirecipientsignatureprovider\/init(sealdocumentswithtabsonly:sealname:signatureprovidername:signatureprovidernamemetadata:signatureprovideroptions:)"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sealDocumentsWithTabsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"sealName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signatureProviderName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"signatureProviderNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"signatureProviderOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProviderOptions","text":"DSAPIRecipientSignatureProviderOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProviderOptions"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"title":"DSAPIRecipientSignatureProvider","abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider/init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider\/init(sealdocumentswithtabsonly:sealname:signatureprovidername:signatureprovidernamemetadata:signatureprovideroptions:)","navigatorTitle":[{"text":"initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sealDocumentsWithTabsOnly"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sealName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"signatureProviderName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureProviderNameMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signatureProviderOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProviderOptions","kind":"typeIdentifier","text":"DSAPIRecipientSignatureProviderOptions"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider\/init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)","title":"init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"title":"The current provider list and the options they require.","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","titleInlineContent":[{"text":"The current provider list and the options they require.","type":"text"}],"url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProviderOptions":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIRecipientSignatureProviderOptions","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovideroptions","kind":"symbol","navigatorTitle":[{"text":"DSAPIRecipientSignatureProviderOptions","kind":"identifier"}],"title":"DSAPIRecipientSignatureProviderOptions","role":"symbol","abstract":[{"type":"text","text":"Option settings for the signature provider. Different providers require or use different options. "},{"type":"reference","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","isActive":true}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProviderOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithSealDocumentsWithTabsOnly:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sealDocumentsWithTabsOnly"},{"kind":"text","text":" "},{"kind":"identifier","text":"sealName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sealName"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureProviderName:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"signatureProviderName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"signatureProviderNameMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":" *) "},{"text":"signatureProviderNameMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"signatureProviderOptions:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProviderOptions","text":"DSAPIRecipientSignatureProviderOptions","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProviderOptions"},{"text":" *) ","kind":"text"},{"text":"signatureProviderOptions","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DSAPIRecipientSignatureProvider","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/title"},{"value":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/fragments","op":"replace"},{"op":"replace","value":"initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider~1init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithSealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider~1init(sealDocumentsWithTabsOnly:sealName:signatureProviderName:signatureProviderNameMetadata:signatureProviderOptions:)\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","op":"replace","value":"DSAPIPropertyMetadata"},{"value":[{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments"},{"op":"replace","value":"DSAPIRecipientSignatureProviderOptions","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProviderOptions\/title"},{"value":[{"text":"DSAPIRecipientSignatureProviderOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProviderOptions\/fragments","op":"replace"}]}]}