{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider\/signatureProviderName","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientsignatureprovider\/signatureprovidername"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipientsignatureprovider\/signatureprovidername"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider(py)signatureProviderName","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"signatureProviderName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"signatureProviderName"}],"role":"symbol","title":"signatureProviderName","modules":[{"name":"DocuSignAPI"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signatureProviderName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The name of an Electronic or Standards Based Signature (digital signature) provider for the signer to use. For details, see "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":". You can also retrieve the list by using the "},{"isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountsignatureproviders\/list\/","type":"reference"},{"type":"text","text":" method.  Example: `universalsignaturepen_default`"}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider/signatureProviderName":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider\/signatureProviderName","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"signatureProviderName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider\/signatureprovidername","navigatorTitle":[{"text":"signatureProviderName","kind":"identifier"}],"title":"signatureProviderName","abstract":[{"type":"text","text":"The name of an Electronic or Standards Based Signature (digital signature) provider for the signer to use. For details, see "},{"isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","type":"reference"},{"type":"text","text":". You can also retrieve the list by using the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountsignatureproviders\/list\/"},{"type":"text","text":" method.  Example: `universalsignaturepen_default`"}],"kind":"symbol"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"title":"More information","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","titleInlineContent":[{"type":"text","text":"More information"}],"type":"link","url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},"/docs/esign-rest-api/reference/accounts/accountsignatureproviders/list/":{"titleInlineContent":[{"type":"text","text":"AccountSignatureProviders: List"}],"title":"AccountSignatureProviders: List","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/accountsignatureproviders\/list\/","url":"\/docs\/esign-rest-api\/reference\/accounts\/accountsignatureproviders\/list\/","type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"title":"DSAPIRecipientSignatureProvider","abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"signatureProviderName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"signatureProviderName","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"signatureProviderName"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"signatureProviderName","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider~1signatureProviderName\/title"},{"value":[{"text":"signatureProviderName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider~1signatureProviderName\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/title","value":"DSAPIRecipientSignatureProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}