{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedEvents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent","text":"DSAPIFailedTelemetryEvent"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitelemetryeventsresponse\/failedevents"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapitelemetryeventsresponse\/failedevents"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse\/failedEvents","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An array containing failed telemetry events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedEvents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFailedTelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent"},{"kind":"text","text":"]?"}],"title":"failedEvents","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEventsResponse(py)failedEvents","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"failedEvents"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEventsResponse":{"role":"symbol","title":"DSAPITelemetryEventsResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}],"abstract":[{"type":"text","text":"This response object is returned after you post a telemetry event."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}],"url":"\/documentation\/docusignapi\/dsapitelemetryeventsresponse"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFailedTelemetryEvent":{"role":"symbol","title":"DSAPIFailedTelemetryEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFailedTelemetryEvent"}],"abstract":[{"type":"text","text":"This response object is returned after you post a telemetry event."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFailedTelemetryEvent"}],"url":"\/documentation\/docusignapi\/dsapifailedtelemetryevent"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEventsResponse/failedEvents":{"role":"symbol","title":"failedEvents","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedEvents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFailedTelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array containing failed telemetry events."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse\/failedEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedEvents"}],"url":"\/documentation\/docusignapi\/dsapitelemetryeventsresponse\/failedevents"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"failedEvents"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"failedEvents"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DSAPIFailedTelemetryEvent *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"failedEvents"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse\/title","value":"DSAPITelemetryEventsResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse\/fragments","value":[{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent\/title","value":"DSAPIFailedTelemetryEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent\/fragments","value":[{"kind":"identifier","text":"DSAPIFailedTelemetryEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse~1failedEvents\/title","value":"failedEvents"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse~1failedEvents\/fragments","value":[{"kind":"identifier","text":"failedEvents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}