{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"failedEvents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent","text":"DSAPIFailedTelemetryEvent"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitelemetryeventsresponse\/init(failedevents:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapitelemetryeventsresponse\/init(failedevents:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse\/init(failedEvents:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"failedEvents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFailedTelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent"},{"kind":"text","text":"]?)"}],"title":"init(failedEvents:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEventsResponse(im)initWithFailedEvents:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFailedEvents:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEventsResponse/init(failedEvents:)":{"role":"symbol","title":"init(failedEvents:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"failedEvents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFailedTelemetryEvent","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFailedTelemetryEvent"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse\/init(failedEvents:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFailedEvents:"}],"url":"\/documentation\/docusignapi\/dsapitelemetryeventsresponse\/init(failedevents:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFailedTelemetryEvent":{"role":"symbol","title":"DSAPIFailedTelemetryEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFailedTelemetryEvent"}],"abstract":[{"type":"text","text":"This response object is returned after you post a telemetry event."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFailedTelemetryEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFailedTelemetryEvent"}],"url":"\/documentation\/docusignapi\/dsapifailedtelemetryevent"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEventsResponse":{"role":"symbol","title":"DSAPITelemetryEventsResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}],"abstract":[{"type":"text","text":"This response object is returned after you post a telemetry event."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}],"url":"\/documentation\/docusignapi\/dsapitelemetryeventsresponse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFailedEvents:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFailedEvents:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFailedEvents:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIFailedTelemetryEvent *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"failedEvents"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse~1init(failedEvents:)\/title","value":"initWithFailedEvents:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse~1init(failedEvents:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFailedEvents:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent\/title","value":"DSAPIFailedTelemetryEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFailedTelemetryEvent\/fragments","value":[{"kind":"identifier","text":"DSAPIFailedTelemetryEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse\/title","value":"DSAPITelemetryEventsResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse\/fragments","value":[{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}