{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"defaultRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","text":"DSAPIRecipientEmailNotification"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"inPersonSignerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","text":"DSAPIRecipientPhoneNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","preciseIdentifier":"s:11DocuSignAPI31DSAPIRecipientSignatureProviderV","text":"DSAPIRecipientSignatureProvider"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapitemplaterole\/init(accesscode:additionalnotifications:clientuserid:defaultrecipient:email:emailnotification:embeddedrecipientstarturl:inpersonsignername:name:phonenumber:recipientsignatureproviders:rolename:routingorder:signinggroupid:tabs:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRole\/init(accessCode:additionalNotifications:clientUserId:defaultRecipient:email:emailNotification:embeddedRecipientStartURL:inPersonSignerName:name:phoneNumber:recipientSignatureProviders:roleName:routingOrder:signingGroupId:tabs:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"defaultRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inPersonSignerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"s:11DocuSignAPI31DSAPIRecipientSignatureProviderV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?)"}],"title":"init(accessCode:additionalNotifications:clientUserId:defaultRecipient:email:emailNotification:embeddedRecipientStartURL:inPersonSignerName:name:phoneNumber:recipientSignatureProviders:roleName:routingOrder:signingGroupId:tabs:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI17DSAPITemplateRoleC10accessCode23additionalNotifications12clientUserId16defaultRecipient5email0O12Notification08embeddedN8StartURL18inPersonSignerName4name11phoneNumber27recipientSignatureProviders04roleW012routingOrder012signingGroupL04tabsACSSSg_SayAA024DSAPIRecipientAdditionalP0CGSgASSbAsA019DSAPIRecipientEmailP0CSgA3sA019DSAPIRecipientPhoneZ0VSgSayAA31DSAPIRecipientSignatureProviderVGSgA3sA9DSAPITabsCSgtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRole"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateRole/init(accessCode:additionalNotifications:clientUserId:defaultRecipient:email:emailNotification:embeddedRecipientStartURL:inPersonSignerName:name:phoneNumber:recipientSignatureProviders:roleName:routingOrder:signingGroupId:tabs:)":{"role":"symbol","title":"init(accessCode:additionalNotifications:clientUserId:defaultRecipient:email:emailNotification:embeddedRecipientStartURL:inPersonSignerName:name:phoneNumber:recipientSignatureProviders:roleName:routingOrder:signingGroupId:tabs:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"defaultRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inPersonSignerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"s:11DocuSignAPI31DSAPIRecipientSignatureProviderV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRole\/init(accessCode:additionalNotifications:clientUserId:defaultRecipient:email:emailNotification:embeddedRecipientStartURL:inPersonSignerName:name:phoneNumber:recipientSignatureProviders:roleName:routingOrder:signingGroupId:tabs:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapitemplaterole\/init(accesscode:additionalnotifications:clientuserid:defaultrecipient:email:emailnotification:embeddedrecipientstarturl:inpersonsignername:name:phonenumber:recipientsignatureproviders:rolename:routingorder:signinggroupid:tabs:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAdditionalNotification":{"role":"symbol","title":"DSAPIRecipientAdditionalNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"abstract":[{"type":"text","text":"Describes an additional notification method."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"url":"\/documentation\/docusignapi\/dsapirecipientadditionalnotification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientEmailNotification":{"role":"symbol","title":"DSAPIRecipientEmailNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"url":"\/documentation\/docusignapi\/dsapirecipientemailnotification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","title":"DSAPITabs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}],"url":"\/documentation\/docusignapi\/dsapitabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateRole":{"role":"symbol","title":"DSAPITemplateRole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITemplateRole"}],"abstract":[{"type":"text","text":"Information about a specific role."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateRole"}],"url":"\/documentation\/docusignapi\/dsapitemplaterole"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"title":"More information","titleInlineContent":[{"type":"text","text":"More information"}],"type":"link","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneNumber":{"role":"symbol","title":"DSAPIRecipientPhoneNumber","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneNumber"}],"abstract":[{"type":"text","text":"Describes the recipient phone number."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientPhoneNumber"}],"url":"\/documentation\/docusignapi\/dsapirecipientphonenumber"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"role":"symbol","title":"DSAPIRecipientSignatureProvider","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/title","value":"DSAPIRecipientAdditionalNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/title","value":"DSAPIRecipientEmailNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITemplateRole\/title","value":"DSAPITemplateRole"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITemplateRole\/fragments","value":[{"kind":"identifier","text":"DSAPITemplateRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}