{"kind":"symbol","metadata":{"symbolKind":"method","title":"foldersPutFolderByIdWithRequestBuilder(accountId:folderId:body:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"foldersPutFolderByIdWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"folderId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIFoldersRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIFoldersRequestV"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPIFoldersResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFoldersResponse","kind":"typeIdentifier"},{"kind":"text","text":">"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"s:11DocuSignAPI07FoldersC0C38foldersPutFolderByIdWithRequestBuilder07accountI006folderI04bodyAA0kL0CyAA20DSAPIFoldersResponseCGSS_SSAA0pK0VSgtFZ","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/foldersapi\/foldersputfolderbyidwithrequestbuilder(accountid:folderid:body:)"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/FoldersAPI\/foldersPutFolderByIdWithRequestBuilder(accountId:folderId:body:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Moves an envelope from its current folder to the specified folder."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"foldersPutFolderByIdWithRequestBuilder"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"folderId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIFoldersRequestV","text":"DSAPIFoldersRequest"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"text":"DSAPIFoldersResponse","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFoldersResponse"},{"kind":"text","text":">"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}],"name":"accountId"},{"content":[{"type":"paragraph","inlineContent":[{"text":"(path) The ID of the folder being accessed.","type":"text"}]}],"name":"folderId"},{"content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}],"name":"body"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}],"kind":"content"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"PUT \/v2.1\/accounts\/{accountId}\/folders\/{folderId}","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"OAuth:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}]}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/FoldersAPI"]]},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFoldersResponse":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFoldersResponse","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapifoldersresponse","title":"DSAPIFoldersResponse","navigatorTitle":[{"text":"DSAPIFoldersResponse","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/FoldersAPI":{"type":"topic","url":"\/documentation\/docusignapi\/foldersapi","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FoldersAPI"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/FoldersAPI","navigatorTitle":[{"text":"FoldersAPI","kind":"identifier"}],"role":"symbol","title":"FoldersAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/FoldersAPI/foldersPutFolderByIdWithRequestBuilder(accountId:folderId:body:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/FoldersAPI\/foldersPutFolderByIdWithRequestBuilder(accountId:folderId:body:)","abstract":[{"text":"Moves an envelope from its current folder to the specified folder.","type":"text"}],"title":"foldersPutFolderByIdWithRequestBuilder(accountId:folderId:body:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"foldersPutFolderByIdWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"folderId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI19DSAPIFoldersRequestV","kind":"typeIdentifier","text":"DSAPIFoldersRequest"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFoldersResponse","text":"DSAPIFoldersResponse"},{"text":">","kind":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/foldersapi\/foldersputfolderbyidwithrequestbuilder(accountid:folderid:body:)","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFoldersRequest":{"url":"\/documentation\/docusignapi\/dsapifoldersrequest","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DSAPIFoldersRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"Information for a folder request."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIFoldersRequest","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFoldersRequest","title":"DSAPIFoldersRequest"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFoldersResponse\/title","value":"DSAPIFoldersResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFoldersResponse\/fragments","value":[{"kind":"identifier","text":"DSAPIFoldersResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1FoldersAPI\/title","value":"FoldersAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1FoldersAPI\/fragments","value":[{"kind":"identifier","text":"FoldersAPI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}