{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFilter","preciseIdentifier":"s:11DocuSignAPI11DSAPIFilterV","text":"DSAPIFilter"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"folderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"folderItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderItemV2","preciseIdentifier":"s:11DocuSignAPI17DSAPIFolderItemV2V","text":"DSAPIFolderItemV2"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"folders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder","text":"DSAPIFolder"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"hasAccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"hasSubFolders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"itemCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"owner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"parentFolderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"parentFolderUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"subFolderCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapifolder\/init(errordetails:filter:folderid:folderitems:folders:hasaccess:hassubfolders:itemcount:name:owner:parentfolderid:parentfolderuri:subfoldercount:type:uri:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder\/init(errorDetails:filter:folderId:folderItems:folders:hasAccess:hasSubFolders:itemCount:name:owner:parentFolderId:parentFolderUri:subFolderCount:type:uri:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIFilter","preciseIdentifier":"s:11DocuSignAPI11DSAPIFilterV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFolderItemV2","preciseIdentifier":"s:11DocuSignAPI17DSAPIFolderItemV2V"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"folders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFolder","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"hasAccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasSubFolders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"owner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parentFolderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parentFolderUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subFolderCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"title":"init(errorDetails:filter:folderId:folderItems:folders:hasAccess:hasSubFolders:itemCount:name:owner:parentFolderId:parentFolderUri:subFolderCount:type:uri:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI11DSAPIFolderC12errorDetails6filter8folderId0H5Items7folders9hasAccess0L10SubFolders9itemCount4name5owner012parentFolderI00tU3Uri03subuQ04type3uriAcA010DSAPIErrorF0CSg_AA11DSAPIFilterVSgSSSgSayAA0D6ItemV2VGSgSayACGSgS2bA2yA13DSAPIUserInfoCSgAY10Foundation3URLVSgA2YA10_tcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"role":"symbol","title":"DSAPIErrorDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIErrorDetails"}],"abstract":[{"type":"text","text":"This object describes errors that occur. It is only valid for responses and ignored in requests."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"url":"\/documentation\/docusignapi\/dsapierrordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolder":{"role":"symbol","title":"DSAPIFolder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFolder"}],"abstract":[{"type":"text","text":"This object contains details about a folder."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFolder"}],"url":"\/documentation\/docusignapi\/dsapifolder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"role":"symbol","title":"DSAPIUserInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"url":"\/documentation\/docusignapi\/dsapiuserinfo"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFilter":{"role":"symbol","title":"DSAPIFilter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFilter"}],"abstract":[{"type":"text","text":"Use this object to create a filtered view of the items in a folder."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFilter"}],"url":"\/documentation\/docusignapi\/dsapifilter"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolderItemV2":{"role":"symbol","title":"DSAPIFolderItemV2","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFolderItemV2"}],"abstract":[{"type":"text","text":"Information about folder item results."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderItemV2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIFolderItemV2"}],"url":"\/documentation\/docusignapi\/dsapifolderitemv2"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolder/init(errorDetails:filter:folderId:folderItems:folders:hasAccess:hasSubFolders:itemCount:name:owner:parentFolderId:parentFolderUri:subFolderCount:type:uri:)":{"role":"symbol","title":"init(errorDetails:filter:folderId:folderItems:folders:hasAccess:hasSubFolders:itemCount:name:owner:parentFolderId:parentFolderUri:subFolderCount:type:uri:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIFilter","preciseIdentifier":"s:11DocuSignAPI11DSAPIFilterV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"folderItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFolderItemV2","preciseIdentifier":"s:11DocuSignAPI17DSAPIFolderItemV2V"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"folders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIFolder","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"hasAccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasSubFolders"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"owner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parentFolderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parentFolderUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subFolderCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder\/init(errorDetails:filter:folderId:folderItems:folders:hasAccess:hasSubFolders:itemCount:name:owner:parentFolderId:parentFolderUri:subFolderCount:type:uri:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapifolder\/init(errordetails:filter:folderid:folderitems:folders:hasaccess:hassubfolders:itemcount:name:owner:parentfolderid:parentfolderuri:subfoldercount:type:uri:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/title","value":"DSAPIFolder"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/fragments","value":[{"kind":"identifier","text":"DSAPIFolder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title","value":"DSAPIUserInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","value":[{"kind":"identifier","text":"DSAPIUserInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}