{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"langCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure","text":"DSAPIConsumerDisclosure"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}]}]},{"name":"recipientId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The ID of the recipient being accessed."}]}]},{"name":"langCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/consumerdisclosuregetconsumerdisclosureenvelopeidrecipientid(accountid:envelopeid:recipientid:langcode:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/envelopesapi\/consumerdisclosuregetconsumerdisclosureenvelopeidrecipientid(accountid:envelopeid:recipientid:langcode:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the default Electronic Record and Signature Disclosure for an envelope."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"langCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIConsumerDisclosure","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)EnvelopesAPI(cm)consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)":{"role":"symbol","title":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"langCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIConsumerDisclosure","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Gets the default Electronic Record and Signature Disclosure for an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:"}],"url":"\/documentation\/docusignapi\/envelopesapi\/consumerdisclosuregetconsumerdisclosureenvelopeidrecipientid(accountid:envelopeid:recipientid:langcode:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"role":"symbol","title":"EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"url":"\/documentation\/docusignapi\/envelopesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure":{"role":"symbol","title":"DSAPIConsumerDisclosure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"abstract":[{"type":"text","text":"Details about consumer disclosures."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"envelopeId"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"recipientId"},{"kind":"text","text":" "},{"kind":"identifier","text":"langCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"langCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DSAPIConsumerDisclosure *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)\/title","value":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientId(accountId:envelopeId:recipientId:langCode:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"consumerDisclosureGetConsumerDisclosureEnvelopeIdRecipientIdWithAccountId:envelopeId:recipientId:langCode:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/title","value":"DSAPIConsumerDisclosure"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/fragments","value":[{"kind":"identifier","text":"DSAPIConsumerDisclosure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}