{"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/customfieldspostcustomfieldswithrequestbuilder(accountid:envelopeid:body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"sections":[],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customFieldsPostCustomFieldsWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","text":"DSAPICustomFields"},{"kind":"text","text":">"}],"title":"customFieldsPostCustomFieldsWithRequestBuilder(accountId:envelopeId:body:)","externalID":"s:11DocuSignAPI09EnvelopesC0C022customFieldsPostCustomF18WithRequestBuilder9accountId08envelopeM04bodyAA0jK0CyAA011DSAPICustomF0CGSS_SSAKSgtFZ"},"kind":"symbol","abstract":[{"type":"text","text":"Creates envelope custom fields for an envelope."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/customFieldsPostCustomFieldsWithRequestBuilder(accountId:envelopeId:body:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"customFieldsPostCustomFieldsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPICustomFields","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":"? = nil) -> ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","text":"DSAPICustomFields"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}],"name":"accountId"},{"name":"envelopeId","content":[{"inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}],"type":"paragraph"}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"text":"(body)  (optional)","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"POST \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/custom_fields","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"items":[{"content":[{"inlineContent":[{"text":"type: oauth2","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"name: docusignAccessCode","type":"text"}]}]}],"type":"unorderedList"}]}]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/customFieldsPostCustomFieldsWithRequestBuilder(accountId:envelopeId:body:)":{"url":"\/documentation\/docusignapi\/envelopesapi\/customfieldspostcustomfieldswithrequestbuilder(accountid:envelopeid:body:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customFieldsPostCustomFieldsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","text":"DSAPICustomFields"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":">","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Creates envelope custom fields for an envelope."}],"title":"customFieldsPostCustomFieldsWithRequestBuilder(accountId:envelopeId:body:)","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/customFieldsPostCustomFieldsWithRequestBuilder(accountId:envelopeId:body:)","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicustomfields","abstract":[{"type":"text","text":"Contains information about custom fields."}],"title":"DSAPICustomFields","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"value":"EnvelopesAPI","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"EnvelopesAPI"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"},{"value":"DSAPICustomFields","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments","value":[{"kind":"identifier","text":"DSAPICustomFields"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}