{"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/customFieldsPutCustomFields(accountId:envelopeId:body:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"customFieldsPutCustomFields","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"content":[{"inlineContent":[{"text":"(path) The envelopeId Guid of the envelope being accessed.","type":"text"}],"type":"paragraph"}],"name":"envelopeId"},{"name":"body","content":[{"inlineContent":[{"type":"text","text":"(body)  (optional)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/customfieldsputcustomfields(accountid:envelopeid:body:completion:)"]},{"paths":["\/documentation\/docusignapi\/envelopesapi\/customfieldsputcustomfields(accountid:envelopeid:body:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Updates envelope custom fields in an envelope."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)EnvelopesAPI(cm)customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:","role":"symbol","modules":[{"name":"DocuSignAPI"}],"title":"customFieldsPutCustomFields(accountId:envelopeId:body:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"customFieldsPutCustomFields","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"DSAPICustomFields","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","text":"DSAPICustomFields"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"navigatorTitle":[{"kind":"identifier","text":"customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:"}]},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/customFieldsPutCustomFields(accountId:envelopeId:body:completion:)":{"navigatorTitle":[{"text":"customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/envelopesapi\/customfieldsputcustomfields(accountid:envelopeid:body:completion:)","role":"symbol","abstract":[{"type":"text","text":"Updates envelope custom fields in an envelope."}],"title":"customFieldsPutCustomFields(accountId:envelopeId:body:completion:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/customFieldsPutCustomFields(accountId:envelopeId:body:completion:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"customFieldsPutCustomFields","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPICustomFields","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","url":"\/documentation\/docusignapi\/dsapicustomfields","abstract":[{"type":"text","text":"Contains information about custom fields."}],"title":"DSAPICustomFields","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"customFieldsPutCustomFieldsWithAccountId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accountId"},{"text":" ","kind":"text"},{"text":"envelopeId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"envelopeId"},{"kind":"text","text":" "},{"text":"body:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","text":"DSAPICustomFields","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"body"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void (^)(DSAPICustomFields *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPICustomFields#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1customFieldsPutCustomFields(accountId:envelopeId:body:completion:)\/title","op":"replace","value":"customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:"},{"value":[{"text":"+ ","kind":"text"},{"text":"customFieldsPutCustomFieldsWithAccountId:envelopeId:body:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1customFieldsPutCustomFields(accountId:envelopeId:body:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","op":"replace","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","value":"DSAPICustomFields","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPICustomFields"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}