{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentsGetDocuments"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentsByUserid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"includeDocumentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"includeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"includeTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"sharedUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocumentsResult","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocumentsResult","text":"DSAPIEnvelopeDocumentsResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}]}]},{"name":"documentsByUserid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"includeDocumentSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"includeMetadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"includeTabs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"recipientId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"sharedUserId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/documentsgetdocuments(accountid:envelopeid:documentsbyuserid:includedocumentsize:includemetadata:includetabs:recipientid:shareduserid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/envelopesapi\/documentsgetdocuments(accountid:envelopeid:documentsbyuserid:includedocumentsize:includemetadata:includetabs:recipientid:shareduserid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets a list of documents in an envelope."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentsGetDocuments"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentsByUserid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeDocumentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sharedUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDocumentsResult","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocumentsResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DocuSignAPI@objc(cs)EnvelopesAPI(cm)documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)":{"role":"symbol","title":"documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentsGetDocuments"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentsByUserid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeDocumentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includeTabs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sharedUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDocumentsResult","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocumentsResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Gets a list of documents in an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:"}],"url":"\/documentation\/docusignapi\/envelopesapi\/documentsgetdocuments(accountid:envelopeid:documentsbyuserid:includedocumentsize:includemetadata:includetabs:recipientid:shareduserid:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"role":"symbol","title":"EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"url":"\/documentation\/docusignapi\/envelopesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDocumentsResult":{"role":"symbol","title":"DSAPIEnvelopeDocumentsResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDocumentsResult"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDocumentsResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDocumentsResult"}],"url":"\/documentation\/docusignapi\/dsapienvelopedocumentsresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentsGetDocumentsWithAccountId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"envelopeId"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentsByUserid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"documentsByUserid"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeDocumentSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"includeDocumentSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeMetadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"includeMetadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeTabs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"includeTabs"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"recipientId"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedUserId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sharedUserId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DSAPIEnvelopeDocumentsResult *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDocumentsResult#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)\/title","value":"documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1documentsGetDocuments(accountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"documentsGetDocumentsWithAccountId:envelopeId:documentsByUserid:includeDocumentSize:includeMetadata:includeTabs:recipientId:sharedUserId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocumentsResult\/title","value":"DSAPIEnvelopeDocumentsResult"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDocumentsResult\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDocumentsResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}