{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopesGetEnvelopeWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"advancedUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"include"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope","text":"DSAPIEnvelope"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}]}]},{"name":"advancedUpdate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) When true, envelope information can be added or modified. (optional)"}]}]},{"name":"include","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"GET \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/envelopesgetenvelopewithrequestbuilder(accountid:envelopeid:advancedupdate:include:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/envelopesGetEnvelopeWithRequestBuilder(accountId:envelopeId:advancedUpdate:include:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the status of a single envelope."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopesGetEnvelopeWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"advancedUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"include"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIEnvelope","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope"},{"kind":"text","text":">"}],"title":"envelopesGetEnvelopeWithRequestBuilder(accountId:envelopeId:advancedUpdate:include:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:11DocuSignAPI09EnvelopesC0C38envelopesGetEnvelopeWithRequestBuilder9accountId08envelopeL014advancedUpdate7includeAA0iJ0CyAA13DSAPIEnvelopeCGSS_S2SSgANtFZ","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"role":"symbol","title":"EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"url":"\/documentation\/docusignapi\/envelopesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/envelopesGetEnvelopeWithRequestBuilder(accountId:envelopeId:advancedUpdate:include:)":{"role":"symbol","title":"envelopesGetEnvelopeWithRequestBuilder(accountId:envelopeId:advancedUpdate:include:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopesGetEnvelopeWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"advancedUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"include"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIEnvelope","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Gets the status of a single envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/envelopesGetEnvelopeWithRequestBuilder(accountId:envelopeId:advancedUpdate:include:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/envelopesapi\/envelopesgetenvelopewithrequestbuilder(accountid:envelopeid:advancedupdate:include:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"role":"symbol","title":"RequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestBuilder"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"url":"\/documentation\/docusignapi\/requestbuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope":{"role":"symbol","title":"DSAPIEnvelope","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelope"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelope"}],"url":"\/documentation\/docusignapi\/dsapienvelope"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/title","value":"DSAPIEnvelope"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelope"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}