{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopesPostEnvelopesOffline"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","text":"DSAPIEnvelopeDefinition"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"multiParts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]>?, "},{"kind":"externalParam","text":"cdseMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"changeRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completedDocumentsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"mergeRolesOnDraft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"tabLabelExactMatches"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary","text":"DSAPIEnvelopeSummary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]},{"name":"multiParts","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(multiParts) (optional)"}]}]},{"name":"cdseMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"changeRoutingOrder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"completedDocumentsOnly","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) If set to true then we want to set the sourceEnvelopeId to indicate that this is a&quot;forward&quot; envelope action (optional)"}]}]},{"name":"mergeRolesOnDraft","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query) When set to "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":", merges template roles and remove empty recipients when you create an envelope with multiple templates. (optional)"}]}]},{"name":"tabLabelExactMatches","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/envelopespostenvelopesoffline(accountid:body:multiparts:cdsemode:changeroutingorder:completeddocumentsonly:mergerolesondraft:tablabelexactmatches:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/envelopesapi\/envelopespostenvelopesoffline(accountid:body:multiparts:cdsemode:changeroutingorder:completeddocumentsonly:mergerolesondraft:tablabelexactmatches:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an envelope."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopesPostEnvelopesOffline"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"multiParts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]>?, "},{"kind":"externalParam","text":"cdseMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"changeRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completedDocumentsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mergeRolesOnDraft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tabLabelExactMatches"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DocuSignAPI@objc(cs)EnvelopesAPI(cm)envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"role":"symbol","title":"EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"url":"\/documentation\/docusignapi\/envelopesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeDefinition":{"role":"symbol","title":"DSAPIEnvelopeDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"abstract":[{"type":"text","text":"Envelope object definition."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}],"url":"\/documentation\/docusignapi\/dsapienvelopedefinition"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)":{"role":"symbol","title":"envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopesPostEnvelopesOffline"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"multiParts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]>?, "},{"kind":"externalParam","text":"cdseMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"changeRoutingOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completedDocumentsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mergeRolesOnDraft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tabLabelExactMatches"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Creates an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:"}],"url":"\/documentation\/docusignapi\/envelopesapi\/envelopespostenvelopesoffline(accountid:body:multiparts:cdsemode:changeroutingorder:completeddocumentsonly:mergerolesondraft:tablabelexactmatches:completion:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeSummary":{"role":"symbol","title":"DSAPIEnvelopeSummary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeSummary"}],"abstract":[{"type":"text","text":"This object describes an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeSummary"}],"url":"\/documentation\/docusignapi\/dsapienvelopesummary"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"envelopesPostEnvelopesOfflineWithAccountId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accountId"},{"kind":"text","text":" "},{"kind":"identifier","text":"body:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeDefinition","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeDefinition","text":"DSAPIEnvelopeDefinition"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"body"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiParts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSArray *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"multiParts"},{"kind":"text","text":" "},{"kind":"identifier","text":"cdseMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cdseMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRoutingOrder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"changeRoutingOrder"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedDocumentsOnly:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"completedDocumentsOnly"},{"kind":"text","text":" "},{"kind":"identifier","text":"mergeRolesOnDraft:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mergeRolesOnDraft"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabLabelExactMatches:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tabLabelExactMatches"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DSAPIEnvelopeSummary *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIEnvelopeSummary#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/title","value":"DSAPIEnvelopeDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeDefinition\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeDefinition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)\/title","value":"envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1envelopesPostEnvelopesOffline(accountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"envelopesPostEnvelopesOfflineWithAccountId:body:multiParts:cdseMode:changeRoutingOrder:completedDocumentsOnly:mergeRolesOnDraft:tabLabelExactMatches:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeSummary\/title","value":"DSAPIEnvelopeSummary"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeSummary\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeSummary"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}