{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/lockpostenvelopelock(accountid:envelopeid:body:locktoken:completion:)"]}],"metadata":{"symbolKind":"method","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lockPostEnvelopeLock","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI16DSAPILockRequestV","text":"DSAPILockRequest"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DSAPILockInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"externalID":"s:11DocuSignAPI09EnvelopesC0C20lockPostEnvelopeLock9accountId08envelopeJ04body0E5Token10completionySS_SSAA16DSAPILockRequestVSgSSyAA0O11InformationCSg_s5Error_pSgtctFZ","role":"symbol","title":"lockPostEnvelopeLock(accountId:envelopeId:body:lockToken:completion:)"},"abstract":[{"type":"text","text":"Locks an envelope."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockPostEnvelopeLock"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockRequest","text":"DSAPILockRequest","preciseIdentifier":"s:11DocuSignAPI16DSAPILockRequestV","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"lockToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","kind":"typeIdentifier","text":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}]},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The envelopeId Guid of the envelope being accessed.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}],"name":"body"},{"content":[{"inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/lockPostEnvelopeLock(accountId:envelopeId:body:lockToken:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockRequest":{"url":"\/documentation\/docusignapi\/dsapilockrequest","title":"DSAPILockRequest","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPILockRequest","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPILockRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"This request object contains information about the lock that you want to create or update."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/lockPostEnvelopeLock(accountId:envelopeId:body:lockToken:completion:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Locks an envelope."}],"title":"lockPostEnvelopeLock(accountId:envelopeId:body:lockToken:completion:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/lockPostEnvelopeLock(accountId:envelopeId:body:lockToken:completion:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lockPostEnvelopeLock","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"DSAPILockRequest","preciseIdentifier":"s:11DocuSignAPI16DSAPILockRequestV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","kind":"typeIdentifier","text":"DSAPILockInformation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}],"url":"\/documentation\/docusignapi\/envelopesapi\/lockpostenvelopelock(accountid:envelopeid:body:locktoken:completion:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation":{"url":"\/documentation\/docusignapi\/dsapilockinformation","title":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILockInformation"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPILockInformation"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI","op":"replace"},{"value":[{"kind":"identifier","text":"EnvelopesAPI"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/title","value":"DSAPILockInformation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/fragments","value":[{"text":"DSAPILockInformation","kind":"identifier"}]}]}]}