{"metadata":{"symbolKind":"method","modules":[{"name":"DocuSignAPI"}],"externalID":"s:11DocuSignAPI09EnvelopesC0C37lockGetEnvelopeLockWithRequestBuilder9accountId08envelopeM0AA0jK0CyAA20DSAPILockInformationCGSS_SStFZ","title":"lockGetEnvelopeLockWithRequestBuilder(accountId:envelopeId:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lockGetEnvelopeLockWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","text":"DSAPILockInformation","kind":"typeIdentifier"},{"kind":"text","text":">"}],"role":"symbol","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/lockGetEnvelopeLockWithRequestBuilder(accountId:envelopeId:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/lockgetenvelopelockwithrequestbuilder(accountid:envelopeid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockGetEnvelopeLockWithRequestBuilder"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","kind":"typeIdentifier","text":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation"},{"text":">","kind":"text"}]}]},{"parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}],"type":"paragraph"}],"name":"envelopeId"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"GET \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/lock","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OAuth:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"type: oauth2"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"name: docusignAccessCode","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"kind":"content"}],"abstract":[{"text":"Gets envelope lock information.","type":"text"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/lockGetEnvelopeLockWithRequestBuilder(accountId:envelopeId:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/lockGetEnvelopeLockWithRequestBuilder(accountId:envelopeId:)","type":"topic","title":"lockGetEnvelopeLockWithRequestBuilder(accountId:envelopeId:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lockGetEnvelopeLockWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","kind":"typeIdentifier","text":"DSAPILockInformation"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"Gets envelope lock information."}],"role":"symbol","kind":"symbol","url":"\/documentation\/docusignapi\/envelopesapi\/lockgetenvelopelockwithrequestbuilder(accountid:envelopeid:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation":{"url":"\/documentation\/docusignapi\/dsapilockinformation","title":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILockInformation"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPILockInformation"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"EnvelopesAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"EnvelopesAPI"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"},{"op":"replace","value":"DSAPILockInformation","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/fragments","value":[{"text":"DSAPILockInformation","kind":"identifier"}],"op":"replace"}]}]}