{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeNotificationRequest","preciseIdentifier":"s:11DocuSignAPI32DSAPIEnvelopeNotificationRequestV","text":"DSAPIEnvelopeNotificationRequest"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotification","text":"DSAPINotification"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PUT \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/notification"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/notificationputenvelopesenvelopeidnotificationwithrequestbuilder(accountid:envelopeid:body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder(accountId:envelopeId:body:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets envelope notifications for an existing envelope."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeNotificationRequest","preciseIdentifier":"s:11DocuSignAPI32DSAPIEnvelopeNotificationRequestV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPINotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotification"},{"kind":"text","text":">"}],"title":"notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder(accountId:envelopeId:body:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:11DocuSignAPI09EnvelopesC0C015notificationPutD40EnvelopeIdNotificationWithRequestBuilder07accountH008envelopeH04bodyAA0kL0CyAA17DSAPINotificationCGSS_SSAA013DSAPIEnvelopeiK0VSgtFZ","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"role":"symbol","title":"RequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestBuilder"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"url":"\/documentation\/docusignapi\/requestbuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder(accountId:envelopeId:body:)":{"role":"symbol","title":"notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder(accountId:envelopeId:body:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIEnvelopeNotificationRequest","preciseIdentifier":"s:11DocuSignAPI32DSAPIEnvelopeNotificationRequestV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPINotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPINotification"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Sets envelope notifications for an existing envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/notificationPutEnvelopesEnvelopeIdNotificationWithRequestBuilder(accountId:envelopeId:body:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/envelopesapi\/notificationputenvelopesenvelopeidnotificationwithrequestbuilder(accountid:envelopeid:body:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"role":"symbol","title":"EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"url":"\/documentation\/docusignapi\/envelopesapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeNotificationRequest":{"role":"symbol","title":"DSAPIEnvelopeNotificationRequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeNotificationRequest"}],"abstract":[{"type":"text","text":"A complex element that specifies the notification settings for the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeNotificationRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeNotificationRequest"}],"url":"\/documentation\/docusignapi\/dsapienvelopenotificationrequest"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotification":{"role":"symbol","title":"DSAPINotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPINotification"}],"abstract":[{"type":"text","text":"A complex element that specifies the notification settings for the envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPINotification"}],"url":"\/documentation\/docusignapi\/dsapinotification"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification\/title","value":"DSAPINotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotification\/fragments","value":[{"kind":"identifier","text":"DSAPINotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}