{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientTabsWithRequestBuilder(accountId:envelopeId:recipientId:body:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"metadata":{"externalID":"s:11DocuSignAPI09EnvelopesC0C44recipientsPutRecipientTabsWithRequestBuilder9accountId08envelopeM009recipientM04bodyAA0jK0CyAA9DSAPITabsCGSS_S2SALSgtFZ","roleHeading":"Type Method","role":"symbol","symbolKind":"method","modules":[{"name":"DocuSignAPI"}],"title":"recipientsPutRecipientTabsWithRequestBuilder(accountId:envelopeId:recipientId:body:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientsPutRecipientTabsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"text":"<","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":">"}]},"kind":"symbol","abstract":[{"type":"text","text":"Updates the tabs for a recipient."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recipientsPutRecipientTabsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier","text":"DSAPITabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"},{"kind":"text","text":">"}]}]},{"parameters":[{"name":"accountId","content":[{"inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}],"type":"paragraph"}]},{"name":"envelopeId","content":[{"inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}],"type":"paragraph"}]},{"name":"recipientId","content":[{"inlineContent":[{"text":"(path) The ID of the recipient being accessed.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(body)  (optional)","type":"text"}]}],"name":"body"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PUT \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/recipients\/{recipientId}\/tabs"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"name: docusignAccessCode","type":"text"}]}]}]}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipienttabswithrequestbuilder(accountid:envelopeid:recipientid:body:)"]}],"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/recipientsPutRecipientTabsWithRequestBuilder(accountId:envelopeId:recipientId:body:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Updates the tabs for a recipient."}],"title":"recipientsPutRecipientTabsWithRequestBuilder(accountId:envelopeId:recipientId:body:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientTabsWithRequestBuilder(accountId:envelopeId:recipientId:body:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsPutRecipientTabsWithRequestBuilder"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":">"}],"url":"\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipienttabswithrequestbuilder(accountid:envelopeid:recipientid:body:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DSAPITabs","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","op":"replace","value":[{"text":"DSAPITabs","kind":"identifier"}]},{"value":"EnvelopesAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","op":"replace","value":[{"kind":"identifier","text":"EnvelopesAPI"}]}]}]}