{"metadata":{"role":"symbol","navigatorTitle":[{"text":"recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)EnvelopesAPI(cm)recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:","roleHeading":"Type Method","title":"recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)","modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recipientsPutRecipientInitialsImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"recipientId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsPutRecipientInitialsImage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipientId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"accountId","content":[{"inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}],"type":"paragraph"}],"name":"envelopeId"},{"content":[{"inlineContent":[{"text":"(path) The ID of the recipient being accessed.","type":"text"}],"type":"paragraph"}],"name":"recipientId"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"completion handler to receive the data and the error objects","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientinitialsimage(accountid:envelopeid:recipientid:image:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientinitialsimage(accountid:envelopeid:recipientid:image:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"abstract":[{"type":"text","text":"Sets the initials image for an accountless signer."}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Sets the initials image for an accountless signer."}],"navigatorTitle":[{"text":"recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:","kind":"identifier"}],"title":"recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsPutRecipientInitialsImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"url":"\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientinitialsimage(accountid:envelopeid:recipientid:image:completion:)","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"recipientsPutRecipientInitialsImageWithAccountId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accountId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"envelopeId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"recipientId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)\/title","value":"recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1recipientsPutRecipientInitialsImage(accountId:envelopeId:recipientId:image:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"recipientsPutRecipientInitialsImageWithAccountId:envelopeId:recipientId:image:completion:"}],"op":"replace"},{"op":"replace","value":"EnvelopesAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title"},{"value":[{"text":"EnvelopesAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"}]}]}