{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsPutRecipientsOffline"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"typeIdentifier","text":"DSAPIRecipients"},{"kind":"text","text":"? = nil, "},{"text":"multiParts","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"text":"Any","kind":"keyword"},{"text":"]>?, ","kind":"text"},{"text":"combineSameOrderRecipients","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"offlineSigning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"resendEnvelope"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary","text":"DSAPIRecipientsUpdateSummary","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":"))","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}]},{"name":"envelopeId","content":[{"inlineContent":[{"text":"(path) The envelopeId Guid of the envelope being accessed.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"(body)  (optional)","type":"text"}],"type":"paragraph"}],"name":"body"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(multiParts) (optional)"}]}],"name":"multiParts"},{"name":"combineSameOrderRecipients","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}]},{"name":"offlineSigning","content":[{"type":"paragraph","inlineContent":[{"text":"(query)  (optional)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"(query) When set to "},{"type":"strong","inlineContent":[{"text":"true","type":"text"}]},{"type":"text","text":", resends the   envelope if the new recipient's routing order is before or the same as the envelope's next recipient. (optional)"}],"type":"paragraph"}],"name":"resendEnvelope"},{"content":[{"inlineContent":[{"text":"completion handler to receive the data and the error objects","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientsoffline(accountid:envelopeid:body:multiparts:combinesameorderrecipients:offlinesigning:resendenvelope:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientsoffline(accountid:envelopeid:body:multiparts:combinesameorderrecipients:offlinesigning:resendenvelope:completion:)"]}],"metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"text":"recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:","kind":"identifier"}],"extendedModule":"DocuSignAPI","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recipientsPutRecipientsOffline","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","text":"DSAPIRecipients","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"multiParts"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SD","kind":"typeIdentifier","text":"Dictionary"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"text":"Any","kind":"keyword"},{"text":"]>?, ","kind":"text"},{"text":"combineSameOrderRecipients","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offlineSigning"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"resendEnvelope"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientsUpdateSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}],"title":"recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)","externalID":"c:@CM@DocuSignAPI@objc(cs)EnvelopesAPI(cm)recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:"},"abstract":[{"type":"text","text":"Updates recipients in a draft envelope or corrects recipient information for an in-process envelope."}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipients","kind":"identifier"}],"abstract":[{"text":"Specifies the envelope recipients.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapirecipients","title":"DSAPIRecipients","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPIRecipients","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientsUpdateSummary":{"url":"\/documentation\/docusignapi\/dsapirecipientsupdatesummary","navigatorTitle":[{"text":"DSAPIRecipientsUpdateSummary","kind":"identifier"}],"kind":"symbol","title":"DSAPIRecipientsUpdateSummary","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientsUpdateSummary"}],"type":"topic","abstract":[{"type":"text","text":"This is the response that the API returns after you update recipients."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Updates recipients in a draft envelope or corrects recipient information for an in-process envelope."}],"navigatorTitle":[{"kind":"identifier","text":"recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:"}],"title":"recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recipientsPutRecipientsOffline","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","kind":"typeIdentifier","text":"DSAPIRecipients"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"multiParts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", ["},{"text":"Any","kind":"keyword"},{"text":"]>?, ","kind":"text"},{"text":"combineSameOrderRecipients","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"offlineSigning","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"resendEnvelope","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientsUpdateSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"url":"\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientsoffline(accountid:envelopeid:body:multiparts:combinesameorderrecipients:offlinesigning:resendenvelope:completion:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"recipientsPutRecipientsOfflineWithAccountId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accountId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"envelopeId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"envelopeId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"body:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","text":"DSAPIRecipients","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"},{"kind":"text","text":" *) "},{"text":"body","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"multiParts:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSArray *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"multiParts"},{"text":" ","kind":"text"},{"text":"combineSameOrderRecipients:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"combineSameOrderRecipients"},{"kind":"text","text":" "},{"text":"offlineSigning:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"offlineSigning"},{"kind":"text","text":" "},{"text":"resendEnvelope:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"resendEnvelope"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary#*$objc(cs)NSError)","text":"void (^)(DSAPIRecipientsUpdateSummary *, NSError *)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","op":"replace","value":"EnvelopesAPI"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"text":"EnvelopesAPI","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title","value":"DSAPIRecipients"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","value":[{"text":"DSAPIRecipients","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary\/title","op":"replace","value":"DSAPIRecipientsUpdateSummary"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary\/fragments","value":[{"text":"DSAPIRecipientsUpdateSummary","kind":"identifier"}],"op":"replace"},{"value":"recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1recipientsPutRecipientsOffline(accountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"recipientsPutRecipientsOfflineWithAccountId:envelopeId:body:multiParts:combineSameOrderRecipients:offlineSigning:resendEnvelope:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}