{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsPutRecipientsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients","kind":"typeIdentifier","text":"DSAPIRecipients","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"combineSameOrderRecipients"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"offlineSigning","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"resendEnvelope","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil) -> ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPIRecipientsUpdateSummary","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}],"name":"accountId"},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The envelopeId Guid of the envelope being accessed.","type":"text"}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]},{"name":"combineSameOrderRecipients","content":[{"type":"paragraph","inlineContent":[{"text":"(query)  (optional)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(query)  (optional)"}]}],"name":"offlineSigning"},{"content":[{"type":"paragraph","inlineContent":[{"text":"(query) When set to ","type":"text"},{"inlineContent":[{"text":"true","type":"text"}],"type":"strong"},{"text":", resends the   envelope if the new recipient's routing order is before or the same as the envelope's next recipient. (optional)","type":"text"}]}],"name":"resendEnvelope"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PUT \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/recipients"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"kind":"content"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientswithrequestbuilder(accountid:envelopeid:body:combinesameorderrecipients:offlinesigning:resendenvelope:)"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientsWithRequestBuilder(accountId:envelopeId:body:combineSameOrderRecipients:offlineSigning:resendEnvelope:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recipientsPutRecipientsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients","text":"DSAPIRecipients","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"combineSameOrderRecipients","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"offlineSigning","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"resendEnvelope"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIRecipientsUpdateSummary","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary"},{"text":">","kind":"text"}],"title":"recipientsPutRecipientsWithRequestBuilder(accountId:envelopeId:body:combineSameOrderRecipients:offlineSigning:resendEnvelope:)","externalID":"s:11DocuSignAPI09EnvelopesC0C41recipientsPutRecipientsWithRequestBuilder9accountId08envelopeL04body016combineSameOrderG014offlineSigning14resendEnvelopeAA0iJ0CyAA28DSAPIRecipientsUpdateSummaryCGSS_SSAA0V0CSgSSSgA2StFZ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"abstract":[{"type":"text","text":"Updates recipients in a draft envelope or corrects recipient information for an in-process envelope."}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/recipientsPutRecipientsWithRequestBuilder(accountId:envelopeId:body:combineSameOrderRecipients:offlineSigning:resendEnvelope:)":{"url":"\/documentation\/docusignapi\/envelopesapi\/recipientsputrecipientswithrequestbuilder(accountid:envelopeid:body:combinesameorderrecipients:offlinesigning:resendenvelope:)","kind":"symbol","title":"recipientsPutRecipientsWithRequestBuilder(accountId:envelopeId:body:combineSameOrderRecipients:offlineSigning:resendEnvelope:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/recipientsPutRecipientsWithRequestBuilder(accountId:envelopeId:body:combineSameOrderRecipients:offlineSigning:resendEnvelope:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientsPutRecipientsWithRequestBuilder"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"DSAPIRecipients","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipients"},{"text":"?, ","kind":"text"},{"text":"combineSameOrderRecipients","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"offlineSigning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"resendEnvelope"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary","text":"DSAPIRecipientsUpdateSummary"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Updates recipients in a draft envelope or corrects recipient information for an in-process envelope."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipients":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipients","kind":"identifier"}],"abstract":[{"text":"Specifies the envelope recipients.","type":"text"}],"url":"\/documentation\/docusignapi\/dsapirecipients","title":"DSAPIRecipients","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPIRecipients","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipients"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientsUpdateSummary":{"url":"\/documentation\/docusignapi\/dsapirecipientsupdatesummary","navigatorTitle":[{"text":"DSAPIRecipientsUpdateSummary","kind":"identifier"}],"kind":"symbol","title":"DSAPIRecipientsUpdateSummary","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientsUpdateSummary"}],"type":"topic","abstract":[{"type":"text","text":"This is the response that the API returns after you update recipients."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"EnvelopesAPI","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"value":"DSAPIRecipients","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipients\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipients"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary\/title","value":"DSAPIRecipientsUpdateSummary"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIRecipientsUpdateSummary"}]}]}]}