{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/tabspostdocumenttabs(accountid:documentid:envelopeid:body:completion:)"]},{"paths":["\/documentation\/docusignapi\/envelopesapi\/tabspostdocumenttabs(accountid:documentid:envelopeid:body:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"abstract":[{"text":"Adds tabs to a document in an envelope.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:","kind":"identifier"}],"roleHeading":"Type Method","title":"tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tabsPostDocumentTabs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)EnvelopesAPI(cm)tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabsPostDocumentTabs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier","text":"DSAPITabs"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(path) The ID of the document being accessed.","type":"text"}]}],"name":"documentId"},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The envelopeId Guid of the envelope being accessed.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}],"name":"body"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"completion handler to receive the data and the error objects"}]}],"name":"completion"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Adds tabs to a document in an envelope."}],"navigatorTitle":[{"text":"tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:","kind":"identifier"}],"title":"tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tabsPostDocumentTabs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"documentId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier","text":"DSAPITabs"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"url":"\/documentation\/docusignapi\/envelopesapi\/tabspostdocumenttabs(accountid:documentid:envelopeid:body:completion:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"tabsPostDocumentTabsWithAccountId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accountId"},{"text":" ","kind":"text"},{"text":"documentId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"envelopeId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"body:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"body"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)DSAPITabs#*$objc(cs)NSError)","kind":"typeIdentifier","text":"void (^)(DSAPITabs *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DSAPITabs","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title"},{"value":[{"kind":"identifier","text":"DSAPITabs"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","op":"replace","value":"EnvelopesAPI"},{"value":[{"text":"EnvelopesAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)\/title","op":"replace","value":"tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:"},{"value":[{"kind":"text","text":"+ "},{"text":"tabsPostDocumentTabsWithAccountId:documentId:envelopeId:body:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI~1tabsPostDocumentTabs(accountId:documentId:envelopeId:body:completion:)\/fragments","op":"replace"}]}]}