{"abstract":[{"type":"text","text":"Updates the tabs for document."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/tabsputdocumenttabswithrequestbuilder(accountid:documentid:envelopeid:body:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/tabsPutDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)"},"metadata":{"externalID":"s:11DocuSignAPI09EnvelopesC0C37tabsPutDocumentTabsWithRequestBuilder9accountId08documentM008envelopeM04bodyAA0jK0CyAA9DSAPITabsCGSS_S2SALSgtFZ","symbolKind":"method","title":"tabsPutDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tabsPutDocumentTabsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier","text":"DSAPITabs"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs","kind":"typeIdentifier"},{"text":">","kind":"text"}],"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tabsPutDocumentTabsWithRequestBuilder"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":"? = nil) -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}]}]},{"name":"documentId","content":[{"inlineContent":[{"type":"text","text":"(path) The ID of the document being accessed."}],"type":"paragraph"}]},{"name":"envelopeId","content":[{"inlineContent":[{"text":"(path) The envelopeId Guid of the envelope being accessed.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(body)  (optional)","type":"text"}]}],"name":"body"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"PUT \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/documents\/{documentId}\/tabs","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"OAuth:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}]}]}]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/tabsPutDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Updates the tabs for document."}],"title":"tabsPutDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/tabsPutDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabsPutDocumentTabsWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"documentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":">"}],"url":"\/documentation\/docusignapi\/envelopesapi\/tabsputdocumenttabswithrequestbuilder(accountid:documentid:envelopeid:body:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPITabs"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}