{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Type Method","role":"symbol","title":"tabsDeleteDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","symbolKind":"method","externalID":"s:11DocuSignAPI09EnvelopesC0C40tabsDeleteDocumentTabsWithRequestBuilder9accountId08documentM008envelopeM04bodyAA0jK0CyAA9DSAPITabsCGSS_S2SALSgtFZ","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tabsDeleteDocumentTabsWithRequestBuilder"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"documentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"envelopeId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":">","kind":"text"}],"modules":[{"name":"DocuSignAPI"}]},"kind":"symbol","abstract":[{"text":"Deletes tabs from a document in an envelope.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/tabsdeletedocumenttabswithrequestbuilder(accountid:documentid:envelopeid:body:)"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/tabsDeleteDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tabsDeleteDocumentTabsWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"documentId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"documentId","content":[{"inlineContent":[{"text":"(path) The ID of the document being accessed.","type":"text"}],"type":"paragraph"}]},{"name":"envelopeId","content":[{"inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"(body)  (optional)"}],"type":"paragraph"}],"name":"body"}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"DELETE \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/documents\/{documentId}\/tabs"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"name: docusignAccessCode"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/tabsDeleteDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabsDeleteDocumentTabsWithRequestBuilder"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?) -> "},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":">","kind":"text"}],"title":"tabsDeleteDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Deletes tabs from a document in an envelope."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/tabsDeleteDocumentTabsWithRequestBuilder(accountId:documentId:envelopeId:body:)","url":"\/documentation\/docusignapi\/envelopesapi\/tabsdeletedocumenttabswithrequestbuilder(accountid:documentid:envelopeid:body:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","op":"replace","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"text":"EnvelopesAPI","kind":"identifier"}]}]}]}