{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewsPostAccountConsoleViewWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsoleViewRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPIConsoleViewRequestV","text":"DSAPIConsoleViewRequest"},{"text":"? = nil) -> ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"text":"DSAPIViewUrl","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},{"parameters":[{"name":"accountId","content":[{"inlineContent":[{"text":"(path) The external account number (int) or account ID Guid.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(body)  (optional)","type":"text"}]}],"name":"body"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"RequestBuilder"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"POST \/v2.1\/accounts\/{accountId}\/views\/console","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Returns a URL to the authentication view UI.","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","externalID":"s:11DocuSignAPI09EnvelopesC0C45viewsPostAccountConsoleViewWithRequestBuilder9accountId4bodyAA0kL0CyAA12DSAPIViewUrlCGSS_AA012DSAPIConsoleiK0VSgtFZ","modules":[{"name":"DocuSignAPI"}],"roleHeading":"Type Method","title":"viewsPostAccountConsoleViewWithRequestBuilder(accountId:body:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewsPostAccountConsoleViewWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPIConsoleViewRequestV","text":"DSAPIConsoleViewRequest"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","kind":"typeIdentifier"},{"text":">","kind":"text"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/viewsPostAccountConsoleViewWithRequestBuilder(accountId:body:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/envelopesapi\/viewspostaccountconsoleviewwithrequestbuilder(accountid:body:)"]}],"sections":[],"references":{"/docs/esign-rest-api/reference/envelopes/envelopeviews/createconsole/":{"title":"EnvelopeViews: createConsole","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createconsole\/","type":"link","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createConsole"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createconsole\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/viewsPostAccountConsoleViewWithRequestBuilder(accountId:body:)":{"type":"topic","role":"symbol","abstract":[{"text":"Returns a URL to the authentication view UI.","type":"text"}],"title":"viewsPostAccountConsoleViewWithRequestBuilder(accountId:body:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/viewsPostAccountConsoleViewWithRequestBuilder(accountId:body:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewsPostAccountConsoleViewWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIConsoleViewRequest","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPIConsoleViewRequestV"},{"text":"?) -> ","kind":"text"},{"text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/docusignapi\/envelopesapi\/viewspostaccountconsoleviewwithrequestbuilder(accountid:body:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsoleViewRequest":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The request object for the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createconsole\/"},{"text":" method.","type":"text"}],"navigatorTitle":[{"text":"DSAPIConsoleViewRequest","kind":"identifier"}],"title":"DSAPIConsoleViewRequest","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsoleViewRequest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIConsoleViewRequest","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiconsoleviewrequest","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl":{"url":"\/documentation\/docusignapi\/dsapiviewurl","navigatorTitle":[{"text":"DSAPIViewUrl","kind":"identifier"}],"kind":"symbol","title":"DSAPIViewUrl","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIViewUrl"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"value":[{"text":"EnvelopesAPI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"},{"value":"DSAPIViewUrl","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/title"},{"value":[{"text":"DSAPIViewUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}