{"kind":"symbol","abstract":[{"text":"Returns a URL to the edit view UI.","type":"text"}],"metadata":{"roleHeading":"Type Method","symbolKind":"method","role":"symbol","title":"viewsPostEnvelopeEditViewWithRequestBuilder(accountId:envelopeId:body:)","modules":[{"name":"DocuSignAPI"}],"externalID":"s:11DocuSignAPI09EnvelopesC0C43viewsPostEnvelopeEditViewWithRequestBuilder9accountId08envelopeN04bodyAA0kL0CyAA12DSAPIViewUrlCGSS_SSAA011DSAPIReturnrK0VSgtFZ","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewsPostEnvelopeEditViewWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI21DSAPIReturnUrlRequestV","text":"DSAPIReturnUrlRequest"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","text":"RequestBuilder"},{"text":"<","kind":"text"},{"text":"DSAPIViewUrl","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl"},{"kind":"text","text":">"}]},"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/viewspostenvelopeeditviewwithrequestbuilder(accountid:envelopeid:body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewsPostEnvelopeEditViewWithRequestBuilder","kind":"identifier"},{"kind":"text","text":"("},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIReturnUrlRequest","preciseIdentifier":"s:11DocuSignAPI21DSAPIReturnUrlRequestV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReturnUrlRequest","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"text":"RequestBuilder","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},{"text":"<","kind":"text"},{"text":"DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}],"type":"paragraph"}],"name":"accountId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}]}],"name":"envelopeId"},{"content":[{"type":"paragraph","inlineContent":[{"text":"(body)  (optional)","type":"text"}]}],"name":"body"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"text":"POST \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/views\/edit","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OAuth:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"type: oauth2","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}],"type":"unorderedList"}]}],"type":"unorderedList"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/viewsPostEnvelopeEditViewWithRequestBuilder(accountId:envelopeId:body:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"url":"\/documentation\/docusignapi\/envelopesapi","title":"EnvelopesAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/viewsPostEnvelopeEditViewWithRequestBuilder(accountId:envelopeId:body:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns a URL to the edit view UI."}],"title":"viewsPostEnvelopeEditViewWithRequestBuilder(accountId:envelopeId:body:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/viewsPostEnvelopeEditViewWithRequestBuilder(accountId:envelopeId:body:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewsPostEnvelopeEditViewWithRequestBuilder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"envelopeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI21DSAPIReturnUrlRequestV","kind":"typeIdentifier","text":"DSAPIReturnUrlRequest"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","kind":"typeIdentifier","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","text":"DSAPIViewUrl"},{"kind":"text","text":">"}],"url":"\/documentation\/docusignapi\/envelopesapi\/viewspostenvelopeeditviewwithrequestbuilder(accountid:envelopeid:body:)","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl":{"url":"\/documentation\/docusignapi\/dsapiviewurl","navigatorTitle":[{"text":"DSAPIViewUrl","kind":"identifier"}],"kind":"symbol","title":"DSAPIViewUrl","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIViewUrl"}],"type":"topic","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"url":"\/documentation\/docusignapi\/requestbuilder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"title":"RequestBuilder","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestBuilder"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIReturnUrlRequest":{"abstract":[{"type":"text","text":"The request body for the "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsender\/"},{"type":"text","text":" method."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIReturnUrlRequest","kind":"identifier"}],"title":"DSAPIReturnUrlRequest","kind":"symbol","navigatorTitle":[{"text":"DSAPIReturnUrlRequest","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReturnUrlRequest","type":"topic","url":"\/documentation\/docusignapi\/dsapireturnurlrequest","role":"symbol"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsender/":{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsender\/","title":"EnvelopeViews: createSender","type":"link","titleInlineContent":[{"text":"EnvelopeViews: createSender","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsender\/"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","value":[{"text":"EnvelopesAPI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/title","value":"DSAPIViewUrl"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/fragments","value":[{"kind":"identifier","text":"DSAPIViewUrl"}],"op":"replace"}]}]}