{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewsPostEnvelopeRecipientViewWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest","text":"DSAPIRecipientViewRequest"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl","text":"DSAPIViewUrl"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"envelopeId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The envelopeId Guid of the envelope being accessed."}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"POST \/v2.1\/accounts\/{accountId}\/envelopes\/{envelopeId}\/views\/recipient"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/envelopesapi\/viewspostenveloperecipientviewwithrequestbuilder(accountid:envelopeid:body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/viewsPostEnvelopeRecipientViewWithRequestBuilder(accountId:envelopeId:body:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a URL to the recipient view UI."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewsPostEnvelopeRecipientViewWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl"},{"kind":"text","text":">"}],"title":"viewsPostEnvelopeRecipientViewWithRequestBuilder(accountId:envelopeId:body:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:11DocuSignAPI09EnvelopesC0C48viewsPostEnvelopeRecipientViewWithRequestBuilder9accountId08envelopeN04bodyAA0kL0CyAA12DSAPIViewUrlCGSS_SSAA014DSAPIRecipientiK0CSgtFZ","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI":{"role":"symbol","title":"EnvelopesAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvelopesAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnvelopesAPI"}],"url":"\/documentation\/docusignapi\/envelopesapi"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createsharedrecipient/":{"title":"EnvelopeViews: createSharedRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createSharedRecipient"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"role":"symbol","title":"RequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestBuilder"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"url":"\/documentation\/docusignapi\/requestbuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/EnvelopesAPI/viewsPostEnvelopeRecipientViewWithRequestBuilder(accountId:envelopeId:body:)":{"role":"symbol","title":"viewsPostEnvelopeRecipientViewWithRequestBuilder(accountId:envelopeId:body:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewsPostEnvelopeRecipientViewWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientViewRequest","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientViewRequest"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPIViewUrl","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIViewUrl"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns a URL to the recipient view UI."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/EnvelopesAPI\/viewsPostEnvelopeRecipientViewWithRequestBuilder(accountId:envelopeId:body:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/envelopesapi\/viewspostenveloperecipientviewwithrequestbuilder(accountid:envelopeid:body:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientViewRequest":{"role":"symbol","title":"DSAPIRecipientViewRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"abstract":[{"type":"text","text":"The request body for the "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createsharedrecipient\/"},{"type":"text","text":" methods."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientViewRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}],"url":"\/documentation\/docusignapi\/dsapirecipientviewrequest"},"/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/":{"title":"EnvelopeViews: createRecipient","titleInlineContent":[{"type":"text","text":"EnvelopeViews: createRecipient"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/","url":"\/docs\/esign-rest-api\/reference\/envelopes\/envelopeviews\/createrecipient\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIViewUrl":{"role":"symbol","title":"DSAPIViewUrl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIViewUrl"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIViewUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIViewUrl"}],"url":"\/documentation\/docusignapi\/dsapiviewurl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/title","value":"EnvelopesAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1EnvelopesAPI\/fragments","value":[{"kind":"identifier","text":"EnvelopesAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/title","value":"DSAPIRecipientViewRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientViewRequest\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientViewRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/title","value":"DSAPIViewUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIViewUrl\/fragments","value":[{"kind":"identifier","text":"DSAPIViewUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}