{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientattachment\/remoteurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipientattachment\/remoteurl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment\/remoteUrl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The URL of a previously staged chunked upload. Using a chunked upload enables you to stage a large, chunkable temp file. You then use the `remoteUrl` property to reference the chunked upload as the content in attachment and document-related requests. The `remoteUrl` property cannot be used for downloads."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"title":"remoteUrl","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment(py)remoteUrl","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"remoteUrl"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment":{"role":"symbol","title":"DSAPIRecipientAttachment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientAttachment"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAttachment"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment/remoteUrl":{"role":"symbol","title":"remoteUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The URL of a previously staged chunked upload. Using a chunked upload enables you to stage a large, chunkable temp file. You then use the `remoteUrl` property to reference the chunked upload as the content in attachment and document-related requests. The `remoteUrl` property cannot be used for downloads."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment\/remoteUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteUrl"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment\/remoteurl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"remoteUrl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"remoteUrl"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"remoteUrl"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/title","value":"DSAPIRecipientAttachment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientAttachment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment~1remoteUrl\/title","value":"remoteUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment~1remoteUrl\/fragments","value":[{"kind":"identifier","text":"remoteUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}