{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"accessCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"accessCodeMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"additionalNotifications"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"allowSystemOverrideForLockedRecipient"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"autoRespondedReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"completedCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"customFields"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"declinedDateTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"declinedReason"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"deliveredDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"deliveryMethodMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"designatorId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"designatorIdGuid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"documentVisibility"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","text":"DSAPIDocumentVisibility","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"emailMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"text":"DSAPIRecipientEmailNotification","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"emailRecipientPostSigningURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"text":"faxNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"faxNumberMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"firstName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"firstNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fullName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"fullNameMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"idCheckConfigurationName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"idCheckInformationInput","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput"},{"kind":"text","text":"? = nil, "},{"text":"identityVerification","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","kind":"typeIdentifier","text":"DSAPIRecipientIdentityVerification","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"inheritEmailNotificationConfiguration"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"lastName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"lastNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"lockedRecipientSmsEditable","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"nameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"noteMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneAuthentication"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","text":"DSAPIRecipientPhoneNumber","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"recipientAttachments","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","text":"DSAPIRecipientAttachment"},{"kind":"text","text":"]? = nil, "},{"text":"recipientAuthenticationStatus","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","text":"DSAPIAuthenticationStatus","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"kind":"text","text":"? = nil, "},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFeatureAvailableMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"recipientIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"recipientType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"recipientTypeMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"requireIdLookup","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"requireIdLookupMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"routingOrder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"routingOrderMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"sentDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"? = nil, ","kind":"text"},{"text":"signedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? = nil, ","kind":"text"},{"text":"signingGroupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signingGroupName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"signingGroupUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","kind":"typeIdentifier","text":"DSAPIUserInfo"},{"kind":"text","text":"]? = nil, "},{"text":"smsAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication"},{"text":"? = nil, ","kind":"text"},{"text":"socialAuthentications","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"statusCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"suppressEmails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"templateLocked","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"templateRequired","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"totalTabCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapieditor\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:allowsystemoverrideforlockedrecipient:autorespondedreason:clientuserid:completedcount:customfields:declineddatetime:declinedreason:delivereddatetime:deliverymet-667t9"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEditor"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEditor\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"accessCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accessCodeMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientAdditionalNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"allowSystemOverrideForLockedRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"autoRespondedReason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"customFields","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"declinedDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"text":"declinedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"deliveredDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"text":"deliveryMethod","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"deliveryMethodMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"designatorId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"designatorIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"documentVisibility","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","kind":"typeIdentifier","text":"DSAPIDocumentVisibility"},{"kind":"text","text":"]?, "},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailNotification"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientEmailNotification","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"text":"?, ","kind":"text"},{"text":"emailRecipientPostSigningURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"text":"DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faxNumberMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fullNameMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"idCheckConfigurationName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationNameMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"idCheckInformationInput","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"identityVerification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientIdentityVerification","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV"},{"text":"?, ","kind":"text"},{"text":"inheritEmailNotificationConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"lastName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lastNameMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"lockedRecipientPhoneAuthEditable","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"nameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"note"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"noteMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication"},{"kind":"text","text":"?, "},{"text":"phoneNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","text":"DSAPIRecipientPhoneNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipientAttachments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","text":"DSAPIRecipientAttachment"},{"text":"]?, ","kind":"text"},{"text":"recipientAuthenticationStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIAuthenticationStatus","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"kind":"text","text":"?, "},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","text":"DSAPIFeatureAvailableMetadata"},{"text":"]?, ","kind":"text"},{"text":"recipientId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipientIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipientTypeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"requireIdLookup"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"roleName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"routingOrder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"routingOrderMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"sentDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"signedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"signingGroupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupUsers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo"},{"text":"]?, ","kind":"text"},{"text":"smsAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","kind":"typeIdentifier","text":"DSAPISocialAuthentication"},{"text":"]?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"statusCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"suppressEmails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"templateLocked","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateRequired"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"totalTabCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","externalID":"s:11DocuSignAPI11DSAPIEditorC10accessCode0eF8Metadata09addAccessF7ToEmail23additionalNotifications37allowSystemOverrideForLockedRecipient19autoRespondedReason12clientUserId14completedCount12customFields16declinedDateTime08declinedV017deliveredDateTime14deliveryMethod014deliveryMethodG0010designatorY0010designatorY4Guid18documentVisibility5email05emailG017emailNotification05emailS14PostSigningURL08embeddedS8StartURL12errorDetails9faxNumber09faxNumberG09firstName09firstNameG08fullName08fullNameG024idCheckConfigurationName024idCheckConfigurationNameG023idCheckInformationInput20identityVerification07inheritK25NotificationConfiguration8lastName08lastNameG006lockedS17PhoneAuthEditable06lockedS11SmsEditable4name04nameG04note04noteG019phoneAuthentication11phoneNumber20recipientAttachments29recipientAuthenticationStatus016recipientFeatureG009recipientY009recipientY4Guid13recipientType013recipientTypeG007requireY6Lookup07requirey6LookupG08roleName12routingOrder012routingOrderG012sentDateTime14signedDateTime012signingGroupY0012signingGroupyG016signingGroupName17signingGroupUsers17smsAuthentication21socialAuthentications6status06statusF014suppressEmails08templateR016templateRequired13totalTabCount04userY0ACSSSg_AA013DSAPIPropertyG0CSgA47_SayAA36DSAPIRecipientAdditionalNotificationCGSgSbA47_A47_A47_SaySSGSg10Foundation4DateVSgA47_A60_A47_A50_A47_A47_SayAA23DSAPIDocumentVisibilityCGSgA47_A50_AA014DSAPIRecipientK12NotificationCSgA47_A47_AA17DSAPIErrorDetailsCSgA47_A50_A47_A50_A47_A50_A47_A50_AA28DSAPIIdCheckInformationInputVSgAA34DSAPIRecipientIdentityVerificationVSgSbA47_A50_A47_A47_A47_A50_A47_A50_AA33DSAPIRecipientPhoneAuthenticationVSgAA25DSAPIRecipientPhoneNumberVSgSayAA24DSAPIRecipientAttachmentCGSgAA25DSAPIAuthenticationStatusVSgSayAA021DSAPIFeatureAvailableG0VGSgA47_A47_A47_A50_SbA50_A47_A47_A50_A60_A60_A47_A50_A47_SayAA13DSAPIUserInfoCGSgAA31DSAPIRecipientSMSAuthenticationCSgSayAA25DSAPISocialAuthenticationCGSgA47_A47_S3bA47_A47_tcfc","modules":[{"name":"DocuSignAPI"}],"symbolKind":"init"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientIdentityVerification":{"abstract":[{"text":"Specifies ID Verification applied on an envelope by workflow ID. See the ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","isActive":true,"type":"reference"},{"text":" method in the ","type":"text"},{"isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","type":"reference"},{"text":" resource for more information on how to retrieve workflow IDs available for an account. This can be used in addition to other ","type":"text"},{"isActive":true,"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","type":"reference"},{"text":" methods.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientIdentityVerification"}],"url":"\/documentation\/docusignapi\/dsapirecipientidentityverification","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientIdentityVerification","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","role":"symbol","title":"DSAPIRecipientIdentityVerification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEditor/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)":{"title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)","url":"\/documentation\/docusignapi\/dsapieditor\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:allowsystemoverrideforlockedrecipient:autorespondedreason:clientuserid:completedcount:customfields:declineddatetime:declinedreason:delivereddatetime:deliverymet-667t9","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"accessCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"accessCodeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"addAccessCodeToEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalNotifications"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"allowSystemOverrideForLockedRecipient","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"autoRespondedReason","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completedCount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"declinedDateTime"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"declinedReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveredDateTime"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"deliveryMethodMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"designatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"designatorIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"documentVisibility"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility"},{"text":"]?, ","kind":"text"},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"errorDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"faxNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faxNumberMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"firstNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"fullName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"fullNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"idCheckConfigurationName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"idCheckInformationInput"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","text":"DSAPIIdCheckInformationInput","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"identityVerification","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","kind":"typeIdentifier","text":"DSAPIRecipientIdentityVerification"},{"kind":"text","text":"?, "},{"text":"inheritEmailNotificationConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"lastName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"lastNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"lockedRecipientSmsEditable","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"nameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"note"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"noteMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"phoneAuthentication","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","text":"DSAPIRecipientPhoneAuthentication"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipientAttachments"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment"},{"kind":"text","text":"]?, "},{"text":"recipientAuthenticationStatus","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"kind":"text","text":"?, "},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFeatureAvailableMetadata","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV"},{"text":"]?, ","kind":"text"},{"text":"recipientId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"recipientIdGuid","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"recipientType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipientTypeMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"requireIdLookup","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"requireIdLookupMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"roleName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"routingOrder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"routingOrderMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sentDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"signedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"text":"signingGroupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupIdMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signingGroupName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupUsers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"]?, "},{"text":"smsAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialAuthentications"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"statusCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"suppressEmails"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"templateLocked","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"templateRequired","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalTabCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEditor\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:allowSystemOverrideForLockedRecipient:autoRespondedReason:clientUserId:completedCount:customFields:declinedDateTime:declinedReason:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:lastName:lastNameMetadata:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:note:noteMetadata:phoneAuthentication:phoneNumber:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:roleName:routingOrder:routingOrderMetadata:sentDateTime:signedDateTime:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:templateLocked:templateRequired:totalTabCount:userId:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocumentVisibility":{"abstract":[{"type":"text","text":"This object configures a recipient's read\/write access to a document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIDocumentVisibility","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapidocumentvisibility","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocumentVisibility"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","role":"symbol","title":"DSAPIDocumentVisibility","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication","type":"topic","navigatorTitle":[{"text":"DSAPISocialAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","role":"symbol","title":"DSAPISocialAuthentication","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneAuthentication":{"abstract":[{"text":"A complex type that contains the elements:  * `recipMayProvideNumber`: A Boolean value that specifies whether the recipient can use the phone number of their choice. * `senderProvidedNumbers`: A list of phone numbers that the recipient can use. * `recordVoicePrint`: Reserved for DocuSign. * `validateRecipProvidedNumber`: Reserved for DocuSign.","type":"text"}],"title":"DSAPIRecipientPhoneAuthentication","url":"\/documentation\/docusignapi\/dsapirecipientphoneauthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"navigatorTitle":[{"text":"DSAPIRecipientPhoneAuthentication","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","role":"symbol","title":"DSAPIRecipientAttachment","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFeatureAvailableMetadata":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFeatureAvailableMetadata","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapifeatureavailablemetadata","type":"topic","navigatorTitle":[{"text":"DSAPIFeatureAvailableMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","role":"symbol","title":"DSAPIFeatureAvailableMetadata","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneNumber":{"abstract":[{"text":"Describes the recipient phone number.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientPhoneNumber","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientphonenumber","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientPhoneNumber","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","role":"symbol","title":"DSAPIRecipientPhoneNumber","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSMSAuthentication":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","type":"topic","title":"DSAPIRecipientSMSAuthentication","role":"symbol","abstract":[{"type":"text","text":"Contains the element senderProvidedNumbers which is an Array  of phone numbers the recipient can use for SMS text authentication."}],"url":"\/documentation\/docusignapi\/dsapirecipientsmsauthentication","navigatorTitle":[{"text":"DSAPIRecipientSMSAuthentication","kind":"identifier"}]},"https://support.docusign.com/en/guides/ndse-user-guide-recipient-authentication":{"type":"link","url":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","title":"recipient authentication","titleInlineContent":[{"type":"text","text":"recipient authentication"}],"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAuthenticationStatus":{"title":"DSAPIAuthenticationStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPIAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiauthenticationstatus","abstract":[{"text":"A complex element that contains information about a user's authentication status.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","role":"symbol","navigatorTitle":[{"text":"DSAPIAuthenticationStatus","kind":"identifier"}]},"/docs/esign-rest-api/reference/accounts/identityverifications/list/":{"type":"link","title":"list","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","titleInlineContent":[{"text":"list","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEditor":{"navigatorTitle":[{"text":"DSAPIEditor","kind":"identifier"}],"abstract":[{"type":"text","text":"A complex type defining the management and access rights of a recipient assigned as an editor on the envelope. Editors have the same management and access rights for the envelope as the sender. They can make changes to the envelope as if they were using the Correct feature. This recipient can add name and email information, add or change the routing order and set authentication options for the remaining recipients. Additionally, this recipient can edit signature\/initial tabs and text tabs for the remaining recipients."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIEditor","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEditor","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/docusignapi\/dsapieditor","title":"DSAPIEditor"},"/docs/esign-rest-api/reference/accounts/identityverifications/":{"type":"link","url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","title":"IdentityVerifications","titleInlineContent":[{"type":"text","text":"IdentityVerifications"}],"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientEmailNotification":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientemailnotification","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","role":"symbol","title":"DSAPIRecipientEmailNotification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAdditionalNotification":{"abstract":[{"type":"text","text":"Describes an additional notification method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRecipientAdditionalNotification","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientadditionalnotification","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","role":"symbol","title":"DSAPIRecipientAdditionalNotification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIdCheckInformationInput":{"url":"\/documentation\/docusignapi\/dsapiidcheckinformationinput","title":"DSAPIIdCheckInformationInput","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIIdCheckInformationInput","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIIdCheckInformationInput","kind":"identifier"}],"abstract":[{"type":"text","text":"A complex element that contains input information related to a recipient ID check."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"}},"variantOverrides":[{"patch":[{"value":"DSAPIDocumentVisibility","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/fragments","value":[{"text":"DSAPIDocumentVisibility","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title","value":"DSAPISocialAuthentication","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments","value":[{"kind":"identifier","text":"DSAPISocialAuthentication"}]},{"value":"DSAPIRecipientAttachment","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPIRecipientAttachment"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/fragments"},{"value":"DSAPIUserInfo","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","value":[{"text":"DSAPIUserInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/title","op":"replace","value":"DSAPIRecipientSMSAuthentication"},{"value":[{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEditor\/title","value":"DSAPIEditor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEditor\/fragments","value":[{"kind":"identifier","text":"DSAPIEditor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/title","value":"DSAPIRecipientEmailNotification"},{"value":[{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DSAPIRecipientAdditionalNotification","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","value":"DSAPIPropertyMetadata"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}