{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText\/underline"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText"]]},"kind":"symbol","abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"text":" the information in the tab is underlined.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"underline","roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIText(py)underline","symbolKind":"property","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"underline","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"underline"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","text":"BoolFromString","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"underline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapitext\/underline"]},{"paths":["\/documentation\/docusignapi\/dsapitext\/underline"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIText/underline":{"type":"topic","url":"\/documentation\/docusignapi\/dsapitext\/underline","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" the information in the tab is underlined.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"underline","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText\/underline","navigatorTitle":[{"text":"underline","kind":"identifier"}],"role":"symbol","title":"underline"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIText":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIText"}],"url":"\/documentation\/docusignapi\/dsapitext","title":"DSAPIText","abstract":[{"text":"A tab that allows the recipient to enter any type of text.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIText"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIText"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"underline","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"underline"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"underline","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"BoolFromString","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments","value":[{"text":"BoolFromString","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText~1underline\/title","value":"underline"},{"value":[{"kind":"identifier","text":"underline"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText~1underline\/fragments"},{"op":"replace","value":"DSAPIText","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIText\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIText"}]}]}]}