{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvents","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvents","text":"DSAPITelemetryEvents"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC","text":"RequestBuilder"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEventsResponse","text":"DSAPITelemetryEventsResponse"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RequestBuilder"}]}]},{"kind":"parameters","parameters":[{"name":"accountId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(path) The external account number (int) or account ID Guid."}]}]},{"name":"body","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(body)  (optional)"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"POST \/v2.1\/accounts\/{accountId}\/chunked_uploads"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OAuth:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"type: oauth2"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name: docusignAccessCode"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"examples:"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/telemetryapi\/createwithrequestbuilder(body:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TelemetryAPI\/createWithRequestBuilder(body:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initiate a new chunked upload."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITelemetryEvents","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvents"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPITelemetryEventsResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEventsResponse"},{"kind":"text","text":">"}],"title":"createWithRequestBuilder(body:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:11DocuSignAPI09TelemetryC0C24createWithRequestBuilder4bodyAA0gH0CyAA28DSAPITelemetryEventsResponseCGAA0jK0CSg_tFZ","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TelemetryAPI"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEvents":{"role":"symbol","title":"DSAPITelemetryEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITelemetryEvents"}],"abstract":[{"type":"text","text":"The telemetry events model."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITelemetryEvents"}],"url":"\/documentation\/docusignapi\/dsapitelemetryevents"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/RequestBuilder":{"role":"symbol","title":"RequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestBuilder"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/RequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestBuilder"}],"url":"\/documentation\/docusignapi\/requestbuilder"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITelemetryEventsResponse":{"role":"symbol","title":"DSAPITelemetryEventsResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}],"abstract":[{"type":"text","text":"This response object is returned after you post a telemetry event."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITelemetryEventsResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}],"url":"\/documentation\/docusignapi\/dsapitelemetryeventsresponse"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TelemetryAPI/createWithRequestBuilder(body:)":{"role":"symbol","title":"createWithRequestBuilder(body:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createWithRequestBuilder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITelemetryEvents","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEvents"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"RequestBuilder","preciseIdentifier":"s:11DocuSignAPI14RequestBuilderC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"DSAPITelemetryEventsResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITelemetryEventsResponse"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Initiate a new chunked upload."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TelemetryAPI\/createWithRequestBuilder(body:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/telemetryapi\/createwithrequestbuilder(body:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/TelemetryAPI":{"role":"symbol","title":"TelemetryAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TelemetryAPI"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/TelemetryAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TelemetryAPI"}],"url":"\/documentation\/docusignapi\/telemetryapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvents\/title","value":"DSAPITelemetryEvents"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEvents\/fragments","value":[{"kind":"identifier","text":"DSAPITelemetryEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse\/title","value":"DSAPITelemetryEventsResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITelemetryEventsResponse\/fragments","value":[{"kind":"identifier","text":"DSAPITelemetryEventsResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TelemetryAPI\/title","value":"TelemetryAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1TelemetryAPI\/fragments","value":[{"kind":"identifier","text":"TelemetryAPI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}