{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeNotificationRequest"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"expirations","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","kind":"typeIdentifier","text":"DSAPIExpirations"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"reminders"},{"text":": ","kind":"text"},{"text":"DSAPIReminders","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders"},{"text":"? = nil, ","kind":"text"},{"text":"useAccountDefaults","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false)"}]}]}],"metadata":{"externalID":"s:11DocuSignAPI32DSAPIEnvelopeNotificationRequestV11expirations9reminders18useAccountDefaultsAcA16DSAPIExpirationsCSg_AA14DSAPIRemindersCSgSbtcfc","symbolKind":"init","title":"init(expirations:reminders:useAccountDefaults:)","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"expirations","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","text":"DSAPIExpirations"},{"text":"?, ","kind":"text"},{"text":"reminders","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","text":"DSAPIReminders"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useAccountDefaults"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapienvelopenotificationrequest\/init(expirations:reminders:useaccountdefaults:)"]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeNotificationRequest\/init(expirations:reminders:useAccountDefaults:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations":{"type":"topic","role":"symbol","abstract":[{"text":"A complex element that specifies the expiration settings for the envelope. When an envelope expires, it is voided and no longer available for signing. ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" there is a short delay between when the envelope expires and when it is voided."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIExpirations"}],"title":"DSAPIExpirations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIExpirations","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiexpirations","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeNotificationRequest":{"title":"DSAPIEnvelopeNotificationRequest","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeNotificationRequest"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeNotificationRequest","role":"symbol","abstract":[{"type":"text","text":"A complex element that specifies the notification settings for the envelope."}],"url":"\/documentation\/docusignapi\/dsapienvelopenotificationrequest","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIEnvelopeNotificationRequest","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeNotificationRequest/init(expirations:reminders:useAccountDefaults:)":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopenotificationrequest\/init(expirations:reminders:useaccountdefaults:)","role":"symbol","abstract":[],"title":"init(expirations:reminders:useAccountDefaults:)","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeNotificationRequest\/init(expirations:reminders:useAccountDefaults:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirations"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations","kind":"typeIdentifier","text":"DSAPIExpirations"},{"text":"?, ","kind":"text"},{"text":"reminders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIReminders","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"useAccountDefaults"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIReminders":{"kind":"symbol","title":"DSAPIReminders","url":"\/documentation\/docusignapi\/dsapireminders","role":"symbol","navigatorTitle":[{"text":"DSAPIReminders","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIReminders"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","type":"topic","abstract":[{"type":"text","text":"A complex element that specifies reminder settings for the envelope."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/title","value":"DSAPIExpirations"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/fragments","value":[{"kind":"identifier","text":"DSAPIExpirations"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/title","value":"DSAPIReminders"},{"value":[{"kind":"identifier","text":"DSAPIReminders"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}