{"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/demo","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"demo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"case","role":"symbol","title":"ObjcEnviromment.demo","externalID":"c:@M@DocuSignAPI@E@ObjcEnviromment@ObjcEnvirommentDemo","roleHeading":"Case","navigatorTitle":[{"text":"ObjcEnvirommentDemo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"demo"}],"modules":[{"name":"DocuSignAPI"}]},"variants":[{"paths":["\/documentation\/docusignapi\/objcenviromment\/demo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objcenviromment\/demo"]}],"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/demo":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/demo","abstract":[],"title":"ObjcEnviromment.demo","navigatorTitle":[{"text":"ObjcEnvirommentDemo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"demo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/docusignapi\/objcenviromment\/demo","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObjcEnviromment"}],"abstract":[],"type":"topic","title":"ObjcEnviromment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","kind":"symbol","url":"\/documentation\/docusignapi\/objcenviromment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcEnviromment"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ObjcEnvirommentDemo"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ObjcEnvirommentDemo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ObjcEnvirommentDemo","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1demo\/title","value":"ObjcEnvirommentDemo","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1demo\/fragments","op":"replace","value":[{"kind":"identifier","text":"ObjcEnvirommentDemo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/title","value":"ObjcEnviromment"},{"value":[{"kind":"identifier","text":"ObjcEnviromment"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}