{"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"DocuSignAPI"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prod","kind":"identifier"}],"role":"symbol","title":"ObjcEnviromment.prod","externalID":"c:@M@DocuSignAPI@E@ObjcEnviromment@ObjcEnvirommentProd","navigatorTitle":[{"text":"ObjcEnvirommentProd","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/objcenviromment\/prod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objcenviromment\/prod"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prod"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/prod","interfaceLanguage":"swift"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/prod":{"abstract":[],"type":"topic","title":"ObjcEnviromment.prod","url":"\/documentation\/docusignapi\/objcenviromment\/prod","navigatorTitle":[{"kind":"identifier","text":"ObjcEnvirommentProd"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/prod","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prod","kind":"identifier"}],"role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment":{"navigatorTitle":[{"text":"ObjcEnviromment","kind":"identifier"}],"title":"ObjcEnviromment","url":"\/documentation\/docusignapi\/objcenviromment","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjcEnviromment","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"ObjcEnvirommentProd","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ObjcEnvirommentProd","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ObjcEnvirommentProd","kind":"identifier"}]}],"kind":"declarations"}},{"value":"ObjcEnvirommentProd","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1prod\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1prod\/fragments","value":[{"kind":"identifier","text":"ObjcEnvirommentProd"}]},{"op":"replace","value":"ObjcEnviromment","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/fragments","value":[{"text":"ObjcEnviromment","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}