{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/stage"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stage"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"DocuSignAPI"}],"roleHeading":"Case","externalID":"c:@M@DocuSignAPI@E@ObjcEnviromment@ObjcEnvirommentStage","title":"ObjcEnviromment.stage","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stage"}],"navigatorTitle":[{"text":"ObjcEnvirommentStage","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment"]]},"variants":[{"paths":["\/documentation\/docusignapi\/objcenviromment\/stage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/objcenviromment\/stage"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"url":"\/documentation\/docusignapi","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","type":"topic","abstract":[],"title":"DocuSignAPI","kind":"symbol","role":"collection"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment/stage":{"title":"ObjcEnviromment.stage","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ObjcEnvirommentStage"}],"kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/objcenviromment\/stage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"stage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment\/stage"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/ObjcEnviromment":{"navigatorTitle":[{"text":"ObjcEnviromment","kind":"identifier"}],"title":"ObjcEnviromment","url":"\/documentation\/docusignapi\/objcenviromment","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/ObjcEnviromment","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjcEnviromment","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ObjcEnvirommentStage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ObjcEnvirommentStage"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ObjcEnvirommentStage"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1stage\/title","value":"ObjcEnvirommentStage"},{"value":[{"kind":"identifier","text":"ObjcEnvirommentStage"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment~1stage\/fragments","op":"replace"},{"value":"ObjcEnviromment","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1ObjcEnviromment\/fragments","value":[{"text":"ObjcEnviromment","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}