{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability\/stopNotifier()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopNotifier"},{"kind":"text","text":"()"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"title":"stopNotifier()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopNotifier","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@CM@DocuSignAPI@objc(cs)Reachability(im)stopNotifier","navigatorTitle":[{"kind":"identifier","text":"stopNotifier"}],"symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/docusignapi\/reachability\/stopnotifier()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/reachability\/stopnotifier()"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/Reachability/stopNotifier()":{"role":"symbol","url":"\/documentation\/docusignapi\/reachability\/stopnotifier()","navigatorTitle":[{"text":"stopNotifier","kind":"identifier"}],"title":"stopNotifier()","type":"topic","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability\/stopNotifier()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopNotifier","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/Reachability":{"type":"topic","url":"\/documentation\/docusignapi\/reachability","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Reachability","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability","navigatorTitle":[{"text":"Reachability","kind":"identifier"}],"role":"symbol","title":"Reachability"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"stopNotifier","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopNotifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopNotifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability~1stopNotifier()\/title","value":"stopNotifier","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability~1stopNotifier()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopNotifier","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability\/title","op":"replace","value":"Reachability"},{"value":[{"kind":"identifier","text":"Reachability"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}