{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whenReachable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability\/NetworkReachable","preciseIdentifier":"s:11DocuSignAPI12ReachabilityC16NetworkReachablea","text":"NetworkReachable"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/reachability\/whenreachable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/reachability\/whenreachable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability\/whenReachable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whenReachable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkReachable","preciseIdentifier":"s:11DocuSignAPI12ReachabilityC16NetworkReachablea"},{"kind":"text","text":"?"}],"title":"whenReachable","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)Reachability(py)whenReachable","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"whenReachable"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/Reachability":{"role":"symbol","title":"Reachability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Reachability"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Reachability"}],"url":"\/documentation\/docusignapi\/reachability"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/Reachability/NetworkReachable":{"role":"symbol","title":"Reachability.NetworkReachable","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkReachable"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability\/NetworkReachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkReachable"}],"url":"\/documentation\/docusignapi\/reachability\/networkreachable"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/Reachability/whenReachable":{"role":"symbol","title":"whenReachable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whenReachable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkReachable","preciseIdentifier":"s:11DocuSignAPI12ReachabilityC16NetworkReachablea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/Reachability\/whenReachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"whenReachable"}],"url":"\/documentation\/docusignapi\/reachability\/whenreachable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"whenReachable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"whenReachable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void (^)(Reachability *)","preciseIdentifier":"c:BFv(#*$@M@DocuSignAPI@objc(cs)Reachability)"},{"kind":"text","text":" "},{"kind":"identifier","text":"whenReachable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability\/title","value":"Reachability"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability\/fragments","value":[{"kind":"identifier","text":"Reachability"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability~1whenReachable\/title","value":"whenReachable"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1Reachability~1whenReachable\/fragments","value":[{"kind":"identifier","text":"whenReachable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}