{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString","text":"BoolFromString","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorMatchWholeWord","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName\/anchorMatchWholeWord","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapifullname\/anchormatchwholeword"]},{"paths":["\/documentation\/docusignapi\/dsapifullname\/anchormatchwholeword"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","navigatorTitle":[{"text":"anchorMatchWholeWord","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorMatchWholeWord"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"anchorMatchWholeWord","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName(py)anchorMatchWholeWord"},"abstract":[{"text":"When ","type":"text"},{"inlineContent":[{"type":"text","text":"true,"}],"type":"strong"},{"type":"text","text":" the text string in a document must match the value of the `anchorString` property in its entirety for an [anchor tab][AnchorTab] to be created. The default value is "},{"type":"strong","inlineContent":[{"type":"text","text":"false."}]},{"text":"  For example, when set to ","type":"text"},{"inlineContent":[{"text":"true,","type":"text"}],"type":"strong"},{"type":"text","text":" if the input is `man` then `man` will match but `manpower`, `fireman`, and `penmanship` will not. When "},{"type":"strong","inlineContent":[{"text":"false,","type":"text"}]},{"type":"text","text":" if the input is `man` then `man`, `manpower`, `fireman`, and `penmanship` will all match.  This functionality uses the following rules:  - Unless punctuation is specified in the `anchorString`, this functionality ignores punctuation and the following characters:    $~><|^+=    For example, the `anchorString` `water` will match on the string `Fetch a pail of water.`  - Strings embedded in other strings are ignored during the matching process.  - In words that have dashes, the parts separated by dashes are treated as distinct words.    Example: If the anchor string is `forget`, then an anchor tab is placed on the `forget` in `forget-me-not`, even when `anchorMatchWholeWord` is set to "},{"type":"strong","inlineContent":[{"type":"text","text":"true."}]},{"text":"  - Letters with accent marks are treated as distinct characters from their unaccented counterparts.  - For single-character anchor strings, if the two characters appear right next to each other in the document, a single anchor tab is placed for both of them.    Example: If the anchor string is `i`, then only one anchor tab is placed in `skiing`.  - Unlike punctuation, numbers are not ignored when finding anchor words.    Example: If the anchor string is `cat`, then `-cat-` is matched but `1cat2` is not when `anchorMatchWholeWord` is set to ","type":"text"},{"inlineContent":[{"text":"true","type":"text"}],"type":"strong"},{"text":" (its default value).   ","type":"text"},{"type":"strong","inlineContent":[{"text":"Note:","type":"text"}]},{"type":"text","text":" You can only specify the value of this property in POST requests.  [AnchorTab]: \/docs\/esign-rest-api\/esign101\/concepts\/tabs\/auto-place\/"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFullName/anchorMatchWholeWord":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName\/anchorMatchWholeWord","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the text string in a document must match the value of the `anchorString` property in its entirety for an [anchor tab][AnchorTab] to be created. The default value is "},{"inlineContent":[{"text":"false.","type":"text"}],"type":"strong"},{"text":"  For example, when set to ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" if the input is `man` then `man` will match but `manpower`, `fireman`, and `penmanship` will not. When ","type":"text"},{"inlineContent":[{"type":"text","text":"false,"}],"type":"strong"},{"text":" if the input is `man` then `man`, `manpower`, `fireman`, and `penmanship` will all match.  This functionality uses the following rules:  - Unless punctuation is specified in the `anchorString`, this functionality ignores punctuation and the following characters:    $~><|^+=    For example, the `anchorString` `water` will match on the string `Fetch a pail of water.`  - Strings embedded in other strings are ignored during the matching process.  - In words that have dashes, the parts separated by dashes are treated as distinct words.    Example: If the anchor string is `forget`, then an anchor tab is placed on the `forget` in `forget-me-not`, even when `anchorMatchWholeWord` is set to ","type":"text"},{"inlineContent":[{"text":"true.","type":"text"}],"type":"strong"},{"text":"  - Letters with accent marks are treated as distinct characters from their unaccented counterparts.  - For single-character anchor strings, if the two characters appear right next to each other in the document, a single anchor tab is placed for both of them.    Example: If the anchor string is `i`, then only one anchor tab is placed in `skiing`.  - Unlike punctuation, numbers are not ignored when finding anchor words.    Example: If the anchor string is `cat`, then `-cat-` is matched but `1cat2` is not when `anchorMatchWholeWord` is set to ","type":"text"},{"type":"strong","inlineContent":[{"text":"true","type":"text"}]},{"type":"text","text":" (its default value).   "},{"inlineContent":[{"type":"text","text":"Note:"}],"type":"strong"},{"type":"text","text":" You can only specify the value of this property in POST requests.  [AnchorTab]: \/docs\/esign-rest-api\/esign101\/concepts\/tabs\/auto-place\/"}],"title":"anchorMatchWholeWord","navigatorTitle":[{"text":"anchorMatchWholeWord","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchorMatchWholeWord","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapifullname\/anchormatchwholeword","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFullName":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName","title":"DSAPIFullName","url":"\/documentation\/docusignapi\/dsapifullname","abstract":[{"text":"A tab that displays the recipient's full name.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFullName","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFullName"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"anchorMatchWholeWord","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"anchorMatchWholeWord","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchorMatchWholeWord"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName~1anchorMatchWholeWord\/title","value":"anchorMatchWholeWord"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName~1anchorMatchWholeWord\/fragments","value":[{"kind":"identifier","text":"anchorMatchWholeWord"}]},{"op":"replace","value":"DSAPIFullName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/title"},{"value":[{"kind":"identifier","text":"DSAPIFullName"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title","op":"replace","value":"BoolFromString"},{"value":[{"kind":"identifier","text":"BoolFromString"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments","op":"replace"}]}]}