{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"BoolFromString","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString","kind":"attribute","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"templateRequired","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapifullname\/templaterequired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapifullname\/templaterequired"]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"templateRequired"}],"title":"templateRequired","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIFullName(py)templateRequired","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templateRequired","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName\/templateRequired","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the sender may not remove the recipient. Used only when working with template recipients."}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFullName/templateRequired":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName\/templateRequired","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" the sender may not remove the recipient. Used only when working with template recipients.","type":"text"}],"title":"templateRequired","navigatorTitle":[{"text":"templateRequired","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templateRequired"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapifullname\/templaterequired","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFullName":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFullName","title":"DSAPIFullName","url":"\/documentation\/docusignapi\/dsapifullname","abstract":[{"text":"A tab that displays the recipient's full name.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFullName","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFullName"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"templateRequired","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"templateRequired","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"templateRequired","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"templateRequired","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName~1templateRequired\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName~1templateRequired\/fragments","value":[{"kind":"identifier","text":"templateRequired"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/title","value":"DSAPIFullName","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIFullName"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFullName\/fragments"},{"op":"replace","value":"BoolFromString","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title"},{"op":"replace","value":[{"kind":"identifier","text":"BoolFromString"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments"}]}]}