{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bulkEnvelopeStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkEnvelopeStatus","preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkEnvelopeStatusV","text":"DSAPIBulkEnvelopeStatus"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"listCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField","text":"DSAPIListCustomField"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"lockInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","text":"DSAPILockInformation"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse","text":"DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"tabUpdateResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"textCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","text":"DSAPITextCustomField"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopeupdatesummary\/init(bulkenvelopestatus:envelopeid:errordetails:listcustomfieldupdateresults:lockinformation:purgestate:recipientupdateresults:tabupdateresults:textcustomfieldupdateresults:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeUpdateSummary\/init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bulkEnvelopeStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIBulkEnvelopeStatus","preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkEnvelopeStatusV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"listCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lockInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPILockInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabUpdateResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"textCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"kind":"text","text":"]?)"}],"title":"init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI26DSAPIEnvelopeUpdateSummaryV18bulkEnvelopeStatus10envelopeId12errorDetails015listCustomFieldE7Results15lockInformation10purgeState09recipienteQ003tabeQ004textopeQ0AcA09DSAPIBulkhI0VSg_SSSgAA010DSAPIErrorM0CSgSayAA09DSAPIListoP0CGSgAA09DSAPILockS0CSgAPSayAA014DSAPIRecipientE8ResponseCGSgAA9DSAPITabsCSgSayAA09DSAPITextoP0CGSgtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeUpdateSummary"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITextCustomField":{"role":"symbol","title":"DSAPITextCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITextCustomField"}],"abstract":[{"type":"text","text":"This object represents a free text custom field where envelope creators and senders can enter custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITextCustomField"}],"url":"\/documentation\/docusignapi\/dsapitextcustomfield"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField":{"role":"symbol","title":"DSAPIListCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIListCustomField"}],"abstract":[{"type":"text","text":"This object represents a list custom field from which envelope creators and senders can select custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIListCustomField"}],"url":"\/documentation\/docusignapi\/dsapilistcustomfield"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientUpdateResponse":{"role":"symbol","title":"DSAPIRecipientUpdateResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientUpdateResponse"}],"abstract":[{"type":"text","text":"The recipient details that are returned after you update the recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientUpdateResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientUpdateResponse"}],"url":"\/documentation\/docusignapi\/dsapirecipientupdateresponse"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBulkEnvelopeStatus":{"role":"symbol","title":"DSAPIBulkEnvelopeStatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBulkEnvelopeStatus"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkEnvelopeStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBulkEnvelopeStatus"}],"url":"\/documentation\/docusignapi\/dsapibulkenvelopestatus"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation":{"role":"symbol","title":"DSAPILockInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILockInformation"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPILockInformation"}],"url":"\/documentation\/docusignapi\/dsapilockinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","title":"DSAPITabs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabs"}],"abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}],"url":"\/documentation\/docusignapi\/dsapitabs"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"role":"symbol","title":"DSAPIErrorDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIErrorDetails"}],"abstract":[{"type":"text","text":"This object describes errors that occur. It is only valid for responses and ignored in requests."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"url":"\/documentation\/docusignapi\/dsapierrordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeUpdateSummary":{"role":"symbol","title":"DSAPIEnvelopeUpdateSummary","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeUpdateSummary"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeUpdateSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeUpdateSummary"}],"url":"\/documentation\/docusignapi\/dsapienvelopeupdatesummary"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeUpdateSummary/init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)":{"role":"symbol","title":"init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bulkEnvelopeStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIBulkEnvelopeStatus","preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkEnvelopeStatusV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"listCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lockInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPILockInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabUpdateResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"textCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeUpdateSummary\/init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopeupdatesummary\/init(bulkenvelopestatus:envelopeid:errordetails:listcustomfieldupdateresults:lockinformation:purgestate:recipientupdateresults:tabupdateresults:textcustomfieldupdateresults:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/title","value":"DSAPITextCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPITextCustomField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/title","value":"DSAPIListCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPIListCustomField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientUpdateResponse\/title","value":"DSAPIRecipientUpdateResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientUpdateResponse\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientUpdateResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/title","value":"DSAPILockInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/fragments","value":[{"kind":"identifier","text":"DSAPILockInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","value":[{"kind":"identifier","text":"DSAPITabs"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}