# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'docusign-sdk-sample-objc' do

  # Pods for docusign-sdk-sample-objc
  pod 'ProgressHUD'
  pod 'DocuSign', :git => 'https://github.com/docusign/native-ios-sdk.git', :branch => "release/2.5.3-legacy"

end
