{"kind":"symbol","metadata":{"roleHeading":"Initializer","symbolKind":"init","role":"symbol","externalID":"s:11DocuSignAPI22DSAPIMemberSharedItemsV9envelopes12errorDetails7folders9templates4userACSayAA15DSAPISharedItemVGSg_AA010DSAPIErrorI0CSgSayAA011DSAPIFoldereN0VGSgSayAA013DSAPITemplateeN0VGSgAA13DSAPIUserInfoCSgtcfc","modules":[{"name":"DocuSignAPI"}],"title":"init(envelopes:errorDetails:folders:templates:user:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"envelopes"},{"kind":"text","text":": ["},{"text":"DSAPISharedItem","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI15DSAPISharedItemV"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"folders"},{"kind":"text","text":": ["},{"text":"DSAPIFolderSharedItem","preciseIdentifier":"s:11DocuSignAPI21DSAPIFolderSharedItemV","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"templates"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateSharedItemV","kind":"typeIdentifier","text":"DSAPITemplateSharedItem"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"?)"}]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapimembershareditems\/init(envelopes:errordetails:folders:templates:user:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIMemberSharedItems"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"envelopes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPISharedItem","preciseIdentifier":"s:11DocuSignAPI15DSAPISharedItemV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISharedItem","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","text":"DSAPIErrorDetails","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"folders","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIFolderSharedItem","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI21DSAPIFolderSharedItemV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderSharedItem"},{"kind":"text","text":"]? = nil, "},{"text":"templates","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPITemplateSharedItem","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateSharedItemV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateSharedItem","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","text":"DSAPIUserInfo","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIMemberSharedItems\/init(envelopes:errorDetails:folders:templates:user:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIMemberSharedItems/init(envelopes:errorDetails:folders:templates:user:)":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapimembershareditems\/init(envelopes:errordetails:folders:templates:user:)","role":"symbol","title":"init(envelopes:errorDetails:folders:templates:user:)","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIMemberSharedItems\/init(envelopes:errorDetails:folders:templates:user:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"envelopes"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI15DSAPISharedItemV","kind":"typeIdentifier","text":"DSAPISharedItem"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"text":"folders","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI21DSAPIFolderSharedItemV","text":"DSAPIFolderSharedItem","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"templates"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPITemplateSharedItemV","text":"DSAPITemplateSharedItem"},{"text":"]?, ","kind":"text"},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"text":"?)","kind":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolderSharedItem":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolderSharedItem","type":"topic","url":"\/documentation\/docusignapi\/dsapifoldershareditem","navigatorTitle":[{"kind":"identifier","text":"DSAPIFolderSharedItem"}],"title":"DSAPIFolderSharedItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIFolderSharedItem","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIMemberSharedItems":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIMemberSharedItems","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIMemberSharedItems","navigatorTitle":[{"text":"DSAPIMemberSharedItems","kind":"identifier"}],"title":"DSAPIMemberSharedItems","abstract":[{"type":"text","text":"Information about shared items."}],"url":"\/documentation\/docusignapi\/dsapimembershareditems"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateSharedItem":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPITemplateSharedItem"}],"title":"DSAPITemplateSharedItem","abstract":[{"type":"text","text":"Information about shared templates."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPITemplateSharedItem","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateSharedItem","url":"\/documentation\/docusignapi\/dsapitemplateshareditem","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISharedItem":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Information about the shared item."}],"navigatorTitle":[{"text":"DSAPISharedItem","kind":"identifier"}],"title":"DSAPISharedItem","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISharedItem","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISharedItem","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapishareditem","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title","value":"DSAPIUserInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","value":[{"kind":"identifier","text":"DSAPIUserInfo"}]},{"value":"DSAPIErrorDetails","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}