{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField","text":"DSAPIListCustomField"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","text":"DSAPITextCustomField"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapicustomfields\/init(listcustomfields:textcustomfields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapicustomfields\/init(listcustomfields:textcustomfields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields\/init(listCustomFields:textCustomFields:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"kind":"text","text":"]?)"}],"title":"init(listCustomFields:textCustomFields:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICustomFields(im)initWithListCustomFields:textCustomFields:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithListCustomFields:textCustomFields:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields/init(listCustomFields:textCustomFields:)":{"role":"symbol","title":"init(listCustomFields:textCustomFields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields\/init(listCustomFields:textCustomFields:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithListCustomFields:textCustomFields:"}],"url":"\/documentation\/docusignapi\/dsapicustomfields\/init(listcustomfields:textcustomfields:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFields":{"role":"symbol","title":"DSAPICustomFields","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFields"}],"abstract":[{"type":"text","text":"Contains information about custom fields."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFields"}],"url":"\/documentation\/docusignapi\/dsapicustomfields"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField":{"role":"symbol","title":"DSAPIListCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIListCustomField"}],"abstract":[{"type":"text","text":"This object represents a list custom field from which envelope creators and senders can select custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIListCustomField"}],"url":"\/documentation\/docusignapi\/dsapilistcustomfield"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITextCustomField":{"role":"symbol","title":"DSAPITextCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITextCustomField"}],"abstract":[{"type":"text","text":"This object represents a free text custom field where envelope creators and senders can enter custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITextCustomField"}],"url":"\/documentation\/docusignapi\/dsapitextcustomfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithListCustomFields:textCustomFields:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithListCustomFields:textCustomFields:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithListCustomFields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIListCustomField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listCustomFields"},{"kind":"text","text":" "},{"kind":"identifier","text":"textCustomFields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPITextCustomField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"textCustomFields"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields~1init(listCustomFields:textCustomFields:)\/title","value":"initWithListCustomFields:textCustomFields:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields~1init(listCustomFields:textCustomFields:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithListCustomFields:textCustomFields:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/title","value":"DSAPICustomFields"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICustomFields\/fragments","value":[{"kind":"identifier","text":"DSAPICustomFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/title","value":"DSAPIListCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPIListCustomField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/title","value":"DSAPITextCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPITextCustomField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}