{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapidocument\/remoteurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapidocument\/remoteurl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/remoteUrl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The file ID from the cloud storage service where the document is located. This information is returned using "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"title":"remoteUrl","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIDocument(py)remoteUrl","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"remoteUrl"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument":{"role":"symbol","title":"DSAPIDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDocument"}],"abstract":[{"type":"text","text":"A document object."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocument"}],"url":"\/documentation\/docusignapi\/dsapidocument"},"/docs/esign-rest-api/reference/cloudstorage/cloudstorage/list/":{"title":"CloudStorage: list","titleInlineContent":[{"type":"text","text":"CloudStorage: list"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/","url":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/"},"/docs/esign-rest-api/reference/cloudstorage/cloudstorage/listfolders/":{"title":"CloudStorage: listFolders","titleInlineContent":[{"type":"text","text":"CloudStorage: listFolders"}],"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/","url":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocument/remoteUrl":{"role":"symbol","title":"remoteUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The file ID from the cloud storage service where the document is located. This information is returned using "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/listfolders\/"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/cloudstorage\/cloudstorage\/list\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocument\/remoteUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteUrl"}],"url":"\/documentation\/docusignapi\/dsapidocument\/remoteurl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"remoteUrl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"remoteUrl"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"remoteUrl"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument\/title","value":"DSAPIDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument\/fragments","value":[{"kind":"identifier","text":"DSAPIDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1remoteUrl\/title","value":"remoteUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocument~1remoteUrl\/fragments","value":[{"kind":"identifier","text":"remoteUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}