{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adoptedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"createdDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"customField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties","text":"DSAPIDateStampProperties"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"externalID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"imageBase64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"initials150ImageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"initialsImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"lastModifiedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nrdsStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signature150ImageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureGroup","preciseIdentifier":"s:11DocuSignAPI19DSAPISignatureGroupV","text":"DSAPISignatureGroup"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureInitials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureRights"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signatureUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureUser","preciseIdentifier":"s:11DocuSignAPI18DSAPISignatureUserV","text":"DSAPISignatureUser"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"stampImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"stampType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountsignature\/init(adopteddatetime:createddatetime:customfield:datestampproperties:disallowuserresizestamp:errordetails:externalid:imagebase64:imagetype:initials150imageid:initialsimageuri:isdefault:lastmodifieddatetime:nrdsid:nrdslastname:nrdsstatus:pho-8o7t5"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSignature\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureGroups:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:signatureUsers:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adoptedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"externalID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageBase64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initials150ImageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialsImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastModifiedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signature150ImageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignatureGroup","preciseIdentifier":"s:11DocuSignAPI19DSAPISignatureGroupV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureInitials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureRights"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignatureUser","preciseIdentifier":"s:11DocuSignAPI18DSAPISignatureUserV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureGroups:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:signatureUsers:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI21DSAPIAccountSignatureV15adoptedDateTime07createdgH011customField19dateStampProperties018disallowUserResizeM012errorDetails10externalID11imageBase640V4Type18initials150ImageId08initialsZ3Uri9isDefault012lastModifiedgH06nrdsId12nrdsLastName10nrdsStatus12phoneticName012signature150Z2Id13signatureFont15signatureGroups11signatureId09signatureZ3Uri17signatureInitials13signatureName15signatureRights09signatureX014signatureUsers11stampFormat05stampZ3Uri11stampSizeMM05stampX06statusAC10Foundation0G0VSg_A11_SSSgAA09DSAPIDatemN0CSgSbAA010DSAPIErrorS0CSgA12_A12_A12_A12_A8_3URLVSgSbA11_A12_A12_A12_A12_A12_A12_SayAA19DSAPISignatureGroupVGSgA12_A21_A12_A12_A12_A12_SayAA014DSAPISignatureP0VGSgA12_A12_A12_A12_A12_tcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSignature"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureGroup":{"role":"symbol","title":"DSAPISignatureGroup","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISignatureGroup"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISignatureGroup"}],"url":"\/documentation\/docusignapi\/dsapisignaturegroup"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSignature/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureGroups:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:signatureUsers:stampFormat:stampImageUri:stampSizeMM:stampType:status:)":{"role":"symbol","title":"init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureGroups:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:signatureUsers:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adoptedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateStampProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIDateStampProperties","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDateStampProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disallowUserResizeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"externalID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageBase64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initials150ImageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialsImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastModifiedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nrdsStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneticName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signature150ImageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureGroups"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignatureGroup","preciseIdentifier":"s:11DocuSignAPI19DSAPISignatureGroupV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"signatureId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureInitials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureRights"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISignatureUser","preciseIdentifier":"s:11DocuSignAPI18DSAPISignatureUserV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"stampFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampImageUri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampSizeMM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"stampType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSignature\/init(adoptedDateTime:createdDateTime:customField:dateStampProperties:disallowUserResizeStamp:errorDetails:externalID:imageBase64:imageType:initials150ImageId:initialsImageUri:isDefault:lastModifiedDateTime:nrdsId:nrdsLastName:nrdsStatus:phoneticName:signature150ImageId:signatureFont:signatureGroups:signatureId:signatureImageUri:signatureInitials:signatureName:signatureRights:signatureType:signatureUsers:stampFormat:stampImageUri:stampSizeMM:stampType:status:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountsignature\/init(adopteddatetime:createddatetime:customfield:datestampproperties:disallowuserresizestamp:errordetails:externalid:imagebase64:imagetype:initials150imageid:initialsimageuri:isdefault:lastmodifieddatetime:nrdsid:nrdslastname:nrdsstatus:pho-8o7t5"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"role":"symbol","title":"DSAPIErrorDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIErrorDetails"}],"abstract":[{"type":"text","text":"This object describes errors that occur. It is only valid for responses and ignored in requests."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"url":"\/documentation\/docusignapi\/dsapierrordetails"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSignature":{"role":"symbol","title":"DSAPIAccountSignature","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAccountSignature"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSignature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIAccountSignature"}],"url":"\/documentation\/docusignapi\/dsapiaccountsignature"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDateStampProperties":{"role":"symbol","title":"DSAPIDateStampProperties","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIDateStampProperties"}],"abstract":[{"type":"text","text":"Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.  This property contains the following information about the central rectangle:  - `DateAreaX`: The X axis position of the top-left corner. - `DateAreaY`: The Y axis position of the top-left corner. - `DateAreaWidth`: The width of the rectangle. - `DateAreaHeight`: The height of the rectangle."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDateStampProperties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDateStampProperties"}],"url":"\/documentation\/docusignapi\/dsapidatestampproperties"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureUser":{"role":"symbol","title":"DSAPISignatureUser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISignatureUser"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISignatureUser"}],"url":"\/documentation\/docusignapi\/dsapisignatureuser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/title","value":"DSAPIDateStampProperties"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDateStampProperties\/fragments","value":[{"kind":"identifier","text":"DSAPIDateStampProperties"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}