{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"expirations","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIExpirations","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"reminders"},{"text":": ","kind":"text"},{"text":"DSAPIReminders","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userOverrideEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountNotification\/init(expirations:reminders:userOverrideEnabled:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountNotification"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiaccountnotification\/init(expirations:reminders:useroverrideenabled:)"]}],"metadata":{"symbolKind":"init","title":"init(expirations:reminders:userOverrideEnabled:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"expirations","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIExpirations","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"text":"?, ","kind":"text"},{"text":"reminders","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIReminders","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders"},{"text":"?, ","kind":"text"},{"text":"userOverrideEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"s:11DocuSignAPI24DSAPIAccountNotificationV11expirations9reminders19userOverrideEnabledAcA16DSAPIExpirationsCSg_AA14DSAPIRemindersCSgSbtcfc","roleHeading":"Initializer"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountNotification":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountNotification","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAccountNotification"}],"url":"\/documentation\/docusignapi\/dsapiaccountnotification","title":"DSAPIAccountNotification","navigatorTitle":[{"text":"DSAPIAccountNotification","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A complex element that specifies notifications (expirations and reminders) for the envelope.","type":"text"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIReminders":{"kind":"symbol","title":"DSAPIReminders","url":"\/documentation\/docusignapi\/dsapireminders","role":"symbol","navigatorTitle":[{"text":"DSAPIReminders","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIReminders"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIReminders","type":"topic","abstract":[{"type":"text","text":"A complex element that specifies reminder settings for the envelope."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountNotification/init(expirations:reminders:userOverrideEnabled:)":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountNotification\/init(expirations:reminders:userOverrideEnabled:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirations"},{"kind":"text","text":": "},{"text":"DSAPIExpirations","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIExpirations"},{"text":"?, ","kind":"text"},{"text":"reminders","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIReminders","text":"DSAPIReminders","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"userOverrideEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/docusignapi\/dsapiaccountnotification\/init(expirations:reminders:useroverrideenabled:)","title":"init(expirations:reminders:userOverrideEnabled:)","kind":"symbol","role":"symbol","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIExpirations":{"type":"topic","role":"symbol","abstract":[{"text":"A complex element that specifies the expiration settings for the envelope. When an envelope expires, it is voided and no longer available for signing. ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" there is a short delay between when the envelope expires and when it is voided."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIExpirations"}],"title":"DSAPIExpirations","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIExpirations","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIExpirations","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiexpirations","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DSAPIReminders","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/title","op":"replace"},{"value":[{"text":"DSAPIReminders","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIReminders\/fragments","op":"replace"},{"value":"DSAPIExpirations","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIExpirations\/fragments","value":[{"text":"DSAPIExpirations","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}