{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"socialAuthentications"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAgent\/socialAuthentications"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"title":"socialAuthentications","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"text":"]?","kind":"text"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAgent(py)socialAuthentications","navigatorTitle":[{"kind":"identifier","text":"socialAuthentications"}],"symbolKind":"property","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAgent"]]},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiagent\/socialauthentications"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiagent\/socialauthentications"]}],"kind":"symbol","abstract":[{"text":"Deprecated.","type":"text"}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAgent/socialAuthentications":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiagent\/socialauthentications","navigatorTitle":[{"text":"socialAuthentications","kind":"identifier"}],"title":"socialAuthentications","type":"topic","abstract":[{"type":"text","text":"Deprecated."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAgent\/socialAuthentications","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"socialAuthentications"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","text":"DSAPISocialAuthentication","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAgent":{"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAgent","url":"\/documentation\/docusignapi\/dsapiagent","title":"DSAPIAgent","abstract":[{"text":"Contains information about an agent recipient. An agent is a recipient who can add name and email information for recipients that appear after the agent in routing order.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAgent"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIAgent"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication","type":"topic","navigatorTitle":[{"text":"DSAPISocialAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","role":"symbol","title":"DSAPISocialAuthentication","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"socialAuthentications"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"socialAuthentications"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSArray<DSAPISocialAuthentication *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"socialAuthentications","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAgent~1socialAuthentications\/title","value":"socialAuthentications","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAgent~1socialAuthentications\/fragments","value":[{"text":"socialAuthentications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAgent\/title","value":"DSAPIAgent"},{"value":[{"kind":"identifier","text":"DSAPIAgent"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAgent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title","value":"DSAPISocialAuthentication"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments","op":"replace","value":[{"text":"DSAPISocialAuthentication","kind":"identifier"}]}]}]}