{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountEsignId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"accountEsignId","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes(py)accountEsignId","navigatorTitle":[{"kind":"identifier","text":"accountEsignId"}],"modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountEsignId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"sections":[],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/accountEsignId","interfaceLanguage":"swift"},"abstract":[{"text":"The GUID of the account associated with the consumer disclosure.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiofflineattributes\/accountesignid"]},{"paths":["\/documentation\/docusignapi\/dsapiofflineattributes\/accountesignid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes":{"abstract":[{"type":"text","text":"Reserved for DocuSign use."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIOfflineAttributes","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiofflineattributes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes","role":"symbol","title":"DSAPIOfflineAttributes","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes/accountEsignId":{"url":"\/documentation\/docusignapi\/dsapiofflineattributes\/accountesignid","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes\/accountEsignId","abstract":[{"text":"The GUID of the account associated with the consumer disclosure.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"accountEsignId","kind":"identifier"}],"title":"accountEsignId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accountEsignId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accountEsignId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountEsignId"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"accountEsignId","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/title","value":"DSAPIOfflineAttributes","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1accountEsignId\/title","op":"replace","value":"accountEsignId"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes~1accountEsignId\/fragments","value":[{"text":"accountEsignId","kind":"identifier"}],"op":"replace"}]}]}