{"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIConsumerDisclosure(im)initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","navigatorTitle":[{"text":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountEsignId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowCDWithdraw"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"allowCDWithdrawMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","text":"DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"changeEmail"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"changeEmailOther","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"companyName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"companyPhone","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"copyCostPerPage"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"copyFeeCollectionMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"copyRequestEmail"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"custom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"enableEsign","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"esignAgreement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"esignText"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"languageCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"mustAgreeToEsign","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pdfId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"useBrand","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"useConsumerDisclosureWithinAccount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"useConsumerDisclosureWithinAccountMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"withdrawAddressLine1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"withdrawAddressLine2","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawByEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawByMail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"withdrawByPhone","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withdrawCity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"withdrawConsequences","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"withdrawEmail","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"withdrawOther","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawPhone"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"withdrawPostalCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"withdrawState","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapiconsumerdisclosure\/init(accountesignid:allowcdwithdraw:allowcdwithdrawmetadata:changeemail:changeemailother:companyname:companyphone:copycostperpage:copyfeecollectionmethod:copyrequestemail:custom:enableesign:esignagreement:esigntext:languagecode:mustagreetoe-8ulkh"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiconsumerdisclosure\/init(accountesignid:allowcdwithdraw:allowcdwithdrawmetadata:changeemail:changeemailother:companyname:companyphone:copycostperpage:copyfeecollectionmethod:copyrequestemail:custom:enableesign:esignagreement:esigntext:languagecode:mustagreetoe-8ulkh"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"accountEsignId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"allowCDWithdraw"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"allowCDWithdrawMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"changeEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"changeEmailOther","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"companyName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"companyPhone","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"copyCostPerPage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"copyFeeCollectionMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"copyRequestEmail","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"custom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"enableEsign"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"esignAgreement"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"esignText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"languageCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"mustAgreeToEsign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"pdfId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"useBrand","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"useConsumerDisclosureWithinAccount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"useConsumerDisclosureWithinAccountMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"withdrawAddressLine1","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"withdrawAddressLine2"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"withdrawByEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"withdrawByMail"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"withdrawByPhone"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"withdrawCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"withdrawConsequences"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"withdrawEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"withdrawOther"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"withdrawPhone","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"withdrawPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"withdrawState","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISettingsMetadata":{"navigatorTitle":[{"kind":"identifier","text":"DSAPISettingsMetadata"}],"role":"symbol","abstract":[{"type":"text","text":"Metadata that indicates whether a property is editable and describes setting-specific options."}],"title":"DSAPISettingsMetadata","kind":"symbol","url":"\/documentation\/docusignapi\/dsapisettingsmetadata","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISettingsMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure":{"type":"topic","title":"DSAPIConsumerDisclosure","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIConsumerDisclosure"}],"navigatorTitle":[{"text":"DSAPIConsumerDisclosure","kind":"identifier"}],"abstract":[{"type":"text","text":"Details about consumer disclosures."}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIConsumerDisclosure/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)":{"url":"\/documentation\/docusignapi\/dsapiconsumerdisclosure\/init(accountesignid:allowcdwithdraw:allowcdwithdrawmetadata:changeemail:changeemailother:companyname:companyphone:copycostperpage:copyfeecollectionmethod:copyrequestemail:custom:enableesign:esignagreement:esigntext:languagecode:mustagreetoe-8ulkh","title":"init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIConsumerDisclosure\/init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountEsignId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"allowCDWithdraw"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowCDWithdrawMetadata"},{"kind":"text","text":": "},{"text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"changeEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"changeEmailOther"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"companyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"companyPhone","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"copyCostPerPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"copyFeeCollectionMethod","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"copyRequestEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"custom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"enableEsign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"esignAgreement"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"esignText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"languageCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mustAgreeToEsign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pdfId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"useBrand"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useConsumerDisclosureWithinAccount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"useConsumerDisclosureWithinAccountMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","kind":"typeIdentifier","text":"DSAPISettingsMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawAddressLine1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"withdrawAddressLine2","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawByEmail"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawByMail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withdrawByPhone"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"withdrawCity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawConsequences","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"withdrawEmail","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withdrawOther","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"withdrawPhone","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withdrawPostalCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"withdrawState","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAccountEsignId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accountEsignId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"allowCDWithdraw:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowCDWithdraw","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowCDWithdrawMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"allowCDWithdrawMetadata"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeEmail:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"changeEmail","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"changeEmailOther:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"changeEmailOther"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyName:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"companyName"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyPhone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"companyPhone"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyCostPerPage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"copyCostPerPage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"copyFeeCollectionMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"copyFeeCollectionMethod","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyRequestEmail:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"copyRequestEmail","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"custom:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"custom"},{"text":" ","kind":"text"},{"text":"enableEsign:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"enableEsign","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"esignAgreement:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"esignAgreement","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"esignText:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"esignText","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"languageCode:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"languageCode"},{"text":" ","kind":"text"},{"text":"mustAgreeToEsign:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"mustAgreeToEsign"},{"kind":"text","text":" "},{"text":"pdfId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"pdfId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"useBrand"},{"text":" ","kind":"text"},{"text":"useConsumerDisclosureWithinAccount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"useConsumerDisclosureWithinAccount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useConsumerDisclosureWithinAccountMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISettingsMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISettingsMetadata","text":"DSAPISettingsMetadata","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"useConsumerDisclosureWithinAccountMetadata","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withdrawAddressLine1:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"withdrawAddressLine1"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawAddressLine2:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"withdrawAddressLine2","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawByEmail:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"withdrawByEmail","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawByMail:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"withdrawByMail"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawByPhone:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"withdrawByPhone"},{"text":" ","kind":"text"},{"text":"withdrawCity:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"withdrawCity","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withdrawConsequences:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"withdrawConsequences","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withdrawEmail:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"withdrawEmail","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withdrawOther:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"withdrawOther"},{"kind":"text","text":" "},{"kind":"identifier","text":"withdrawPhone:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"withdrawPhone"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withdrawPostalCode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"withdrawPostalCode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withdrawState:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"withdrawState"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DSAPISettingsMetadata","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISettingsMetadata\/fragments","value":[{"kind":"identifier","text":"DSAPISettingsMetadata"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/title","op":"replace","value":"DSAPIConsumerDisclosure"},{"value":[{"text":"DSAPIConsumerDisclosure","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure\/fragments"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)\/title","op":"replace","value":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAccountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIConsumerDisclosure~1init(accountEsignId:allowCDWithdraw:allowCDWithdrawMetadata:changeEmail:changeEmailOther:companyName:companyPhone:copyCostPerPage:copyFeeCollectionMethod:copyRequestEmail:custom:enableEsign:esignAgreement:esignText:languageCode:mustAgreeToEsign:pdfId:useBrand:useConsumerDisclosureWithinAccount:useConsumerDisclosureWithinAccountMetadata:withdrawAddressLine1:withdrawAddressLine2:withdrawByEmail:withdrawByMail:withdrawByPhone:withdrawCity:withdrawConsequences:withdrawEmail:withdrawOther:withdrawPhone:withdrawPostalCode:withdrawState:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}