{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField","text":"DSAPIListCustomField"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","text":"DSAPITextCustomField"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapicustomfieldsenvelope\/init(listcustomfields:textcustomfields:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFieldsEnvelope\/init(listCustomFields:textCustomFields:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"kind":"text","text":"]?)"}],"title":"init(listCustomFields:textCustomFields:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI25DSAPICustomFieldsEnvelopeV010listCustomE004texthE0ACSayAA09DSAPIListH5FieldCGSg_SayAA09DSAPITexthK0CGSgtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFieldsEnvelope"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITextCustomField":{"role":"symbol","title":"DSAPITextCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITextCustomField"}],"abstract":[{"type":"text","text":"This object represents a free text custom field where envelope creators and senders can enter custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITextCustomField"}],"url":"\/documentation\/docusignapi\/dsapitextcustomfield"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFieldsEnvelope/init(listCustomFields:textCustomFields:)":{"role":"symbol","title":"init(listCustomFields:textCustomFields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIListCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"textCustomFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFieldsEnvelope\/init(listCustomFields:textCustomFields:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapicustomfieldsenvelope\/init(listcustomfields:textcustomfields:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICustomFieldsEnvelope":{"role":"symbol","title":"DSAPICustomFieldsEnvelope","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPICustomFieldsEnvelope"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICustomFieldsEnvelope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICustomFieldsEnvelope"}],"url":"\/documentation\/docusignapi\/dsapicustomfieldsenvelope"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField":{"role":"symbol","title":"DSAPIListCustomField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIListCustomField"}],"abstract":[{"type":"text","text":"This object represents a list custom field from which envelope creators and senders can select custom data."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIListCustomField"}],"url":"\/documentation\/docusignapi\/dsapilistcustomfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/title","value":"DSAPITextCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPITextCustomField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/title","value":"DSAPIListCustomField"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/fragments","value":[{"kind":"identifier","text":"DSAPIListCustomField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}