{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lockDurationInSeconds"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"lockedByApp","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lockedByUser"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"lockedUntilDateTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"lockToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"lockType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"useScratchPad"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false)","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation\/init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapilockinformation\/init(errordetails:lockdurationinseconds:lockedbyapp:lockedbyuser:lockeduntildatetime:locktoken:locktype:usescratchpad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapilockinformation\/init(errordetails:lockdurationinseconds:lockedbyapp:lockedbyuser:lockeduntildatetime:locktoken:locktype:usescratchpad:)"]}],"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation(im)initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:","symbolKind":"init","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockDurationInSeconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lockedByApp","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lockedByUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier","text":"DSAPIUserInfo"},{"text":"?, ","kind":"text"},{"text":"lockedUntilDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"useScratchPad","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation":{"url":"\/documentation\/docusignapi\/dsapilockinformation","title":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILockInformation"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPILockInformation"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation/init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapilockinformation\/init(errordetails:lockdurationinseconds:lockedbyapp:lockedbyuser:lockeduntildatetime:locktoken:locktype:usescratchpad:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockDurationInSeconds"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedByApp"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockedByUser"},{"text":": ","kind":"text"},{"text":"DSAPIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedUntilDateTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"text":"lockToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"lockType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useScratchPad"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation\/init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)","title":"init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)","navigatorTitle":[{"text":"initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithErrorDetails:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"kind":"text","text":" *) "},{"text":"errorDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockDurationInSeconds:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lockDurationInSeconds"},{"kind":"text","text":" "},{"text":"lockedByApp:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lockedByApp"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockedByUser:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo"},{"text":" *) ","kind":"text"},{"text":"lockedByUser","kind":"internalParam"},{"kind":"text","text":" "},{"text":"lockedUntilDateTime:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"lockedUntilDateTime"},{"text":" ","kind":"text"},{"text":"lockToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lockToken"},{"kind":"text","text":" "},{"text":"lockType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"lockType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useScratchPad:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useScratchPad"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/title","value":"DSAPILockInformation","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPILockInformation"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments","value":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"op":"replace"},{"op":"replace","value":"DSAPIUserInfo","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIUserInfo"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation~1init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)\/title","value":"initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation~1init(errorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithErrorDetails:lockDurationInSeconds:lockedByApp:lockedByUser:lockedUntilDateTime:lockToken:lockType:useScratchPad:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}