{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTransferRule"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"carbonCopyOriginalOwner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"envelopeTransferRuleId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"eventType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fromGroup"},{"text":": ","kind":"text"},{"text":"DSAPIGroup","preciseIdentifier":"s:11DocuSignAPI10DSAPIGroupV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIGroup","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"fromUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIUserInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation"},{"kind":"text","text":"? = nil, "},{"text":"modifiedDate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"? = nil, ","kind":"text"},{"text":"modifiedUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIUserInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"toFolder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder","kind":"typeIdentifier","text":"DSAPIFolder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder"},{"text":"? = nil, ","kind":"text"},{"text":"toUser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","text":"DSAPIUserInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTransferRule\/init(carbonCopyOriginalOwner:enabled:envelopeTransferRuleId:eventType:fromGroup:fromUser:modifiedDate:modifiedUser:toFolder:toUser:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopetransferrule\/init(carboncopyoriginalowner:enabled:envelopetransferruleid:eventtype:fromgroup:fromuser:modifieddate:modifieduser:tofolder:touser:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:11DocuSignAPI25DSAPIEnvelopeTransferRuleV23carbonCopyOriginalOwner7enabled08envelopeeF2Id9eventType9fromGroup0P4User12modifiedDate0sR08toFolder0uR0ACSb_SbSSSgAnA10DSAPIGroupVSgAA20DSAPIUserInformationCSg10Foundation0T0VSgAtA11DSAPIFolderCSgATtcfc","roleHeading":"Initializer","title":"init(carbonCopyOriginalOwner:enabled:envelopeTransferRuleId:eventType:fromGroup:fromUser:modifiedDate:modifiedUser:toFolder:toUser:)","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"carbonCopyOriginalOwner","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"envelopeTransferRuleId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"eventType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"fromGroup","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIGroup","preciseIdentifier":"s:11DocuSignAPI10DSAPIGroupV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"text":"DSAPIUserInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"modifiedDate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"text":"modifiedUser","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIUserInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation"},{"kind":"text","text":"?, "},{"text":"toFolder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIFolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"text":"?, ","kind":"text"},{"text":"toUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIUserInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"modules":[{"name":"DocuSignAPI"}]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolder":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFolder"}],"url":"\/documentation\/docusignapi\/dsapifolder","title":"DSAPIFolder","kind":"symbol","abstract":[{"type":"text","text":"This object contains details about a folder."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFolder"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInformation":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIUserInformation","kind":"identifier"}],"type":"topic","title":"DSAPIUserInformation","abstract":[{"type":"text","text":"User information."}],"url":"\/documentation\/docusignapi\/dsapiuserinformation","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInformation"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTransferRule/init(carbonCopyOriginalOwner:enabled:envelopeTransferRuleId:eventType:fromGroup:fromUser:modifiedDate:modifiedUser:toFolder:toUser:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTransferRule\/init(carbonCopyOriginalOwner:enabled:envelopeTransferRuleId:eventType:fromGroup:fromUser:modifiedDate:modifiedUser:toFolder:toUser:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"carbonCopyOriginalOwner"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"envelopeTransferRuleId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"fromGroup","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI10DSAPIGroupV","text":"DSAPIGroup"},{"text":"?, ","kind":"text"},{"text":"fromUser","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","text":"DSAPIUserInformation","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"modifiedDate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"text":"modifiedUser","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIUserInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"toFolder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIFolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"toUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIUserInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInformation"},{"kind":"text","text":"?)"}],"type":"topic","title":"init(carbonCopyOriginalOwner:enabled:envelopeTransferRuleId:eventType:fromGroup:fromUser:modifiedDate:modifiedUser:toFolder:toUser:)","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopetransferrule\/init(carboncopyoriginalowner:enabled:envelopetransferruleid:eventtype:fromgroup:fromuser:modifieddate:modifieduser:tofolder:touser:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTransferRule":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeTransferRule"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTransferRule","abstract":[{"type":"text","text":"This object contains details about an envelope transfer rule."}],"title":"DSAPIEnvelopeTransferRule","role":"symbol","kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopetransferrule","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIEnvelopeTransferRule","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIGroup":{"kind":"symbol","abstract":[{"type":"text","text":"This object contains information about a group."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIGroup","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIGroup","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIGroup"}],"url":"\/documentation\/docusignapi\/dsapigroup","type":"topic","role":"symbol","title":"DSAPIGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DSAPIFolder","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIFolder"}]},{"value":"DSAPIUserInformation","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInformation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInformation\/fragments","value":[{"text":"DSAPIUserInformation","kind":"identifier"}]}]}]}