{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider","text":"DSAPIRecipientSignatureProvider"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiinpersonsigner\/recipientsignatureproviders"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiinpersonsigner\/recipientsignatureproviders"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner\/recipientSignatureProviders","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The default signature provider is the DocuSign Electronic signature system. This parameter is used to specify one or more Standards Based Signature (digital signature) providers for the signer to use. "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider"},{"kind":"text","text":"]?"}],"title":"recipientSignatureProviders","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner(py)recipientSignatureProviders","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"recipientSignatureProviders"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInPersonSigner/recipientSignatureProviders":{"role":"symbol","title":"recipientSignatureProviders","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The default signature provider is the DocuSign Electronic signature system. This parameter is used to specify one or more Standards Based Signature (digital signature) providers for the signer to use. "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner\/recipientSignatureProviders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recipientSignatureProviders"}],"url":"\/documentation\/docusignapi\/dsapiinpersonsigner\/recipientsignatureproviders"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"role":"symbol","title":"DSAPIRecipientSignatureProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"title":"More information","titleInlineContent":[{"type":"text","text":"More information"}],"type":"link","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInPersonSigner":{"role":"symbol","title":"DSAPIInPersonSigner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIInPersonSigner"}],"abstract":[{"type":"text","text":"Contains information about an in-person recipient. This is a DocuSign user, acting as a Signing Host, who is in the same physical location as the signer. To learn about the fields used for the eNotary feature, see the [recipients resource][resource].  [resource]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipients\/#in-person-signer-recipient"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIInPersonSigner"}],"url":"\/documentation\/docusignapi\/dsapiinpersonsigner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recipientSignatureProviders"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recipientSignatureProviders"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DSAPIRecipientSignatureProvider *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recipientSignatureProviders"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner~1recipientSignatureProviders\/title","value":"recipientSignatureProviders"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner~1recipientSignatureProviders\/fragments","value":[{"kind":"identifier","text":"recipientSignatureProviders"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/title","value":"DSAPIRecipientSignatureProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner\/title","value":"DSAPIInPersonSigner"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner\/fragments","value":[{"kind":"identifier","text":"DSAPIInPersonSigner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}