{"variants":[{"paths":["\/documentation\/docusignapi\/dsapiinpersonsigner\/signernamemetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapiinpersonsigner\/signernamemetadata"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner\/signerNameMetadata"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner"]]},"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"text":"signerNameMetadata","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIInPersonSigner(py)signerNameMetadata","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signerNameMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"signerNameMetadata","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signerNameMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInPersonSigner/signerNameMetadata":{"navigatorTitle":[{"kind":"identifier","text":"signerNameMetadata"}],"url":"\/documentation\/docusignapi\/dsapiinpersonsigner\/signernamemetadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signerNameMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"title":"signerNameMetadata","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner\/signerNameMetadata","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIInPersonSigner":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIInPersonSigner","kind":"identifier"}],"type":"topic","title":"DSAPIInPersonSigner","abstract":[{"type":"text","text":"Contains information about an in-person recipient. This is a DocuSign user, acting as a Signing Host, who is in the same physical location as the signer. To learn about the fields used for the eNotary feature, see the [recipients resource][resource].  [resource]: \/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipients\/#in-person-signer-recipient"}],"url":"\/documentation\/docusignapi\/dsapiinpersonsigner","navigatorTitle":[{"text":"DSAPIInPersonSigner","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIInPersonSigner"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"signerNameMetadata","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"signerNameMetadata"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":" * "},{"kind":"identifier","text":"signerNameMetadata"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner~1signerNameMetadata\/title","value":"signerNameMetadata","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner~1signerNameMetadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"signerNameMetadata"}]},{"value":"DSAPIInPersonSigner","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIInPersonSigner"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIInPersonSigner\/fragments"},{"value":"DSAPIPropertyMetadata","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","op":"replace"}]}]}