{"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"requireInitialOnSharedChange"}],"title":"requireInitialOnSharedChange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requireInitialOnSharedChange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRadioGroup(py)requireInitialOnSharedChange","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"BoolFromString","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requireInitialOnSharedChange","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup\/requireInitialOnSharedChange","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup"]]},"abstract":[{"type":"text","text":"Optional element for field markup. When "},{"inlineContent":[{"type":"text","text":"true,"}],"type":"strong"},{"text":" the signer is required to initial when they modify a shared field.","type":"text"}],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiradiogroup\/requireinitialonsharedchange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiradiogroup\/requireinitialonsharedchange"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/":{"type":"link","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","title":"`radio`","titleInlineContent":[{"type":"text","text":"`radio`"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadioGroup/requireInitialOnSharedChange":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapiradiogroup\/requireinitialonsharedchange","navigatorTitle":[{"kind":"identifier","text":"requireInitialOnSharedChange"}],"title":"requireInitialOnSharedChange","type":"topic","abstract":[{"type":"text","text":"Optional element for field markup. When "},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"text":" the signer is required to initial when they modify a shared field.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup\/requireInitialOnSharedChange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireInitialOnSharedChange"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRadioGroup":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIRadioGroup"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapiradiogroup","role":"symbol","abstract":[{"text":"This group tab is used to place radio buttons on a document. The `radios` property contains a list of ","type":"text"},{"type":"reference","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/","isActive":true},{"text":" objects  associated with the group. Only one radio button can be selected in a group.","type":"text"}],"title":"DSAPIRadioGroup","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRadioGroup","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIRadioGroup","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"requireInitialOnSharedChange","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"requireInitialOnSharedChange"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"requireInitialOnSharedChange","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"requireInitialOnSharedChange","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup~1requireInitialOnSharedChange\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup~1requireInitialOnSharedChange\/fragments","value":[{"text":"requireInitialOnSharedChange","kind":"identifier"}],"op":"replace"},{"value":"DSAPIRadioGroup","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRadioGroup\/fragments","value":[{"text":"DSAPIRadioGroup","kind":"identifier"}],"op":"replace"},{"value":"BoolFromString","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title"},{"value":[{"text":"BoolFromString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments"}]}]}