{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient"]]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/addAccessCodeToEmail","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Optional. When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"text":" the access code will be added to the email sent to the recipient. This nullifies the security measure of `accessCode` on the recipient.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAccessCodeToEmail"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient(py)addAccessCodeToEmail","roleHeading":"Instance Property","title":"addAccessCodeToEmail","navigatorTitle":[{"kind":"identifier","text":"addAccessCodeToEmail"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addAccessCodeToEmail"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"DocuSignAPI"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/addaccesscodetoemail"]},{"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/addaccesscodetoemail"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient":{"url":"\/documentation\/docusignapi\/dsapinotaryrecipient","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient","title":"DSAPINotaryRecipient","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPINotaryRecipient","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPINotaryRecipient","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient/addAccessCodeToEmail":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/addAccessCodeToEmail","title":"addAccessCodeToEmail","url":"\/documentation\/docusignapi\/dsapinotaryrecipient\/addaccesscodetoemail","abstract":[{"type":"text","text":"Optional. When "},{"type":"strong","inlineContent":[{"text":"true,","type":"text"}]},{"text":" the access code will be added to the email sent to the recipient. This nullifies the security measure of `accessCode` on the recipient.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"addAccessCodeToEmail","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addAccessCodeToEmail"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"addAccessCodeToEmail","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"addAccessCodeToEmail"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"addAccessCodeToEmail","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/title","value":"DSAPINotaryRecipient"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPINotaryRecipient"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/fragments"},{"value":"addAccessCodeToEmail","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient~1addAccessCodeToEmail\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient~1addAccessCodeToEmail\/fragments","value":[{"text":"addAccessCodeToEmail","kind":"identifier"}]}]}]}