{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"accessCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"accessCodeMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"addAccessCodeToEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"additionalNotifications","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","text":"DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]? = nil, "},{"text":"agentCanEditEmail","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"agentCanEditName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"allowSystemOverrideForLockedRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"autoNavigation"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"autoRespondedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"bulkRecipientsUri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canSignOffline"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"completedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"creationReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"customFields"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"declinedDateTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"? = nil, ","kind":"text"},{"text":"declinedReason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"defaultRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"delegatedBy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDelegationInfo","text":"DSAPIDelegationInfo","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"delegatedTo","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDelegationInfo","text":"DSAPIDelegationInfo","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV"},{"text":"]? = nil, ","kind":"text"},{"text":"deliveredDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"deliveryMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"deliveryMethodMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"designatorId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"designatorIdGuid"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"documentVisibility","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DSAPIDocumentVisibility","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"emailMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"emailNotification","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"excludedDocuments"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"faxNumberMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"firstName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"fullNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckConfigurationNameMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"idCheckInformationInput","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","text":"DSAPIIdCheckInformationInput","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"identityVerification"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","text":"DSAPIRecipientIdentityVerification","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"inheritEmailNotificationConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"isBulkRecipient"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"isBulkRecipientMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"lastName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"lastNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"liveOakStartURL"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"lockedRecipientSmsEditable","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"notaryId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"notarySignerEmailSent"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"notarySigners","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"notaryType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"note","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"noteMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"offlineAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes","kind":"typeIdentifier","text":"DSAPIOfflineAttributes","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"text":"DSAPIRecipientPhoneAuthentication","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"text":"DSAPIRecipientPhoneNumber","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"proofFile"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientProofFile","preciseIdentifier":"s:11DocuSignAPI23DSAPIRecipientProofFileV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientProofFile","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"recipientAttachments","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","kind":"typeIdentifier","text":"DSAPIRecipientAttachment"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recipientAuthenticationStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","text":"DSAPIAuthenticationStatus"},{"kind":"text","text":"? = nil, "},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFeatureAvailableMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"recipientId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"recipientIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"recipientSignatureProviders","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider"},{"text":"]? = nil, ","kind":"text"},{"text":"recipientSuppliesTabs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"recipientType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"recipientTypeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"? = nil, "},{"text":"requireIdLookup","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"requireIdLookupMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"requireSignerCertificate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"requireSignOnPaper","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"requireUploadSignature","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"roleName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"routingOrder"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"routingOrderMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"sentDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"? = nil, ","kind":"text"},{"text":"signatureInfo","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureInformation","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureInformation","text":"DSAPIRecipientSignatureInformation"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signedDateTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signInEachLocation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"signInEachLocationMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signingGroupId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"signingGroupIdMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":"? = nil, ","kind":"text"},{"text":"signingGroupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"signingGroupUsers"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","text":"DSAPIUserInfo","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"smsAuthentication"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"socialAuthentications"},{"text":": [","kind":"text"},{"text":"DSAPISocialAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication"},{"text":"]? = nil, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"statusCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"suppressEmails"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"tabs","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","text":"DSAPITabs"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"templateLocked"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"templateRequired"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"totalTabCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:agentcaneditemail:agentcaneditname:allowsystemoverrideforlockedrecipient:autonavigation:autorespondedreason:bulkrecipientsuri:cansignoffline:clientuserid:comple-5tyg3"]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:liveOakStartURL:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:notarySigners:notaryType:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"accessCodeMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"addAccessCodeToEmail"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"additionalNotifications"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification","kind":"typeIdentifier","text":"DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]?, "},{"text":"agentCanEditEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"agentCanEditName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"allowSystemOverrideForLockedRecipient"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoNavigation"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoRespondedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bulkRecipientsUri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canSignOffline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completedCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"creationReason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"customFields","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"text":"declinedDateTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"declinedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"defaultRecipient"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegatedBy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","text":"DSAPIDelegationInfo","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"delegatedTo","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","text":"DSAPIDelegationInfo"},{"kind":"text","text":"]?, "},{"text":"deliveredDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethodMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"designatorId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"designatorIdGuid"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"documentVisibility"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","text":"DSAPIDocumentVisibility","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","text":"DSAPIRecipientEmailNotification"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"emailRecipientPostSigningURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"embeddedRecipientStartURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"excludedDocuments","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"faxNumber"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"faxNumberMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"firstName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstNameMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"fullName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullNameMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","text":"DSAPIIdCheckInformationInput"},{"text":"?, ","kind":"text"},{"text":"identityVerification","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIRecipientIdentityVerification","preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"inheritEmailNotificationConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"isBulkRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"isBulkRecipientMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"lastName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"lastNameMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"liveOakStartURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockedRecipientPhoneAuthEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nameMetadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"notaryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"notarySignerEmailSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"notarySigners","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"notaryType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"note","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"noteMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"offlineAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes","text":"DSAPIOfflineAttributes"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"phoneAuthentication"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"phoneNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV","kind":"typeIdentifier","text":"DSAPIRecipientPhoneNumber"},{"kind":"text","text":"?, "},{"text":"proofFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIRecipientProofFile","preciseIdentifier":"s:11DocuSignAPI23DSAPIRecipientProofFileV"},{"text":"?, ","kind":"text"},{"text":"recipientAttachments","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment"},{"text":"]?, ","kind":"text"},{"text":"recipientAuthenticationStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV","text":"DSAPIAuthenticationStatus","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","kind":"typeIdentifier","text":"DSAPIFeatureAvailableMetadata"},{"kind":"text","text":"]?, "},{"text":"recipientId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"recipientIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"recipientSignatureProviders"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider"},{"text":"]?, ","kind":"text"},{"text":"recipientSuppliesTabs","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recipientType"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"recipientTypeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"requireIdLookup"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requireIdLookupMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requireSignerCertificate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requireSignOnPaper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"requireUploadSignature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"roleName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"routingOrder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"routingOrderMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"sentDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signatureInfo"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientSignatureInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signedDateTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signInEachLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"signInEachLocationMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"signingGroupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"signingGroupIdMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"signingGroupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"signingGroupUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier","text":"DSAPIUserInfo"},{"kind":"text","text":"]?, "},{"text":"smsAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"statusCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"suppressEmails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"tabs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPITabs","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"templateLocked"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateRequired"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"totalTabCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"externalID":"s:11DocuSignAPI20DSAPINotaryRecipientC10accessCode0fG8Metadata09addAccessG7ToEmail23additionalNotifications012agentCanEditL00opQ4Name028allowSystemOverrideForLockedE014autoNavigation0X15RespondedReason17bulkRecipientsUri03canB7Offline12clientUserId14completedCount14creationReason12customFields16declinedDateTime14declinedReason07defaultE011delegatedBy09delegatedK017deliveredDateTime14deliveryMethod014deliveryMethodH012designatorId16designatorIdGuid18documentVisibility5email05emailH017emailNotification05emailE14PostSigningURL08embeddedE8StartURL12errorDetails17excludedDocuments9faxNumber09faxNumberH005firstR005firstrH004fullR004fullrH0020idCheckConfigurationR0020idCheckConfigurationrH023idCheckInformationInput20identityVerification07inheritL25NotificationConfiguration06isBulkE006isBulkeH004lastR004lastrH015liveOakStartURL06lockedE17PhoneAuthEditable06lockedE11SmsEditable4name04nameH08notaryId012notarySignerL4Sent13notarySigners10notaryType4note04noteH017offlineAttributes19phoneAuthentication11phoneNumber9proofFile20recipientAttachments29recipientAuthenticationStatus016recipientFeatureH011recipientId15recipientIdGuid27recipientSignatureProviders21recipientSuppliesTabs13recipientType013recipientTypeH015requireIdLookup015requireIdLookupH024requireSignerCertificate07requireB7OnPaper22requireUploadSignature04roleR012routingOrder012routingOrderH012sentDateTime13signatureInfo14signedDateTime18signInEachLocation018signInEachLocationH014signingGroupId014signingGroupIdH0012signingGroupR017signingGroupUsers17smsAuthentication21socialAuthentications6status06statusG014suppressEmails4tabs08templateW016templateRequired13totalTabCount6userIdACSSSg_AA013DSAPIPropertyH0CSgA75_SayAA36DSAPIRecipientAdditionalNotificationCGSgA75_A75_S2bA75_10Foundation3URLVSgSbA75_A75_A75_SaySSGSgA83_4DateVSgA75_SbAA19DSAPIDelegationInfoVSgSayA93_GSgA91_A75_A78_A75_A75_SayAA23DSAPIDocumentVisibilityCGSgA75_A78_AA014DSAPIRecipientL12NotificationCSgA75_A75_AA17DSAPIErrorDetailsCSgA88_A75_A78_A75_A78_A75_A78_A75_A78_AA28DSAPIIdCheckInformationInputVSgAA34DSAPIRecipientIdentityVerificationVSgSbA75_A78_A75_A78_A75_A75_A75_A75_A78_A75_A75_A88_A75_A75_A78_AA22DSAPIOfflineAttributesCSgAA33DSAPIRecipientPhoneAuthenticationVSgAA25DSAPIRecipientPhoneNumberVSgAA23DSAPIRecipientProofFileVSgSayAA24DSAPIRecipientAttachmentCGSgAA25DSAPIAuthenticationStatusVSgSayAA021DSAPIFeatureAvailableH0VGSgA75_A75_SayAA31DSAPIRecipientSignatureProviderCGSgSbA75_A78_SbA78_A75_S2bA75_A75_A78_A91_AA34DSAPIRecipientSignatureInformationCSgA91_SbA78_A75_A78_A75_SayAA13DSAPIUserInfoCGSgAA31DSAPIRecipientSMSAuthenticationCSgSayAA25DSAPISocialAuthenticationCGSgA75_A75_SbAA9DSAPITabsCSgS2bA75_A75_tcfc","title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:liveOakStartURL:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:notarySigners:notaryType:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","symbolKind":"init","role":"symbol"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDocumentVisibility":{"abstract":[{"type":"text","text":"This object configures a recipient's read\/write access to a document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIDocumentVisibility","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapidocumentvisibility","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIDocumentVisibility"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDocumentVisibility","role":"symbol","title":"DSAPIDocumentVisibility","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSMSAuthentication":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","type":"topic","title":"DSAPIRecipientSMSAuthentication","role":"symbol","abstract":[{"type":"text","text":"Contains the element senderProvidedNumbers which is an Array  of phone numbers the recipient can use for SMS text authentication."}],"url":"\/documentation\/docusignapi\/dsapirecipientsmsauthentication","navigatorTitle":[{"text":"DSAPIRecipientSMSAuthentication","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientEmailNotification":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientemailnotification","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientEmailNotification","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","role":"symbol","title":"DSAPIRecipientEmailNotification","kind":"symbol"},"/docs/idevidence-api/":{"type":"link","titleInlineContent":[{"type":"text","text":"ID Evidence"}],"url":"\/docs\/idevidence-api\/","title":"ID Evidence","identifier":"\/docs\/idevidence-api\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneNumber":{"abstract":[{"text":"Describes the recipient phone number.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientPhoneNumber","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientphonenumber","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientPhoneNumber","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneNumber","role":"symbol","title":"DSAPIRecipientPhoneNumber","kind":"symbol"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"type":"link","url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","title":"More information","titleInlineContent":[{"type":"text","text":"More information"}],"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},"https://support.docusign.com/en/guides/ndse-user-guide-recipient-authentication":{"type":"link","titleInlineContent":[{"text":"recipient authentication","type":"text"}],"url":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","title":"recipient authentication","identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserInfo":{"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserInfo","type":"topic","url":"\/documentation\/docusignapi\/dsapiuserinfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserInfo"}],"title":"DSAPIUserInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserInfo"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:liveOakStartURL:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:notarySigners:notaryType:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:liveOakStartURL:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:notarySigners:notaryType:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","url":"\/documentation\/docusignapi\/dsapinotaryrecipient\/init(accesscode:accesscodemetadata:addaccesscodetoemail:additionalnotifications:agentcaneditemail:agentcaneditname:allowsystemoverrideforlockedrecipient:autonavigation:autorespondedreason:bulkrecipientsuri:cansignoffline:clientuserid:comple-5tyg3","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"accessCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accessCodeMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"addAccessCodeToEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"additionalNotifications","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientAdditionalNotification","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAdditionalNotification"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"agentCanEditEmail"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"agentCanEditName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"allowSystemOverrideForLockedRecipient","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"autoNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"autoRespondedReason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"bulkRecipientsUri","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"canSignOffline","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"clientUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"creationReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"declinedDateTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"declinedReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"defaultRecipient","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegatedBy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIDelegationInfo","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"delegatedTo","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI19DSAPIDelegationInfoV","text":"DSAPIDelegationInfo"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"deliveredDateTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deliveryMethod"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"deliveryMethodMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"designatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"designatorIdGuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"documentVisibility","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIDocumentVisibility","kind":"typeIdentifier","text":"DSAPIDocumentVisibility"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"email"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"emailMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"emailNotification","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIRecipientEmailNotification","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"text":"emailRecipientPostSigningURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"errorDetails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"excludedDocuments","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"faxNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"faxNumberMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"firstName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"firstNameMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fullName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"fullNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"idCheckConfigurationName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"idCheckConfigurationNameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"idCheckInformationInput","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIIdCheckInformationInput","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"text":"?, ","kind":"text"},{"text":"identityVerification","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI34DSAPIRecipientIdentityVerificationV","kind":"typeIdentifier","text":"DSAPIRecipientIdentityVerification"},{"kind":"text","text":"?, "},{"text":"inheritEmailNotificationConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"isBulkRecipient","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isBulkRecipientMetadata"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"text":"lastName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lastNameMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"liveOakStartURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lockedRecipientPhoneAuthEditable","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lockedRecipientSmsEditable"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"nameMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"notaryId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"notarySignerEmailSent"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"notarySigners","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"notaryType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"note","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noteMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","kind":"typeIdentifier","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"offlineAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPIOfflineAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIOfflineAttributes"},{"text":"?, ","kind":"text"},{"text":"phoneAuthentication","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIRecipientPhoneAuthentication","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"phoneNumber"},{"text":": ","kind":"text"},{"text":"DSAPIRecipientPhoneNumber","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI25DSAPIRecipientPhoneNumberV"},{"kind":"text","text":"?, "},{"text":"proofFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI23DSAPIRecipientProofFileV","text":"DSAPIRecipientProofFile"},{"text":"?, ","kind":"text"},{"text":"recipientAttachments","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","text":"DSAPIRecipientAttachment"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"recipientAuthenticationStatus"},{"kind":"text","text":": "},{"text":"DSAPIAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI25DSAPIAuthenticationStatusV"},{"text":"?, ","kind":"text"},{"text":"recipientFeatureMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DocuSignAPI29DSAPIFeatureAvailableMetadataV","text":"DSAPIFeatureAvailableMetadata"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientIdGuid"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"recipientSignatureProviders","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureProvider"},{"text":"]?, ","kind":"text"},{"text":"recipientSuppliesTabs","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipientType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"recipientTypeMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"requireIdLookup","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"requireIdLookupMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"requireSignerCertificate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"requireSignOnPaper","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"requireUploadSignature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"roleName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"routingOrder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"routingOrderMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sentDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"signatureInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSignatureInformation","text":"DSAPIRecipientSignatureInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signedDateTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signInEachLocation"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"signInEachLocationMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata"},{"text":"?, ","kind":"text"},{"text":"signingGroupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"signingGroupIdMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"signingGroupUsers"},{"text":": [","kind":"text"},{"text":"DSAPIUserInfo","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserInfo","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"smsAuthentication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"socialAuthentications"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"text":"]?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"suppressEmails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"tabs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DSAPITabs","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"templateLocked"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"templateRequired","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"totalTabCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","title":"init(accessCode:accessCodeMetadata:addAccessCodeToEmail:additionalNotifications:agentCanEditEmail:agentCanEditName:allowSystemOverrideForLockedRecipient:autoNavigation:autoRespondedReason:bulkRecipientsUri:canSignOffline:clientUserId:completedCount:creationReason:customFields:declinedDateTime:declinedReason:defaultRecipient:delegatedBy:delegatedTo:deliveredDateTime:deliveryMethod:deliveryMethodMetadata:designatorId:designatorIdGuid:documentVisibility:email:emailMetadata:emailNotification:emailRecipientPostSigningURL:embeddedRecipientStartURL:errorDetails:excludedDocuments:faxNumber:faxNumberMetadata:firstName:firstNameMetadata:fullName:fullNameMetadata:idCheckConfigurationName:idCheckConfigurationNameMetadata:idCheckInformationInput:identityVerification:inheritEmailNotificationConfiguration:isBulkRecipient:isBulkRecipientMetadata:lastName:lastNameMetadata:liveOakStartURL:lockedRecipientPhoneAuthEditable:lockedRecipientSmsEditable:name:nameMetadata:notaryId:notarySignerEmailSent:notarySigners:notaryType:note:noteMetadata:offlineAttributes:phoneAuthentication:phoneNumber:proofFile:recipientAttachments:recipientAuthenticationStatus:recipientFeatureMetadata:recipientId:recipientIdGuid:recipientSignatureProviders:recipientSuppliesTabs:recipientType:recipientTypeMetadata:requireIdLookup:requireIdLookupMetadata:requireSignerCertificate:requireSignOnPaper:requireUploadSignature:roleName:routingOrder:routingOrderMetadata:sentDateTime:signatureInfo:signedDateTime:signInEachLocation:signInEachLocationMetadata:signingGroupId:signingGroupIdMetadata:signingGroupName:signingGroupUsers:smsAuthentication:socialAuthentications:status:statusCode:suppressEmails:tabs:templateLocked:templateRequired:totalTabCount:userId:)","abstract":[],"role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIDelegationInfo":{"url":"\/documentation\/docusignapi\/dsapidelegationinfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIDelegationInfo","kind":"identifier"}],"title":"DSAPIDelegationInfo","navigatorTitle":[{"kind":"identifier","text":"DSAPIDelegationInfo"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIDelegationInfo","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientProofFile":{"abstract":[{"type":"text","text":"The proof file of the recipient. "},{"identifier":"\/docs\/idevidence-api\/","isActive":true,"type":"reference"},{"text":" uses proof files to store the identification data that recipients submit when verifying their ID with ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/","type":"reference","isActive":true}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientProofFile","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientprooffile","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientProofFile","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientProofFile","role":"symbol","title":"DSAPIRecipientProofFile","kind":"symbol"},"/docs/esign-rest-api/reference/accounts/identityverifications/list/":{"type":"link","titleInlineContent":[{"type":"text","text":"list"}],"url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","title":"list","identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIOfflineAttributes":{"abstract":[{"type":"text","text":"Reserved for DocuSign use."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DSAPIOfflineAttributes","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiofflineattributes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIOfflineAttributes","role":"symbol","title":"DSAPIOfflineAttributes","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"/docs/esign-rest-api/reference/accounts/identityverifications/":{"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","url":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","title":"IdentityVerifications","titleInlineContent":[{"type":"text","text":"IdentityVerifications"}],"type":"link"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFeatureAvailableMetadata":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIFeatureAvailableMetadata","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapifeatureavailablemetadata","type":"topic","navigatorTitle":[{"text":"DSAPIFeatureAvailableMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFeatureAvailableMetadata","role":"symbol","title":"DSAPIFeatureAvailableMetadata","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAdditionalNotification":{"abstract":[{"type":"text","text":"Describes an additional notification method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPIRecipientAdditionalNotification","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientadditionalnotification","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAdditionalNotification","role":"symbol","title":"DSAPIRecipientAdditionalNotification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureInformation":{"navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureInformation"}],"title":"DSAPIRecipientSignatureInformation","url":"\/documentation\/docusignapi\/dsapirecipientsignatureinformation","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureInformation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientSignatureInformation","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Allows the sender to pre-specify the signature name, signature initials and signature font used in the signature stamp for the recipient.  Used only with recipient types In Person Signers and Signers."}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIdCheckInformationInput":{"url":"\/documentation\/docusignapi\/dsapiidcheckinformationinput","title":"DSAPIIdCheckInformationInput","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIIdCheckInformationInput","kind":"identifier"}],"navigatorTitle":[{"text":"DSAPIIdCheckInformationInput","kind":"identifier"}],"abstract":[{"type":"text","text":"A complex element that contains input information related to a recipient ID check."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","role":"symbol","title":"DSAPIRecipientAttachment","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient":{"url":"\/documentation\/docusignapi\/dsapinotaryrecipient","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient","title":"DSAPINotaryRecipient","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPINotaryRecipient","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPINotaryRecipient","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAuthenticationStatus":{"title":"DSAPIAuthenticationStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPIAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapiauthenticationstatus","abstract":[{"text":"A complex element that contains information about a user's authentication status.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAuthenticationStatus","role":"symbol","navigatorTitle":[{"text":"DSAPIAuthenticationStatus","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientIdentityVerification":{"abstract":[{"text":"Specifies ID Verification applied on an envelope by workflow ID. See the ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/list\/","isActive":true,"type":"reference"},{"text":" method in the ","type":"text"},{"isActive":true,"identifier":"\/docs\/esign-rest-api\/reference\/accounts\/identityverifications\/","type":"reference"},{"text":" resource for more information on how to retrieve workflow IDs available for an account. This can be used in addition to other ","type":"text"},{"isActive":true,"identifier":"https:\/\/support.docusign.com\/en\/guides\/ndse-user-guide-recipient-authentication","type":"reference"},{"text":" methods.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientIdentityVerification"}],"url":"\/documentation\/docusignapi\/dsapirecipientidentityverification","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientIdentityVerification","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientIdentityVerification","role":"symbol","title":"DSAPIRecipientIdentityVerification","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication","type":"topic","navigatorTitle":[{"text":"DSAPISocialAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","role":"symbol","title":"DSAPISocialAuthentication","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneAuthentication":{"abstract":[{"text":"A complex type that contains the elements:  * `recipMayProvideNumber`: A Boolean value that specifies whether the recipient can use the phone number of their choice. * `senderProvidedNumbers`: A list of phone numbers that the recipient can use. * `recordVoicePrint`: Reserved for DocuSign. * `validateRecipProvidedNumber`: Reserved for DocuSign.","type":"text"}],"title":"DSAPIRecipientPhoneAuthentication","url":"\/documentation\/docusignapi\/dsapirecipientphoneauthentication","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"navigatorTitle":[{"text":"DSAPIRecipientPhoneAuthentication","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientSignatureProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"title":"DSAPIRecipientSignatureProvider","abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"isActive":true,"type":"reference","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"kind":"symbol"},"/docs/esign-rest-api/esign101/concepts/documents/":{"type":"link","titleInlineContent":[{"type":"text","text":"ID Verification"}],"url":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/","title":"ID Verification","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/documents\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/title","value":"DSAPIDocumentVisibility"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIDocumentVisibility\/fragments","value":[{"kind":"identifier","text":"DSAPIDocumentVisibility"}]},{"value":"DSAPIRecipientSMSAuthentication","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/title","op":"replace","value":"DSAPIRecipientEmailNotification"},{"value":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/fragments"},{"op":"replace","value":"DSAPIUserInfo","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/title"},{"value":[{"text":"DSAPIUserInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/title","value":"DSAPIOfflineAttributes"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIOfflineAttributes\/fragments","value":[{"kind":"identifier","text":"DSAPIOfflineAttributes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","value":"DSAPITabs","op":"replace"},{"value":[{"text":"DSAPITabs","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/title","value":"DSAPIRecipientAdditionalNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAdditionalNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientAdditionalNotification"}]},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","op":"replace","value":"DSAPIErrorDetails"},{"value":[{"kind":"identifier","text":"DSAPIErrorDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureInformation\/title","value":"DSAPIRecipientSignatureInformation"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureInformation\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIRecipientSignatureInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/title","value":"DSAPIRecipientAttachment"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/fragments","value":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/title","value":"DSAPINotaryRecipient"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/fragments","value":[{"kind":"identifier","text":"DSAPINotaryRecipient"}]},{"op":"replace","value":"DSAPISocialAuthentication","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments","value":[{"text":"DSAPISocialAuthentication","kind":"identifier"}]},{"op":"replace","value":"DSAPIPropertyMetadata","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"text":"DSAPIPropertyMetadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/title","value":"DSAPIRecipientSignatureProvider"},{"value":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSignatureProvider\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}