{"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/lastName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient"]]},"abstract":[{"type":"text","text":"The user's last name.  Maximum Length: 50 characters."}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient(py)lastName","modules":[{"name":"DocuSignAPI"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"lastName"}],"title":"lastName"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lastName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/lastname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/lastname"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient":{"url":"\/documentation\/docusignapi\/dsapinotaryrecipient","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient","title":"DSAPINotaryRecipient","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPINotaryRecipient","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPINotaryRecipient","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient/lastName":{"title":"lastName","navigatorTitle":[{"text":"lastName","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapinotaryrecipient\/lastname","kind":"symbol","abstract":[{"text":"The user's last name.  Maximum Length: 50 characters.","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/lastName","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"lastName","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"lastName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"lastName","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/title","value":"DSAPINotaryRecipient","op":"replace"},{"op":"replace","value":[{"text":"DSAPINotaryRecipient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/fragments"},{"value":"lastName","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient~1lastName\/title","op":"replace"},{"value":[{"kind":"identifier","text":"lastName"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient~1lastName\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}