{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPINotaryRecipient(py)recipientAttachments","modules":[{"name":"DocuSignAPI"}],"role":"symbol","title":"recipientAttachments","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recipientAttachments","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"recipientAttachments","kind":"identifier"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/recipientattachments"]},{"paths":["\/documentation\/docusignapi\/dsapinotaryrecipient\/recipientattachments"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/recipientAttachments"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Reserved for DocuSign."}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recipientAttachments","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIRecipientAttachment","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment"},{"kind":"text","text":"]?"}]}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient":{"url":"\/documentation\/docusignapi\/dsapinotaryrecipient","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient","title":"DSAPINotaryRecipient","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DSAPINotaryRecipient","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DSAPINotaryRecipient","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPINotaryRecipient/recipientAttachments":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPINotaryRecipient\/recipientAttachments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recipientAttachments","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientAttachment","text":"DSAPIRecipientAttachment","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","title":"recipientAttachments","abstract":[{"text":"Reserved for DocuSign.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"recipientAttachments"}],"url":"\/documentation\/docusignapi\/dsapinotaryrecipient\/recipientattachments"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientAttachment":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapirecipientattachment","type":"topic","navigatorTitle":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientAttachment","role":"symbol","title":"DSAPIRecipientAttachment","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"recipientAttachments","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"recipientAttachments","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DSAPIRecipientAttachment *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recipientAttachments"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DSAPINotaryRecipient","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient\/fragments","value":[{"text":"DSAPINotaryRecipient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient~1recipientAttachments\/title","value":"recipientAttachments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPINotaryRecipient~1recipientAttachments\/fragments","value":[{"text":"recipientAttachments","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/title","value":"DSAPIRecipientAttachment"},{"op":"replace","value":[{"text":"DSAPIRecipientAttachment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientAttachment\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}