{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"accountName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"accountSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation","text":"DSAPIAccountSettingsInformation"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"allowTransactionRooms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"billingPeriodDaysRemaining"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"billingPeriodEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"billingPeriodEnvelopesAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"billingPeriodEnvelopesSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"billingPeriodStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"billingProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"canUpgrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"connectPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"createdDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"currencyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"currentPlanId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"displayApplianceStartUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"displayApplianceUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"distributorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"docuSignLandingUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"dssValues"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"envelopeSendingBlocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"envelopeUnitPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"externalAccountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"forgottenPasswordQuestionsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isDowngrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"planClassification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"planEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"planName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"planStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientDomains"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientDomain","preciseIdentifier":"s:11DocuSignAPI20DSAPIRecipientDomainV","text":"DSAPIRecipientDomain"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"seatsAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"seatsInUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"status21CFRPart11"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"suspensionDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"suspensionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"useDisplayAppliance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountinformation\/init(accountidguid:accountname:accountsettings:allowtransactionrooms:billingperioddaysremaining:billingperiodenddate:billingperiodenvelopesallowed:billingperiodenvelopessent:billingperiodstartdate:billingprofile:canupgrade:connectpermission-3qsox"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation\/init(accountIdGuid:accountName:accountSettings:allowTransactionRooms:billingPeriodDaysRemaining:billingPeriodEndDate:billingPeriodEnvelopesAllowed:billingPeriodEnvelopesSent:billingPeriodStartDate:billingProfile:canUpgrade:connectPermission:createdDate:currencyCode:currentPlanId:displayApplianceStartUrl:displayApplianceUrl:distributorCode:docuSignLandingUrl:dssValues:envelopeSendingBlocked:envelopeUnitPrice:externalAccountId:forgottenPasswordQuestionsCount:isDowngrade:paymentMethod:planClassification:planEndDate:planName:planStartDate:recipientDomains:seatsAllowed:seatsInUse:status21CFRPart11:suspensionDate:suspensionStatus:useDisplayAppliance:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accountName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accountSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIAccountSettingsInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"allowTransactionRooms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingPeriodDaysRemaining"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodEnvelopesAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodEnvelopesSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canUpgrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currencyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currentPlanId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"displayApplianceStartUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"displayApplianceUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"distributorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"docuSignLandingUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dssValues"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeSendingBlocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeUnitPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"externalAccountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forgottenPasswordQuestionsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDowngrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planClassification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientDomains"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientDomain","preciseIdentifier":"s:11DocuSignAPI20DSAPIRecipientDomainV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"seatsAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seatsInUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status21CFRPart11"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suspensionDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suspensionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useDisplayAppliance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(accountIdGuid:accountName:accountSettings:allowTransactionRooms:billingPeriodDaysRemaining:billingPeriodEndDate:billingPeriodEnvelopesAllowed:billingPeriodEnvelopesSent:billingPeriodStartDate:billingProfile:canUpgrade:connectPermission:createdDate:currencyCode:currentPlanId:displayApplianceStartUrl:displayApplianceUrl:distributorCode:docuSignLandingUrl:dssValues:envelopeSendingBlocked:envelopeUnitPrice:externalAccountId:forgottenPasswordQuestionsCount:isDowngrade:paymentMethod:planClassification:planEndDate:planName:planStartDate:recipientDomains:seatsAllowed:seatsInUse:status21CFRPart11:suspensionDate:suspensionStatus:useDisplayAppliance:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI23DSAPIAccountInformationC13accountIdGuid0F4Name0F8Settings21allowTransactionRooms26billingPeriodDaysRemaining0nO7EndDate0nO16EnvelopesAllowed0noT4Sent0no5StartS00N7Profile10canUpgrade17connectPermission07createdS012currencyCode011currentPlanG0016displayApplianceW3Url19displayApplianceUrl15distributorCode04docuB10LandingUrl9dssValues22envelopeSendingBlocked17envelopeUnitPrice015externalAccountG031forgottenPasswordQuestionsCount11isDowngrade13paymentMethod18planClassification04planrS004planI004planwS016recipientDomains05seatsU010seatsInUse17status21CFRPart11010suspensionS016suspensionStatus19useDisplayApplianceACSSSg_A13_AA0djE0CSgSbA13_10Foundation0S0VSgA13_A13_A20_A13_SbA13_A20_A13_A13_A17_3URLVSgA23_A13_A23_SDyS2SGSgSbA13_A13_A13_SbA13_A13_A20_A13_A20_SayAA20DSAPIRecipientDomainVGSgA13_A13_A13_A20_A13_Sbtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountInformation":{"role":"symbol","title":"DSAPIAccountInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAccountInformation"}],"abstract":[{"type":"text","text":"Contains account Information."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIAccountInformation"}],"url":"\/documentation\/docusignapi\/dsapiaccountinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountSettingsInformation":{"role":"symbol","title":"DSAPIAccountSettingsInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAccountSettingsInformation"}],"abstract":[{"type":"text","text":"Contains account settings information. Used in requests to set property values. Used in responses to report property values."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountSettingsInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIAccountSettingsInformation"}],"url":"\/documentation\/docusignapi\/dsapiaccountsettingsinformation"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientDomain":{"role":"symbol","title":"DSAPIRecipientDomain","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientDomain"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientDomain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientDomain"}],"url":"\/documentation\/docusignapi\/dsapirecipientdomain"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountInformation/init(accountIdGuid:accountName:accountSettings:allowTransactionRooms:billingPeriodDaysRemaining:billingPeriodEndDate:billingPeriodEnvelopesAllowed:billingPeriodEnvelopesSent:billingPeriodStartDate:billingProfile:canUpgrade:connectPermission:createdDate:currencyCode:currentPlanId:displayApplianceStartUrl:displayApplianceUrl:distributorCode:docuSignLandingUrl:dssValues:envelopeSendingBlocked:envelopeUnitPrice:externalAccountId:forgottenPasswordQuestionsCount:isDowngrade:paymentMethod:planClassification:planEndDate:planName:planStartDate:recipientDomains:seatsAllowed:seatsInUse:status21CFRPart11:suspensionDate:suspensionStatus:useDisplayAppliance:)":{"role":"symbol","title":"init(accountIdGuid:accountName:accountSettings:allowTransactionRooms:billingPeriodDaysRemaining:billingPeriodEndDate:billingPeriodEnvelopesAllowed:billingPeriodEnvelopesSent:billingPeriodStartDate:billingProfile:canUpgrade:connectPermission:createdDate:currencyCode:currentPlanId:displayApplianceStartUrl:displayApplianceUrl:distributorCode:docuSignLandingUrl:dssValues:envelopeSendingBlocked:envelopeUnitPrice:externalAccountId:forgottenPasswordQuestionsCount:isDowngrade:paymentMethod:planClassification:planEndDate:planName:planStartDate:recipientDomains:seatsAllowed:seatsInUse:status21CFRPart11:suspensionDate:suspensionStatus:useDisplayAppliance:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountIdGuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accountName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"accountSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIAccountSettingsInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountSettingsInformation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"allowTransactionRooms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingPeriodDaysRemaining"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodEnvelopesAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodEnvelopesSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingPeriodStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"canUpgrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"createdDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currencyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currentPlanId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"displayApplianceStartUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"displayApplianceUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"distributorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"docuSignLandingUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dssValues"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"envelopeSendingBlocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"envelopeUnitPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"externalAccountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forgottenPasswordQuestionsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDowngrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planClassification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"planStartDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientDomains"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientDomain","preciseIdentifier":"s:11DocuSignAPI20DSAPIRecipientDomainV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"seatsAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"seatsInUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status21CFRPart11"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suspensionDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suspensionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useDisplayAppliance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation\/init(accountIdGuid:accountName:accountSettings:allowTransactionRooms:billingPeriodDaysRemaining:billingPeriodEndDate:billingPeriodEnvelopesAllowed:billingPeriodEnvelopesSent:billingPeriodStartDate:billingProfile:canUpgrade:connectPermission:createdDate:currencyCode:currentPlanId:displayApplianceStartUrl:displayApplianceUrl:distributorCode:docuSignLandingUrl:dssValues:envelopeSendingBlocked:envelopeUnitPrice:externalAccountId:forgottenPasswordQuestionsCount:isDowngrade:paymentMethod:planClassification:planEndDate:planName:planStartDate:recipientDomains:seatsAllowed:seatsInUse:status21CFRPart11:suspensionDate:suspensionStatus:useDisplayAppliance:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapiaccountinformation\/init(accountidguid:accountname:accountsettings:allowtransactionrooms:billingperioddaysremaining:billingperiodenddate:billingperiodenvelopesallowed:billingperiodenvelopessent:billingperiodstartdate:billingprofile:canupgrade:connectpermission-3qsox"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountInformation\/title","value":"DSAPIAccountInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountInformation\/fragments","value":[{"kind":"identifier","text":"DSAPIAccountInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/title","value":"DSAPIAccountSettingsInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountSettingsInformation\/fragments","value":[{"kind":"identifier","text":"DSAPIAccountSettingsInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}