{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDowngrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiaccountinformation\/isdowngrade"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiaccountinformation\/isdowngrade"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation\/isDowngrade","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the account has been downgraded from a premium account type. Otherwise "},{"type":"strong","inlineContent":[{"type":"text","text":"false."}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDowngrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isDowngrade","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIAccountInformation(py)isDowngrade","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"isDowngrade"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountInformation/isDowngrade":{"role":"symbol","title":"isDowngrade","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDowngrade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true,"}]},{"type":"text","text":" the account has been downgraded from a premium account type. Otherwise "},{"type":"strong","inlineContent":[{"type":"text","text":"false."}]}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation\/isDowngrade","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDowngrade"}],"url":"\/documentation\/docusignapi\/dsapiaccountinformation\/isdowngrade"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIAccountInformation":{"role":"symbol","title":"DSAPIAccountInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIAccountInformation"}],"abstract":[{"type":"text","text":"Contains account Information."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIAccountInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIAccountInformation"}],"url":"\/documentation\/docusignapi\/dsapiaccountinformation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isDowngrade"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isDowngrade"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDowngrade"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountInformation~1isDowngrade\/title","value":"isDowngrade"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountInformation~1isDowngrade\/fragments","value":[{"kind":"identifier","text":"isDowngrade"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountInformation\/title","value":"DSAPIAccountInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIAccountInformation\/fragments","value":[{"kind":"identifier","text":"DSAPIAccountInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}