{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSignatureAdoptionStyles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations\/availablesignatureadoptionstyles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations\/availablesignatureadoptionstyles"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations\/availableSignatureAdoptionStyles","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSignatureAdoptionStyles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"title":"availableSignatureAdoptionStyles","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations(py)availableSignatureAdoptionStyles","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"availableSignatureAdoptionStyles"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureAdoptionConfigurations":{"role":"symbol","title":"DSAPISignatureAdoptionConfigurations","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}],"abstract":[{"type":"text","text":"Contains information about the current envelope purge configuration for an account, which enables account administrators to purge documents from completed and voided envelopes after a set number of days (`retentionDays`)."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}],"url":"\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureAdoptionConfigurations/availableSignatureAdoptionStyles":{"role":"symbol","title":"availableSignatureAdoptionStyles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSignatureAdoptionStyles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations\/availableSignatureAdoptionStyles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"availableSignatureAdoptionStyles"}],"url":"\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations\/availablesignatureadoptionstyles"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"availableSignatureAdoptionStyles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"availableSignatureAdoptionStyles"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"availableSignatureAdoptionStyles"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/title","value":"DSAPISignatureAdoptionConfigurations"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/fragments","value":[{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations~1availableSignatureAdoptionStyles\/title","value":"availableSignatureAdoptionStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations~1availableSignatureAdoptionStyles\/fragments","value":[{"kind":"identifier","text":"availableSignatureAdoptionStyles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}