{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations\/signatureAdoptMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)BoolFromString","kind":"attribute","text":"BoolFromString","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signatureAdoptMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations"]]},"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"signatureAdoptMode","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPISignatureAdoptionConfigurations(py)signatureAdoptMode","modules":[{"name":"DocuSignAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"signatureAdoptMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"signatureAdoptMode","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations\/signatureadoptmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations\/signatureadoptmode"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureAdoptionConfigurations/signatureAdoptMode":{"navigatorTitle":[{"text":"signatureAdoptMode","kind":"identifier"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations\/signatureadoptmode","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations\/signatureAdoptMode","title":"signatureAdoptMode","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signatureAdoptMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISignatureAdoptionConfigurations":{"url":"\/documentation\/docusignapi\/dsapisignatureadoptionconfigurations","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPISignatureAdoptionConfigurations","kind":"identifier"}],"title":"DSAPISignatureAdoptionConfigurations","navigatorTitle":[{"kind":"identifier","text":"DSAPISignatureAdoptionConfigurations"}],"abstract":[{"text":"Contains information about the current envelope purge configuration for an account, which enables account administrators to purge documents from completed and voided envelopes after a set number of days (`retentionDays`).","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISignatureAdoptionConfigurations","kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/BoolFromString":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BoolFromString","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/BoolFromString","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BoolFromString"}],"url":"\/documentation\/docusignapi\/boolfromstring","title":"BoolFromString","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"signatureAdoptMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"signatureAdoptMode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"signatureAdoptMode","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"signatureAdoptMode","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations~1signatureAdoptMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations~1signatureAdoptMode\/fragments","value":[{"kind":"identifier","text":"signatureAdoptMode"}],"op":"replace"},{"op":"replace","value":"DSAPISignatureAdoptionConfigurations","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/title"},{"op":"replace","value":[{"text":"DSAPISignatureAdoptionConfigurations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISignatureAdoptionConfigurations\/fragments"},{"op":"replace","value":"BoolFromString","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1BoolFromString\/fragments","value":[{"kind":"identifier","text":"BoolFromString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}