{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateUpdateSummary\/init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)"},"metadata":{"symbolKind":"init","title":"init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"bulkEnvelopeStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkEnvelopeStatusV","kind":"typeIdentifier","text":"DSAPIBulkEnvelopeStatus"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"errorDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIErrorDetails","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"text":"listCustomFieldUpdateResults","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIListCustomField","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lockInformation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","text":"DSAPILockInformation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"purgeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"recipientUpdateResults","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"tabUpdateResults","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"text":"?, ","kind":"text"},{"text":"textCustomFieldUpdateResults","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","text":"DSAPITextCustomField","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"modules":[{"name":"DocuSignAPI"}],"role":"symbol","externalID":"s:11DocuSignAPI26DSAPITemplateUpdateSummaryV18bulkEnvelopeStatus10envelopeId12errorDetails015listCustomFieldE7Results15lockInformation10purgeState09recipienteQ003tabeQ004textopeQ0AcA09DSAPIBulkhI0VSg_SSSgAA010DSAPIErrorM0CSgSayAA09DSAPIListoP0CGSgAA09DSAPILockS0CSgAPSayAA014DSAPIRecipientE8ResponseCGSgAA9DSAPITabsCSgSayAA09DSAPITextoP0CGSgtcfc","roleHeading":"Initializer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateUpdateSummary"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bulkEnvelopeStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkEnvelopeStatusV","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkEnvelopeStatus","kind":"typeIdentifier","text":"DSAPIBulkEnvelopeStatus"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"envelopeId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"errorDetails"},{"text":": ","kind":"text"},{"text":"DSAPIErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails"},{"text":"? = nil, ","kind":"text"},{"text":"listCustomFieldUpdateResults","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","kind":"typeIdentifier","text":"DSAPIListCustomField"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"lockInformation"},{"text":": ","kind":"text"},{"text":"DSAPILockInformation","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"purgeState"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"recipientUpdateResults","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientUpdateResponse","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]? = nil, "},{"text":"tabUpdateResults","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"textCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"text":"DSAPITextCustomField","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField"},{"text":"]? = nil)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapitemplateupdatesummary\/init(bulkenvelopestatus:envelopeid:errordetails:listcustomfieldupdateresults:lockinformation:purgestate:recipientupdateresults:tabupdateresults:textcustomfieldupdateresults:)"]}],"sections":[],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientUpdateResponse":{"type":"topic","url":"\/documentation\/docusignapi\/dsapirecipientupdateresponse","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIRecipientUpdateResponse","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientUpdateResponse","role":"symbol","title":"DSAPIRecipientUpdateResponse","abstract":[{"text":"The recipient details that are returned after you update the recipient.","type":"text"}],"navigatorTitle":[{"text":"DSAPIRecipientUpdateResponse","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabs":{"role":"symbol","url":"\/documentation\/docusignapi\/dsapitabs","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPITabs"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabs","abstract":[{"type":"text","text":"Tabs indicate to recipients where they should sign, initial, or enter data on a document. They are represented graphically as symbols on documents at the time of signing. Tabs can also display data to the recipients."}],"kind":"symbol","title":"DSAPITabs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPITabs"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIErrorDetails":{"type":"topic","title":"DSAPIErrorDetails","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIErrorDetails","role":"symbol","navigatorTitle":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapierrordetails","abstract":[{"text":"This object describes errors that occur. It is only valid for responses and ignored in requests.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIErrorDetails","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITextCustomField":{"navigatorTitle":[{"text":"DSAPITextCustomField","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapitextcustomfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITextCustomField"}],"role":"symbol","abstract":[{"type":"text","text":"This object represents a free text custom field where envelope creators and senders can enter custom data."}],"title":"DSAPITextCustomField","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITextCustomField","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateUpdateSummary/init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateUpdateSummary\/init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","abstract":[],"title":"init(bulkEnvelopeStatus:envelopeId:errorDetails:listCustomFieldUpdateResults:lockInformation:purgeState:recipientUpdateResults:tabUpdateResults:textCustomFieldUpdateResults:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bulkEnvelopeStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkEnvelopeStatusV","kind":"typeIdentifier","text":"DSAPIBulkEnvelopeStatus"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"envelopeId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"errorDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIErrorDetails","text":"DSAPIErrorDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"listCustomFieldUpdateResults"},{"text":": [","kind":"text"},{"text":"DSAPIListCustomField","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIListCustomField"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"lockInformation"},{"kind":"text","text":": "},{"text":"DSAPILockInformation","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPILockInformation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"purgeState","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipientUpdateResults","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse","text":"DSAPIRecipientUpdateResponse","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"tabUpdateResults","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITabs","text":"DSAPITabs"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"textCustomFieldUpdateResults"},{"kind":"text","text":": ["},{"text":"DSAPITextCustomField","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPITextCustomField","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapitemplateupdatesummary\/init(bulkenvelopestatus:envelopeid:errordetails:listcustomfieldupdateresults:lockinformation:purgestate:recipientupdateresults:tabupdateresults:textcustomfieldupdateresults:)","type":"topic","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITemplateUpdateSummary":{"navigatorTitle":[{"text":"DSAPITemplateUpdateSummary","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapitemplateupdatesummary","role":"symbol","abstract":[],"title":"DSAPITemplateUpdateSummary","type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITemplateUpdateSummary","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPITemplateUpdateSummary","kind":"identifier"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIListCustomField":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIListCustomField","role":"symbol","navigatorTitle":[{"text":"DSAPIListCustomField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIListCustomField","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This object represents a list custom field from which envelope creators and senders can select custom data.","type":"text"}],"title":"DSAPIListCustomField","url":"\/documentation\/docusignapi\/dsapilistcustomfield","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBulkEnvelopeStatus":{"type":"topic","abstract":[],"url":"\/documentation\/docusignapi\/dsapibulkenvelopestatus","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkEnvelopeStatus","navigatorTitle":[{"kind":"identifier","text":"DSAPIBulkEnvelopeStatus"}],"title":"DSAPIBulkEnvelopeStatus","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIBulkEnvelopeStatus","kind":"identifier"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPILockInformation":{"url":"\/documentation\/docusignapi\/dsapilockinformation","title":"DSAPILockInformation","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPILockInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPILockInformation"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPILockInformation"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientUpdateResponse\/title","value":"DSAPIRecipientUpdateResponse"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientUpdateResponse\/fragments","value":[{"text":"DSAPIRecipientUpdateResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/title","op":"replace","value":"DSAPITabs"},{"value":[{"kind":"identifier","text":"DSAPITabs"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/title","value":"DSAPIErrorDetails"},{"value":[{"text":"DSAPIErrorDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIErrorDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/title","value":"DSAPITextCustomField"},{"value":[{"text":"DSAPITextCustomField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITextCustomField\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/title","value":"DSAPIListCustomField"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIListCustomField\/fragments","value":[{"text":"DSAPIListCustomField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/title","value":"DSAPILockInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPILockInformation\/fragments","op":"replace","value":[{"text":"DSAPILockInformation","kind":"identifier"}]}]}]}