{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification","text":"DSAPIRecipientEmailNotification"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"hostEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"hostName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV","text":"DSAPIIdCheckInformationInput"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"identificationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV","text":"DSAPIRecipientPhoneAuthentication"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","preciseIdentifier":"s:11DocuSignAPI31DSAPIRecipientSignatureProviderV","text":"DSAPIRecipientSignatureProvider"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication","text":"DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication","text":"DSAPISocialAuthentication"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkSendingCopyTab","preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkSendingCopyTabV","text":"DSAPIBulkSendingCopyTab"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapibulksendingcopyrecipient\/init(accesscode:clientuserid:customfields:deliverymethod:email:emailnotification:embeddedrecipientstarturl:faxnumber:hostemail:hostname:idcheckconfigurationname:idcheckinformationinput:identificationmethod:name:note:phoneauthentication:reci-8pi9h"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkSendingCopyRecipient\/init(accessCode:clientUserId:customFields:deliveryMethod:email:emailNotification:embeddedRecipientStartURL:faxNumber:hostEmail:hostName:idCheckConfigurationName:idCheckInformationInput:identificationMethod:name:note:phoneAuthentication:recipientId:recipientSignatureProviders:roleName:signerName:signingGroupId:smsAuthentication:socialAuthentications:tabs:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hostEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hostName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"identificationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"s:11DocuSignAPI31DSAPIRecipientSignatureProviderV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBulkSendingCopyTab","preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkSendingCopyTabV"},{"kind":"text","text":"]?)"}],"title":"init(accessCode:clientUserId:customFields:deliveryMethod:email:emailNotification:embeddedRecipientStartURL:faxNumber:hostEmail:hostName:idCheckConfigurationName:idCheckInformationInput:identificationMethod:name:note:phoneAuthentication:recipientId:recipientSignatureProviders:roleName:signerName:signingGroupId:smsAuthentication:socialAuthentications:tabs:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DocuSignAPI29DSAPIBulkSendingCopyRecipientV10accessCode12clientUserId12customFields14deliveryMethod5email0Q12Notification08embeddedG8StartURL9faxNumber9hostEmail0X4Name020idCheckConfigurationZ023idCheckInformationInput014identificationP04name4note19phoneAuthentication09recipientL027recipientSignatureProviders04roleZ006signerZ0012signingGroupL017smsAuthentication21socialAuthentications4tabsACSSSg_A0_SaySSGSgA0_A0_AA014DSAPIRecipientyR0CSgA0_A0_A0_A0_A0_AA28DSAPIIdCheckInformationInputVSgA0_A0_A0_AA33DSAPIRecipientPhoneAuthenticationVSgA0_SayAA31DSAPIRecipientSignatureProviderVGSgA0_A0_A0_AA31DSAPIRecipientSMSAuthenticationCSgSayAA25DSAPISocialAuthenticationCGSgSayAA0deF3TabVGSgtcfc","modules":[{"name":"DocuSignAPI"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkSendingCopyRecipient"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientPhoneAuthentication":{"role":"symbol","title":"DSAPIRecipientPhoneAuthentication","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"abstract":[{"type":"text","text":"A complex type that contains the elements:  * `recipMayProvideNumber`: A Boolean value that specifies whether the recipient can use the phone number of their choice. * `senderProvidedNumbers`: A list of phone numbers that the recipient can use. * `recordVoicePrint`: Reserved for DocuSign. * `validateRecipProvidedNumber`: Reserved for DocuSign."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientPhoneAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientPhoneAuthentication"}],"url":"\/documentation\/docusignapi\/dsapirecipientphoneauthentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSignatureProvider":{"role":"symbol","title":"DSAPIRecipientSignatureProvider","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"abstract":[{"type":"text","text":"An Electronic or Standards Based Signature (digital signature) provider for the signer to use. "},{"type":"reference","isActive":true,"identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSignatureProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSignatureProvider"}],"url":"\/documentation\/docusignapi\/dsapirecipientsignatureprovider"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientEmailNotification":{"role":"symbol","title":"DSAPIRecipientEmailNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientEmailNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}],"url":"\/documentation\/docusignapi\/dsapirecipientemailnotification"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIIdCheckInformationInput":{"role":"symbol","title":"DSAPIIdCheckInformationInput","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIIdCheckInformationInput"}],"abstract":[{"type":"text","text":"A complex element that contains input information related to a recipient ID check."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIIdCheckInformationInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIIdCheckInformationInput"}],"url":"\/documentation\/docusignapi\/dsapiidcheckinformationinput"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBulkSendingCopyRecipient/init(accessCode:clientUserId:customFields:deliveryMethod:email:emailNotification:embeddedRecipientStartURL:faxNumber:hostEmail:hostName:idCheckConfigurationName:idCheckInformationInput:identificationMethod:name:note:phoneAuthentication:recipientId:recipientSignatureProviders:roleName:signerName:signingGroupId:smsAuthentication:socialAuthentications:tabs:)":{"role":"symbol","title":"init(accessCode:clientUserId:customFields:deliveryMethod:email:emailNotification:embeddedRecipientStartURL:faxNumber:hostEmail:hostName:idCheckConfigurationName:idCheckInformationInput:identificationMethod:name:note:phoneAuthentication:recipientId:recipientSignatureProviders:roleName:signerName:signingGroupId:smsAuthentication:socialAuthentications:tabs:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"deliveryMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"emailNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientEmailNotification","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientEmailNotification"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"embeddedRecipientStartURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faxNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hostEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hostName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckConfigurationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idCheckInformationInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIIdCheckInformationInput","preciseIdentifier":"s:11DocuSignAPI28DSAPIIdCheckInformationInputV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"identificationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientPhoneAuthentication","preciseIdentifier":"s:11DocuSignAPI33DSAPIRecipientPhoneAuthenticationV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipientSignatureProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientSignatureProvider","preciseIdentifier":"s:11DocuSignAPI31DSAPIRecipientSignatureProviderV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"roleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"signingGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"smsAuthentication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIRecipientSMSAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientSMSAuthentication"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialAuthentications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPISocialAuthentication","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPISocialAuthentication"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tabs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIBulkSendingCopyTab","preciseIdentifier":"s:11DocuSignAPI23DSAPIBulkSendingCopyTabV"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkSendingCopyRecipient\/init(accessCode:clientUserId:customFields:deliveryMethod:email:emailNotification:embeddedRecipientStartURL:faxNumber:hostEmail:hostName:idCheckConfigurationName:idCheckInformationInput:identificationMethod:name:note:phoneAuthentication:recipientId:recipientSignatureProviders:roleName:signerName:signingGroupId:smsAuthentication:socialAuthentications:tabs:)","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi\/dsapibulksendingcopyrecipient\/init(accesscode:clientuserid:customfields:deliverymethod:email:emailnotification:embeddedrecipientstarturl:faxnumber:hostemail:hostname:idcheckconfigurationname:idcheckinformationinput:identificationmethod:name:note:phoneauthentication:reci-8pi9h"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBulkSendingCopyRecipient":{"role":"symbol","title":"DSAPIBulkSendingCopyRecipient","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBulkSendingCopyRecipient"}],"abstract":[{"type":"text","text":"This object contains details about a bulk send recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkSendingCopyRecipient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBulkSendingCopyRecipient"}],"url":"\/documentation\/docusignapi\/dsapibulksendingcopyrecipient"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIBulkSendingCopyTab":{"role":"symbol","title":"DSAPIBulkSendingCopyTab","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIBulkSendingCopyTab"}],"abstract":[{"type":"text","text":"A tab associated with the bulk send recipient. In a bulk send request, each recipient tab must match a recipient tab on the envelope or template that you want to send. To match up, the `tabLabel` for this tab and the `tabLabel` for the corresponding tab on the envelope or template must be the same.  For example, if the envelope has a placeholder text tab with the `tabLabel` `childName`, you must assign the same `tabLabel` `childName` to the tab here that you are populating with that information."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIBulkSendingCopyTab","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIBulkSendingCopyTab"}],"url":"\/documentation\/docusignapi\/dsapibulksendingcopytab"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientSMSAuthentication":{"role":"symbol","title":"DSAPIRecipientSMSAuthentication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"abstract":[{"type":"text","text":"Contains the element senderProvidedNumbers which is an Array  of phone numbers the recipient can use for SMS text authentication."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientSMSAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}],"url":"\/documentation\/docusignapi\/dsapirecipientsmsauthentication"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPISocialAuthentication":{"role":"symbol","title":"DSAPISocialAuthentication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPISocialAuthentication"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPISocialAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPISocialAuthentication"}],"url":"\/documentation\/docusignapi\/dsapisocialauthentication"},"/docs/esign-rest-api/esign101/concepts/standards-based-signatures/":{"title":"More information","titleInlineContent":[{"type":"text","text":"More information"}],"type":"link","identifier":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/","url":"\/docs\/esign-rest-api\/esign101\/concepts\/standards-based-signatures\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/title","value":"DSAPIRecipientEmailNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientEmailNotification\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientEmailNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/title","value":"DSAPIRecipientSMSAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientSMSAuthentication\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientSMSAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/title","value":"DSAPISocialAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPISocialAuthentication\/fragments","value":[{"kind":"identifier","text":"DSAPISocialAuthentication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}