{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle\/lockedMetadata"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapititle\/lockedmetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapititle\/lockedmetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"lockedMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","text":"DSAPIPropertyMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DocuSignAPI"}],"role":"symbol","roleHeading":"Instance Property","title":"lockedMetadata","symbolKind":"property","navigatorTitle":[{"text":"lockedMetadata","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockedMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITitle(py)lockedMetadata"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITitle":{"url":"\/documentation\/docusignapi\/dsapititle","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITitle"}],"navigatorTitle":[{"text":"DSAPITitle","kind":"identifier"}],"title":"DSAPITitle","abstract":[{"type":"text","text":"A tab that displays the recipient's title."}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITitle/lockedMetadata":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITitle\/lockedMetadata","url":"\/documentation\/docusignapi\/dsapititle\/lockedmetadata","title":"lockedMetadata","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lockedMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"lockedMetadata"}],"kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lockedMetadata"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"lockedMetadata","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"lockedMetadata"}]}]},"op":"replace"},{"op":"replace","value":"DSAPITitle","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle\/fragments","value":[{"text":"DSAPITitle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DSAPIPropertyMetadata","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle~1lockedMetadata\/title","value":"lockedMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITitle~1lockedMetadata\/fragments","value":[{"kind":"identifier","text":"lockedMetadata"}]}]}]}