{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recipientUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse","text":"DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapirecipientsupdatesummary\/init(recipientupdateresults:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapirecipientsupdatesummary\/init(recipientupdateresults:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary\/init(recipientUpdateResults:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recipientUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]?)"}],"title":"init(recipientUpdateResults:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientsUpdateSummary(im)initWithRecipientUpdateResults:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRecipientUpdateResults:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientsUpdateSummary/init(recipientUpdateResults:)":{"role":"symbol","title":"init(recipientUpdateResults:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recipientUpdateResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIRecipientUpdateResponse","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIRecipientUpdateResponse"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary\/init(recipientUpdateResults:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRecipientUpdateResults:"}],"url":"\/documentation\/docusignapi\/dsapirecipientsupdatesummary\/init(recipientupdateresults:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientsUpdateSummary":{"role":"symbol","title":"DSAPIRecipientsUpdateSummary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientsUpdateSummary"}],"abstract":[{"type":"text","text":"This is the response that the API returns after you update recipients."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientsUpdateSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientsUpdateSummary"}],"url":"\/documentation\/docusignapi\/dsapirecipientsupdatesummary"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIRecipientUpdateResponse":{"role":"symbol","title":"DSAPIRecipientUpdateResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIRecipientUpdateResponse"}],"abstract":[{"type":"text","text":"The recipient details that are returned after you update the recipient."}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIRecipientUpdateResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIRecipientUpdateResponse"}],"url":"\/documentation\/docusignapi\/dsapirecipientupdateresponse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithRecipientUpdateResults:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRecipientUpdateResults:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRecipientUpdateResults:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIRecipientUpdateResponse *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"recipientUpdateResults"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary~1init(recipientUpdateResults:)\/title","value":"initWithRecipientUpdateResults:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary~1init(recipientUpdateResults:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRecipientUpdateResults:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary\/title","value":"DSAPIRecipientsUpdateSummary"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientsUpdateSummary\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientsUpdateSummary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientUpdateResponse\/title","value":"DSAPIRecipientUpdateResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIRecipientUpdateResponse\/fragments","value":[{"kind":"identifier","text":"DSAPIRecipientUpdateResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}