{"metadata":{"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPICarbonCopy(py)clientUserId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientUserId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"clientUserId","role":"symbol","modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"clientUserId"}]},"abstract":[{"text":"Not applicable for Carbon Copy recipients.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICarbonCopy"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"clientUserId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICarbonCopy\/clientUserId","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/docusignapi\/dsapicarboncopy\/clientuserid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapicarboncopy\/clientuserid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICarbonCopy":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPICarbonCopy"}],"abstract":[{"type":"text","text":"Contains information about a carbon copy recipient. Carbon copy recipients get a copy of the envelope but don't need to sign, initial, date or add information to any of the documents."}],"title":"DSAPICarbonCopy","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICarbonCopy","url":"\/documentation\/docusignapi\/dsapicarboncopy","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPICarbonCopy"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPICarbonCopy/clientUserId":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapicarboncopy\/clientuserid","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPICarbonCopy\/clientUserId","navigatorTitle":[{"text":"clientUserId","kind":"identifier"}],"abstract":[{"type":"text","text":"Not applicable for Carbon Copy recipients."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"clientUserId","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"clientUserId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientUserId"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"clientUserId"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICarbonCopy\/title","op":"replace","value":"DSAPICarbonCopy"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICarbonCopy\/fragments","value":[{"kind":"identifier","text":"DSAPICarbonCopy"}]},{"value":"clientUserId","op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICarbonCopy~1clientUserId\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPICarbonCopy~1clientUserId\/fragments","value":[{"text":"clientUserId","kind":"identifier"}],"op":"replace"}]}]}