{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formPageNumberMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup\/formPageNumberMetadata"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup"]]},"metadata":{"modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formPageNumberMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DSAPIPropertyMetadata","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":"?","kind":"text"}],"role":"symbol","title":"formPageNumberMetadata","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPITabGroup(py)formPageNumberMetadata","roleHeading":"Instance Property","navigatorTitle":[{"text":"formPageNumberMetadata","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/docusignapi\/dsapitabgroup\/formpagenumbermetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapitabgroup\/formpagenumbermetadata"]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIPropertyMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"Metadata about a property.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSAPIPropertyMetadata"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","url":"\/documentation\/docusignapi\/dsapipropertymetadata","title":"DSAPIPropertyMetadata"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabGroup/formPageNumberMetadata":{"kind":"symbol","url":"\/documentation\/docusignapi\/dsapitabgroup\/formpagenumbermetadata","role":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup\/formPageNumberMetadata","navigatorTitle":[{"text":"formPageNumberMetadata","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formPageNumberMetadata"},{"text":": ","kind":"text"},{"text":"DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"kind":"text","text":"?"}],"title":"formPageNumberMetadata","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPITabGroup":{"navigatorTitle":[{"kind":"identifier","text":"DSAPITabGroup"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPITabGroup","type":"topic","title":"DSAPITabGroup","url":"\/documentation\/docusignapi\/dsapitabgroup","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPITabGroup"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"formPageNumberMetadata"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"formPageNumberMetadata","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DSAPIPropertyMetadata","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIPropertyMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIPropertyMetadata"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"formPageNumberMetadata"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/title","value":"DSAPIPropertyMetadata"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIPropertyMetadata\/fragments","value":[{"text":"DSAPIPropertyMetadata","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup~1formPageNumberMetadata\/title","value":"formPageNumberMetadata"},{"value":[{"text":"formPageNumberMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup~1formPageNumberMetadata\/fragments","op":"replace"},{"op":"replace","value":"DSAPITabGroup","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPITabGroup\/fragments","value":[{"text":"DSAPITabGroup","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}