{"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults"]]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopetemplateresults\/envelopetemplates"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapienvelopetemplateresults\/envelopetemplates"]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"DocuSignAPI"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"envelopeTemplates","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate","text":"DSAPIEnvelopeTemplate"},{"kind":"text","text":"]?"}],"role":"symbol","title":"envelopeTemplates","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplateResults(py)envelopeTemplates","roleHeading":"Instance Property","navigatorTitle":[{"text":"envelopeTemplates","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/envelopeTemplates","interfaceLanguage":"swift"},"abstract":[{"text":"The list of requested templates.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeTemplates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelopeTemplate","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate"},{"text":"]?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplate":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplate","kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopetemplate","abstract":[],"title":"DSAPIEnvelopeTemplate","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}],"navigatorTitle":[{"text":"DSAPIEnvelopeTemplate","kind":"identifier"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults/envelopeTemplates":{"navigatorTitle":[{"text":"envelopeTemplates","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults\/envelopetemplates","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"envelopeTemplates","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DSAPIEnvelopeTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelopeTemplate"},{"text":"]?","kind":"text"}],"role":"symbol","abstract":[{"text":"The list of requested templates.","type":"text"}],"title":"envelopeTemplates","kind":"symbol","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults\/envelopeTemplates","type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTemplateResults":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapienvelopetemplateresults","title":"DSAPIEnvelopeTemplateResults","type":"topic","abstract":[{"text":"Information about templates.","type":"text"}],"navigatorTitle":[{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTemplateResults"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"envelopeTemplates","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"envelopeTemplates"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<DSAPIEnvelopeTemplate *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"envelopeTemplates"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"DSAPIEnvelopeTemplate","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate\/title"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplate\/fragments","value":[{"kind":"identifier","text":"DSAPIEnvelopeTemplate"}],"op":"replace"},{"value":"envelopeTemplates","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1envelopeTemplates\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults~1envelopeTemplates\/fragments","value":[{"kind":"identifier","text":"envelopeTemplates"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults\/title","value":"DSAPIEnvelopeTemplateResults"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelopeTemplateResults\/fragments","value":[{"text":"DSAPIEnvelopeTemplateResults","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}