{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopesInformation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"continuationToken"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"endPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"envelopes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIEnvelope","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"text":"envelopeTransactionStatuses","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIEnvelopeTransactionStatus","preciseIdentifier":"s:11DocuSignAPI30DSAPIEnvelopeTransactionStatusV","kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTransactionStatus"},{"text":"]? = nil, ","kind":"text"},{"text":"folders","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFolder","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder","kind":"typeIdentifier"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"lastQueriedDateTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"? = nil, "},{"text":"nextUri","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"previousUri"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"resultSetSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"startPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"totalSetSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil)"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopesInformation\/init(continuationToken:endPosition:envelopes:envelopeTransactionStatuses:folders:lastQueriedDateTime:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)"},"metadata":{"externalID":"s:11DocuSignAPI25DSAPIEnvelopesInformationV17continuationToken11endPosition9envelopes27envelopeTransactionStatuses7folders19lastQueriedDateTime7nextUri08previousT013resultSetSize05startI005totalwX0ACSSSg_AOSayAA13DSAPIEnvelopeCGSgSayAA013DSAPIEnvelopeL6StatusVGSgSayAA11DSAPIFolderCGSg10Foundation0Q0VSgA0_3URLVSgA6_A3Otcfc","roleHeading":"Initializer","title":"init(continuationToken:endPosition:envelopes:envelopeTransactionStatuses:folders:lastQueriedDateTime:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"continuationToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"endPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"envelopes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIEnvelope","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope"},{"text":"]?, ","kind":"text"},{"text":"envelopeTransactionStatuses","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11DocuSignAPI30DSAPIEnvelopeTransactionStatusV","text":"DSAPIEnvelopeTransactionStatus","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"folders","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DSAPIFolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"lastQueriedDateTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nextUri","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"previousUri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"text":"resultSetSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"startPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"totalSetSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"modules":[{"name":"DocuSignAPI"}]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapienvelopesinformation\/init(continuationtoken:endposition:envelopes:envelopetransactionstatuses:folders:lastquerieddatetime:nexturi:previousuri:resultsetsize:startposition:totalsetsize:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopeTransactionStatus":{"url":"\/documentation\/docusignapi\/dsapienvelopetransactionstatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSAPIEnvelopeTransactionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopeTransactionStatus"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopeTransactionStatus","title":"DSAPIEnvelopeTransactionStatus","type":"topic","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopesInformation":{"abstract":[{"text":"Result set for the Envelopes: listStatusChanges method","type":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopesInformation","type":"topic","url":"\/documentation\/docusignapi\/dsapienvelopesinformation","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelopesInformation"}],"title":"DSAPIEnvelopesInformation","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSAPIEnvelopesInformation","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelope":{"kind":"symbol","role":"symbol","url":"\/documentation\/docusignapi\/dsapienvelope","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSAPIEnvelope","kind":"identifier"}],"abstract":[],"title":"DSAPIEnvelope","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelope","navigatorTitle":[{"kind":"identifier","text":"DSAPIEnvelope"}],"type":"topic"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIEnvelopesInformation/init(continuationToken:endPosition:envelopes:envelopeTransactionStatuses:folders:lastQueriedDateTime:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)":{"title":"init(continuationToken:endPosition:envelopes:envelopeTransactionStatuses:folders:lastQueriedDateTime:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"continuationToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"endPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"envelopes","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIEnvelope","kind":"typeIdentifier","text":"DSAPIEnvelope"},{"kind":"text","text":"]?, "},{"text":"envelopeTransactionStatuses","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11DocuSignAPI30DSAPIEnvelopeTransactionStatusV","text":"DSAPIEnvelopeTransactionStatus","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"folders","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIFolder","kind":"typeIdentifier","text":"DSAPIFolder"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"lastQueriedDateTime"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"nextUri","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"previousUri","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"text":"resultSetSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"startPosition"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"totalSetSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIEnvelopesInformation\/init(continuationToken:endPosition:envelopes:envelopeTransactionStatuses:folders:lastQueriedDateTime:nextUri:previousUri:resultSetSize:startPosition:totalSetSize:)","kind":"symbol","url":"\/documentation\/docusignapi\/dsapienvelopesinformation\/init(continuationtoken:endposition:envelopes:envelopetransactionstatuses:folders:lastquerieddatetime:nexturi:previousuri:resultsetsize:startposition:totalsetsize:)","abstract":[]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIFolder":{"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIFolder","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIFolder"}],"url":"\/documentation\/docusignapi\/dsapifolder","title":"DSAPIFolder","kind":"symbol","abstract":[{"type":"text","text":"This object contains details about a folder."}],"navigatorTitle":[{"kind":"identifier","text":"DSAPIFolder"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/title","value":"DSAPIEnvelope","op":"replace"},{"value":[{"kind":"identifier","text":"DSAPIEnvelope"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIEnvelope\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/title","value":"DSAPIFolder"},{"op":"replace","value":[{"kind":"identifier","text":"DSAPIFolder"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIFolder\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}