{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userSignatures"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature","text":"DSAPIUserSignature"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/docusignapi\/dsapiusersignaturesinformation\/init(usersignatures:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapiusersignaturesinformation\/init(usersignatures:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(userSignatures:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userSignatures"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"kind":"text","text":"]?)"}],"title":"init(userSignatures:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignaturesInformation(im)initWithUserSignatures:","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUserSignatures:"}]},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation"]]},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"role":"collection","title":"DocuSignAPI","abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","kind":"symbol","type":"topic","url":"\/documentation\/docusignapi"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation/init(userSignatures:)":{"role":"symbol","title":"init(userSignatures:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userSignatures"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DSAPIUserSignature","preciseIdentifier":"c:@M@DocuSignAPI@objc(cs)DSAPIUserSignature"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation\/init(userSignatures:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUserSignatures:"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation\/init(usersignatures:)"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignature":{"role":"symbol","title":"DSAPIUserSignature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignature"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignature"}],"url":"\/documentation\/docusignapi\/dsapiusersignature"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIUserSignaturesInformation":{"role":"symbol","title":"DSAPIUserSignaturesInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"abstract":[],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIUserSignaturesInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}],"url":"\/documentation\/docusignapi\/dsapiusersignaturesinformation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithUserSignatures:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserSignatures:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUserSignatures:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DSAPIUserSignature *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userSignatures"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation~1init(userSignatures:)\/title","value":"initWithUserSignatures:"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation~1init(userSignatures:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserSignatures:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/title","value":"DSAPIUserSignature"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignature\/fragments","value":[{"kind":"identifier","text":"DSAPIUserSignature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation\/title","value":"DSAPIUserSignaturesInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIUserSignaturesInformation\/fragments","value":[{"kind":"identifier","text":"DSAPIUserSignaturesInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}