{"metadata":{"role":"symbol","navigatorTitle":[{"text":"conditionalParentLabel","kind":"identifier"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIList(py)conditionalParentLabel","modules":[{"name":"DocuSignAPI"}],"title":"conditionalParentLabel","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"conditionalParentLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/conditionalParentLabel"},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"]]},"abstract":[{"text":"For conditional fields this is the `tabLabel` of the parent tab that controls this tab's visibility.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapilist\/conditionalparentlabel"]},{"paths":["\/documentation\/docusignapi\/dsapilist\/conditionalparentlabel"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"conditionalParentLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"kind":"symbol","references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList":{"title":"DSAPIList","abstract":[{"text":"This tab offers a list of options to choose from. The `listItems` property contains a list of ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","isActive":true,"type":"reference"},{"text":" objects to specify the selectable options.","type":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapilist","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIList"}],"navigatorTitle":[{"text":"DSAPIList","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList/conditionalParentLabel":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"For conditional fields this is the `tabLabel` of the parent tab that controls this tab's visibility."}],"navigatorTitle":[{"text":"conditionalParentLabel","kind":"identifier"}],"title":"conditionalParentLabel","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/conditionalParentLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"conditionalParentLabel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapilist\/conditionalparentlabel","kind":"symbol"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/":{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","type":"link","titleInlineContent":[{"text":"`listItem`","type":"text"}],"title":"`listItem`","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"conditionalParentLabel","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"conditionalParentLabel","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"conditionalParentLabel","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"DSAPIList","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/fragments","value":[{"text":"DSAPIList","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1conditionalParentLabel\/title","value":"conditionalParentLabel","op":"replace"},{"value":[{"text":"conditionalParentLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1conditionalParentLabel\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}