{"abstract":[{"type":"text","text":"The font color to use for the information in the tab. Possible values are:   - Black - BrightBlue - BrightRed - DarkGreen - DarkRed - Gold - Green - NavyBlue - Purple - White"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/fontColor"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontColor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","title":"fontColor","navigatorTitle":[{"text":"fontColor","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontColor"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIList(py)fontColor","modules":[{"name":"DocuSignAPI"}]},"variants":[{"paths":["\/documentation\/docusignapi\/dsapilist\/fontcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/docusignapi\/dsapilist\/fontcolor"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList/fontColor":{"type":"topic","kind":"symbol","title":"fontColor","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/fontColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fontColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"The font color to use for the information in the tab. Possible values are:   - Black - BrightBlue - BrightRed - DarkGreen - DarkRed - Gold - Green - NavyBlue - Purple - White","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"fontColor","kind":"identifier"}],"url":"\/documentation\/docusignapi\/dsapilist\/fontcolor"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList":{"title":"DSAPIList","abstract":[{"text":"This tab offers a list of options to choose from. The `listItems` property contains a list of ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","isActive":true,"type":"reference"},{"text":" objects to specify the selectable options.","type":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapilist","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIList"}],"navigatorTitle":[{"text":"DSAPIList","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/":{"type":"link","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","title":"`listItem`","titleInlineContent":[{"text":"`listItem`","type":"text"}],"url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fontColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"fontColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"fontColor","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1fontColor\/title","value":"fontColor"},{"value":[{"text":"fontColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1fontColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/title","value":"DSAPIList"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/fragments","op":"replace","value":[{"kind":"identifier","text":"DSAPIList"}]}]}]}