{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/recipientId"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recipientId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/docusignapi\/dsapilist\/recipientid"]},{"paths":["\/documentation\/docusignapi\/dsapilist\/recipientid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DocuSignAPI"}],"navigatorTitle":[{"text":"recipientId","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recipientId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"recipientId","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIList(py)recipientId"},"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList":{"title":"DSAPIList","abstract":[{"text":"This tab offers a list of options to choose from. The `listItems` property contains a list of ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","isActive":true,"type":"reference"},{"text":" objects to specify the selectable options.","type":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapilist","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIList"}],"navigatorTitle":[{"text":"DSAPIList","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/":{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","type":"link","title":"`listItem`","url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","titleInlineContent":[{"type":"text","text":"`listItem`"}]},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList/recipientId":{"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/recipientId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recipientId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/docusignapi\/dsapilist\/recipientid","title":"recipientId","navigatorTitle":[{"text":"recipientId","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recipientId"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"recipientId","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"recipientId","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/title","value":"DSAPIList","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/fragments","value":[{"text":"DSAPIList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1recipientId\/title","value":"recipientId"},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1recipientId\/fragments","value":[{"text":"recipientId","kind":"identifier"}],"op":"replace"}]}]}