{"kind":"symbol","metadata":{"symbolKind":"property","title":"requireAll","modules":[{"name":"DocuSignAPI"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DocuSignAPI@objc(cs)DSAPIList(py)requireAll","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requireAll"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"requireAll","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireAll"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI","doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/requireAll"},"abstract":[{"text":"When ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"text":" and shared is true, information must be entered in this field to complete the envelope.","type":"text"}],"variants":[{"paths":["\/documentation\/docusignapi\/dsapilist\/requireall"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/docusignapi\/dsapilist\/requireall"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/docusignapi","abstract":[],"title":"DocuSignAPI","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList":{"title":"DSAPIList","abstract":[{"text":"This tab offers a list of options to choose from. The `listItems` property contains a list of ","type":"text"},{"identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","isActive":true,"type":"reference"},{"text":" objects to specify the selectable options.","type":"text"}],"role":"symbol","url":"\/documentation\/docusignapi\/dsapilist","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSAPIList"}],"navigatorTitle":[{"text":"DSAPIList","kind":"identifier"}],"identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList"},"/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/":{"url":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","identifier":"\/docs\/esign-rest-api\/reference\/envelopes\/enveloperecipienttabs\/create\/","titleInlineContent":[{"type":"text","text":"`listItem`"}],"type":"link","title":"`listItem`"},"doc://com.DocuSign.DocuSIgnAPI/documentation/DocuSignAPI/DSAPIList/requireAll":{"navigatorTitle":[{"kind":"identifier","text":"requireAll"}],"kind":"symbol","url":"\/documentation\/docusignapi\/dsapilist\/requireall","role":"symbol","title":"requireAll","abstract":[{"type":"text","text":"When "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"text":" and shared is true, information must be entered in this field to complete the envelope.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.DocuSign.DocuSIgnAPI\/documentation\/DocuSignAPI\/DSAPIList\/requireAll","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requireAll","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"requireAll"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"requireAll"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"requireAll","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/title","op":"replace","value":"DSAPIList"},{"value":[{"text":"DSAPIList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList\/fragments","op":"replace"},{"value":"requireAll","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1requireAll\/title","op":"replace"},{"value":[{"kind":"identifier","text":"requireAll"}],"op":"replace","path":"\/references\/doc:~1~1com.DocuSign.DocuSIgnAPI~1documentation~1DocuSignAPI~1DSAPIList~1requireAll\/fragments"}]}]}